## Домашнее задание

В этой тетрадке вам предлагается реализовать задания при помощи библиотеки numpy. Крайне желательно при выполнении разных заданий не использовать циклы. Если вы не понимаете, как выполнить конкретную задачу без циклов - убирайте их постепенно, разбейте выполнение задачи на этапы и постепенно векторизуйте каждый этап.

Если вам непонятно, как выполнить ту или иную операцию - не стесняйтесь гуглить, если над вами повис дедлайн, а вы всё ещё на чём-то застряли - пишите преподу/в чат, это ок.

**Обсудить решение лучше и сделать в итоге хоть что-то гораздо лучше, чем скатать чужой код или сдать пустую тетрадку.**

In [43]:
import numpy as np

### Drill (1 балл)

Задание 1.

Инициализируйте нулями массивы следующих форм:

* (5)
* (5, 1)
* (10, 2)
* (3, 6, 2)
* (4, 3, 2, 1)

In [44]:
print(np.zeros(5))
print(np.zeros((5, 1)))
print()
print(np.zeros((10, 2)))
print()
print(np.zeros((3, 6, 2)))
print()
print(np.zeros((4, 3, 2, 1)))

[0. 0. 0. 0. 0.]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]

[[[[0.]
   [0.]]

  [[0.]
   [0.]]

  [[0.]
   [0.]]]


 [[[0.]
   [0.]]

  [[0.]
   [0.]]

  [[0.]
   [0.]]]


 [[[0.]
   [0.]]

  [[0.]
   [0.]]

  [[0.]
   [0.]]]


 [[[0.]
   [0.]]

  [[0.]
   [0.]]

  [[0.]
   [0.]]]]


Задание 2.

Инициализируйте единицами массивы таких же форм и приведите их к целочисленному виду:

In [3]:
print(np.ones(5).astype(int))
print(np.ones((5, 1)).astype(int))
print(np.ones((10, 2)).astype(int))
print(np.ones((3, 6, 2)).astype(int))
print(np.ones((4, 3, 2, 1)).astype(int))

[1 1 1 1 1]
[[1]
 [1]
 [1]
 [1]
 [1]]
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]
[[[1 1]
  [1 1]
  [1 1]
  [1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]
  [1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]
  [1 1]
  [1 1]
  [1 1]]]
[[[[1]
   [1]]

  [[1]
   [1]]

  [[1]
   [1]]]


 [[[1]
   [1]]

  [[1]
   [1]]

  [[1]
   [1]]]


 [[[1]
   [1]]

  [[1]
   [1]]

  [[1]
   [1]]]


 [[[1]
   [1]]

  [[1]
   [1]]

  [[1]
   [1]]]]


Задание 3.

Выполните для векторов выше `reshape` в "форму"
* с двумя компонентами
* с тремя компонентами
* с четырьмя компонентами

In [4]:
a = np.ones(5)
print(a.reshape(1, 5))
print(a.reshape(1,1,5))
print(a.reshape(1,1,1,5))
print()
a = np.ones((5, 1))
print(a.reshape(5))
print(a.reshape(1,1,5))
print(a.reshape(1,1,1,5))
print()
a = np.ones((3,6,2))
print(a.reshape(36))
print(a.reshape(2, 18))
print(a.reshape(2,2,3,3))
print()
a = np.ones((4,3,2,1))
print(a.reshape(24))
print(a.reshape(3, 8))
print(a.reshape(2,3,4))

[[1. 1. 1. 1. 1.]]
[[[1. 1. 1. 1. 1.]]]
[[[[1. 1. 1. 1. 1.]]]]

[1. 1. 1. 1. 1.]
[[[1. 1. 1. 1. 1.]]]
[[[[1. 1. 1. 1. 1.]]]]

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]]

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


Задание 4.

Для вектора ниже посчитайте его
* Максимум по 1 оси
* Минимум по 0 оси
* Сумму по всем осям
* Среднее по 0 оси
* Медиану по 1 оси

In [5]:
v = np.random.randint(0, 9, size=(5, 7))

In [6]:
print(v)
print()
print(v.max(axis=1))
print(v.min(axis=0))
print(v.sum(axis=0))
print(v.sum(axis=1))
print(v.mean(axis=0))
print(np.median(v, axis=1))

[[8 4 1 1 1 8 6]
 [8 2 2 5 6 2 0]
 [4 4 2 1 2 3 4]
 [3 4 3 0 0 5 8]
 [8 1 0 7 8 3 4]]

[8 8 4 8 8]
[3 1 0 0 0 2 0]
[31 15  8 14 17 21 22]
[29 25 20 23 31]
[6.2 3.  1.6 2.8 3.4 4.2 4.4]
[4. 2. 3. 3. 4.]


Задание 5.

Для всё того же вектора `v` выведите
* Его shape
* 0 компоненту его "формы"
* 1 компоненту его "формы"

In [7]:
print(v)
print(v.shape)
print(v[0].astype(int).tolist())
print(v[1].astype(int).tolist())

[[8 4 1 1 1 8 6]
 [8 2 2 5 6 2 0]
 [4 4 2 1 2 3 4]
 [3 4 3 0 0 5 8]
 [8 1 0 7 8 3 4]]
(5, 7)
[8, 4, 1, 1, 1, 8, 6]
[8, 2, 2, 5, 6, 2, 0]


Задание 6.

Для этого же вектора выведите
* Все числа больше 5
* Все числа меньше 7 в обратном порядке
* Все числа больше 3, которые делятся на 4 без остатка
* Все числа, остаток от деления на 5 которых равен 3
* Индекс максимума
* Индекс минимума
* Cписок с индексами элементов отсортированного массива в исходном (неотсортированном)

In [8]:
print(v)
print()
(print(v[v>5]))
print(v[v<7][::-1])
print(v[(v>3) & (v % 4 == 0)])
print(v[v%5==3])
print(v.argmax())
print(v.argmin())
print(v.argsort())

[[8 4 1 1 1 8 6]
 [8 2 2 5 6 2 0]
 [4 4 2 1 2 3 4]
 [3 4 3 0 0 5 8]
 [8 1 0 7 8 3 4]]

[8 8 6 8 6 8 8 7 8]
[4 3 0 1 5 0 0 3 4 3 4 3 2 1 2 4 4 0 2 6 5 2 2 6 1 1 1 4]
[8 4 8 8 4 4 4 4 8 8 8 4]
[8 8 8 3 3 3 8 8 8 3]
0
13
[[2 3 4 1 6 0 5]
 [6 1 2 5 3 4 0]
 [3 2 4 5 0 1 6]
 [3 4 0 2 1 5 6]
 [2 1 5 6 3 0 4]]


Задание 7.

Выполните следующие операции над вектором (независимо, не обязательно делать это в последовательности):
* Умножьте его на 3
* Разделите на 7
* Возведите в степень $\frac{2}{3}$
* Посчитайте $\sin$ от него
* Посчитайте $\log$ от него

In [9]:
a = np.random.randint(1, 9, size=(7))
print(a)
print()
print(a*3)
print(a/7)
print(a**(2/3))
print(np.sin(a))
print(np.log(a))

[1 4 4 3 8 1 4]

[ 3 12 12  9 24  3 12]
[0.14285714 0.57142857 0.57142857 0.42857143 1.14285714 0.14285714
 0.57142857]
[1.         2.5198421  2.5198421  2.08008382 4.         1.
 2.5198421 ]
[ 0.84147098 -0.7568025  -0.7568025   0.14112001  0.98935825  0.84147098
 -0.7568025 ]
[0.         1.38629436 1.38629436 1.09861229 2.07944154 0.
 1.38629436]


### Разные инициализации + индексирование (3 балла)

Задание 8.

Необходимо построить квадрат $3 \times 3$ из нечётных чисел

In [10]:
a = np.arange(1, 18, 2)
print(a.reshape(3,3))

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]


Задание 9.

Необходимо построить квадрат $4 \times 4$ из четных чисел в обратном порядке

In [11]:
a = np.arange(0, 32, 2)[::-1]
print(a.reshape(4,4))

[[30 28 26 24]
 [22 20 18 16]
 [14 12 10  8]
 [ 6  4  2  0]]


Задание 10.

Необходимо построить сетку координат $11 \times 11$ с точкой $(0,0)$ в центре и шагом $0.1$ между клетками

In [12]:
a = np.arange(-60, 61)
print((a/10).reshape(11,11))

[[-6.  -5.9 -5.8 -5.7 -5.6 -5.5 -5.4 -5.3 -5.2 -5.1 -5. ]
 [-4.9 -4.8 -4.7 -4.6 -4.5 -4.4 -4.3 -4.2 -4.1 -4.  -3.9]
 [-3.8 -3.7 -3.6 -3.5 -3.4 -3.3 -3.2 -3.1 -3.  -2.9 -2.8]
 [-2.7 -2.6 -2.5 -2.4 -2.3 -2.2 -2.1 -2.  -1.9 -1.8 -1.7]
 [-1.6 -1.5 -1.4 -1.3 -1.2 -1.1 -1.  -0.9 -0.8 -0.7 -0.6]
 [-0.5 -0.4 -0.3 -0.2 -0.1  0.   0.1  0.2  0.3  0.4  0.5]
 [ 0.6  0.7  0.8  0.9  1.   1.1  1.2  1.3  1.4  1.5  1.6]
 [ 1.7  1.8  1.9  2.   2.1  2.2  2.3  2.4  2.5  2.6  2.7]
 [ 2.8  2.9  3.   3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8]
 [ 3.9  4.   4.1  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9]
 [ 5.   5.1  5.2  5.3  5.4  5.5  5.6  5.7  5.8  5.9  6. ]]


Задание 11.

Замощение сетки $8\times8$ при помощи $0$ и $1$ в шахматном порядке, клетка с индексом $(0,0)$ замощается $1$

In [13]:
a=np.zeros((8,8))
a[0:8:2, 0:8:2] = 1
a[1:8:2, 1:8:2] = 1
print(a)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


Задание 12.

То же замощение, но клетка с индексом $(0,0)$ замощается $0$

In [14]:
a=np.zeros((8,8))
a[0:8:2, 1:8:2] = 1
a[1:8:2, 0:8:2] = 1
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


Задание 13.

Необходимо построить нижне-треугольную матрицу переменного размера (задается передачей параметра в функцию). Это единичная матрица,замощённая $1$ под главной диагональю

In [15]:
a = np.ones(5)
print(np.tril(a, 0))

[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]]


Задание 14.

Необходимо построить верхне-треугольную матрицу переменного размера. Это единичная матрица, замощённая $1$ над главной диагональю

In [16]:
b = np.ones(5)
print(np.triu(b, 0))

[[1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 1.]]


Задание 15.

Необходимо построить матрицу, в которой единицы стоят на побочной диагонали (идущей из левого нижнего угла в правый верхний), в остальных местах стоят $0$

In [17]:
a = np.eye(5)[::-1]
print(a)

[[0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]


### Операции + аггрегации (3 балла)

Задание 16.

Дана выборка $\{X_i\}$ некоторой случайной величины $X$, необходимо оценить
* Математическое ожидание $E[X] = \frac{1}{N}\sum_{i=1}^N X_i$ этой случайной величины
* Дисперсию $D[X] = \frac{1}{N}\sum_{i=1}^N (X_i - E[X])^2$ этой случайной величины

In [18]:
def expected_value(x):
    assert len(x) > 0
    return sum(x) / len(x)


def dispersion(x):
    assert len(x) > 0
    d = 0
    e = expected_value(x)
    for x_i in x:
        d += (x_i - e) ** 2
    return d / len(x)

In [19]:
def expected_value_np(x):
    return  np.sum(x) / np.size(x)

In [20]:
def dispersion_np(x):
    return np.var(x)

In [21]:
np.testing.assert_array_equal(expected_value([1]), expected_value_np(np.array([1])))
np.testing.assert_array_equal(expected_value([3, 4]), expected_value_np(np.array([3, 4])))
np.testing.assert_array_equal(expected_value([-1, 0, 1]), expected_value_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(expected_value([-99, -98]), expected_value_np(np.array([-99, -98])))

np.testing.assert_array_equal(dispersion([1]), dispersion_np(np.array([1])))
np.testing.assert_array_equal(dispersion([3, 4]), dispersion_np(np.array([3, 4])))
np.testing.assert_array_equal(dispersion([-1, 0, 1]), dispersion_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(dispersion([-99, -98]), dispersion_np(np.array([-99, -98])))

Задание 17.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое квадратов разностей их значений

In [40]:
def mean_square_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    # Здесь и далее эти проверки !не нужно! дублировать в свои функции; Здесь они для того, чтобы лишний раз подчеркнуть валидность входных данных
    s = 0
    for i in range(len(y1)):
        s += (y1[i] - y2[i]) ** 2
    return s / len(y1)

In [41]:
def mean_square_difference_np(y1, y2):
    return ((np.mean(y1))-(np.mean(y2)))**2

In [42]:
assert mean_square_difference([1], [1]) == mean_square_difference_np(np.array([1]), np.array([1]))
assert mean_square_difference([1, 2], [1, 2]) == mean_square_difference_np(np.array([1, 2]), np.array([1, 2]))

Задание 18.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое модулей разностей их значений

In [25]:
def mean_abs_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    s = 0
    for i in range(len(y1)):
        s += abs(y1[i] - y2[i])
    return s / len(y1)

In [26]:
def mean_abs_difference_np(y1, y2):
    return np.mean(abs(y1-y2))

In [27]:
assert mean_abs_difference([1], [1]) == mean_abs_difference_np(np.array([1]), np.array([1]))
assert mean_abs_difference([1, 2], [1, 2]) == mean_abs_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_abs_difference([-1, 1], [0, 0]) == mean_abs_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_abs_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_abs_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 19.

Даны два вектора $y_1$ и $y_2$, в которых присутствуют только $0$ и $1$. Необходимо посчитать вероятность совпадения - в скольких точках значения двух векторов совпадают

In [28]:
def matching_proba(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    assert len(set(y1)) <= 2
    assert len(set(y2)) <= 2
    assert 0 in set(y1) or 1 in set(y1) or (0 in set(y1) and 1 in set(y1))
    assert 0 in set(y2) or 1 in set(y2) or (0 in set(y2) and 1 in set(y2))

    return sum([y1[i] == y2[i] for i in range(len(y1))]) / len(y1)

In [29]:
def matching_proba_np(y1, y2):
    a = y1+y2
    a = a[a!=1]
    return np.size(a)/np.size(y1)

In [30]:
np.testing.assert_array_equal(matching_proba([0, 1], [1, 0]), matching_proba_np(np.array([0, 1]), np.array([1, 0])))
np.testing.assert_array_equal(matching_proba([0, 1, 0, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 1, 0, 1]), np.array([0, 0, 1, 1])))
np.testing.assert_array_equal(matching_proba([0, 0, 1, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1])))

Задание 20.

Даны два вектора: $y_1$, $y_2$. В $y_1$ и $y_2$ присутствуют только $0$ и $1$.

Необходимо найти границы (индексы), такие, что если мы разделим вдоль какой-то из этих границ оба вектора на две части, то
* в левой части пересекающихся в $y_1$ и $y_2$ нулей будет строго больше, чем пересекающихся единиц или непересекающихся элементов
* в правой - пересекающихся единиц строго больше, чем пересекающихся нулей или непересекающихся элементов.

Если какая-то из частей не содержит элементов вовсе, то будем считать, что она подходит под условие.

In [31]:
def find_thresholds(y1, y2, debug=False):
    assert len(y1) == len(y2) and len(y1) > 0
    n = len(y1)
    matching_zeros = [1 if y1[i] == y2[i] == 0 else 0 for i in range(n)]
    matching_ones = [1 if y1[i] == y2[i] == 1 else 0 for i in range(n)]
    res = []
    if sum(matching_ones) / n > 0.5:
        res.append(0)
    for i in range(1, n):
        if debug: # если вам непонятна логика работы этой функции, передайте третьим аргументом True
            print(matching_zeros[:i], matching_ones[i:], i)
        if sum(matching_zeros[:i]) / i > 0.5 and sum(matching_ones[i:]) / (n - i) > 0.5:
            res.append(i)
    if sum(matching_zeros) / n > 0.5:
        res.append(n)
    return res

In [32]:
def find_thresholds_np(y1, y2):
    return # Ваш код

In [33]:
np.testing.assert_array_equal(find_thresholds([0], [0]), find_thresholds_np(np.array([0]), np.array([0])))
np.testing.assert_array_equal(find_thresholds([1], [1]), find_thresholds_np(np.array([1]), np.array([1])))
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 1], [0, 0, 1, 1]), 
    find_thresholds_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1]))
)
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 0, 0, 1, 1, 1], [0, 0, 0, 0, 0, 1, 1, 1]),
    find_thresholds_np(np.array([0, 0, 1, 0, 0, 1, 1, 1]), np.array([0, 0, 0, 0, 0, 1, 1, 1]))
)

AssertionError: 
Arrays are not equal

Mismatched elements: 1 / 1 (100%)
 x: array([1])
 y: array(None, dtype=object)

### Разные действия с матрицами (3 балла)

Задание 21.

Дана матрица размера $(32, 3, 16, 16)$, заполненная случайными числами от 0 до 9. При помощи **ровно двух** преобразований приведите её к виду $(32, 1)$. При выполнении задания **можно** создавать вспомогательные матрицы!

In [34]:
data = np.random.randint(0, 10, size=(32, 3, 16, 16))
data2 = np.ones((3*16*16,1))

data = data.reshape(32, 3*16*16)
data = np.matmul(data, data2)

assert data.shape == (32, 1)

Задание 22.

Даны две матрицы $m_1$ размером $(32, 256)$ и $m_2$ размером $(32, 512)$, а также две вспомогательные матрицы $W_1$ размером $(256, 32)$ и $W_2$ размером $(512, 16)$. Используя **все** данные матрицы, сделайте так, чтобы на выходе получилась **ровно одна** матрица размером $(32, 32)$

In [35]:
m1 = np.random.randint(0, 10, size=(32, 256))
m2 = np.random.randint(0, 10, size=(32, 512))
W1 = np.random.randint(0, 10, size=(256, 32))
W2 = np.random.randint(0, 10, size=(512, 16))

result = m2.dot(W2).dot((m2.dot(W2).reshape(-1, 32)).dot(m1).dot(W1))

assert result.shape == (32, 32)

Задание 23.

Приведите полученную на последнем шаге матрицу к виду $(32, 3)$ и сделайте так, чтобы все значения в этой матрице были в промежутке от $0$ до $1$

In [36]:
# Вжух! (∩｀-´)⊃━☆ﾟ.*･｡ﾟ
c = np.random.randint(0, 9, size=(32, 3))
d  =np.zeros((32,3))
result = np.matmul(result, c)
z = d*result
c = np.random.randint(0, 1, size=(32, 3))
result = c+z

assert result.shape == (32, 3)
assert ((result >= 0) & (result <= 1)).all()