## Домашнее задание

В этой тетрадке вам предлагается реализовать задания при помощи библиотеки numpy. Крайне желательно при выполнении разных заданий не использовать циклы. Если вы не понимаете, как выполнить конкретную задачу без циклов - убирайте их постепенно, разбейте выполнение задачи на этапы и постепенно векторизуйте каждый этап.

Если вам непонятно, как выполнить ту или иную операцию - не стесняйтесь гуглить, если над вами повис дедлайн, а вы всё ещё на чём-то застряли - пишите преподу/в чат, это ок.

**Обсудить решение лучше и сделать в итоге хоть что-то гораздо лучше, чем скатать чужой код или сдать пустую тетрадку.**

In [2]:
import numpy as np

### Drill (1 балл)

Задание 1.

Инициализируйте нулями массивы следующих форм:

* (5)
* (5, 1)
* (10, 2)
* (3, 6, 2)
* (4, 3, 2, 1)

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.zeros((5,1))

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [9]:
np.zeros((10, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [10]:
np.zeros((3, 6, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [11]:
np.zeros((4, 3, 2, 1))

array([[[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]],


       [[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]],


       [[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]],


       [[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]]])

Задание 2.

Инициализируйте единицами массивы таких же форм и приведите их к целочисленному виду:

In [13]:
np.ones(5, dtype=int)

array([1, 1, 1, 1, 1])

In [14]:
np.ones((5,1), dtype=int)

array([[1],
       [1],
       [1],
       [1],
       [1]])

In [15]:
np.ones((10, 2), dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [16]:
np.ones((3, 6, 2), dtype=int)

array([[[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]])

In [17]:
np.ones((4, 3, 2, 1), dtype=int)

array([[[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]],


       [[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]],


       [[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]],


       [[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]]])

Задание 3.

Выполните для векторов выше `reshape` в "форму"
* с двумя компонентами
* с тремя компонентами
* с четырьмя компонентами

In [21]:
print(np.ones(5, dtype=int).reshape((1, 5)))
print(np.ones(5, dtype=int).reshape((1, 1, 5)))
print(np.ones(5, dtype=int).reshape((1, 1, 1, 5)))

[[1 1 1 1 1]]
[[[1 1 1 1 1]]]
[[[[1 1 1 1 1]]]]


In [24]:
print(np.ones((1,5), dtype=int).reshape((1, 1, 5)))
print(np.ones((1,5), dtype=int).reshape((1, 1, 1, 5)))

[1 1 1 1 1]
[[[1 1 1 1 1]]]
[[[[1 1 1 1 1]]]]


In [25]:
print(np.ones((10,2), dtype=int).reshape((2, 2, 5)))
print(np.ones((10,2), dtype=int).reshape((2, 1, 2, 5)))

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[[[1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]]]
[[[[1 1 1 1 1]
   [1 1 1 1 1]]]


 [[[1 1 1 1 1]
   [1 1 1 1 1]]]]


In [27]:
print(np.ones((3, 6, 2), dtype=int).reshape((6, 6)))
print(np.ones((3, 6, 2), dtype=int).reshape((2, 2, 3, 3)))

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
[[[[1 1 1]
   [1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]]]


 [[[1 1 1]
   [1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]]]]


In [29]:
print(np.ones((4, 3, 2, 1), dtype=int).reshape((6, 4)))
print(np.ones((4, 3, 2, 1), dtype=int).reshape((2, 2, 6)))

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[[1 1 1 1 1 1]
  [1 1 1 1 1 1]]

 [[1 1 1 1 1 1]
  [1 1 1 1 1 1]]]


Задание 4.

Для вектора ниже посчитайте его
* Максимум по 1 оси
* Минимум по 0 оси
* Сумму по всем осям
* Среднее по 0 оси
* Медиану по 1 оси

In [31]:
v = np.random.randint(0, 9, size=(5, 7))

In [37]:
print(v)
print(v.max(axis=1))
print(v.min(axis=0))
print(v.sum())
print(v.mean(axis=0))
print(np.median(v, axis=1))

[[2 3 7 6 8 5 3]
 [2 1 2 3 6 0 7]
 [7 8 2 7 5 2 0]
 [3 3 8 1 1 5 7]
 [7 6 5 0 5 1 4]]
[7 8 8 7 8 5 7]
[2 1 2 0 1 0 0]
142
[4.2 4.2 4.8 3.4 5.  2.6 4.2]
[5. 2. 5. 3. 5.]


Задание 5.

Для всё того же вектора `v` выведите
* Его shape
* 0 компоненту его "формы"
* 1 компоненту его "формы"

In [38]:
print(v.shape)
print(v.shape[0])
print(v.shape[1])

(5, 7)
5
7


Задание 6.

Для этого же вектора выведите
* Все числа больше 5
* Все числа меньше 7 в обратном порядке
* Все числа больше 3, которые делятся на 4 без остатка
* Все числа, остаток от деления на 5 которых равен 3
* Индекс максимума
* Индекс минимума
* Cписок с индексами элементов отсортированного массива в исходном (неотсортированном)

In [40]:
v[v > 5]

array([7, 6, 8, 6, 7, 7, 8, 7, 8, 7, 7, 6])

In [44]:
v[v < 7][::-1]

array([4, 1, 5, 0, 5, 6, 5, 1, 1, 3, 3, 0, 2, 5, 2, 0, 6, 3, 2, 1, 2, 3,
       5, 6, 3, 2])

In [45]:
v[(v > 3) & (v % 4 == 0)]

array([8, 8, 8, 4])

In [46]:
v[(v % 5 == 3)]

array([3, 8, 3, 3, 8, 3, 3, 8])

In [53]:
np.argmax(v)

4

In [51]:
np.argmin(v)

12

In [54]:
np.argsort(v)

array([[0, 1, 6, 5, 3, 2, 4],
       [5, 1, 0, 2, 3, 4, 6],
       [6, 2, 5, 4, 0, 3, 1],
       [3, 4, 0, 1, 5, 6, 2],
       [3, 5, 6, 2, 4, 1, 0]], dtype=int64)

Задание 7.

Выполните следующие операции над вектором (независимо, не обязательно делать это в последовательности):
* Умножьте его на 3
* Разделите на 7
* Возведите в степень $\frac{2}{3}$
* Посчитайте $\sin$ от него
* Посчитайте $\log$ от него

In [60]:
a = np.random.randint(1, 9, size=(5, 7))

In [61]:
a*3

array([[24,  9,  9,  6,  6, 24, 18],
       [ 3, 18, 18, 24,  3, 21,  9],
       [18, 21, 21, 18, 12, 18, 21],
       [24, 15, 18, 18,  6, 24,  3],
       [ 6, 24, 18,  9, 15,  3, 18]])

In [62]:
a/7

array([[1.14285714, 0.42857143, 0.42857143, 0.28571429, 0.28571429,
        1.14285714, 0.85714286],
       [0.14285714, 0.85714286, 0.85714286, 1.14285714, 0.14285714,
        1.        , 0.42857143],
       [0.85714286, 1.        , 1.        , 0.85714286, 0.57142857,
        0.85714286, 1.        ],
       [1.14285714, 0.71428571, 0.85714286, 0.85714286, 0.28571429,
        1.14285714, 0.14285714],
       [0.28571429, 1.14285714, 0.85714286, 0.42857143, 0.71428571,
        0.14285714, 0.85714286]])

In [63]:
a**(2/3)

array([[4.        , 2.08008382, 2.08008382, 1.58740105, 1.58740105,
        4.        , 3.30192725],
       [1.        , 3.30192725, 3.30192725, 4.        , 1.        ,
        3.65930571, 2.08008382],
       [3.30192725, 3.65930571, 3.65930571, 3.30192725, 2.5198421 ,
        3.30192725, 3.65930571],
       [4.        , 2.92401774, 3.30192725, 3.30192725, 1.58740105,
        4.        , 1.        ],
       [1.58740105, 4.        , 3.30192725, 2.08008382, 2.92401774,
        1.        , 3.30192725]])

In [64]:
np.sin(a)

array([[ 0.98935825,  0.14112001,  0.14112001,  0.90929743,  0.90929743,
         0.98935825, -0.2794155 ],
       [ 0.84147098, -0.2794155 , -0.2794155 ,  0.98935825,  0.84147098,
         0.6569866 ,  0.14112001],
       [-0.2794155 ,  0.6569866 ,  0.6569866 , -0.2794155 , -0.7568025 ,
        -0.2794155 ,  0.6569866 ],
       [ 0.98935825, -0.95892427, -0.2794155 , -0.2794155 ,  0.90929743,
         0.98935825,  0.84147098],
       [ 0.90929743,  0.98935825, -0.2794155 ,  0.14112001, -0.95892427,
         0.84147098, -0.2794155 ]])

In [65]:
np.log(a)

array([[2.07944154, 1.09861229, 1.09861229, 0.69314718, 0.69314718,
        2.07944154, 1.79175947],
       [0.        , 1.79175947, 1.79175947, 2.07944154, 0.        ,
        1.94591015, 1.09861229],
       [1.79175947, 1.94591015, 1.94591015, 1.79175947, 1.38629436,
        1.79175947, 1.94591015],
       [2.07944154, 1.60943791, 1.79175947, 1.79175947, 0.69314718,
        2.07944154, 0.        ],
       [0.69314718, 2.07944154, 1.79175947, 1.09861229, 1.60943791,
        0.        , 1.79175947]])

### Разные инициализации + индексирование (3 балла)

Задание 8.

Необходимо построить квадрат $3 \times 3$ из нечётных чисел

In [73]:
np.arange(1, 18, 2).reshape(3, 3)

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

Задание 9.

Необходимо построить квадрат $4 \times 4$ из четных чисел в обратном порядке

In [76]:
np.arange(32, 0, -2).reshape(4, 4)

array([[32, 30, 28, 26],
       [24, 22, 20, 18],
       [16, 14, 12, 10],
       [ 8,  6,  4,  2]])

Задание 10.

Необходимо построить сетку координат $11 \times 11$ с точкой $(0,0)$ в центре и шагом $0.1$ между клетками

In [86]:
np.around(np.arange(-6.0, 6.1, 0.1).reshape(11, 11), decimals=2)

array([[-6. , -5.9, -5.8, -5.7, -5.6, -5.5, -5.4, -5.3, -5.2, -5.1, -5. ],
       [-4.9, -4.8, -4.7, -4.6, -4.5, -4.4, -4.3, -4.2, -4.1, -4. , -3.9],
       [-3.8, -3.7, -3.6, -3.5, -3.4, -3.3, -3.2, -3.1, -3. , -2.9, -2.8],
       [-2.7, -2.6, -2.5, -2.4, -2.3, -2.2, -2.1, -2. , -1.9, -1.8, -1.7],
       [-1.6, -1.5, -1.4, -1.3, -1.2, -1.1, -1. , -0.9, -0.8, -0.7, -0.6],
       [-0.5, -0.4, -0.3, -0.2, -0.1, -0. ,  0.1,  0.2,  0.3,  0.4,  0.5],
       [ 0.6,  0.7,  0.8,  0.9,  1. ,  1.1,  1.2,  1.3,  1.4,  1.5,  1.6],
       [ 1.7,  1.8,  1.9,  2. ,  2.1,  2.2,  2.3,  2.4,  2.5,  2.6,  2.7],
       [ 2.8,  2.9,  3. ,  3.1,  3.2,  3.3,  3.4,  3.5,  3.6,  3.7,  3.8],
       [ 3.9,  4. ,  4.1,  4.2,  4.3,  4.4,  4.5,  4.6,  4.7,  4.8,  4.9],
       [ 5. ,  5.1,  5.2,  5.3,  5.4,  5.5,  5.6,  5.7,  5.8,  5.9,  6. ]])

Задание 11.

Замощение сетки $8\times8$ при помощи $0$ и $1$ в шахматном порядке, клетка с индексом $(0,0)$ замощается $1$

In [89]:
a = np.zeros((8, 8))
a[::2, 0::2] = 1
a[1::2, 1::2] = 1
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

Задание 12.

То же замощение, но клетка с индексом $(0,0)$ замощается $0$

In [90]:
a = np.zeros((8, 8))
a[::2, 1::2] = 1
a[1::2, 0::2] = 1
a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

Задание 13.

Необходимо построить нижне-треугольную матрицу переменного размера (задается передачей параметра в функцию). Это единичная матрица,замощённая $1$ под главной диагональю

In [9]:
def tril(n):
    a = np.zeros((n, n))
    a[np.tril_indices(n)] = 1
    a = a - np.eye(n)
    return a
tril(4)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.]])

Задание 14.

Необходимо построить верхне-треугольную матрицу переменного размера. Это единичная матрица, замощённая $1$ над главной диагональю

In [10]:
def triu(n):
    a = np.zeros((n, n))
    a[np.triu_indices(n)] = 1
    a = a - np.eye(n)
    return a
triu(4)

array([[0., 1., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

Задание 15.

Необходимо построить матрицу, в которой единицы стоят на побочной диагонали (идущей из левого нижнего угла в правый верхний), в остальных местах стоят $0$

In [22]:
def opp_diag(n):
    a = np.eye(n)
    a = np.fliplr(a)
    return a
opp_diag(4)

array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.]])

### Операции + аггрегации (3 балла)

Задание 16.

Дана выборка $\{X_i\}$ некоторой случайной величины $X$, необходимо оценить
* Математическое ожидание $E[X] = \frac{1}{N}\sum_{i=1}^N X_i$ этой случайной величины
* Дисперсию $D[X] = \frac{1}{N}\sum_{i=1}^N (X_i - E[X])^2$ этой случайной величины

In [24]:
def expected_value(x):
    assert len(x) > 0
    return sum(x) / len(x)


def dispersion(x):
    assert len(x) > 0
    d = 0
    e = expected_value(x)
    for x_i in x:
        d += (x_i - e) ** 2
    return d / len(x)

In [25]:
def expected_value_np(x):
    return x.mean()

In [31]:
def dispersion_np(x):
    x = (x - expected_value_np(x))**2
    return x.mean()

In [32]:
np.testing.assert_array_equal(expected_value([1]), expected_value_np(np.array([1])))
np.testing.assert_array_equal(expected_value([3, 4]), expected_value_np(np.array([3, 4])))
np.testing.assert_array_equal(expected_value([-1, 0, 1]), expected_value_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(expected_value([-99, -98]), expected_value_np(np.array([-99, -98])))

np.testing.assert_array_equal(dispersion([1]), dispersion_np(np.array([1])))
np.testing.assert_array_equal(dispersion([3, 4]), dispersion_np(np.array([3, 4])))
np.testing.assert_array_equal(dispersion([-1, 0, 1]), dispersion_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(dispersion([-99, -98]), dispersion_np(np.array([-99, -98])))

Задание 17.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое квадратов разностей их значений

In [33]:
def mean_square_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    # Здесь и далее эти проверки !не нужно! дублировать в свои функции; Здесь они для того, чтобы лишний раз подчеркнуть валидность входных данных
    s = 0
    for i in range(len(y1)):
        s += (y1[i] - y2[i]) ** 2
    return s / len(y1)

In [34]:
def mean_square_difference_np(y1, y2):
    return ((y1-y2)**2).mean()

In [35]:
assert mean_square_difference([1], [1]) == mean_square_difference_np(np.array([1]), np.array([1]))
assert mean_square_difference([1, 2], [1, 2]) == mean_square_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_square_difference([-1, 1], [0, 0]) == mean_square_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_square_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_square_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 18.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое модулей разностей их значений

In [36]:
def mean_abs_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    s = 0
    for i in range(len(y1)):
        s += abs(y1[i] - y2[i])
    return s / len(y1)

In [44]:
def mean_abs_difference_np(y1, y2):
    return np.abs(y1-y2).mean()

In [45]:
assert mean_abs_difference([1], [1]) == mean_abs_difference_np(np.array([1]), np.array([1]))
assert mean_abs_difference([1, 2], [1, 2]) == mean_abs_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_abs_difference([-1, 1], [0, 0]) == mean_abs_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_abs_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_abs_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 19.

Даны два вектора $y_1$ и $y_2$, в которых присутствуют только $0$ и $1$. Необходимо посчитать вероятность совпадения - в скольких точках значения двух векторов совпадают

In [47]:
def matching_proba(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    assert len(set(y1)) <= 2
    assert len(set(y2)) <= 2
    assert 0 in set(y1) or 1 in set(y1) or (0 in set(y1) and 1 in set(y1))
    assert 0 in set(y2) or 1 in set(y2) or (0 in set(y2) and 1 in set(y2))

    return sum([y1[i] == y2[i] for i in range(len(y1))]) / len(y1)

In [49]:
def matching_proba_np(y1, y2):
    return (y1==y2).mean()

In [50]:
np.testing.assert_array_equal(matching_proba([0, 1], [1, 0]), matching_proba_np(np.array([0, 1]), np.array([1, 0])))
np.testing.assert_array_equal(matching_proba([0, 1, 0, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 1, 0, 1]), np.array([0, 0, 1, 1])))
np.testing.assert_array_equal(matching_proba([0, 0, 1, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1])))

Задание 20.

Даны два вектора: $y_1$, $y_2$. В $y_1$ и $y_2$ присутствуют только $0$ и $1$.

Необходимо найти границы (индексы), такие, что если мы разделим вдоль какой-то из этих границ оба вектора на две части, то
* в левой части пересекающихся в $y_1$ и $y_2$ нулей будет строго больше, чем пересекающихся единиц или непересекающихся элементов
* в правой - пересекающихся единиц строго больше, чем пересекающихся нулей или непересекающихся элементов.

Если какая-то из частей не содержит элементов вовсе, то будем считать, что она подходит под условие.

In [99]:
def find_thresholds(y1, y2, debug=False):
    assert len(y1) == len(y2) and len(y1) > 0
    n = len(y1)
    matching_zeros = [1 if y1[i] == y2[i] == 0 else 0 for i in range(n)]
    matching_ones = [1 if y1[i] == y2[i] == 1 else 0 for i in range(n)]
    res = []
    if sum(matching_ones) / n > 0.5:
        res.append(0)
    for i in range(1, n):
        if debug: # если вам непонятна логика работы этой функции, передайте третьим аргументом True
            print(matching_zeros[:i], matching_ones[i:], i)
        if sum(matching_zeros[:i]) / i > 0.5 and sum(matching_ones[i:]) / (n - i) > 0.5:
            res.append(i)
    if sum(matching_zeros) / n > 0.5:
        res.append(n)
    return res

In [163]:
def find_thresholds_np(y1, y2):
    matching_zeros = (y1==y2) & (y1==0)
    matching_ones = (y1==y2) & (y1==1)
    sum_m_z = np.cumsum(matching_zeros)
    matching_ones = matching_ones[::-1]
    sum_m_o = np.cumsum(matching_ones)
    sum_m_z = sum_m_z / np.arange(1, len(y1)+1)
    sum_m_o = sum_m_o / np.arange(1, len(y1)+1)
    sum_m_z = np.array(sum_m_z)
    sum_m_o = np.array(sum_m_o)
    sum_m_z = np.insert(sum_m_z, 0, 1)
    sum_m_o = np.insert(sum_m_o, 0, 1)
    sum_m_z = (sum_m_z > 0.5) 
    sum_m_o = (sum_m_o > 0.5) 
    sum_m_o = sum_m_o[::-1]
    res = sum_m_o * sum_m_z
    return np.nonzero(res)[0]

In [164]:
np.testing.assert_array_equal(find_thresholds([0], [0]), find_thresholds_np(np.array([0]), np.array([0])))
np.testing.assert_array_equal(find_thresholds([1], [1]), find_thresholds_np(np.array([1]), np.array([1])))
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 1], [0, 0, 1, 1]), 
    find_thresholds_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1]))
)
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 0, 0, 1, 1, 1], [0, 0, 0, 0, 0, 1, 1, 1]),
    find_thresholds_np(np.array([0, 0, 1, 0, 0, 1, 1, 1]), np.array([0, 0, 0, 0, 0, 1, 1, 1]))
)

### Разные действия с матрицами (3 балла)

Задание 21.

Дана матрица размера $(32, 3, 16, 16)$, заполненная случайными числами от 0 до 9. При помощи **ровно двух** преобразований приведите её к виду $(32, 1)$. При выполнении задания **можно** создавать вспомогательные матрицы!

In [98]:
data = np.random.randint(0, 10, size=(32, 3, 16, 16))

# Преобразование 1
data = data.reshape((32, 768))
# Преобразование 2
data = np.dot(data, np.zeros((768, 1)))

assert data.shape == (32, 1)

Задание 22.

Даны две матрицы $m_1$ размером $(32, 256)$ и $m_2$ размером $(32, 512)$, а также две вспомогательные матрицы $W_1$ размером $(256, 32)$ и $W_2$ размером $(512, 16)$. Используя **все** данные матрицы, сделайте так, чтобы на выходе получилась **ровно одна** матрица размером $(32, 32)$

In [180]:
m1 = np.random.randint(0, 10, size=(32, 256))
m2 = np.random.randint(0, 10, size=(32, 512))
W1 = np.random.randint(0, 10, size=(256, 32))
W2 = np.random.randint(0, 10, size=(512, 16))
result = np.dot(m1, np.dot(np.dot(np.dot(W1, np.dot(m2, W2)),W2.transpose()),m2.transpose()))
assert result.shape == (32, 32)

Задание 23.

Приведите полученную на последнем шаге матрицу к виду $(32, 3)$ и сделайте так, чтобы все значения в этой матрице были в промежутке от $0$ до $1$

In [189]:
# Вжух! (∩｀-´)⊃━☆ﾟ.*･｡ﾟ
result = np.dot(m1, np.dot(np.dot(np.dot(W1, np.dot(m2, W2)),W2.transpose()),m2.transpose())) # то, что мы получили на предыдущем шаге 
result = np.abs(np.dot(result, np.ones((32, 3))))/(np.abs(np.dot(result, np.ones((32, 3)))).max())
assert result.shape == (32, 3)
assert ((result >= 0) & (result <= 1)).all()

[[0.23521801 0.23521801 0.23521801]
 [0.12466331 0.12466331 0.12466331]
 [0.11669614 0.11669614 0.11669614]
 [0.25142093 0.25142093 0.25142093]
 [0.39480104 0.39480104 0.39480104]
 [0.34884678 0.34884678 0.34884678]
 [0.19111507 0.19111507 0.19111507]
 [0.41927236 0.41927236 0.41927236]
 [0.18034925 0.18034925 0.18034925]
 [0.15082852 0.15082852 0.15082852]
 [0.02544854 0.02544854 0.02544854]
 [0.35715733 0.35715733 0.35715733]
 [0.10738887 0.10738887 0.10738887]
 [0.26303361 0.26303361 0.26303361]
 [0.03910722 0.03910722 0.03910722]
 [0.03851026 0.03851026 0.03851026]
 [0.5529213  0.5529213  0.5529213 ]
 [0.05525264 0.05525264 0.05525264]
 [0.30544223 0.30544223 0.30544223]
 [0.17669576 0.17669576 0.17669576]
 [0.19039133 0.19039133 0.19039133]
 [0.19222667 0.19222667 0.19222667]
 [0.04936105 0.04936105 0.04936105]
 [0.06287471 0.06287471 0.06287471]
 [0.097015   0.097015   0.097015  ]
 [0.04002688 0.04002688 0.04002688]
 [0.09162473 0.09162473 0.09162473]
 [0.54368778 0.54368778 0.54

In [ ]:
Анекдот:
    В дверь постучали х раз 
    -Уравнение - подумал Штирлиц 
    У и Й тихо смеялись за дверью 