## Домашнее задание

В этой тетрадке вам предлагается реализовать задания при помощи библиотеки numpy. Крайне желательно при выполнении разных заданий не использовать циклы. Если вы не понимаете, как выполнить конкретную задачу без циклов - убирайте их постепенно, разбейте выполнение задачи на этапы и постепенно векторизуйте каждый этап.

Если вам непонятно, как выполнить ту или иную операцию - не стесняйтесь гуглить, если над вами повис дедлайн, а вы всё ещё на чём-то застряли - пишите преподу/в чат, это ок.

**Обсудить решение лучше и сделать в итоге хоть что-то гораздо лучше, чем скатать чужой код или сдать пустую тетрадку.**




In [1]:
import numpy as np

### Drill (1 балл)

Задание 1.

Инициализируйте нулями массивы следующих форм:

* (5)
* (5, 1)
* (10, 2)
* (3, 6, 2)
* (4, 3, 2, 1)

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.zeros((5, 1))

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [4]:
np.zeros((10, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [5]:
np.zeros((3, 6, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [6]:
np.zeros((4, 3, 2, 1))

array([[[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]],


       [[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]],


       [[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]],


       [[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]]])

Задание 2.

Инициализируйте единицами массивы таких же форм и приведите их к целочисленному виду:

In [7]:
a1 = np.ones(5, dtype=int)
a1

array([1, 1, 1, 1, 1])

In [8]:
a2 = np.ones((5, 1), dtype=int)
a2

array([[1],
       [1],
       [1],
       [1],
       [1]])

In [9]:
a3 = np.ones((10, 2), dtype=int)
a3

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [10]:
a4 = np.ones((3, 6, 2), dtype=int)
a4

array([[[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]])

In [11]:
a5 = np.ones((4, 3, 2, 1), dtype=int)
a5

array([[[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]],


       [[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]],


       [[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]],


       [[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]]])

Задание 3.

Выполните для векторов выше `reshape` в "форму"
* с двумя компонентами
* с тремя компонентами
* с четырьмя компонентами

In [12]:
print(a1.reshape((1, 5)))
print()
print(a1.reshape((1, 5, 1)))
print()
print(a1.reshape((1, 5, 1, 1)))

[[1 1 1 1 1]]

[[[1]
  [1]
  [1]
  [1]
  [1]]]

[[[[1]]

  [[1]]

  [[1]]

  [[1]]

  [[1]]]]


In [13]:
print(a2.reshape((1, 5)))
print()
print(a2.reshape((1, 5, 1)))
print()
print(a2.reshape((1, 1, 5, 1)))

[[1 1 1 1 1]]

[[[1]
  [1]
  [1]
  [1]
  [1]]]

[[[[1]
   [1]
   [1]
   [1]
   [1]]]]


In [14]:
print(a3.reshape((10, 2)))
print(a3.reshape((4, 5, 1)))
print(a3.reshape((2, 2, 1, 5)))

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]
[[[1]
  [1]
  [1]
  [1]
  [1]]

 [[1]
  [1]
  [1]
  [1]
  [1]]

 [[1]
  [1]
  [1]
  [1]
  [1]]

 [[1]
  [1]
  [1]
  [1]
  [1]]]
[[[[1 1 1 1 1]]

  [[1 1 1 1 1]]]


 [[[1 1 1 1 1]]

  [[1 1 1 1 1]]]]


In [15]:
print(a4.reshape((18, 2)))
print(a4.reshape((4, 3, 3)))
print(a4.reshape((2, 2, 9, 1)))

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]
[[[[1]
   [1]
   [1]
   [1]
   [1]
   [1]
   [1]
   [1]
   [1]]

  [[1]
   [1]
   [1]
   [1]
   [1]
   [1]
   [1]
   [1]
   [1]]]


 [[[1]
   [1]
   [1]
   [1]
   [1]
   [1]
   [1]
   [1]
   [1]]

  [[1]
   [1]
   [1]
   [1]
   [1]
   [1]
   [1]
   [1]
   [1]]]]


In [16]:
print(a5.reshape((12, 2)))
print(a5.reshape((4, 3, -1)))
print(a5.reshape((2, 2, -1, 2)))

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]
[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]
[[[[1 1]
   [1 1]
   [1 1]]

  [[1 1]
   [1 1]
   [1 1]]]


 [[[1 1]
   [1 1]
   [1 1]]

  [[1 1]
   [1 1]
   [1 1]]]]


Задание 4.

Для вектора ниже посчитайте его
* Максимум по 1 оси
* Минимум по 0 оси
* Сумму по всем осям
* Среднее по 0 оси
* Медиану по 1 оси

In [17]:
v = np.random.randint(0, 9, size=(5, 7))

In [18]:
np.max(v , axis = 1)

array([8, 6, 8, 8, 6])

In [19]:
np.min(v , axis = 0)

array([1, 0, 2, 1, 2, 0, 1])

In [20]:
np.sum(v)

141

In [21]:
np.mean(v, axis = 0)

array([3.8, 3.2, 4.4, 3.8, 5.4, 3.2, 4.4])

In [22]:
np.median(v, axis = 1)

array([4., 3., 4., 4., 2.])

Задание 5.

Для всё того же вектора `v` выведите
* Его shape
* 0 компоненту его "формы"
* 1 компоненту его "формы"

In [23]:
print(v.shape)
print(v.shape[0])
print(v.shape[1])

(5, 7)
5
7


Задание 6.

Для этого же вектора выведите
* Все числа больше 5
* Все числа меньше 7 в обратном порядке
* Все числа больше 3, которые делятся на 4 без остатка
* Все числа, остаток от деления на 5 которых равен 3
* Индекс максимума
* Индекс минимума
* Cписок с индексами элементов отсортированного массива в исходном (неотсортированном)

In [24]:
v

array([[7, 4, 8, 3, 4, 0, 3],
       [3, 0, 4, 6, 5, 3, 2],
       [4, 2, 4, 4, 8, 7, 8],
       [1, 4, 4, 5, 8, 2, 8],
       [4, 6, 2, 1, 2, 4, 1]])

In [25]:
v[v > 5]

array([7, 8, 6, 8, 7, 8, 8, 8, 6])

In [26]:
v[v < 7][::-1]

array([1, 4, 2, 1, 2, 6, 4, 2, 5, 4, 4, 1, 4, 4, 2, 4, 2, 3, 5, 6, 4, 0,
       3, 3, 0, 4, 3, 4])

In [27]:
v[(v > 3) & (v % 4 == 0)]

array([4, 8, 4, 4, 4, 4, 4, 8, 8, 4, 4, 8, 8, 4, 4])

In [28]:
v[v % 5 == 3]

array([8, 3, 3, 3, 3, 8, 8, 8, 8])

In [29]:
print(np.argmax(v))
print(np.argmin(v))
v.argsort(axis = None)

2
5


array([ 8,  5, 34, 31, 21, 30, 32, 15, 26, 13,  3,  6,  7, 12, 28, 23, 22,
       17,  1,  4, 16, 14, 33,  9, 11, 24, 10, 29,  0, 19, 25, 20,  2, 27,
       18])

Задание 7.

Выполните следующие операции над вектором (независимо, не обязательно делать это в последовательности):
* Умножьте его на 3
* Разделите на 7
* Возведите в степень $\frac{2}{3}$
* Посчитайте $\sin$ от него
* Посчитайте $\log$ от него

In [30]:
print(v, '\n')
print(v*3, '\n')
print(np.round(v/7, 3), '\n')
print(np.round(v**(2/3), 3), '\n')
print(np.round(np.sin(v), 3), '\n')
print(np.round(np.log(v), 3))

[[7 4 8 3 4 0 3]
 [3 0 4 6 5 3 2]
 [4 2 4 4 8 7 8]
 [1 4 4 5 8 2 8]
 [4 6 2 1 2 4 1]] 

[[21 12 24  9 12  0  9]
 [ 9  0 12 18 15  9  6]
 [12  6 12 12 24 21 24]
 [ 3 12 12 15 24  6 24]
 [12 18  6  3  6 12  3]] 

[[1.    0.571 1.143 0.429 0.571 0.    0.429]
 [0.429 0.    0.571 0.857 0.714 0.429 0.286]
 [0.571 0.286 0.571 0.571 1.143 1.    1.143]
 [0.143 0.571 0.571 0.714 1.143 0.286 1.143]
 [0.571 0.857 0.286 0.143 0.286 0.571 0.143]] 

[[3.659 2.52  4.    2.08  2.52  0.    2.08 ]
 [2.08  0.    2.52  3.302 2.924 2.08  1.587]
 [2.52  1.587 2.52  2.52  4.    3.659 4.   ]
 [1.    2.52  2.52  2.924 4.    1.587 4.   ]
 [2.52  3.302 1.587 1.    1.587 2.52  1.   ]] 

[[ 0.657 -0.757  0.989  0.141 -0.757  0.     0.141]
 [ 0.141  0.    -0.757 -0.279 -0.959  0.141  0.909]
 [-0.757  0.909 -0.757 -0.757  0.989  0.657  0.989]
 [ 0.841 -0.757 -0.757 -0.959  0.989  0.909  0.989]
 [-0.757 -0.279  0.909  0.841  0.909 -0.757  0.841]] 

[[1.946 1.386 2.079 1.099 1.386  -inf 1.099]
 [1.099  -inf 1.386 1.792

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in log
  


### Разные инициализации + индексирование (3 балла)

Задание 8.

Необходимо построить квадрат $3 \times 3$ из нечётных чисел

In [31]:
np.arange(1, 18, 2).reshape((3, 3))

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

Задание 9.

Необходимо построить квадрат $4 \times 4$ из четных чисел в обратном порядке

In [32]:
np.arange(32, 1, -2).reshape((4, 4))

array([[32, 30, 28, 26],
       [24, 22, 20, 18],
       [16, 14, 12, 10],
       [ 8,  6,  4,  2]])

Задание 10.

Необходимо построить сетку координат $11 \times 11$ с точкой $(0,0)$ в центре и шагом $0.1$ между клетками

In [59]:
def f(i, j):
  i1, j1= np.abs(i-5).reshape(-1), np.abs(j-5).reshape(-1)
  
  return np.array(tuple(zip(i1, j1))).reshape(11, 11, 2)/10

print(np.fromfunction(f, (11, 11), dtype=float))

[[[0.5 0.5]
  [0.5 0.4]
  [0.5 0.3]
  [0.5 0.2]
  [0.5 0.1]
  [0.5 0. ]
  [0.5 0.1]
  [0.5 0.2]
  [0.5 0.3]
  [0.5 0.4]
  [0.5 0.5]]

 [[0.4 0.5]
  [0.4 0.4]
  [0.4 0.3]
  [0.4 0.2]
  [0.4 0.1]
  [0.4 0. ]
  [0.4 0.1]
  [0.4 0.2]
  [0.4 0.3]
  [0.4 0.4]
  [0.4 0.5]]

 [[0.3 0.5]
  [0.3 0.4]
  [0.3 0.3]
  [0.3 0.2]
  [0.3 0.1]
  [0.3 0. ]
  [0.3 0.1]
  [0.3 0.2]
  [0.3 0.3]
  [0.3 0.4]
  [0.3 0.5]]

 [[0.2 0.5]
  [0.2 0.4]
  [0.2 0.3]
  [0.2 0.2]
  [0.2 0.1]
  [0.2 0. ]
  [0.2 0.1]
  [0.2 0.2]
  [0.2 0.3]
  [0.2 0.4]
  [0.2 0.5]]

 [[0.1 0.5]
  [0.1 0.4]
  [0.1 0.3]
  [0.1 0.2]
  [0.1 0.1]
  [0.1 0. ]
  [0.1 0.1]
  [0.1 0.2]
  [0.1 0.3]
  [0.1 0.4]
  [0.1 0.5]]

 [[0.  0.5]
  [0.  0.4]
  [0.  0.3]
  [0.  0.2]
  [0.  0.1]
  [0.  0. ]
  [0.  0.1]
  [0.  0.2]
  [0.  0.3]
  [0.  0.4]
  [0.  0.5]]

 [[0.1 0.5]
  [0.1 0.4]
  [0.1 0.3]
  [0.1 0.2]
  [0.1 0.1]
  [0.1 0. ]
  [0.1 0.1]
  [0.1 0.2]
  [0.1 0.3]
  [0.1 0.4]
  [0.1 0.5]]

 [[0.2 0.5]
  [0.2 0.4]
  [0.2 0.3]
  [0.2 0.2]
  [0.2 0.1]
  

Задание 11.

Замощение сетки $8\times8$ при помощи $0$ и $1$ в шахматном порядке, клетка с индексом $(0,0)$ замощается $1$

In [35]:
X = np.ones((8,8), dtype=int)
X[1::2, 0::2] = 0
X[0::2, 1::2] = 0
print(X)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


Задание 12.

То же замощение, но клетка с индексом $(0,0)$ замощается $0$

In [36]:
X = np.ones((8,8), dtype=int)
X[0::2, 0::2] = 0
X[1::2, 1::2] = 0
print(X)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Задание 13.

Необходимо построить нижне-треугольную матрицу переменного размера (задается передачей параметра в функцию). Это единичная матрица,замощённая $1$ под главной диагональю

In [37]:
n = 4

a = np.fromfunction(lambda i, j: (i-j), (n, n))
a = np.where(a>=0, 1, 0)
print(a)

[[1 0 0 0]
 [1 1 0 0]
 [1 1 1 0]
 [1 1 1 1]]


Задание 14.

Необходимо построить верхне-треугольную матрицу переменного размера. Это единичная матрица, замощённая $1$ над главной диагональю

In [38]:
n = 4

a = np.fromfunction(lambda i, j: (i-j), (n, n))
a = np.where(a <= 0, 1, 0)
print(a)

[[1 1 1 1]
 [0 1 1 1]
 [0 0 1 1]
 [0 0 0 1]]


Задание 15.

Необходимо построить матрицу, в которой единицы стоят на побочной диагонали (идущей из левого нижнего угла в правый верхний), в остальных местах стоят $0$

In [39]:
n = 4

a = np.fromfunction(lambda i, j: i+j==n-1, (n, n))
a = np.where(a, 1, 0)
print(a)

[[0 0 0 1]
 [0 0 1 0]
 [0 1 0 0]
 [1 0 0 0]]


### Операции + аггрегации (3 балла)

Задание 16.

Дана выборка $\{X_i\}$ некоторой случайной величины $X$, необходимо оценить
* Математическое ожидание $E[X] = \frac{1}{N}\sum_{i=1}^N X_i$ этой случайной величины
* Дисперсию $D[X] = \frac{1}{N}\sum_{i=1}^N (X_i - E[X])^2$ этой случайной величины

In [40]:
def expected_value(x):
    assert len(x) > 0
    return sum(x) / len(x)


def dispersion(x):
    assert len(x) > 0
    d = 0
    e = expected_value(x)
    for x_i in x:
        d += (x_i - e) ** 2
    return d / len(x)

In [41]:
def expected_value_np(x):
    return np.sum(x)/x.shape

In [42]:
def dispersion_np(x):
    return np.sum((expected_value_np(x) - x)**2)/x.shape

In [43]:
np.testing.assert_array_equal(expected_value([1]), expected_value_np(np.array([1])))
np.testing.assert_array_equal(expected_value([3, 4]), expected_value_np(np.array([3, 4])))
np.testing.assert_array_equal(expected_value([-1, 0, 1]), expected_value_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(expected_value([-99, -98]), expected_value_np(np.array([-99, -98])))

np.testing.assert_array_equal(dispersion([1]), dispersion_np(np.array([1])))
np.testing.assert_array_equal(dispersion([3, 4]), dispersion_np(np.array([3, 4])))
np.testing.assert_array_equal(dispersion([-1, 0, 1]), dispersion_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(dispersion([-99, -98]), dispersion_np(np.array([-99, -98])))

Задание 17.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое квадратов разностей их значений

In [44]:
def mean_square_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    # Здесь и далее эти проверки !не нужно! дублировать в свои функции; Здесь они для того, чтобы лишний раз подчеркнуть валидность входных данных
    s = 0
    for i in range(len(y1)):
        s += (y1[i] - y2[i]) ** 2
    return s / len(y1)

In [45]:
def mean_square_difference_np(y1, y2):
    return np.sum((y1-y2)**2)/y1.shape

In [46]:
assert mean_square_difference([1], [1]) == mean_square_difference_np(np.array([1]), np.array([1]))
assert mean_square_difference([1, 2], [1, 2]) == mean_square_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_square_difference([-1, 1], [0, 0]) == mean_square_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_square_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_square_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 18.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое модулей разностей их значений

In [47]:
def mean_abs_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    s = 0
    for i in range(len(y1)):
        s += abs(y1[i] - y2[i])
    return s / len(y1)

In [48]:
def mean_abs_difference_np(y1, y2):
    return np.sum(np.abs((y1-y2)))/y1.shape

In [49]:
assert mean_abs_difference([1], [1]) == mean_abs_difference_np(np.array([1]), np.array([1]))
assert mean_abs_difference([1, 2], [1, 2]) == mean_abs_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_abs_difference([-1, 1], [0, 0]) == mean_abs_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_abs_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_abs_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 19.

Даны два вектора $y_1$ и $y_2$, в которых присутствуют только $0$ и $1$. Необходимо посчитать вероятность совпадения - в скольких точках значения двух векторов совпадают

In [50]:
def matching_proba(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    assert len(set(y1)) <= 2
    assert len(set(y2)) <= 2
    assert 0 in set(y1) or 1 in set(y1) or (0 in set(y1) and 1 in set(y1))
    assert 0 in set(y2) or 1 in set(y2) or (0 in set(y2) and 1 in set(y2))

    return sum([y1[i] == y2[i] for i in range(len(y1))]) / len(y1)

In [51]:
def matching_proba_np(y1, y2):
    return y1[y1 == y2].shape[0] / y1.shape[0]

In [52]:
np.testing.assert_array_equal(matching_proba([0, 1], [1, 0]), matching_proba_np(np.array([0, 1]), np.array([1, 0])))
np.testing.assert_array_equal(matching_proba([0, 1, 0, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 1, 0, 1]), np.array([0, 0, 1, 1])))
np.testing.assert_array_equal(matching_proba([0, 0, 1, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1])))

Задание 20.

Даны два вектора: $y_1$, $y_2$. В $y_1$ и $y_2$ присутствуют только $0$ и $1$.

Необходимо найти границы (индексы), такие, что если мы разделим вдоль какой-то из этих границ оба вектора на две части, то
* в левой части пересекающихся в $y_1$ и $y_2$ нулей будет строго больше, чем пересекающихся единиц или непересекающихся элементов
* в правой - пересекающихся единиц строго больше, чем пересекающихся нулей или непересекающихся элементов.

Если какая-то из частей не содержит элементов вовсе, то будем считать, что она подходит под условие.

In [53]:
def find_thresholds(y1, y2, debug=False):
    assert len(y1) == len(y2) and len(y1) > 0
    n = len(y1)
    matching_zeros = [1 if y1[i] == y2[i] == 0 else 0 for i in range(n)]
    matching_ones = [1 if y1[i] == y2[i] == 1 else 0 for i in range(n)]
    res = []
    #print(matching_zeros, matching_ones, '\n')
    if sum(matching_ones) / n > 0.5:
        res.append(0)
    for i in range(1, n):
        if debug: # если вам непонятна логика работы этой функции, передайте третьим аргументом True
            print(matching_zeros[:i], matching_ones[i:], i)
        if sum(matching_zeros[:i]) / i > 0.5 and sum(matching_ones[i:]) / (n - i) > 0.5:
            res.append(i)
    if sum(matching_zeros) / n > 0.5:
        res.append(n)
    return res

In [54]:
def find_thresholds_np(y1, y2):
  res = np.array([-2])

  m_ones = y1*y2*2-1
  m_zeros = np.where((y1+ y2) == 0, 1, -1)
  #print(m_zeros, m_ones)
  zeros_sum = np.cumsum(m_zeros)
  #print(zeros_sum)
  ones_sum_back = np.cumsum(m_ones[::-1])[::-1]
  #print(ones_sum_back)
  if ones_sum_back[0] > 0:
    res = np.append(res, [0])
  elif zeros_sum[-1] > 0:
    res = np.append(res, zeros_sum.shape[0])

  zeros_sum = np.append(zeros_sum[-1], zeros_sum[:-1])

  indices = np.where((ones_sum_back > 0) & (zeros_sum > 0))[0] 
  res = sorted(np.append(res, indices)[1:])
  return res

In [55]:
np.testing.assert_array_equal(find_thresholds([0], [0]), find_thresholds_np(np.array([0]), np.array([0])))
np.testing.assert_array_equal(find_thresholds([1], [1]), find_thresholds_np(np.array([1]), np.array([1])))
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 1], [0, 0, 1, 1]), 
    find_thresholds_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1]))
)
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 0, 0, 1, 1, 1], [0, 0, 0, 0, 0, 1, 1, 1]),
    find_thresholds_np(np.array([0, 0, 1, 0, 0, 1, 1, 1]), np.array([0, 0, 0, 0, 0, 1, 1, 1]))
)

### Разные действия с матрицами (3 балла)

Задание 21.

Дана матрица размера $(32, 3, 16, 16)$, заполненная случайными числами от 0 до 9. При помощи **ровно двух** преобразований приведите её к виду $(32, 1)$. При выполнении задания **можно** создавать вспомогательные матрицы!

In [56]:
data = np.random.randint(0, 10, size=(32, 3, 16, 16))

data = data.reshape(32, -1)
data = np.dot(data, np.ones((16*16*3, 1)))

assert data.shape == (32, 1)

Задание 22.

Даны две матрицы $m_1$ размером $(32, 256)$ и $m_2$ размером $(32, 512)$, а также две вспомогательные матрицы $W_1$ размером $(256, 32)$ и $W_2$ размером $(512, 16)$. Используя **все** данные матрицы, сделайте так, чтобы на выходе получилась **ровно одна** матрица размером $(32, 32)$

In [57]:
m1 = np.random.randint(0, 10, size=(32, 256))
m2 = np.random.randint(0, 10, size=(32, 512))
W1 = np.random.randint(0, 10, size=(256, 32))
W2 = np.random.randint(0, 10, size=(512, 16))

result = np.dot(np.dot(np.dot(np.dot(np.dot(m1, W1), m2), W2), W2.transpose()), m2.transpose())

assert result.shape == (32, 32)

Задание 23.

Приведите полученную на последнем шаге матрицу к виду $(32, 3)$ и сделайте так, чтобы все значения в этой матрице были в промежутке от $0$ до $1$

In [58]:
# Вжух! (∩｀-´)⊃━☆ﾟ.*･｡ﾟ
result = np.dot(result, np.ones((32, 3))) 
result = result / result.reshape(-1)[result.argmax()]

assert result.shape == (32, 3)
assert ((result >= 0) & (result <= 1)).all()