<a href="https://colab.research.google.com/github/victory256/Sample-ML-Repo/blob/hw01/%D0%AF%D0%BA%D1%83%D0%B1%D0%BE%D0%B2%D0%B0_hw01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Домашнее задание

В этой тетрадке вам предлагается реализовать задания при помощи библиотеки numpy. Крайне желательно при выполнении разных заданий не использовать циклы. Если вы не понимаете, как выполнить конкретную задачу без циклов - убирайте их постепенно, разбейте выполнение задачи на этапы и постепенно векторизуйте каждый этап.

Если вам непонятно, как выполнить ту или иную операцию - не стесняйтесь гуглить, если над вами повис дедлайн, а вы всё ещё на чём-то застряли - пишите преподу/в чат, это ок.

**Обсудить решение лучше и сделать в итоге хоть что-то гораздо лучше, чем скатать чужой код или сдать пустую тетрадку.**

In [1]:
import numpy as np

### Drill (1 балл)

Задание 1.

Инициализируйте нулями массивы следующих форм:

* (5)
* (5, 1)
* (10, 2)
* (3, 6, 2)
* (4, 3, 2, 1)

In [2]:
np.zeros(5) #1

array([0., 0., 0., 0., 0.])

In [3]:
np.zeros((5,1)) #2

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [4]:
np.zeros((10,2)) #3

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [5]:
np.zeros((3, 6, 2)) #4

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [6]:
np.zeros((4, 3, 2, 1)) #5

array([[[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]],


       [[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]],


       [[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]],


       [[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]]])

Задание 2.

Инициализируйте единицами массивы таких же форм и приведите их к целочисленному виду:

In [7]:
np.ones(5, dtype=int) #1 или np.ones(5).astype(int)

array([1, 1, 1, 1, 1])

In [8]:
np.ones((5, 1), dtype=int) #2 или np.ones((5, 1)).astype(int)

array([[1],
       [1],
       [1],
       [1],
       [1]])

In [9]:
np.ones((10, 2), dtype=int) #3 или np.ones((10, 2)).astype(int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [10]:
np.ones((3, 6, 2), dtype=int) #4 или np.ones((3, 6, 2)).astype(int)

array([[[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]])

In [11]:
np.ones((4, 3, 2, 1), dtype=int) #5 или np.ones((4, 3, 2, 1)).astype(int)

array([[[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]],


       [[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]],


       [[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]],


       [[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]]])

Задание 3.

Выполните для векторов выше `reshape` в "форму"
* с двумя компонентами
* с тремя компонентами
* с четырьмя компонентами

In [12]:
np.ones(5, dtype=int).reshape(1,-1) #1_2comp

array([[1, 1, 1, 1, 1]])

In [13]:
np.ones(5, dtype=int).reshape(1,1,-1) #1_3comp

array([[[1, 1, 1, 1, 1]]])

In [14]:
np.ones(5, dtype=int).reshape(1,1,1,-1) #1_4comp

array([[[[1, 1, 1, 1, 1]]]])

In [15]:
np.ones((5, 1), dtype=int).reshape(1,-1) #2_2comp

array([[1, 1, 1, 1, 1]])

In [16]:
np.ones((5, 1), dtype=int).reshape(1,1,-1) #2_3comp

array([[[1, 1, 1, 1, 1]]])

In [17]:
np.ones((5, 1), dtype=int).reshape(1,1,1,-1) #2_4comp

array([[[[1, 1, 1, 1, 1]]]])

In [18]:
np.ones((10, 2), dtype=int).reshape(5,-1) #3_2comp

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [19]:
np.ones((10, 2), dtype=int).reshape(5,2,-1) #3_3comp

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [20]:
np.ones((10, 2), dtype=int).reshape(2,5,2,-1) #3_4comp

array([[[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]],


       [[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]]])

In [21]:
np.ones((3, 6, 2), dtype=int).reshape(2,-1) #4_2comp

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [22]:
np.ones((3, 6, 2), dtype=int).reshape(2,3,-1) #4_3comp

array([[[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]]])

In [23]:
np.ones((3, 6, 2), dtype=int).reshape(2,3,2,-1) #4_4comp

array([[[[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]]],


       [[[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]]]])

In [24]:
np.ones((4, 3, 2, 1), dtype=int).reshape(12,-1) #5_2comp

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [25]:
np.ones((4, 3, 2, 1), dtype=int).reshape(6,2,-1) #5_3comp

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [26]:
np.ones((4, 3, 2, 1), dtype=int).reshape(2,3,1,-1) #5_4comp

array([[[[1, 1, 1, 1]],

        [[1, 1, 1, 1]],

        [[1, 1, 1, 1]]],


       [[[1, 1, 1, 1]],

        [[1, 1, 1, 1]],

        [[1, 1, 1, 1]]]])

Задание 4.

Для вектора ниже посчитайте его
* Максимум по 1 оси
* Минимум по 0 оси
* Сумму по всем осям
* Среднее по 0 оси
* Медиану по 1 оси

In [27]:
v = np.random.randint(0, 9, size=(5, 7))
v

array([[5, 4, 1, 2, 6, 6, 5],
       [4, 8, 4, 5, 1, 8, 7],
       [1, 5, 3, 8, 5, 2, 8],
       [0, 4, 3, 7, 2, 6, 0],
       [8, 8, 6, 0, 7, 5, 2]])

In [28]:
print(f'Максимум по 1 оси = {np.max(v,axis=1)}')
print(f'Минимум по 0 оси = {np.min(v,axis=0)}')
print(f'Сумму по всем осям = {np.sum(v)}')
print(f'Среднее по 0 оси = {np.mean(v,axis=0)}')
print(f'Медиану по 1 оси = {np.median(v,axis=1)}')

Максимум по 1 оси = [6 8 8 7 8]
Минимум по 0 оси = [0 4 1 0 1 2 0]
Сумму по всем осям = 156
Среднее по 0 оси = [3.6 5.8 3.4 4.4 4.2 5.4 4.4]
Медиану по 1 оси = [5. 5. 5. 3. 6.]


Задание 5.

Для всё того же вектора `v` выведите
* Его shape
* 0 компоненту его "формы"
* 1 компоненту его "формы"

In [29]:
print(f'Его shape = {v.shape}')
print(f'0 компоненту его "формы" = {v[:,0]}')
print(f'1 компоненту его "формы" = {v[0,:]}')

Его shape = (5, 7)
0 компоненту его "формы" = [5 4 1 0 8]
1 компоненту его "формы" = [5 4 1 2 6 6 5]


Задание 6.

Для этого же вектора выведите
* Все числа больше 5
* Все числа меньше 7 в обратном порядке
* Все числа больше 3, которые делятся на 4 без остатка
* Все числа, остаток от деления на 5 которых равен 3
* Индекс максимума
* Индекс минимума
* Cписок с индексами элементов отсортированного массива в исходном (неотсортированном)

In [30]:
print(f'Все числа больше 5 = {v[v > 5]}')
print(f'Все числа меньше 7 в обратном порядке = {v[v < 7][::-1]}')
print(f'Все числа больше 3, которые делятся на 4 без остатка = {v[(v > 3) & (v % 4 == 0)]}')
print(f'Все числа, остаток от деления на 5 которых равен 3 = {v[v % 5 == 3]}')
print(f'Индекс максимума = {v.argmax()}')
print(f'Индекс минимума = {v.argmin()}')
print(f'Cписок с индексами элементов отсортированного массива в исходном (неотсортированном) = {np.argsort(v, axis=None)}')

Все числа больше 5 = [6 6 8 8 7 8 8 7 6 8 8 6 7]
Все числа меньше 7 в обратном порядке = [2 5 0 6 0 6 2 3 4 0 2 5 3 5 1 1 5 4 4 5 6 6 2 1 4 5]
Все числа больше 3, которые делятся на 4 без остатка = [4 4 8 4 8 8 8 4 8 8]
Все числа, остаток от деления на 5 которых равен 3 = [8 8 3 8 8 3 8 8]
Индекс максимума = 8
Индекс минимума = 21
Cписок с индексами элементов отсортированного массива в исходном (неотсортированном) = [31 27 21 14  2 11 34  3 25 19 23 16  9  7  1 22 18  0 15 10 33  6  4 30
  5 26 13 32 24  8 12 28 29 20 17]


Задание 7.

Выполните следующие операции над вектором (независимо, не обязательно делать это в последовательности):
* Умножьте его на 3
* Разделите на 7
* Возведите в степень $\frac{2}{3}$
* Посчитайте $\sin$ от него
* Посчитайте $\log$ от него

In [31]:
print(f'Умножьте его на 3 = \n{v*3}')
print(f'Разделите на 7 = \n{np.around(v/7, decimals = 2)}')
print(f'Возведите в степень  2/3 = \n{np.around(v**(2/3), decimals = 2)}')
print(f'Посчитайте  sin  от него = \n{np.around(np.sin(v), decimals = 2)}')
print(f'Посчитайте  log  от него = \n{np.around(np.log(v), decimals = 2)}')

Умножьте его на 3 = 
[[15 12  3  6 18 18 15]
 [12 24 12 15  3 24 21]
 [ 3 15  9 24 15  6 24]
 [ 0 12  9 21  6 18  0]
 [24 24 18  0 21 15  6]]
Разделите на 7 = 
[[0.71 0.57 0.14 0.29 0.86 0.86 0.71]
 [0.57 1.14 0.57 0.71 0.14 1.14 1.  ]
 [0.14 0.71 0.43 1.14 0.71 0.29 1.14]
 [0.   0.57 0.43 1.   0.29 0.86 0.  ]
 [1.14 1.14 0.86 0.   1.   0.71 0.29]]
Возведите в степень  2/3 = 
[[2.92 2.52 1.   1.59 3.3  3.3  2.92]
 [2.52 4.   2.52 2.92 1.   4.   3.66]
 [1.   2.92 2.08 4.   2.92 1.59 4.  ]
 [0.   2.52 2.08 3.66 1.59 3.3  0.  ]
 [4.   4.   3.3  0.   3.66 2.92 1.59]]
Посчитайте  sin  от него = 
[[-0.96 -0.76  0.84  0.91 -0.28 -0.28 -0.96]
 [-0.76  0.99 -0.76 -0.96  0.84  0.99  0.66]
 [ 0.84 -0.96  0.14  0.99 -0.96  0.91  0.99]
 [ 0.   -0.76  0.14  0.66  0.91 -0.28  0.  ]
 [ 0.99  0.99 -0.28  0.    0.66 -0.96  0.91]]
Посчитайте  log  от него = 
[[1.61 1.39 0.   0.69 1.79 1.79 1.61]
 [1.39 2.08 1.39 1.61 0.   2.08 1.95]
 [0.   1.61 1.1  2.08 1.61 0.69 2.08]
 [-inf 1.39 1.1  1.95 0.69 1.79 -i

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in log
  """


### Разные инициализации + индексирование (3 балла)

Задание 8.

Необходимо построить квадрат $3 \times 3$ из нечётных чисел

In [32]:
np.random.choice(np.arange(1,101,2),size=(3,3))

array([[59, 21, 55],
       [31, 91, 17],
       [25, 19,  1]])

Задание 9.

Необходимо построить квадрат $4 \times 4$ из четных чисел в обратном порядке

In [33]:
mass_9 = np.random.choice(np.arange(2,102,2),size=(16)) # сортируем список случайных четных чисел
mass_9[mass_9.argsort()].reshape(4,4)   # переводим в матрицу (4,4)

array([[12, 22, 22, 24],
       [36, 38, 44, 58],
       [60, 60, 64, 66],
       [86, 90, 90, 92]])

Задание 10.

Необходимо построить сетку координат $11 \times 11$ с точкой $(0,0)$ в центре и шагом $0.1$ между клетками

In [34]:
x = np.linspace(-0.5,0.5, 11)
Z = np.zeros((11,11), [('x',float),('y',float)]) 
Z['x'], Z['y'] = np.meshgrid(x, x)
Z

array([[(-0.5, -0.5), (-0.4, -0.5), (-0.3, -0.5), (-0.2, -0.5),
        (-0.1, -0.5), ( 0. , -0.5), ( 0.1, -0.5), ( 0.2, -0.5),
        ( 0.3, -0.5), ( 0.4, -0.5), ( 0.5, -0.5)],
       [(-0.5, -0.4), (-0.4, -0.4), (-0.3, -0.4), (-0.2, -0.4),
        (-0.1, -0.4), ( 0. , -0.4), ( 0.1, -0.4), ( 0.2, -0.4),
        ( 0.3, -0.4), ( 0.4, -0.4), ( 0.5, -0.4)],
       [(-0.5, -0.3), (-0.4, -0.3), (-0.3, -0.3), (-0.2, -0.3),
        (-0.1, -0.3), ( 0. , -0.3), ( 0.1, -0.3), ( 0.2, -0.3),
        ( 0.3, -0.3), ( 0.4, -0.3), ( 0.5, -0.3)],
       [(-0.5, -0.2), (-0.4, -0.2), (-0.3, -0.2), (-0.2, -0.2),
        (-0.1, -0.2), ( 0. , -0.2), ( 0.1, -0.2), ( 0.2, -0.2),
        ( 0.3, -0.2), ( 0.4, -0.2), ( 0.5, -0.2)],
       [(-0.5, -0.1), (-0.4, -0.1), (-0.3, -0.1), (-0.2, -0.1),
        (-0.1, -0.1), ( 0. , -0.1), ( 0.1, -0.1), ( 0.2, -0.1),
        ( 0.3, -0.1), ( 0.4, -0.1), ( 0.5, -0.1)],
       [(-0.5,  0. ), (-0.4,  0. ), (-0.3,  0. ), (-0.2,  0. ),
        (-0.1,  0. ), ( 0. ,  0. ), ( 0.1

Задание 11.

Замощение сетки $8\times8$ при помощи $0$ и $1$ в шахматном порядке, клетка с индексом $(0,0)$ замощается $1$

In [35]:
mass_11 = np.zeros((8,8),dtype=int)
mass_11[::2,::2]=1
mass_11[1::2,1::2]=1
mass_11

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

Задание 12.

То же замощение, но клетка с индексом $(0,0)$ замощается $0$

In [36]:
mass_12 = np.ones((8,8),dtype=int)
mass_12[::2,::2]=0
mass_12[1::2,1::2]=0
mass_12

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

Задание 13.

Необходимо построить нижне-треугольную матрицу переменного размера (задается передачей параметра в функцию). Это единичная матрица,замощённая $1$ под главной диагональю

In [37]:
n = 5 # размерность матрицы
mass_13 = np.zeros((n,n),dtype=int)
mass_13[np.tril_indices(n)] = 1  # индексы нижнего треугольника массива 
mass_13

array([[1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1]])

Задание 14.

Необходимо построить верхне-треугольную матрицу переменного размера. Это единичная матрица, замощённая $1$ над главной диагональю

In [38]:
n = 5 # размерность матрицы
mass_14 = np.zeros((n,n),dtype=int)
mass_14[np.tril_indices(n)] = 1  # индексы нижнего треугольника массива 
mass_14.transpose()

array([[1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1],
       [0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1],
       [0, 0, 0, 0, 1]])

Задание 15.

Необходимо построить матрицу, в которой единицы стоят на побочной диагонали (идущей из левого нижнего угла в правый верхний), в остальных местах стоят $0$

In [39]:
n = 5 # размерность матрицы
mass_15 = np.eye(n,dtype=int)
np.fliplr(mass_15)  # зеркально отображаем относительно вертикальной оси или mass_15 [:,::-1]

array([[0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0]])

### Операции + аггрегации (3 балла)

Задание 16.

Дана выборка $\{X_i\}$ некоторой случайной величины $X$, необходимо оценить
* Математическое ожидание $E[X] = \frac{1}{N}\sum_{i=1}^N X_i$ этой случайной величины
* Дисперсию $D[X] = \frac{1}{N}\sum_{i=1}^N (X_i - E[X])^2$ этой случайной величины

In [40]:
def expected_value(x):
    assert len(x) > 0
    return sum(x) / len(x)


def dispersion(x):
    assert len(x) > 0
    d = 0
    e = expected_value(x)
    for x_i in x:
        d += (x_i - e) ** 2
    return d / len(x)

In [41]:
def expected_value_np(x):
    return np.sum(x)/np.size(x)

In [42]:
def dispersion_np(x):
    return np.sum(np.power(x-expected_value_np(x),2))/np.size(x)

In [43]:
np.testing.assert_array_equal(expected_value([1]), expected_value_np(np.array([1])))
np.testing.assert_array_equal(expected_value([3, 4]), expected_value_np(np.array([3, 4])))
np.testing.assert_array_equal(expected_value([-1, 0, 1]), expected_value_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(expected_value([-99, -98]), expected_value_np(np.array([-99, -98])))

np.testing.assert_array_equal(dispersion([1]), dispersion_np(np.array([1])))
np.testing.assert_array_equal(dispersion([3, 4]), dispersion_np(np.array([3, 4])))
np.testing.assert_array_equal(dispersion([-1, 0, 1]), dispersion_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(dispersion([-99, -98]), dispersion_np(np.array([-99, -98])))

Задание 17.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое квадратов разностей их значений

In [44]:
def mean_square_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    # Здесь и далее эти проверки !не нужно! дублировать в свои функции; Здесь они для того, чтобы лишний раз подчеркнуть валидность входных данных
    s = 0
    for i in range(len(y1)):
        s += (y1[i] - y2[i]) ** 2
    return s / len(y1)

In [45]:
def mean_square_difference_np(y1, y2):
    return np.mean(np.power(y1-y2,2))

In [46]:
assert mean_square_difference([1], [1]) == mean_square_difference_np(np.array([1]), np.array([1]))
assert mean_square_difference([1, 2], [1, 2]) == mean_square_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_square_difference([-1, 1], [0, 0]) == mean_square_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_square_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_square_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 18.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое модулей разностей их значений

In [47]:
def mean_abs_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    s = 0
    for i in range(len(y1)):
        s += abs(y1[i] - y2[i])
    return s / len(y1)

In [48]:
def mean_abs_difference_np(y1, y2):
    return np.mean(np.absolute(y1-y2))

In [49]:
assert mean_abs_difference([1], [1]) == mean_abs_difference_np(np.array([1]), np.array([1]))
assert mean_abs_difference([1, 2], [1, 2]) == mean_abs_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_abs_difference([-1, 1], [0, 0]) == mean_abs_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_abs_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_abs_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 19.

Даны два вектора $y_1$ и $y_2$, в которых присутствуют только $0$ и $1$. Необходимо посчитать вероятность совпадения - в скольких точках значения двух векторов совпадают

In [50]:
def matching_proba(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    assert len(set(y1)) <= 2
    assert len(set(y2)) <= 2
    assert 0 in set(y1) or 1 in set(y1) or (0 in set(y1) and 1 in set(y1))
    assert 0 in set(y2) or 1 in set(y2) or (0 in set(y2) and 1 in set(y2))

    return sum([y1[i] == y2[i] for i in range(len(y1))]) / len(y1)

In [51]:
def matching_proba_np(y1, y2):
    return np.sum(y1 == y2)/np.size(y1)

In [52]:
np.testing.assert_array_equal(matching_proba([0, 1], [1, 0]), matching_proba_np(np.array([0, 1]), np.array([1, 0])))
np.testing.assert_array_equal(matching_proba([0, 1, 0, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 1, 0, 1]), np.array([0, 0, 1, 1])))
np.testing.assert_array_equal(matching_proba([0, 0, 1, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1])))

Задание 20.

Даны два вектора: $y_1$, $y_2$. В $y_1$ и $y_2$ присутствуют только $0$ и $1$.

Необходимо найти границы (индексы), такие, что если мы разделим вдоль какой-то из этих границ оба вектора на две части, то
* в левой части пересекающихся в $y_1$ и $y_2$ нулей будет строго больше, чем пересекающихся единиц или непересекающихся элементов
* в правой - пересекающихся единиц строго больше, чем пересекающихся нулей или непересекающихся элементов.

Если какая-то из частей не содержит элементов вовсе, то будем считать, что она подходит под условие.

In [53]:
def find_thresholds(y1, y2, debug=False):
    assert len(y1) == len(y2) and len(y1) > 0
    n = len(y1)
    matching_zeros = [1 if y1[i] == y2[i] == 0 else 0 for i in range(n)]
    matching_ones = [1 if y1[i] == y2[i] == 1 else 0 for i in range(n)]
    res = []
    if sum(matching_ones) / n > 0.5:
        res.append(0)
    for i in range(1, n):
        if debug: # если вам непонятна логика работы этой функции, передайте третьим аргументом True
            print(matching_zeros[:i], matching_ones[i:], i)
        if sum(matching_zeros[:i]) / i > 0.5 and sum(matching_ones[i:]) / (n - i) > 0.5:
            res.append(i)
    if sum(matching_zeros) / n > 0.5:
        res.append(n)
    return res

In [54]:
def find_thresholds_np(y1, y2):
    intersec = (y1 == y2)
    intersec_zero = np.logical_and(y1 == y2, y1 == 0) # отмечаем True места списков пересечения нулей
    count_zero_left = np.cumsum(intersec_zero) # считаем кол-во пересечений 0 слева для каждой позиции
    count_zero_right = np.cumsum(intersec_zero[::-1])[::-1] # считаем кол-во пересечений 0 справа для каждой позиции
    intersec_ones = np.logical_and(y1 == y2, y1 == 1) # отмечаем True места списков пересечения единиц
    count_ones_left = np.cumsum(intersec_ones) # считаем кол-во пересечений 1 слева для каждой позиции
    count_ones_right = np.cumsum(intersec_ones[::-1])[::-1] # считаем кол-во пересечений 1 справа для каждой позиции
    not_intersec = (y1 != y2) # отмечаем True места НЕ пересечения списков
    count_not_intersec_left = np.cumsum(not_intersec) # считаем кол-во НЕ пересечений элементов слева для каждой позиции
    count_not_intersec_right = np.cumsum(not_intersec[::-1])[::-1] # считаем кол-во НЕ пересечений элементов справа для каждой позиции
    # в левой части пересекающихся 0 будет строго больше, чем пересекающихся 1 или НЕпересекающихся элементов, т.е. все "НЕ правильные"
    answer_left = count_zero_left > count_ones_left + count_not_intersec_left
    np_true = np.array([True])
    # добавляем слева True т.к. Если какая-то из частей не содержит элементов вовсе, то будем считать, что она подходит под условие.
    answer_left = np.concatenate((np_true, answer_left), axis=None) 
    # в правой части пересекающихся 1 будет строго больше, чем пересекающихся 0 или НЕпересекающихся элементов, т.е. все "НЕ правильные"
    answer_right = count_ones_right > count_zero_right + count_not_intersec_right
    # добавляем справа True т.к. Если какая-то из частей не содержит элементов вовсе, то будем считать, что она подходит под условие.
    answer_right = np.concatenate((answer_right, np_true), axis=None) 
    answer = np.logical_and(answer_left, answer_right) # отмечаем True подходящие под все условия места
    answer_index = np.nonzero(answer)[0] # список индексов
    return answer_index

In [55]:
np.testing.assert_array_equal(find_thresholds([0], [0]), find_thresholds_np(np.array([0]), np.array([0])))
np.testing.assert_array_equal(find_thresholds([1], [1]), find_thresholds_np(np.array([1]), np.array([1])))
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 1], [0, 0, 1, 1]), 
    find_thresholds_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1]))
)
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 0, 0, 1, 1, 1], [0, 0, 0, 0, 0, 1, 1, 1]),
    find_thresholds_np(np.array([0, 0, 1, 0, 0, 1, 1, 1]), np.array([0, 0, 0, 0, 0, 1, 1, 1]))
)

### Разные действия с матрицами (3 балла)

Задание 21.

Дана матрица размера $(32, 3, 16, 16)$, заполненная случайными числами от 0 до 9. При помощи **ровно двух** преобразований приведите её к виду $(32, 1)$. При выполнении задания **можно** создавать вспомогательные матрицы!

In [56]:
data = np.random.randint(0, 10, size=(32, 3, 16, 16))

data = np.reshape(data,(32,1,-1)) # Преобразование 1 = меняем размер с 4-х компонент до 3-х
data = np.min(data, axis=2) # Преобразование 2 = схлопываем по третьей компоненте, заменяя на min
assert data.shape == (32, 1)


Задание 22.

Даны две матрицы $m_1$ размером $(32, 256)$ и $m_2$ размером $(32, 512)$, а также две вспомогательные матрицы $W_1$ размером $(256, 32)$ и $W_2$ размером $(512, 16)$. Используя **все** данные матрицы, сделайте так, чтобы на выходе получилась **ровно одна** матрица размером $(32, 32)$

In [57]:
m1 = np.random.randint(0, 10, size=(32, 256))
m2 = np.random.randint(0, 10, size=(32, 512))
W1 = np.random.randint(0, 10, size=(256, 32))
W2 = np.random.randint(0, 10, size=(512, 16))

W2 = np.matmul(m2,W2) # shape = (32, 16)
W2 = np.hstack((W2,W2)) # shape = (32, 32)
W1 = np.matmul(W1,W2) # shape = (32, 16)
result = np.matmul(m1,W1)

assert result.shape == (32, 32)

Задание 23.

Приведите полученную на последнем шаге матрицу к виду $(32, 3)$ и сделайте так, чтобы все значения в этой матрице были в промежутке от $0$ до $1$

In [58]:
# Вжух! (∩｀-´)⊃━☆ﾟ.*･｡ﾟ
mass_23 = np.hstack((result,result,result)) # shape = (32, 96)
mass_23 = np.reshape(mass_23,(32,3,-1)) # shape = (32, 3, 32)
mass_23 = np.min(mass_23, axis=2) # shape = (32, 3)
result = (mass_23 - np.min(mass_23)) / (np.max(mass_23) - np.min(mass_23)) # MinMax нормализация

assert result.shape == (32, 3)
assert ((result >= 0) & (result <= 1)).all()