## Домашнее задание

В этой тетрадке вам предлагается реализовать задания при помощи библиотеки numpy. Крайне желательно при выполнении разных заданий не использовать циклы. Если вы не понимаете, как выполнить конкретную задачу без циклов - убирайте их постепенно, разбейте выполнение задачи на этапы и постепенно векторизуйте каждый этап.

Если вам непонятно, как выполнить ту или иную операцию - не стесняйтесь гуглить, если над вами повис дедлайн, а вы всё ещё на чём-то застряли - пишите преподу/в чат, это ок.

**Обсудить решение лучше и сделать в итоге хоть что-то гораздо лучше, чем скатать чужой код или сдать пустую тетрадку.**

In [418]:
import numpy as np

### Drill (1 балл)

Задание 1.

Инициализируйте нулями массивы следующих форм:

* (5)
* (5, 1)
* (10, 2)
* (3, 6, 2)
* (4, 3, 2, 1)

In [419]:
first_one = np.zeros(shape=5).astype(int)


In [420]:
first_two = np.zeros(shape=(5, 1)).astype(int)


In [421]:
first_three = np.zeros(shape=(10, 2)).astype(int)


In [422]:
first_four = np.zeros(shape=(3, 6, 2)).astype(int)


In [423]:
first_five = np.zeros(shape=(4, 3, 2, 1)).astype(int)
first_five

array([[[[0],
         [0]],

        [[0],
         [0]],

        [[0],
         [0]]],


       [[[0],
         [0]],

        [[0],
         [0]],

        [[0],
         [0]]],


       [[[0],
         [0]],

        [[0],
         [0]],

        [[0],
         [0]]],


       [[[0],
         [0]],

        [[0],
         [0]],

        [[0],
         [0]]]])

Задание 2.

Инициализируйте единицами массивы таких же форм и приведите их к целочисленному виду:

In [424]:
second_one = np.ones(shape=5).astype(int)


In [425]:
second_two = np.ones(shape=(5, 1)).astype(int)


In [426]:
second_three = np.ones(shape=(10, 2)).astype(int)


In [427]:
second_four = np.ones(shape=(3, 6, 2)).astype(int)


In [428]:
second_five = np.ones(shape=(4, 3, 2, 1)).astype(int)
second_five

array([[[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]],


       [[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]],


       [[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]],


       [[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]]])

Задание 3.

Выполните для векторов выше `reshape` в "форму"
* с двумя компонентами
* с тремя компонентами
* с четырьмя компонентами

In [429]:
second_one_2 = second_one.reshape((5, 1))
second_one_3 = second_one.reshape((5, 1, 1))
second_one_4 = second_one.reshape((5, 1, 1, 1))
second_one_4

array([[[[1]]],


       [[[1]]],


       [[[1]]],


       [[[1]]],


       [[[1]]]])

In [430]:
second_two_2 = second_two.reshape((5, 1))
second_two_3 = second_two.reshape((5, 1, 1))
second_two_4 = second_two.reshape((5, 1, 1, 1))
second_two_4

array([[[[1]]],


       [[[1]]],


       [[[1]]],


       [[[1]]],


       [[[1]]]])

In [431]:
second_three_2 = second_three.reshape((5, 4))
second_three_3 = second_three.reshape(2, 5, 2)
second_three_4 = second_three.reshape(1, 2, 5, 2)
second_three_4

array([[[[1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1]]]])

In [432]:
second_four_2 = second_four.reshape((6, 6))
second_four_3 = second_four.reshape((9, 2, 2))
second_four_4 = second_four.reshape((3, 3, 2, 2))
second_four_4

array([[[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]]])

In [433]:
second_five_2 = second_five.reshape((8, 3))
second_five_3 = second_five.reshape((4, 2, 3))
second_five_4 = second_five.reshape((2, 2, 2, 3))
second_five_4

array([[[[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]]],


       [[[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]]]])

Задание 4.

Для вектора ниже посчитайте его
* Максимум по 1 оси
* Минимум по 0 оси
* Сумму по всем осям
* Среднее по 0 оси
* Медиану по 1 оси

In [434]:
v = np.random.randint(0, 9, size=(5, 7))
v

array([[7, 7, 7, 4, 8, 3, 0],
       [1, 1, 8, 4, 7, 7, 1],
       [1, 6, 6, 0, 6, 7, 6],
       [6, 6, 1, 8, 1, 7, 4],
       [4, 1, 4, 0, 0, 5, 2]])

In [435]:
print(np.max(v, axis=1))
print(np.min(v, axis=0))
print(v.sum())
print(v.mean(axis=0))
print(np.median(v, axis=1))

[8 8 7 8 5]
[1 1 1 0 0 3 0]
146
[3.8 4.2 5.2 3.2 4.4 5.8 2.6]
[7. 4. 6. 6. 2.]


Задание 5.

Для всё того же вектора `v` выведите
* Его shape
* 0 компоненту его "формы"
* 1 компоненту его "формы"

In [436]:
print(v.shape)
print(v.shape[0])
print(v.shape[1])

(5, 7)
5
7


Задание 6.

Для этого же вектора выведите
* Все числа больше 5
* Все числа меньше 7 в обратном порядке
* Все числа больше 3, которые делятся на 4 без остатка
* Все числа, остаток от деления на 5 которых равен 3
* Индекс максимума
* Индекс минимума
* Cписок с индексами элементов отсортированного массива в исходном (неотсортированном)

In [437]:
print(v[v > 5])

[7 7 7 8 8 7 7 6 6 6 7 6 6 6 8 7]


In [438]:
print(v[v < 7])
print(v[v < 7][::-1])

[4 3 0 1 1 4 1 1 6 6 0 6 6 6 6 1 1 4 4 1 4 0 0 5 2]
[2 5 0 0 4 1 4 4 1 1 6 6 6 6 0 6 6 1 1 4 1 1 0 3 4]


In [439]:
print(v[(v > 3) & (v % 4 == 0)])

[4 8 8 4 8 4 4 4]


In [440]:
print(v[v % 5 == 3])

[8 3 8 8]


In [441]:
print(np.unravel_index(v.argmax(axis=None), v.shape))
print(np.unravel_index(v.argmin(axis=None), v.shape))
sorts = np.unravel_index(indices=v.argsort(axis=None), shape=v.shape)
print(list(zip(sorts[0], sorts[1])))

(0, 4)
(0, 6)
[(2, 3), (4, 4), (4, 3), (0, 6), (4, 1), (3, 4), (3, 2), (1, 0), (1, 1), (2, 0), (1, 6), (4, 6), (0, 5), (1, 3), (4, 2), (0, 3), (4, 0), (3, 6), (4, 5), (2, 1), (2, 2), (2, 4), (2, 6), (3, 0), (3, 1), (0, 1), (0, 2), (1, 5), (1, 4), (2, 5), (3, 5), (0, 0), (0, 4), (3, 3), (1, 2)]


Задание 7.

Выполните следующие операции над вектором (независимо, не обязательно делать это в последовательности):
* Умножьте его на 3
* Разделите на 7
* Возведите в степень $\frac{2}{3}$
* Посчитайте $\sin$ от него
* Посчитайте $\log$ от него

In [442]:
v * 3

array([[21, 21, 21, 12, 24,  9,  0],
       [ 3,  3, 24, 12, 21, 21,  3],
       [ 3, 18, 18,  0, 18, 21, 18],
       [18, 18,  3, 24,  3, 21, 12],
       [12,  3, 12,  0,  0, 15,  6]])

In [443]:
v / 7

array([[1.        , 1.        , 1.        , 0.57142857, 1.14285714,
        0.42857143, 0.        ],
       [0.14285714, 0.14285714, 1.14285714, 0.57142857, 1.        ,
        1.        , 0.14285714],
       [0.14285714, 0.85714286, 0.85714286, 0.        , 0.85714286,
        1.        , 0.85714286],
       [0.85714286, 0.85714286, 0.14285714, 1.14285714, 0.14285714,
        1.        , 0.57142857],
       [0.57142857, 0.14285714, 0.57142857, 0.        , 0.        ,
        0.71428571, 0.28571429]])

In [444]:
v ** (2 / 3)

array([[3.65930571, 3.65930571, 3.65930571, 2.5198421 , 4.        ,
        2.08008382, 0.        ],
       [1.        , 1.        , 4.        , 2.5198421 , 3.65930571,
        3.65930571, 1.        ],
       [1.        , 3.30192725, 3.30192725, 0.        , 3.30192725,
        3.65930571, 3.30192725],
       [3.30192725, 3.30192725, 1.        , 4.        , 1.        ,
        3.65930571, 2.5198421 ],
       [2.5198421 , 1.        , 2.5198421 , 0.        , 0.        ,
        2.92401774, 1.58740105]])

In [445]:
np.sin(v)

array([[ 0.6569866 ,  0.6569866 ,  0.6569866 , -0.7568025 ,  0.98935825,
         0.14112001,  0.        ],
       [ 0.84147098,  0.84147098,  0.98935825, -0.7568025 ,  0.6569866 ,
         0.6569866 ,  0.84147098],
       [ 0.84147098, -0.2794155 , -0.2794155 ,  0.        , -0.2794155 ,
         0.6569866 , -0.2794155 ],
       [-0.2794155 , -0.2794155 ,  0.84147098,  0.98935825,  0.84147098,
         0.6569866 , -0.7568025 ],
       [-0.7568025 ,  0.84147098, -0.7568025 ,  0.        ,  0.        ,
        -0.95892427,  0.90929743]])

In [446]:
np.log(v)

C:\Users\NADUTK~1.FED\AppData\Local\Temp/ipykernel_61420/3686484441.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(v)


array([[1.94591015, 1.94591015, 1.94591015, 1.38629436, 2.07944154,
        1.09861229,       -inf],
       [0.        , 0.        , 2.07944154, 1.38629436, 1.94591015,
        1.94591015, 0.        ],
       [0.        , 1.79175947, 1.79175947,       -inf, 1.79175947,
        1.94591015, 1.79175947],
       [1.79175947, 1.79175947, 0.        , 2.07944154, 0.        ,
        1.94591015, 1.38629436],
       [1.38629436, 0.        , 1.38629436,       -inf,       -inf,
        1.60943791, 0.69314718]])

### Разные инициализации + индексирование (3 балла)

Задание 8.

Необходимо построить квадрат $3 \times 3$ из нечётных чисел

In [447]:
np.arange(start=1, stop=9 * 2 + 1, step=2).reshape((3, 3))

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

Задание 9.

Необходимо построить квадрат $4 \times 4$ из четных чисел в обратном порядке

In [448]:
np.arange(start=16 * 2, stop=0, step=-2).reshape((4, 4))

array([[32, 30, 28, 26],
       [24, 22, 20, 18],
       [16, 14, 12, 10],
       [ 8,  6,  4,  2]])

Задание 10.

Необходимо построить сетку координат $11 \times 11$ с точкой $(0,0)$ в центре и шагом $0.1$ между клетками

In [449]:
horizontal = [1, 0.9, 0.8, 0.7, 0.6, 0.5, 0.6, 0.7, 0.8, 0.9, 1]
vertical = [0, -0.1, -0.2, -0.3, -0.4, -0.5, -0.4, -0.3, -0.2, -0.1, 0]
one, two = np.meshgrid(horizontal, vertical)
one + two

array([[1. , 0.9, 0.8, 0.7, 0.6, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ],
       [0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
       [0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8],
       [0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7],
       [0.6, 0.5, 0.4, 0.3, 0.2, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6],
       [0.5, 0.4, 0.3, 0.2, 0.1, 0. , 0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.5, 0.4, 0.3, 0.2, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6],
       [0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7],
       [0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8],
       [0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
       [1. , 0.9, 0.8, 0.7, 0.6, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]])

Задание 11.

Замощение сетки $8\times8$ при помощи $0$ и $1$ в шахматном порядке, клетка с индексом $(0,0)$ замощается $1$

In [450]:
line = [-0.5, 0.5] * 4
one, two = np.meshgrid(line, line)
np.abs(one - two)

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

Задание 12.

То же замощение, но клетка с индексом $(0,0)$ замощается $0$

In [451]:
np.abs(one + two)

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

Задание 13.

Необходимо построить нижне-треугольную матрицу переменного размера (задается передачей параметра в функцию). Это единичная матрица,замощённая $1$ под главной диагональю

In [452]:
from numpy import ndarray


def lower_triangle_matrix(size: int) -> ndarray:
    return np.tril(np.ones((size, size), int), -1)


lower_triangle_matrix(4)

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 1, 0, 0],
       [1, 1, 1, 0]])

Задание 14.

Необходимо построить верхне-треугольную матрицу переменного размера. Это единичная матрица, замощённая $1$ над главной диагональю

In [453]:
def upper_triangle_matrix(size: int) -> ndarray:
    return np.triu(np.ones((size, size), int), 1)


upper_triangle_matrix(4)

array([[0, 1, 1, 1],
       [0, 0, 1, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])

Задание 15.

Необходимо построить матрицу, в которой единицы стоят на побочной диагонали (идущей из левого нижнего угла в правый верхний), в остальных местах стоят $0$

In [454]:
def secondary_diagonal(size: int) -> ndarray:
    return np.fliplr(np.eye(size, dtype=int))


secondary_diagonal(4)

array([[0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0]])

### Операции + аггрегации (3 балла)

Задание 16.

Дана выборка $\{X_i\}$ некоторой случайной величины $X$, необходимо оценить
* Математическое ожидание $E[X] = \frac{1}{N}\sum_{i=1}^N X_i$ этой случайной величины
* Дисперсию $D[X] = \frac{1}{N}\sum_{i=1}^N (X_i - E[X])^2$ этой случайной величины

In [455]:
def expected_value(x):
    assert len(x) > 0
    return sum(x) / len(x)


def dispersion(x):
    assert len(x) > 0
    d = 0
    e = expected_value(x)
    for x_i in x:
        d += (x_i - e) ** 2
    return d / len(x)

In [456]:
def expected_value_np(x: ndarray) -> float:
    assert x.size > 0
    return x.sum() / x.size


expected_value([1, 2, 3, 4])

2.5

In [457]:
def dispersion_np(x: ndarray) -> float:
    assert x.size > 0
    expected = expected_value(x)
    return np.sum(np.vectorize(lambda element: (element - expected) ** 2)(x)) / x.size

In [458]:
np.testing.assert_array_equal(expected_value([1]), expected_value_np(np.array([1])))
np.testing.assert_array_equal(expected_value([3, 4]), expected_value_np(np.array([3, 4])))
np.testing.assert_array_equal(expected_value([-1, 0, 1]), expected_value_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(expected_value([-99, -98]), expected_value_np(np.array([-99, -98])))

np.testing.assert_array_equal(dispersion([1]), dispersion_np(np.array([1])))
np.testing.assert_array_equal(dispersion([3, 4]), dispersion_np(np.array([3, 4])))
np.testing.assert_array_equal(dispersion([-1, 0, 1]), dispersion_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(dispersion([-99, -98]), dispersion_np(np.array([-99, -98])))

Задание 17.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое квадратов разностей их значений

In [459]:
def mean_square_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    # Здесь и далее эти проверки !не нужно! дублировать в свои функции; Здесь они для того, чтобы лишний раз подчеркнуть валидность входных данных
    s = 0
    for i in range(len(y1)):
        s += (y1[i] - y2[i]) ** 2
    return s / len(y1)

In [460]:
def mean_square_difference_np(y1, y2):
    return np.sum((y1 - y2) ** 2) / y1.size

In [461]:
assert mean_square_difference([1], [1]) == mean_square_difference_np(np.array([1]), np.array([1]))
assert mean_square_difference([1, 2], [1, 2]) == mean_square_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_square_difference([-1, 1], [0, 0]) == mean_square_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_square_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_square_difference_np(
    np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 18.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое модулей разностей их значений

In [462]:
def mean_abs_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    s = 0
    for i in range(len(y1)):
        s += abs(y1[i] - y2[i])
    return s / len(y1)

In [463]:
def mean_abs_difference_np(y1, y2):
    return np.mean(np.abs(y1 - y2))

In [464]:
assert mean_abs_difference([1], [1]) == mean_abs_difference_np(np.array([1]), np.array([1]))
assert mean_abs_difference([1, 2], [1, 2]) == mean_abs_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_abs_difference([-1, 1], [0, 0]) == mean_abs_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_abs_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_abs_difference_np(
    np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 19.

Даны два вектора $y_1$ и $y_2$, в которых присутствуют только $0$ и $1$. Необходимо посчитать вероятность совпадения - в скольких точках значения двух векторов совпадают

In [465]:
def matching_proba(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    assert len(set(y1)) <= 2
    assert len(set(y2)) <= 2
    assert 0 in set(y1) or 1 in set(y1) or (0 in set(y1) and 1 in set(y1))
    assert 0 in set(y2) or 1 in set(y2) or (0 in set(y2) and 1 in set(y2))

    return sum([y1[i] == y2[i] for i in range(len(y1))]) / len(y1)

In [466]:
def matching_proba_np(y1, y2):
    return np.mean(np.equal(y1, y2))

In [467]:
np.testing.assert_array_equal(matching_proba([0, 1], [1, 0]), matching_proba_np(np.array([0, 1]), np.array([1, 0])))
np.testing.assert_array_equal(matching_proba([0, 1, 0, 1], [0, 0, 1, 1]),
                              matching_proba_np(np.array([0, 1, 0, 1]), np.array([0, 0, 1, 1])))
np.testing.assert_array_equal(matching_proba([0, 0, 1, 1], [0, 0, 1, 1]),
                              matching_proba_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1])))

Задание 20.

Даны два вектора: $y_1$, $y_2$. В $y_1$ и $y_2$ присутствуют только $0$ и $1$.

Необходимо найти границы (индексы), такие, что если мы разделим вдоль какой-то из этих границ оба вектора на две части, то
* в левой части пересекающихся в $y_1$ и $y_2$ нулей будет строго больше, чем пересекающихся единиц или непересекающихся элементов
* в правой - пересекающихся единиц строго больше, чем пересекающихся нулей или непересекающихся элементов.

Если какая-то из частей не содержит элементов вовсе, то будем считать, что она подходит под условие.

In [468]:
def find_thresholds(y1, y2, debug=False):
    assert len(y1) == len(y2) and len(y1) > 0
    n = len(y1)
    matching_zeros = [1 if y1[i] == y2[i] == 0 else 0 for i in range(n)]
    matching_ones = [1 if y1[i] == y2[i] == 1 else 0 for i in range(n)]
    res = []
    if sum(matching_ones) / n > 0.5:
        res.append(0)
    for i in range(1, n):
        if debug:  # если вам непонятна логика работы этой функции, передайте третьим аргументом True
            print(matching_zeros[:i], matching_ones[i:], i)
        if sum(matching_zeros[:i]) / i > 0.5 and sum(matching_ones[i:]) / (n - i) > 0.5:
            res.append(i)
    if sum(matching_zeros) / n > 0.5:
        res.append(n)
    return res

In [469]:
def find_thresholds_np(y1, y2):
    length = y1.size
    prefix = np.zeros(length + 1).astype(int)
    postfix = np.zeros(length + 1).astype(int)
    prefix[1:] = np.cumsum(np.vectorize(lambda x1, x2: (x1 == x2) & (x1 == 0))(y1, y2))
    postfix[:length] = np.flip(np.cumsum(np.vectorize(lambda x1, x2: x1 == x2 & x1 == 1)
                                (np.flip(y1), np.flip(y2))))
    answer = np.array([])
    if postfix[0] > length * 0.5:
        answer = np.append(answer, 0)
    array = np.arange(1, length)
    middle = array[(prefix[array] / array > 0.5) & (postfix[array] / (length - array) > 0.5)]
    answer = np.append(answer, middle)
    if prefix[length] > length * 0.5:
        answer = np.append(answer, length)
    return answer.astype(int)

In [470]:
np.testing.assert_array_equal(find_thresholds([0], [0]), find_thresholds_np(np.array([0]), np.array([0])))
np.testing.assert_array_equal(find_thresholds([1], [1]), find_thresholds_np(np.array([1]), np.array([1])))
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 1], [0, 0, 1, 1]),
    find_thresholds_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1]))
)
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 0, 0, 1, 1, 1], [0, 0, 0, 0, 0, 1, 1, 1]),
    find_thresholds_np(np.array([0, 0, 1, 0, 0, 1, 1, 1]), np.array([0, 0, 0, 0, 0, 1, 1, 1]))
)

### Разные действия с матрицами (3 балла)

Задание 21.

Дана матрица размера $(32, 3, 16, 16)$, заполненная случайными числами от 0 до 9. При помощи **ровно двух** преобразований приведите её к виду $(32, 1)$. При выполнении задания **можно** создавать вспомогательные матрицы!

In [471]:
data = np.random.randint(0, 10, size=(32, 3, 16, 16))
data = data.reshape((32, 768))
helper = np.random.randint(0, 10, size=(768, 1))
data = np.matmul(data, helper)

assert data.shape == (32, 1)

Задание 22.

Даны две матрицы $m_1$ размером $(32, 256)$ и $m_2$ размером $(32, 512)$, а также две вспомогательные матрицы $W_1$ размером $(256, 32)$ и $W_2$ размером $(512, 16)$. Используя **все** данные матрицы, сделайте так, чтобы на выходе получилась **ровно одна** матрица размером $(32, 32)$

In [472]:
m1 = np.random.randint(0, 10, size=(32, 256))
m2 = np.random.randint(0, 10, size=(32, 512))
W1 = np.random.randint(0, 10, size=(256, 32))
W2 = np.random.randint(0, 10, size=(512, 16))

result = np.matmul(np.matmul(m1, W1),
                   np.matmul(
                       np.matmul(
                           np.matmul(m2, W2), W2.T), m2.T))
assert result.shape == (32, 32)
print(result.shape)

(32, 32)


Задание 23.

Приведите полученную на последнем шаге матрицу к виду $(32, 3)$ и сделайте так, чтобы все значения в этой матрице были в промежутке от $0$ до $1$

In [473]:
# Вжух! (∩｀-´)⊃━☆ﾟ.*･｡ﾟ
result = np.abs(np.matmul(result, np.random.randint(0, 10, size=(32, 3))))
maximum = np.max(result)
result = np.divide(result, maximum)

assert result.shape == (32, 3)
assert ((result >= 0) & (result <= 1)).all()