## Домашнее задание

В этой тетрадке вам предлагается реализовать задания при помощи библиотеки numpy. Крайне желательно при выполнении разных заданий не использовать циклы. Если вы не понимаете, как выполнить конкретную задачу без циклов - убирайте их постепенно, разбейте выполнение задачи на этапы и постепенно векторизуйте каждый этап.

Если вам непонятно, как выполнить ту или иную операцию - не стесняйтесь гуглить, если над вами повис дедлайн, а вы всё ещё на чём-то застряли - пишите преподу/в чат, это ок.

**Обсудить решение лучше и сделать в итоге хоть что-то гораздо лучше, чем скатать чужой код или сдать пустую тетрадку.**

In [97]:
import numpy as np

### Drill (1 балл)

Задание 1.

Инициализируйте нулями массивы следующих форм:

* (5)
* (5, 1)
* (10, 2)
* (3, 6, 2)
* (4, 3, 2, 1)

In [98]:
# Ваш код
z1 = np.zeros((5))
z2 = np.zeros((5,1))
z3 = np.zeros((10,2))
z4 = np.zeros((3,6,2))
z5 = np.zeros((4,3,2,1))
z = [z1, z2, z3, z4, z5]
print(z3)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


Задание 2.

Инициализируйте единицами массивы таких же форм и приведите их к целочисленному виду:

In [99]:
o1 = np.ones((5), dtype=int)
o2 = np.ones((5,1), dtype=int)
o3 = np.ones((10,2), dtype=int)
o4 = np.ones((3,6,2), dtype=int)
o5 = np.ones((4,3,2,1), dtype=int)
o = [o1, o2, o3, o4, o5]
##print(m1, m2, m3, m4, m5, sep='\n')

Задание 3.

Выполните для векторов выше `reshape` в "форму"
* с двумя компонентами
* с тремя компонентами
* с четырьмя компонентами

In [100]:
o1.reshape((5, 1))
o2.reshape((5, 1))
o3.reshape((10, 2))
o4.reshape((3, 12))
o5.reshape((4, 6))

o1.reshape((5, 1, 1))
o2.reshape((5, 1, 1))
o3.reshape((10, 2, 1))
o4.reshape((3, 6, 2))
o5.reshape((4, 3, 2))

o1.reshape((5, 1, 1, 1))
o2.reshape((5, 1, 1, 1))
o3.reshape((10, 2, 1, 1))
o4.reshape((3, 6, 2, 1))
o5.reshape((4, 3, 2, 1))

array([[[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]],


       [[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]],


       [[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]],


       [[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]]])

Задание 4.

Для вектора ниже посчитайте его
* Максимум по 1 оси
* Минимум по 0 оси
* Сумму по всем осям
* Среднее по 0 оси
* Медиану по 1 оси

In [101]:
v = np.random.randint(0, 9, size=(5, 7))

In [102]:
print(v, '\n')


print(np.amax(v, axis=1))
print(np.amin(v, axis=0))
print(np.sum(v, axis=(0,1)))
print(np.mean(v, axis=0))
print(np.median(v, axis=1))




[[8 0 8 4 7 0 5]
 [3 7 0 5 3 1 7]
 [3 6 0 7 6 2 3]
 [7 3 8 0 2 2 3]
 [5 5 7 6 4 8 6]] 

[8 7 7 8 8]
[3 0 0 0 2 0 3]
151
[5.2 4.2 4.6 4.4 4.4 2.6 4.8]
[5. 3. 3. 3. 6.]


Задание 5.

Для всё того же вектора `v` выведите
* Его shape
* 0 компоненту его "формы"
* 1 компоненту его "формы"

In [103]:
print(v.shape)
print(v.shape[0], v.shape[1])

(5, 7)
5 7


Задание 6.

Для этого же вектора выведите
* Все числа больше 5
* Все числа меньше 7 в обратном порядке
* Все числа больше 3, которые делятся на 4 без остатка
* Все числа, остаток от деления на 5 которых равен 3
* Индекс максимума
* Индекс минимума
* Cписок с индексами элементов отсортированного массива в исходном (неотсортированном)

In [104]:
print(v[v >= 2])
print(v[v<7][::-1])
print(v[np.logical_and(v > 3, v % 4 == 0)] )
print(np.argmax(v))
print(np.argmin(v))
print(np.argsort(v))



[8 8 4 7 5 3 7 5 3 7 3 6 7 6 2 3 7 3 8 2 2 3 5 5 7 6 4 8 6]
[6 4 6 5 5 3 2 2 0 3 3 2 6 0 6 3 1 3 5 0 3 5 0 4 0]
[8 8 4 8 4 8]
0
1
[[1 5 3 6 4 0 2]
 [2 5 0 4 3 1 6]
 [2 5 0 6 1 4 3]
 [3 4 5 1 6 0 2]
 [4 0 1 3 6 2 5]]


Задание 7.

Выполните следующие операции над вектором (независимо, не обязательно делать это в последовательности):
* Умножьте его на 3
* Разделите на 7
* Возведите в степень $\frac{2}{3}$
* Посчитайте $\sin$ от него
* Посчитайте $\log$ от него

In [105]:
print(v)
print(3 * v)
print(v / 7)
print(v ** (2.0 / 3.0))
print(np.sin(v))
print(np.log(v))

[[8 0 8 4 7 0 5]
 [3 7 0 5 3 1 7]
 [3 6 0 7 6 2 3]
 [7 3 8 0 2 2 3]
 [5 5 7 6 4 8 6]]
[[24  0 24 12 21  0 15]
 [ 9 21  0 15  9  3 21]
 [ 9 18  0 21 18  6  9]
 [21  9 24  0  6  6  9]
 [15 15 21 18 12 24 18]]
[[1.14285714 0.         1.14285714 0.57142857 1.         0.
  0.71428571]
 [0.42857143 1.         0.         0.71428571 0.42857143 0.14285714
  1.        ]
 [0.42857143 0.85714286 0.         1.         0.85714286 0.28571429
  0.42857143]
 [1.         0.42857143 1.14285714 0.         0.28571429 0.28571429
  0.42857143]
 [0.71428571 0.71428571 1.         0.85714286 0.57142857 1.14285714
  0.85714286]]
[[4.         0.         4.         2.5198421  3.65930571 0.
  2.92401774]
 [2.08008382 3.65930571 0.         2.92401774 2.08008382 1.
  3.65930571]
 [2.08008382 3.30192725 0.         3.65930571 3.30192725 1.58740105
  2.08008382]
 [3.65930571 2.08008382 4.         0.         1.58740105 1.58740105
  2.08008382]
 [2.92401774 2.92401774 3.65930571 3.30192725 2.5198421  4.
  3.30192725]]
[[ 

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in log
  


### Разные инициализации + индексирование (3 балла)

Задание 8.

Необходимо построить квадрат $3 \times 3$ из нечётных чисел

In [106]:
np.reshape(np.array(range(1, 19, 2)), (3,3))

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

Задание 9.

Необходимо построить квадрат $4 \times 4$ из четных чисел в обратном порядке

In [107]:
np.reshape(np.array(range(32, 0, -2)), (4, 4))

array([[32, 30, 28, 26],
       [24, 22, 20, 18],
       [16, 14, 12, 10],
       [ 8,  6,  4,  2]])

Задание 10.

Необходимо построить сетку координат $11 \times 11$ с точкой $(0,0)$ в центре и шагом $0.1$ между клетками

In [108]:
np.reshape(list(map(lambda x: (abs(5 - x // 11) + abs(5 - x % 11) ),range(121))), (11, 11)) / 10.0

array([[1. , 0.9, 0.8, 0.7, 0.6, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ],
       [0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
       [0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8],
       [0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7],
       [0.6, 0.5, 0.4, 0.3, 0.2, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6],
       [0.5, 0.4, 0.3, 0.2, 0.1, 0. , 0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.5, 0.4, 0.3, 0.2, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6],
       [0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7],
       [0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8],
       [0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
       [1. , 0.9, 0.8, 0.7, 0.6, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]])

Задание 11.

Замощение сетки $8\times8$ при помощи $0$ и $1$ в шахматном порядке, клетка с индексом $(0,0)$ замощается $1$

In [109]:
np.reshape(np.array(list(map(lambda x: 1 - (x % 2 + (x//8) % 2) % 2, list(range(64))))), (8, 8))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

Задание 12.

То же замощение, но клетка с индексом $(0,0)$ замощается $0$

In [110]:
np.reshape(np.array(list(map(lambda x: (x % 2 + (x//8) % 2) % 2, list(range(64))))), (8, 8))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

Задание 13.

Необходимо построить нижне-треугольную матрицу переменного размера (задается передачей параметра в функцию). Это единичная матрица,замощённая $1$ под главной диагональю

In [111]:
def lower_triangle_matrix(n):
  return np.reshape(np.array(list(map(lambda x: int(x % n <= x // n), list(range(n * n))))), (n, n))
print(lower_triangle_matrix(10))

[[1 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0]
 [1 1 1 0 0 0 0 0 0 0]
 [1 1 1 1 0 0 0 0 0 0]
 [1 1 1 1 1 0 0 0 0 0]
 [1 1 1 1 1 1 0 0 0 0]
 [1 1 1 1 1 1 1 0 0 0]
 [1 1 1 1 1 1 1 1 0 0]
 [1 1 1 1 1 1 1 1 1 0]
 [1 1 1 1 1 1 1 1 1 1]]


Задание 14.

Необходимо построить верхне-треугольную матрицу переменного размера. Это единичная матрица, замощённая $1$ над главной диагональю

In [112]:
def upper_triangle_matrix(n):
  return np.reshape(np.array(list(map(lambda x: int(x % n >= x // n), list(range(n * n))))), (n, n))
print(upper_triangle_matrix(10))

[[1 1 1 1 1 1 1 1 1 1]
 [0 1 1 1 1 1 1 1 1 1]
 [0 0 1 1 1 1 1 1 1 1]
 [0 0 0 1 1 1 1 1 1 1]
 [0 0 0 0 1 1 1 1 1 1]
 [0 0 0 0 0 1 1 1 1 1]
 [0 0 0 0 0 0 1 1 1 1]
 [0 0 0 0 0 0 0 1 1 1]
 [0 0 0 0 0 0 0 0 1 1]
 [0 0 0 0 0 0 0 0 0 1]]


Задание 15.

Необходимо построить матрицу, в которой единицы стоят на побочной диагонали (идущей из левого нижнего угла в правый верхний), в остальных местах стоят $0$

In [113]:
def side_matrix(n):
  return np.reshape(np.array(list(map(lambda x: int(n - x % n == x // n), list(range(n * n))))), (n, n))
print(side_matrix(10))

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]]


### Операции + аггрегации (3 балла)

Задание 16.

Дана выборка $\{X_i\}$ некоторой случайной величины $X$, необходимо оценить
* Математическое ожидание $E[X] = \frac{1}{N}\sum_{i=1}^N X_i$ этой случайной величины
* Дисперсию $D[X] = \frac{1}{N}\sum_{i=1}^N (X_i - E[X])^2$ этой случайной величины

In [114]:
def expected_value(x):
    assert len(x) > 0
    return sum(x) / len(x)


def dispersion(x):
    assert len(x) > 0
    d = 0
    e = expected_value(x)
    for x_i in x:
        d += (x_i - e) ** 2
    return d / len(x)

In [115]:
def expected_value_np(x):
    return np.mean(x)

In [116]:
def dispersion_np(x):
    return np.mean((x - np.mean(x)) ** 2)

In [117]:
np.testing.assert_array_equal(expected_value([1]), expected_value_np(np.array([1])))
np.testing.assert_array_equal(expected_value([3, 4]), expected_value_np(np.array([3, 4])))
np.testing.assert_array_equal(expected_value([-1, 0, 1]), expected_value_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(expected_value([-99, -98]), expected_value_np(np.array([-99, -98])))

np.testing.assert_array_equal(dispersion([1]), dispersion_np(np.array([1])))
np.testing.assert_array_equal(dispersion([3, 4]), dispersion_np(np.array([3, 4])))
np.testing.assert_array_equal(dispersion([-1, 0, 1]), dispersion_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(dispersion([-99, -98]), dispersion_np(np.array([-99, -98])))

Задание 17.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое квадратов разностей их значений

In [118]:
def mean_square_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    # Здесь и далее эти проверки !не нужно! дублировать в свои функции; Здесь они для того, чтобы лишний раз подчеркнуть валидность входных данных
    s = 0
    for i in range(len(y1)):
        s += (y1[i] - y2[i]) ** 2
    return s / len(y1)

In [119]:
def mean_square_difference_np(y1, y2):
    return (int(np.square(np.linalg.norm(y1-y2)) * 100000)) / ( 100000 * len(y1)) ## грязный хак потому что 0.1+0.1+0.1 != 0.3 :)

In [120]:
assert mean_square_difference([1], [1]) == mean_square_difference_np(np.array([1]), np.array([1]))
assert mean_square_difference([1, 2], [1, 2]) == mean_square_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_square_difference([-1, 1], [0, 0]) == mean_square_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_square_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_square_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 18.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое модулей разностей их значений

In [121]:
def mean_abs_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    s = 0
    for i in range(len(y1)):
        s += abs(y1[i] - y2[i])
    return s / len(y1)

In [122]:
def mean_abs_difference_np(y1, y2):
    return np.linalg.norm(y1 - y2, ord=1) / len(y1)

In [123]:
assert mean_abs_difference([1], [1]) == mean_abs_difference_np(np.array([1]), np.array([1]))
assert mean_abs_difference([1, 2], [1, 2]) == mean_abs_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_abs_difference([-1, 1], [0, 0]) == mean_abs_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_abs_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_abs_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 19.

Даны два вектора $y_1$ и $y_2$, в которых присутствуют только $0$ и $1$. Необходимо посчитать вероятность совпадения - в скольких точках значения двух векторов совпадают

In [124]:
def matching_proba(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    assert len(set(y1)) <= 2
    assert len(set(y2)) <= 2
    assert 0 in set(y1) or 1 in set(y1) or (0 in set(y1) and 1 in set(y1))
    assert 0 in set(y2) or 1 in set(y2) or (0 in set(y2) and 1 in set(y2))

    return sum([y1[i] == y2[i] for i in range(len(y1))]) / len(y1)

In [125]:
def matching_proba_np(y1, y2):
    return ((y1 + y2) % 2 == 0).sum() / len(y1)

    

In [126]:
np.testing.assert_array_equal(matching_proba([0, 1], [1, 0]), matching_proba_np(np.array([0, 1]), np.array([1, 0])))
np.testing.assert_array_equal(matching_proba([0, 1, 0, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 1, 0, 1]), np.array([0, 0, 1, 1])))
np.testing.assert_array_equal(matching_proba([0, 0, 1, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1])))

Задание 20.

Даны два вектора: $y_1$, $y_2$. В $y_1$ и $y_2$ присутствуют только $0$ и $1$.

Необходимо найти границы (индексы), такие, что если мы разделим вдоль какой-то из этих границ оба вектора на две части, то
* в левой части пересекающихся в $y_1$ и $y_2$ нулей будет строго больше, чем пересекающихся единиц или непересекающихся элементов
* в правой - пересекающихся единиц строго больше, чем пересекающихся нулей или непересекающихся элементов.

Если какая-то из частей не содержит элементов вовсе, то будем считать, что она подходит под условие.

In [127]:
def find_thresholds(y1, y2, debug=False):
    assert len(y1) == len(y2) and len(y1) > 0
    n = len(y1)
    matching_zeros = [1 if y1[i] == y2[i] == 0 else 0 for i in range(n)]
    matching_ones = [1 if y1[i] == y2[i] == 1 else 0 for i in range(n)]
    res = []
    if sum(matching_ones) / n > 0.5:
        res.append(0)
    for i in range(1, n):
        if debug: # если вам непонятна логика работы этой функции, передайте третьим аргументом True
            print(matching_zeros[:i], matching_ones[i:], i)
        if sum(matching_zeros[:i]) / i > 0.5 and sum(matching_ones[i:]) / (n - i) > 0.5:
            res.append(i)
    if sum(matching_zeros) / n > 0.5:
        res.append(n)
    return res

In [128]:
def division(y1, y2, index):
  count_intersect_zeros = np.sum((y1[:index] + y2[:index]) == 0)
  others_in_first_part = len(y1[:index]) - count_intersect_zeros
  
  count_intersect_ones = np.sum((y1[index:] + y2[index:]) == 2)
  others_in_second_part = len(y1[index:]) - count_intersect_ones
  return (count_intersect_zeros > others_in_first_part or (len(y1[:index]) == 0)) and (count_intersect_ones > others_in_second_part or (len(y1[index:]) == 0))



def find_thresholds_np(y1, y2):
    return list(filter(lambda x: division(y1, y2, x), range(len(y1) + 1)))

In [129]:
np.testing.assert_array_equal(find_thresholds([0], [0]), find_thresholds_np(np.array([0]), np.array([0])))
np.testing.assert_array_equal(find_thresholds([1], [1]), find_thresholds_np(np.array([1]), np.array([1])))
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 1], [0, 0, 1, 1]), 
    find_thresholds_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1]))
)
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 0, 0, 1, 1, 1], [0, 0, 0, 0, 0, 1, 1, 1]),
    find_thresholds_np(np.array([0, 0, 1, 0, 0, 1, 1, 1]), np.array([0, 0, 0, 0, 0, 1, 1, 1]))
)

### Разные действия с матрицами (3 балла)

Задание 21.

Дана матрица размера $(32, 3, 16, 16)$, заполненная случайными числами от 0 до 9. При помощи **ровно двух** преобразований приведите её к виду $(32, 1)$. При выполнении задания **можно** создавать вспомогательные матрицы!

In [130]:
data = np.random.randint(0, 10, size=(32, 3, 16, 16))
sz1 = 32 * 3 * 16 * 16
sz2 = 3 * 16 * 16

# Преобразование 1
data = np.reshape(data, (32, sz2))
# Преобразование 2
data = np.delete(data, range(1, len(data[0])), 1)

assert data.shape == (32, 1)

Задание 22.

Даны две матрицы $m_1$ размером $(32, 256)$ и $m_2$ размером $(32, 512)$, а также две вспомогательные матрицы $W_1$ размером $(256, 32)$ и $W_2$ размером $(512, 16)$. Используя **все** данные матрицы, сделайте так, чтобы на выходе получилась **ровно одна** матрица размером $(32, 32)$

In [131]:
m1 = np.random.randint(0, 10, size=(32, 256))
m2 = np.random.randint(0, 10, size=(32, 512))
W1 = np.random.randint(0, 10, size=(256, 32))
W2 = np.random.randint(0, 10, size=(512, 16))

result = m1 @ W1 + np.concatenate((m2 @ W2, np.zeros((32, 16))), axis = 1)

assert result.shape == (32, 32)

Задание 23.

Приведите полученную на последнем шаге матрицу к виду $(32, 3)$ и сделайте так, чтобы все значения в этой матрице были в промежутке от $0$ до $1$

In [132]:
# Вжух! (∩｀-´)⊃━☆ﾟ.*･｡ﾟ

result = np.abs(result[:, :3]) / 1000000000

assert result.shape == (32, 3)
assert ((result >= 0) & (result <= 1)).all()