## Домашнее задание

В этой тетрадке вам предлагается реализовать задания при помощи библиотеки numpy. Крайне желательно при выполнении разных заданий не использовать циклы. Если вы не понимаете, как выполнить конкретную задачу без циклов - убирайте их постепенно, разбейте выполнение задачи на этапы и постепенно векторизуйте каждый этап.

Если вам непонятно, как выполнить ту или иную операцию - не стесняйтесь гуглить, если над вами повис дедлайн, а вы всё ещё на чём-то застряли - пишите преподу/в чат, это ок.

**Обсудить решение лучше и сделать в итоге хоть что-то гораздо лучше, чем скатать чужой код или сдать пустую тетрадку.**

In [2]:
import numpy as np

### Drill (1 балл)

Задание 1.

Инициализируйте нулями массивы следующих форм:

* (5)
* (5, 1)
* (10, 2)
* (3, 6, 2)
* (4, 3, 2, 1)

In [8]:
zeros_1d = np.zeros(5)
zeros_2d = np.zeros((5, 1))
zeros_2d_2 = np.zeros((10, 2))
zeros_3d = np.zeros((3, 6, 2))
zeros_4d = np.zeros((4, 3, 2, 1))

Задание 2.

Инициализируйте единицами массивы таких же форм и приведите их к целочисленному виду:

In [20]:
ones_1d = np.ones(5, dtype=np.int16)
ones_2d = np.ones((5, 1), dtype=np.int16)
ones_2d_2 = np.ones((10, 2), dtype=np.int16)
ones_3d = np.ones((3, 6, 2), dtype=np.int16)
ones_4d = np.ones((4, 3, 2, 1), dtype=np.int16)

Задание 3.

Выполните для векторов выше `reshape` в "форму"
* с двумя компонентами
* с тремя компонентами
* с четырьмя компонентами

In [25]:
zeroes_1d_2 = ones_1d.reshape((1, 5))
zeroes_1d_3 = ones_1d.reshape((1, 1, 5))
zeroes_1d_4 = ones_1d.reshape((1, 1, 1, 5))

zeroes_2d_2 = ones_2d.reshape((1, 5))
zeroes_2d_3 = ones_2d.reshape((1, 1, 5))
zeroes_2d_4 = ones_2d.reshape((1, 1, 1, 5))

zeroes_2d_2_2 = ones_2d_2.reshape((2, 10))
zeroes_2d_2_3 = ones_2d_2.reshape((2, 2, 5))
zeroes_2d_2_4 = ones_2d_2.reshape((1, 2, 2, 5))

zeroes_3d_2 = ones_3d.reshape((6, 6))
zeroes_3d_3 = ones_3d.reshape((3, 3, 4))
zeroes_3d_4 = ones_3d.reshape((3, 3, 2, 2))

zeroes_4d_2 = ones_4d.reshape((4, 6))
zeroes_4d_3 = ones_4d.reshape((2, 2, 6))
zeroes_4d_4 = ones_4d.reshape((1, 2, 3, 4))

4


Задание 4.

Для вектора ниже посчитайте его
* Максимум по 1 оси
* Минимум по 0 оси
* Сумму по всем осям
* Среднее по 0 оси
* Медиану по 1 оси

In [220]:
v = np.random.randint(0, 9, size=(5, 7))

In [221]:
print(v)

[[4 5 5 5 0 4 3]
 [7 8 4 1 8 4 3]
 [5 0 8 0 1 4 4]
 [1 8 1 3 4 2 5]
 [0 2 2 4 6 7 0]]


In [222]:
print(np.max(v, axis=1))
print(np.max(v, axis=0))
print(np.sum(v, axis=(0, 1)))
print(np.mean(v, axis=0))
print(np.median(v, axis=1))

[5 8 8 8 7]
[7 8 8 5 8 7 5]
128
[3.4 4.6 4.  2.6 3.8 4.2 3. ]
[4. 4. 4. 3. 2.]


Задание 5.

Для всё того же вектора `v` выведите
* Его shape
* 0 компоненту его "формы"
* 1 компоненту его "формы"

In [223]:
print(v.shape)
print(v.shape[0])
print(v.shape[1])

(5, 7)
5
7


Задание 6.

Для этого же вектора выведите
* Все числа больше 5
* Все числа меньше 7 в обратном порядке
* Все числа больше 3, которые делятся на 4 без остатка
* Все числа, остаток от деления на 5 которых равен 3
* Индекс максимума
* Индекс минимума
* Cписок с индексами элементов отсортированного массива в исходном (неотсортированном)

In [224]:
print(v[v > 5])
print(v[v < 7][::-1])
print(v[(v > 3) & (v % 4 == 0)])
print(v[v % 5 == 3])
print(v.argmax())
print(v.argmin())
print(v.argsort())

[7 8 8 8 8 6 7]
[0 6 4 2 2 0 5 2 4 3 1 1 4 4 1 0 0 5 3 4 1 4 3 4 0 5 5 5 4]
[4 4 8 4 8 4 8 4 4 8 4 4]
[3 8 8 3 8 8 3]
8
4
[[4 6 0 5 1 2 3]
 [3 6 2 5 0 1 4]
 [1 3 4 5 6 0 2]
 [0 2 5 3 4 6 1]
 [0 6 1 2 3 4 5]]


In [36]:
print(v)

[[4 0 1 2 8 3 0]
 [1 8 4 4 1 8 5]
 [7 4 4 8 6 1 8]
 [6 5 7 5 6 2 8]
 [5 4 3 5 5 3 0]]


Задание 7.

Выполните следующие операции над вектором (независимо, не обязательно делать это в последовательности):
* Умножьте его на 3
* Разделите на 7
* Возведите в степень $\frac{2}{3}$
* Посчитайте $\sin$ от него
* Посчитайте $\log$ от него

In [37]:
print(v * 3)
print(v / 7)
print(v ** (2/3))
print(np.sin(v))
print(np.log(v))

[[12  0  3  6 24  9  0]
 [ 3 24 12 12  3 24 15]
 [21 12 12 24 18  3 24]
 [18 15 21 15 18  6 24]
 [15 12  9 15 15  9  0]]
[[0.57142857 0.         0.14285714 0.28571429 1.14285714 0.42857143
  0.        ]
 [0.14285714 1.14285714 0.57142857 0.57142857 0.14285714 1.14285714
  0.71428571]
 [1.         0.57142857 0.57142857 1.14285714 0.85714286 0.14285714
  1.14285714]
 [0.85714286 0.71428571 1.         0.71428571 0.85714286 0.28571429
  1.14285714]
 [0.71428571 0.57142857 0.42857143 0.71428571 0.71428571 0.42857143
  0.        ]]
[[2.5198421  0.         1.         1.58740105 4.         2.08008382
  0.        ]
 [1.         4.         2.5198421  2.5198421  1.         4.
  2.92401774]
 [3.65930571 2.5198421  2.5198421  4.         3.30192725 1.
  4.        ]
 [3.30192725 2.92401774 3.65930571 2.92401774 3.30192725 1.58740105
  4.        ]
 [2.92401774 2.5198421  2.08008382 2.92401774 2.92401774 2.08008382
  0.        ]]
[[-0.7568025   0.          0.84147098  0.90929743  0.98935825  0.14112001

/tmp/ipykernel_16529/676646889.py:5: RuntimeWarning: divide by zero encountered in log
  print(np.log(v))


### Разные инициализации + индексирование (3 балла)

Задание 8.

Необходимо построить квадрат $3 \times 3$ из нечётных чисел

In [48]:
odd = np.arange(1, 18, 2).reshape(3, 3)
odd

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

Задание 9.

Необходимо построить квадрат $4 \times 4$ из четных чисел в обратном порядке

In [50]:
even = np.arange(0, 32, 2)[::-1].reshape(4, 4)
even

array([[30, 28, 26, 24],
       [22, 20, 18, 16],
       [14, 12, 10,  8],
       [ 6,  4,  2,  0]])

Задание 10.

Необходимо построить сетку координат $11 \times 11$ с точкой $(0,0)$ в центре и шагом $0.1$ между клетками

In [31]:
x = np.linspace(-0.5, 0.5, 11)
y = np.linspace(0.5, -0.5, 11)
grid = np.meshgrid(x, y)
np.stack((grid[0], grid[1]))

array([[[-0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,
          0.5],
        [-0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,
          0.5],
        [-0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,
          0.5],
        [-0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,
          0.5],
        [-0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,
          0.5],
        [-0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,
          0.5],
        [-0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,
          0.5],
        [-0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,
          0.5],
        [-0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,
          0.5],
        [-0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,
          0.5],
        [-0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,
          0.5]],

       [[ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5, 

Задание 11.

Замощение сетки $8\times8$ при помощи $0$ и $1$ в шахматном порядке, клетка с индексом $(0,0)$ замощается $1$

In [46]:
1 - np.indices((8, 8)).sum(axis=0) % 2

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

Задание 12.

То же замощение, но клетка с индексом $(0,0)$ замощается $0$

In [47]:
np.indices((8, 8)).sum(axis=0) % 2

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

Задание 13.

Необходимо построить нижне-треугольную матрицу переменного размера (задается передачей параметра в функцию). Это единичная матрица,замощённая $1$ под главной диагональю

In [52]:
def lower_ones_init(x, y):
    return np.tril(np.ones((x, y)), -1)

lower_ones_init(5, 5)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.]])

Задание 14.

Необходимо построить верхне-треугольную матрицу переменного размера. Это единичная матрица, замощённая $1$ над главной диагональю

In [53]:
def upper_ones_init(x, y):
    return np.triu(np.ones((x, y)), 1)

upper_ones_init(5, 5)

array([[0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

Задание 15.

Необходимо построить матрицу, в которой единицы стоят на побочной диагонали (идущей из левого нижнего угла в правый верхний), в остальных местах стоят $0$

In [57]:
shape = 5
np.eye(shape)[::-1]

array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.]])

### Операции + аггрегации (3 балла)

Задание 16.

Дана выборка $\{X_i\}$ некоторой случайной величины $X$, необходимо оценить
* Математическое ожидание $E[X] = \frac{1}{N}\sum_{i=1}^N X_i$ этой случайной величины
* Дисперсию $D[X] = \frac{1}{N}\sum_{i=1}^N (X_i - E[X])^2$ этой случайной величины

In [60]:
def expected_value(x):
    assert len(x) > 0
    return sum(x) / len(x)


def dispersion(x):
    assert len(x) > 0
    d = 0
    e = expected_value(x)
    for x_i in x:
        d += (x_i - e) ** 2
    return d / len(x)

In [63]:
def expected_value_np(x):
    return np.mean(x)

In [64]:
def dispersion_np(x):
    return np.var(x)

In [71]:
np.testing.assert_array_equal(expected_value([1]), expected_value_np(np.array([1])))
np.testing.assert_array_equal(expected_value([3, 4]), expected_value_np(np.array([3, 4])))
np.testing.assert_array_equal(expected_value([-1, 0, 1]), expected_value_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(expected_value([-99, -98]), expected_value_np(np.array([-99, -98])))

np.testing.assert_array_equal(dispersion([1]), dispersion_np(np.array([1])))
np.testing.assert_array_equal(dispersion([3, 4]), dispersion_np(np.array([3, 4])))
np.testing.assert_array_equal(dispersion([-1, 0, 1]), dispersion_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(dispersion([-99, -98]), dispersion_np(np.array([-99, -98])))

Задание 17.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое квадратов разностей их значений

In [74]:
def mean_square_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    # Здесь и далее эти проверки !не нужно! дублировать в свои функции; Здесь они для того, чтобы лишний раз подчеркнуть валидность входных данных
    s = 0
    for i in range(len(y1)):
        s += (y1[i] - y2[i]) ** 2
    return s / len(y1)

In [79]:
def mean_square_difference_np(y1, y2):
    return np.mean(((y2 - y1)**2))

In [80]:
assert mean_square_difference([1], [1]) == mean_square_difference_np(np.array([1]), np.array([1]))
assert mean_square_difference([1, 2], [1, 2]) == mean_square_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_square_difference([-1, 1], [0, 0]) == mean_square_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_square_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_square_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 18.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое модулей разностей их значений

In [81]:
def mean_abs_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    s = 0
    for i in range(len(y1)):
        s += abs(y1[i] - y2[i])
    return s / len(y1)

In [86]:
def mean_abs_difference_np(y1, y2):
    return np.mean((np.abs((y2 - y1))))

In [87]:
assert mean_abs_difference([1], [1]) == mean_abs_difference_np(np.array([1]), np.array([1]))
assert mean_abs_difference([1, 2], [1, 2]) == mean_abs_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_abs_difference([-1, 1], [0, 0]) == mean_abs_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_abs_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_abs_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 19.

Даны два вектора $y_1$ и $y_2$, в которых присутствуют только $0$ и $1$. Необходимо посчитать вероятность совпадения - в скольких точках значения двух векторов совпадают

In [89]:
def matching_proba(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    assert len(set(y1)) <= 2
    assert len(set(y2)) <= 2
    assert 0 in set(y1) or 1 in set(y1) or (0 in set(y1) and 1 in set(y1))
    assert 0 in set(y2) or 1 in set(y2) or (0 in set(y2) and 1 in set(y2))

    return sum([y1[i] == y2[i] for i in range(len(y1))]) / len(y1)

In [90]:
def matching_proba_np(y1, y2):
    return np.sum(y1 == y2) / len(y1)

In [91]:
np.testing.assert_array_equal(matching_proba([0, 1], [1, 0]), matching_proba_np(np.array([0, 1]), np.array([1, 0])))
np.testing.assert_array_equal(matching_proba([0, 1, 0, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 1, 0, 1]), np.array([0, 0, 1, 1])))
np.testing.assert_array_equal(matching_proba([0, 0, 1, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1])))

Задание 20.

Даны два вектора: $y_1$, $y_2$. В $y_1$ и $y_2$ присутствуют только $0$ и $1$.

Необходимо найти границы (индексы), такие, что если мы разделим вдоль какой-то из этих границ оба вектора на две части, то
* в левой части пересекающихся в $y_1$ и $y_2$ нулей будет строго больше, чем пересекающихся единиц или непересекающихся элементов
* в правой - пересекающихся единиц строго больше, чем пересекающихся нулей или непересекающихся элементов.

Если какая-то из частей не содержит элементов вовсе, то будем считать, что она подходит под условие.

In [4]:
def find_thresholds(y1, y2, debug=False):
    assert len(y1) == len(y2) and len(y1) > 0
    n = len(y1)
    matching_zeros = [1 if y1[i] == y2[i] == 0 else 0 for i in range(n)]
    matching_ones = [1 if y1[i] == y2[i] == 1 else 0 for i in range(n)]
    res = []
    if sum(matching_ones) / n > 0.5:
        res.append(0)
    for i in range(1, n):
        if debug: # если вам непонятна логика работы этой функции, передайте третьим аргументом True
            print(matching_zeros[:i], matching_ones[i:], i)
        if sum(matching_zeros[:i]) / i > 0.5 and sum(matching_ones[i:]) / (n - i) > 0.5:
            res.append(i)
    if sum(matching_zeros) / n > 0.5:
        res.append(n)
    return res


In [5]:
def find_thresholds_np(y1, y2):
    coords = np.tril(np.ones((len(y1), len(y1)))).astype(bool)
    y1 = np.tile(y1, (len(y1), 1))
    y2 = np.tile(y2, (len(y2), 1))
    comparison_1 = (y1 == y2) & (y1 == 1) & (y2 == 1)
    comparison_1 = np.triu(comparison_1, 1)
    comparison_1 = np.sum(comparison_1, axis=1) / np.sum(np.triu(np.ones((len(y1), len(y1))), 1), axis=1)
    comparison_2 = (y1 == y2) & (y1 == 0) & (y2 == 0)
    comparison_2 = np.tril(comparison_2, -1)
    comparison_2 = np.sum(comparison_2, axis=1) / np.sum(np.tril(np.ones((len(y1), len(y1))), -1), axis=1)
    comparison = comparison_1 + comparison_2
    return np.nonzero(comparison >= 1)[0]

In [6]:
np.testing.assert_array_equal(find_thresholds([0], [0]), find_thresholds_np(np.array([0]), np.array([0])))
np.testing.assert_array_equal(find_thresholds([1], [1]), find_thresholds_np(np.array([1]), np.array([1])))
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 1], [0, 0, 1, 1]), 
    find_thresholds_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1]))
)
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 0, 0, 1, 1, 1], [0, 0, 0, 0, 0, 1, 1, 1]),
    find_thresholds_np(np.array([0, 0, 1, 0, 0, 1, 1, 1]), np.array([0, 0, 0, 0, 0, 1, 1, 1]))
)

/tmp/ipykernel_5183/4108402986.py:7: RuntimeWarning: invalid value encountered in true_divide
  comparison_1 = np.sum(comparison_1, axis=1) / np.sum(np.triu(np.ones((len(y1), len(y1))), 1), axis=1)
/tmp/ipykernel_5183/4108402986.py:10: RuntimeWarning: invalid value encountered in true_divide
  comparison_2 = np.sum(comparison_2, axis=1) / np.sum(np.tril(np.ones((len(y1), len(y1))), -1), axis=1)


AssertionError: 
Arrays are not equal

(shapes (1,), (0,) mismatch)
 x: array([1])
 y: array([], dtype=int64)

### Разные действия с матрицами (3 балла)

Задание 21.

Дана матрица размера $(32, 3, 16, 16)$, заполненная случайными числами от 0 до 9. При помощи **ровно двух** преобразований приведите её к виду $(32, 1)$. При выполнении задания **можно** создавать вспомогательные матрицы!

In [7]:
data = np.random.randint(0, 10, size=(32, 3, 16, 16))
data_2 = np.random.randint(0, 10, size=(48*16, 1))

data = data.reshape(32, 48*16)
data = np.matmul(data, data_2)

assert data.shape == (32, 1)

Задание 22.

Даны две матрицы $m_1$ размером $(32, 256)$ и $m_2$ размером $(32, 512)$, а также две вспомогательные матрицы $W_1$ размером $(256, 32)$ и $W_2$ размером $(512, 16)$. Используя **все** данные матрицы, сделайте так, чтобы на выходе получилась **ровно одна** матрица размером $(32, 32)$

In [8]:
m1 = np.random.randint(0, 10, size=(32, 256))
m2 = np.random.randint(0, 10, size=(32, 512))
W1 = np.random.randint(0, 10, size=(256, 32))
W2 = np.random.randint(0, 10, size=(512, 16))

step_1 = np.matmul(m1, W1)
step_2 = np.matmul(step_1, m1)
step_3 = np.matmul(step_2, m2.reshape(256, 64))
step_4 = np.matmul(step_3, m2.reshape(64, 256))

result = np.matmul(step_4, W2.reshape(256, 32))

assert result.shape == (32, 32)

Задание 23.

Приведите полученную на последнем шаге матрицу к виду $(32, 3)$ и сделайте так, чтобы все значения в этой матрице были в промежутке от $0$ до $1$

In [9]:
# Вжух! (∩｀-´)⊃━☆ﾟ.*･｡ﾟ
result = np.matmul(result, np.eye(32, 3)) / np.max(np.matmul(result, np.eye(32, 3)))

assert result.shape == (32, 3)
assert ((result >= 0) & (result <= 1)).all()