## Домашнее задание

В этой тетрадке вам предлагается реализовать задания при помощи библиотеки numpy. Крайне желательно при выполнении разных заданий не использовать циклы. Если вы не понимаете, как выполнить конкретную задачу без циклов - убирайте их постепенно, разбейте выполнение задачи на этапы и постепенно векторизуйте каждый этап.

Если вам непонятно, как выполнить ту или иную операцию - не стесняйтесь гуглить, если над вами повис дедлайн, а вы всё ещё на чём-то застряли - пишите преподу/в чат, это ок.

**Обсудить решение лучше и сделать в итоге хоть что-то гораздо лучше, чем скатать чужой код или сдать пустую тетрадку.**

In [1]:
import numpy as np

### Drill (1 балл)

Задание 1.

Инициализируйте нулями массивы следующих форм:

* (5)
* (5, 1)
* (10, 2)
* (3, 6, 2)
* (4, 3, 2, 1)

In [2]:
np.zeros(5)
np.zeros((5, 1))
np.zeros((10, 2))
np.zeros((3, 6, 2))
np.zeros((4, 3, 2, 1))
print()

Задание 2.

Инициализируйте единицами массивы таких же форм и приведите их к целочисленному виду:

In [3]:
v1 = np.ones(5, dtype=int)
v2 = np.ones((5, 1), dtype=int)
v3 = np.ones((10, 2), dtype=int)
v4 = np.ones((3, 6, 2), dtype=int)
v5 = np.ones((4, 3, 2, 1), dtype=int)
print()

Задание 3.

Выполните для векторов выше `reshape` в "форму"
* с двумя компонентами
* с тремя компонентами
* с четырьмя компонентами

In [4]:
v1.reshape((5, 1))
v2.reshape((1, 5))
v3.reshape((2, 10))
v4.reshape((6, 6))
v5.reshape((4, 6))

v1.reshape((5, 1, 1))
v2.reshape((1, 5, 1))
v3.reshape((2, 2, 5))
v4.reshape((9, 2, 2))
v5.reshape((2, 6, 2))

v1.reshape((5, 1, 1, 1))
v2.reshape((1, 5, 1, 1))
v3.reshape((2, 2, 5, 1))
v4.reshape((3, 3, 2, 2))
v5.reshape((2, 3, 2, 2))

print()


Задание 4.

Для вектора ниже посчитайте его
* Максимум по 1 оси
* Минимум по 0 оси
* Сумму по всем осям
* Среднее по 0 оси
* Медиану по 1 оси

In [5]:
v = np.random.randint(0, 9, size=(5, 7))
print(v)

[[2 8 7 1 6 8 0]
 [7 1 0 7 3 8 1]
 [7 7 8 7 0 7 3]
 [0 1 4 2 8 1 6]
 [8 8 4 5 4 7 0]]


In [6]:
print(v.max(axis=1))
print(v.min(axis=0))
print(v.sum())
print(np.average(v, axis=0))
print(np.median(v, axis=1))


[8 8 8 8 8]
[0 1 0 1 0 1 0]
156
[4.8 5.  4.6 4.4 4.2 6.2 2. ]
[6. 3. 7. 2. 5.]


Задание 5.

Для всё того же вектора `v` выведите
* Его shape
* 0 компоненту его "формы"
* 1 компоненту его "формы"

In [7]:
print(v.shape)
print(v.shape[0])
print(v.shape[1])

(5, 7)
5
7


Задание 6.

Для этого же вектора выведите
* Все числа больше 5
* Все числа меньше 7 в обратном порядке
* Все числа больше 3, которые делятся на 4 без остатка
* Все числа, остаток от деления на 5 которых равен 3
* Индекс максимума
* Индекс минимума
* Cписок с индексами элементов отсортированного массива в исходном (неотсортированном)

In [67]:
print(v[v > 5])
print(v[v < 7][::-1])
print(v[(v > 3) & (v % 4 == 0)])
print(v[v % 5 == 3])
print(np.argmax(v))
print(np.argmin(v))
print(v)
print(v.argsort(axis=None))


[8 7 6 8 7 7 8 7 7 8 7 7 8 6 8 8 7]
[0 4 5 4 6 1 2 4 1 0 3 0 1 3 0 1 0 6 1 2]
[8 8 8 8 4 8 8 8 4 4]
[8 8 3 8 8 3 8 8 8]
1
6
[[2 8 7 1 6 8 0]
 [7 1 0 7 3 8 1]
 [7 7 8 7 0 7 3]
 [0 1 4 2 8 1 6]
 [8 8 4 5 4 7 0]]
[34 21  6 18  9 26  3 22  8 13 24  0 11 20 23 32 30 31 27  4  2 17 19  7
 33 15 14 10 25  1 16 28 29  5 12]


Задание 7.

Выполните следующие операции над вектором (независимо, не обязательно делать это в последовательности):
* Умножьте его на 3
* Разделите на 7
* Возведите в степень $\frac{2}{3}$
* Посчитайте $\sin$ от него
* Посчитайте $\log$ от него

In [9]:
print(v * 3)
print(v / 7)
print(v ** 2/3)
print(np.sin(v))
print(np.log(v))


[[ 6 24 21  3 18 24  0]
 [21  3  0 21  9 24  3]
 [21 21 24 21  0 21  9]
 [ 0  3 12  6 24  3 18]
 [24 24 12 15 12 21  0]]
[[0.28571429 1.14285714 1.         0.14285714 0.85714286 1.14285714
  0.        ]
 [1.         0.14285714 0.         1.         0.42857143 1.14285714
  0.14285714]
 [1.         1.         1.14285714 1.         0.         1.
  0.42857143]
 [0.         0.14285714 0.57142857 0.28571429 1.14285714 0.14285714
  0.85714286]
 [1.14285714 1.14285714 0.57142857 0.71428571 0.57142857 1.
  0.        ]]
[[ 1.33333333 21.33333333 16.33333333  0.33333333 12.         21.33333333
   0.        ]
 [16.33333333  0.33333333  0.         16.33333333  3.         21.33333333
   0.33333333]
 [16.33333333 16.33333333 21.33333333 16.33333333  0.         16.33333333
   3.        ]
 [ 0.          0.33333333  5.33333333  1.33333333 21.33333333  0.33333333
  12.        ]
 [21.33333333 21.33333333  5.33333333  8.33333333  5.33333333 16.33333333
   0.        ]]
[[ 0.90929743  0.98935825  0.6569866  

/var/folders/h1/t_mhn1ls3kng9jp7k_fn_mqm0000gn/T/ipykernel_8155/377420040.py:5: RuntimeWarning: divide by zero encountered in log
  print(np.log(v))


### Разные инициализации + индексирование (3 балла)

Задание 8.

Необходимо построить квадрат $3 \times 3$ из нечётных чисел

In [10]:
np.arange(1, 18, 2).reshape((3, 3))

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

Задание 9.

Необходимо построить квадрат $4 \times 4$ из четных чисел в обратном порядке

In [11]:
np.arange(32, 1, -2).reshape((4, 4))

array([[32, 30, 28, 26],
       [24, 22, 20, 18],
       [16, 14, 12, 10],
       [ 8,  6,  4,  2]])

Задание 10.

Необходимо построить сетку координат $11 \times 11$ с точкой $(0,0)$ в центре и шагом $0.1$ между клетками

In [63]:
# Как я понял массив снизу отвечает за координату по x, а сверху за y
np.mgrid[6:-6.1:-0.1, -6:6.1:0.1]

array([[[ 6. ,  6. ,  6. , ...,  6. ,  6. ,  6. ],
        [ 5.9,  5.9,  5.9, ...,  5.9,  5.9,  5.9],
        [ 5.8,  5.8,  5.8, ...,  5.8,  5.8,  5.8],
        ...,
        [-5.8, -5.8, -5.8, ..., -5.8, -5.8, -5.8],
        [-5.9, -5.9, -5.9, ..., -5.9, -5.9, -5.9],
        [-6. , -6. , -6. , ..., -6. , -6. , -6. ]],

       [[-6. , -5.9, -5.8, ...,  5.8,  5.9,  6. ],
        [-6. , -5.9, -5.8, ...,  5.8,  5.9,  6. ],
        [-6. , -5.9, -5.8, ...,  5.8,  5.9,  6. ],
        ...,
        [-6. , -5.9, -5.8, ...,  5.8,  5.9,  6. ],
        [-6. , -5.9, -5.8, ...,  5.8,  5.9,  6. ],
        [-6. , -5.9, -5.8, ...,  5.8,  5.9,  6. ]]])

Задание 11.

Замощение сетки $8\times8$ при помощи $0$ и $1$ в шахматном порядке, клетка с индексом $(0,0)$ замощается $1$

In [13]:
lol = lambda x: ((x % 11) + (x // 11)) % 2

lol(np.arange(11, 132).reshape((11, 11)))

array([[1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]])

Задание 12.

То же замощение, но клетка с индексом $(0,0)$ замощается $0$

In [14]:
lol(np.arange(121).reshape((11, 11)))

array([[0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]])

Задание 13.

Необходимо построить нижне-треугольную матрицу переменного размера (задается передачей параметра в функцию). Это единичная матрица,замощённая $1$ под главной диагональю

In [71]:
def cheburek(shape):
    big = np.eye(shape)
    small = np.eye(shape - 1)
    big[1:shape, 0:shape - 1] += small;
    return big


cheburek(5)

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [0., 1., 1., 0., 0.],
       [0., 0., 1., 1., 0.],
       [0., 0., 0., 1., 1.]])

Задание 14.

Необходимо построить верхне-треугольную матрицу переменного размера. Это единичная матрица, замощённая $1$ над главной диагональю

In [76]:
def arbidol(shape):
    big = np.eye(shape)
    small = np.eye(shape - 1)
    big[0:shape - 1, 1:shape] += small;
    return big


arbidol(5)

array([[1., 1., 0., 0., 0.],
       [0., 1., 1., 0., 0.],
       [0., 0., 1., 1., 0.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1.]])

Задание 15.

Необходимо построить матрицу, в которой единицы стоят на побочной диагонали (идущей из левого нижнего угла в правый верхний), в остальных местах стоят $0$

In [80]:
def idk(shape):
    ans = np.zeros((shape, shape))
    ans[:, ::-1] = np.eye(shape)
    return ans

idk(5)

array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.]])

### Операции + аггрегации (3 балла)

Задание 16.

Дана выборка $\{X_i\}$ некоторой случайной величины $X$, необходимо оценить
* Математическое ожидание $E[X] = \frac{1}{N}\sum_{i=1}^N X_i$ этой случайной величины
* Дисперсию $D[X] = \frac{1}{N}\sum_{i=1}^N (X_i - E[X])^2$ этой случайной величины

In [18]:
def expected_value(x):
    assert len(x) > 0
    return sum(x) / len(x)

def dispersion(x):
    assert len(x) > 0
    d = 0
    e = expected_value(x)
    for x_i in x:
        d += (x_i - e) ** 2
    return d / len(x)

In [19]:
def expected_value_np(x):
    assert len(x) > 0
    return x.sum() / len(x)

In [20]:
# Я знаю формулу круче вашей
def dispersion_np(x):
    assert len(x) > 0
    return expected_value_np(x * x) - expected_value_np(x)**2

In [21]:
np.testing.assert_array_equal(expected_value([1]), expected_value_np(np.array([1])))
np.testing.assert_array_equal(expected_value([3, 4]), expected_value_np(np.array([3, 4])))
np.testing.assert_array_equal(expected_value([-1, 0, 1]), expected_value_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(expected_value([-99, -98]), expected_value_np(np.array([-99, -98])))

np.testing.assert_array_equal(dispersion([1]), dispersion_np(np.array([1])))
np.testing.assert_array_equal(dispersion([3, 4]), dispersion_np(np.array([3, 4])))
np.testing.assert_array_equal(dispersion([-1, 0, 1]), dispersion_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(dispersion([-99, -98]), dispersion_np(np.array([-99, -98])))

Задание 17.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое квадратов разностей их значений

In [22]:
def mean_square_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    # Здесь и далее эти проверки !не нужно! дублировать в свои функции; Здесь они для того, чтобы лишний раз подчеркнуть валидность входных данных
    s = 0
    for i in range(len(y1)):
        s += (y1[i] - y2[i]) ** 2
    return s / len(y1)

In [23]:
def mean_square_difference_np(y1, y2):
    return ((y1 - y2)**2).sum() / len(y1)

In [24]:
assert mean_square_difference([1], [1]) == mean_square_difference_np(np.array([1]), np.array([1]))
assert mean_square_difference([1, 2], [1, 2]) == mean_square_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_square_difference([-1, 1], [0, 0]) == mean_square_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_square_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_square_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 18.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое модулей разностей их значений

In [25]:
def mean_abs_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    s = 0
    for i in range(len(y1)):
        s += abs(y1[i] - y2[i])
    return s / len(y1)

In [26]:
def mean_abs_difference_np(y1, y2):
    return abs(y1 - y2).sum() / len(y1)

In [27]:
assert mean_abs_difference([1], [1]) == mean_abs_difference_np(np.array([1]), np.array([1]))
assert mean_abs_difference([1, 2], [1, 2]) == mean_abs_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_abs_difference([-1, 1], [0, 0]) == mean_abs_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_abs_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_abs_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 19.

Даны два вектора $y_1$ и $y_2$, в которых присутствуют только $0$ и $1$. Необходимо посчитать вероятность совпадения - в скольких точках значения двух векторов совпадают

In [28]:
def matching_proba(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    assert len(set(y1)) <= 2
    assert len(set(y2)) <= 2
    assert 0 in set(y1) or 1 in set(y1) or (0 in set(y1) and 1 in set(y1))
    assert 0 in set(y2) or 1 in set(y2) or (0 in set(y2) and 1 in set(y2))

    return sum([y1[i] == y2[i] for i in range(len(y1))]) / len(y1)

In [29]:
def matching_proba_np(y1, y2):
    return 1 - (y1 ^ y2).sum()/len(y1)

In [30]:
np.testing.assert_array_equal(matching_proba([0, 1], [1, 0]), matching_proba_np(np.array([0, 1]), np.array([1, 0])))
np.testing.assert_array_equal(matching_proba([0, 1, 0, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 1, 0, 1]), np.array([0, 0, 1, 1])))
np.testing.assert_array_equal(matching_proba([0, 0, 1, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1])))

Задание 20.

Даны два вектора: $y_1$, $y_2$. В $y_1$ и $y_2$ присутствуют только $0$ и $1$.

Необходимо найти границы (индексы), такие, что если мы разделим вдоль какой-то из этих границ оба вектора на две части, то
* в левой части пересекающихся в $y_1$ и $y_2$ нулей будет строго больше, чем пересекающихся единиц или непересекающихся элементов
* в правой - пересекающихся единиц строго больше, чем пересекающихся нулей или непересекающихся элементов.

Если какая-то из частей не содержит элементов вовсе, то будем считать, что она подходит под условие.

In [31]:
def find_thresholds(y1, y2, debug=False):
    assert len(y1) == len(y2) and len(y1) > 0
    n = len(y1)
    matching_zeros = [1 if y1[i] == y2[i] == 0 else 0 for i in range(n)]
    matching_ones = [1 if y1[i] == y2[i] == 1 else 0 for i in range(n)]
    res = []
    if sum(matching_ones) / n > 0.5:
        res.append(0)
    for i in range(1, n):
        if debug: # если вам непонятна логика работы этой функции, передайте третьим аргументом True
            print(matching_zeros[:i], matching_ones[i:], i)
        if sum(matching_zeros[:i]) / i > 0.5 and sum(matching_ones[i:]) / (n - i) > 0.5:
            res.append(i)
    if sum(matching_zeros) / n > 0.5:
        res.append(n)
    return res

find_thresholds([0, 0, 1, 0, 0, 1, 1, 1], [0, 0, 0, 0, 0, 1, 1, 1], True)

[1] [0, 0, 0, 0, 1, 1, 1] 1
[1, 1] [0, 0, 0, 1, 1, 1] 2
[1, 1, 0] [0, 0, 1, 1, 1] 3
[1, 1, 0, 1] [0, 1, 1, 1] 4
[1, 1, 0, 1, 1] [1, 1, 1] 5
[1, 1, 0, 1, 1, 0] [1, 1] 6
[1, 1, 0, 1, 1, 0, 0] [1] 7


[3, 4, 5, 6, 7]

In [32]:
# Рофлорешение, стирать было обидно

def find_thresholds_np(y1, y2):
    n = len(y1)

    matching_zeros = (2 - np.array(y1) - np.array(y2)) // 2 # 1 if y1[i] == y2[i] == 0
    matching_ones = (np.array(y1) + np.array(y2)) // 2 # 1 if y1[i] == y2[i] == 1

    indexes = np.arange(n + 1)
    res = []
    def awful(x):
        if x == 0:
            return 1 if matching_ones.sum() / n > 0.5 else 0

        if x == n:
            return 1 if matching_zeros.sum() / n > 0.5 else 0

        return 1 if (matching_zeros[:x].sum() / x > 0.5 and matching_ones[x:].sum() / (n - x) > 0.5) else 0

    vawful = np.vectorize(awful)
    mask = vawful(indexes)

    return indexes[mask == 1]

In [59]:
# Норм решение

def find_thresholds_np(y1, y2):
    n = len(y1)

    matching_zeros = (2 - np.array(y1) - np.array(y2)) // 2 # 1 if y1[i] == y2[i] == 0
    matching_ones = (np.array(y1) + np.array(y2)) // 2 # 1 if y1[i] == y2[i] == 1

    prev_zeros = np.cumsum(matching_zeros)
    prev_ones = np.cumsum(matching_ones[::-1])

    reverse_indexes = 1 / np.arange(1, n + 1)

    norm_zeros = prev_zeros @ np.diag(reverse_indexes)
    norm_ones = prev_ones @ np.diag(reverse_indexes)

    pos_zeros = np.arange(1, n + 1)[norm_zeros > 0.5]
    pos_ones = np.arange(n)[::-1][norm_ones > 0.5]

    if matching_ones.sum() / n > 0.5:
        pos_zeros = np.append(pos_zeros, 0)
        pos_ones = np.append(pos_ones, 0)
        
    if matching_zeros.sum() / n > 0.5:
        pos_zeros = np.append(pos_zeros, n)
        pos_ones = np.append(pos_ones, n)


    return np.intersect1d(pos_zeros, pos_ones)

find_thresholds_np(np.array([0, 0, 1, 0, 0, 1, 1, 1]), np.array([0, 0, 0, 0, 0, 1, 1, 1]))


array([3, 4, 5, 6, 7])

In [60]:
np.testing.assert_array_equal(find_thresholds([0], [0]), find_thresholds_np(np.array([0]), np.array([0])))
np.testing.assert_array_equal(find_thresholds([1], [1]), find_thresholds_np(np.array([1]), np.array([1])))
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 1], [0, 0, 1, 1]), 
    find_thresholds_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1]))
)
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 0, 0, 1, 1, 1], [0, 0, 0, 0, 0, 1, 1, 1]),
    find_thresholds_np(np.array([0, 0, 1, 0, 0, 1, 1, 1]), np.array([0, 0, 0, 0, 0, 1, 1, 1]))
)

### Разные действия с матрицами (3 балла)

Задание 21.

Дана матрица размера $(32, 3, 16, 16)$, заполненная случайными числами от 0 до 9. При помощи **ровно двух** преобразований приведите её к виду $(32, 1)$. При выполнении задания **можно** создавать вспомогательные матрицы!

In [ ]:
data = np.random.randint(0, 10, size=(32, 3, 16, 16))

data = data.reshape(32, -1)
data = data[:, :1]

assert data.shape == (32, 1)

Задание 22.

Даны две матрицы $m_1$ размером $(32, 256)$ и $m_2$ размером $(32, 512)$, а также две вспомогательные матрицы $W_1$ размером $(256, 32)$ и $W_2$ размером $(512, 16)$. Используя **все** данные матрицы, сделайте так, чтобы на выходе получилась **ровно одна** матрица размером $(32, 32)$

In [ ]:
m1 = np.random.randint(0, 10, size=(32, 256))
m2 = np.random.randint(0, 10, size=(32, 512))
W1 = np.random.randint(0, 10, size=(256, 32))
W2 = np.random.randint(0, 10, size=(512, 16))

result = m1 @ W1 @ m2 @ np.concatenate((W2, W2), axis=1)

assert result.shape == (32, 32)

Задание 23.

Приведите полученную на последнем шаге матрицу к виду $(32, 3)$ и сделайте так, чтобы все значения в этой матрице были в промежутке от $0$ до $1$

In [ ]:
# Вжух! (∩｀-´)⊃━☆ﾟ.*･｡ﾟ
result = result[:, :3] / result.max()

assert result.shape == (32, 3)
assert ((result >= 0) & (result <= 1)).all()