## Домашнее задание

В этой тетрадке вам предлагается реализовать задания при помощи библиотеки numpy. Крайне желательно при выполнении разных заданий не использовать циклы. Если вы не понимаете, как выполнить конкретную задачу без циклов - убирайте их постепенно, разбейте выполнение задачи на этапы и постепенно векторизуйте каждый этап.

Если вам непонятно, как выполнить ту или иную операцию - не стесняйтесь гуглить, если над вами повис дедлайн, а вы всё ещё на чём-то застряли - пишите преподу/в чат, это ок.

**Обсудить решение лучше и сделать в итоге хоть что-то гораздо лучше, чем скатать чужой код или сдать пустую тетрадку.**

In [1]:
import numpy as np

### Drill (1 балл)

Задание 1.

Инициализируйте нулями массивы следующих форм:

* (5)
* (5, 1)
* (10, 2)
* (3, 6, 2)
* (4, 3, 2, 1)

In [2]:
np.zeros(5)
np.zeros((5, 1))
np.zeros((3, 6 ,2))
np.zeros((4, 3, 2, 1))

array([[[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]],


       [[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]],


       [[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]],


       [[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]]])

Задание 2.

Инициализируйте единицами массивы таких же форм и приведите их к целочисленному виду:

In [3]:
np.ones(5).astype(int)
np.ones((5, 1)).astype(int)
np.ones((10,2)).astype(int)
np.ones((3,6,2)).astype(int)
np.ones((4,3,2,1)).astype(int)

array([[[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]],


       [[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]],


       [[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]],


       [[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]]])

Задание 3.

Выполните для векторов выше `reshape` в "форму"
* с двумя компонентами
* с тремя компонентами
* с четырьмя компонентами

In [4]:
np.reshape(np.ones(5).astype(int), (5, 1))
np.reshape(np.ones((5, 1)).astype(int), (5, 1))
np.reshape(np.ones((10, 2)).astype(int), (10, 2))
np.reshape(np.ones((3, 6, 2)).astype(int), (2, 18))
np.reshape(np.ones((4, 3, 2, 1)).astype(int), (12,2))

np.reshape(np.ones(5).astype(int), (5,1,1))
np.reshape(np.ones((5, 1)).astype(int), (5,1,1))
np.reshape(np.ones((10, 2)).astype(int), (10,2,1))
np.reshape(np.ones((3, 6, 2)).astype(int), (3,6,2))
np.reshape(np.ones((4, 3, 2, 1)).astype(int), (12,2,1))

np.reshape(np.ones(5).astype(int), (5,1,1,1))
np.reshape(np.ones((5, 1)).astype(int), (5,1,1,1))
np.reshape(np.ones((10, 2)).astype(int), (10,2,1,1))
np.reshape(np.ones((3, 6, 2)).astype(int), (3,6,2,1))
np.reshape(np.ones((4, 3, 2, 1)).astype(int), (12,2,1,1))

Задание 4.

Для вектора ниже посчитайте его
* Максимум по 1 оси
* Минимум по 0 оси
* Сумму по всем осям
* Среднее по 0 оси
* Медиану по 1 оси

In [5]:
v = np.random.randint(0, 9, size=(5, 7))

In [6]:
print(np.amax(v, axis = 1))
print(np.amax(v, axis = 0))
print(np.mean(v))
print(np.mean(v, axis = 1))
print(np.median(v, axis = 0))

[7 5 8 8 8]
[3 8 7 7 8 8 8]
3.342857142857143
[2.42857143 1.42857143 3.42857143 6.         3.42857143]
[1. 6. 0. 1. 6. 3. 2.]


Задание 5.

Для всё того же вектора `v` выведите
* Его shape
* 0 компоненту его "формы"
* 1 компоненту его "формы"

In [7]:
print(np.shape(v))
print(np.shape(v)[0])
print(np.shape(v)[1])

(5, 7)
5
7


Задание 6.

Для этого же вектора выведите
* Все числа больше 5
* Все числа меньше 7 в обратном порядке
* Все числа больше 3, которые делятся на 4 без остатка
* Все числа, остаток от деления на 5 которых равен 3
* Индекс максимума
* Индекс минимума
* Cписок с индексами элементов отсортированного массива в исходном (неотсортированном)

In [8]:
print(v[v>5])
print(v[v<7][::-1])
print(v[(v>3) & (v%3==0)])
print(v[v%5==3])
print(np.argmax(v))
print(np.argmin(v))
print(np.argsort(v))

[6 7 7 8 8 7 8 8 8 6 8 7]
[6 1 0 2 0 0 3 2 3 2 0 2 2 0 0 0 5 2 1 0 0 4 0 6 0]
[6 6]
[8 3 3 8 8 8 8 8]
18
0
[[0 3 5 6 4 1 2]
 [3 4 5 0 1 6 2]
 [2 0 3 6 5 1 4]
 [2 0 3 1 4 5 6]
 [0 2 3 1 4 6 5]]


Задание 7.

Выполните следующие операции над вектором (независимо, не обязательно делать это в последовательности):
* Умножьте его на 3
* Разделите на 7
* Возведите в степень $\frac{2}{3}$
* Посчитайте $\sin$ от него
* Посчитайте $\log$ от него

In [9]:
print(v*3)
print(v//7)
print(v**(2/3))
print(np.sin(v))
print(np.log(v))

[[ 0 18 21  0 12  0  0]
 [ 3  6 15  0  0  0  6]
 [ 6 21  0  6 24  9  6]
 [ 9 24  0 21 24 24 24]
 [ 0  6  0  3 18 24 21]]
[[0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 1 0 0 1 0 0]
 [0 1 0 1 1 1 1]
 [0 0 0 0 0 1 1]]
[[0.         3.30192725 3.65930571 0.         2.5198421  0.
  0.        ]
 [1.         1.58740105 2.92401774 0.         0.         0.
  1.58740105]
 [1.58740105 3.65930571 0.         1.58740105 4.         2.08008382
  1.58740105]
 [2.08008382 4.         0.         3.65930571 4.         4.
  4.        ]
 [0.         1.58740105 0.         1.         3.30192725 4.
  3.65930571]]
[[ 0.         -0.2794155   0.6569866   0.         -0.7568025   0.
   0.        ]
 [ 0.84147098  0.90929743 -0.95892427  0.          0.          0.
   0.90929743]
 [ 0.90929743  0.6569866   0.          0.90929743  0.98935825  0.14112001
   0.90929743]
 [ 0.14112001  0.98935825  0.          0.6569866   0.98935825  0.98935825
   0.98935825]
 [ 0.          0.90929743  0.          0.84147098 -0.2794155   0.98935825


C:\Users\lemuzme\AppData\Local\Temp\ipykernel_13796\1610129750.py:5: RuntimeWarning: divide by zero encountered in log
  print(np.log(v))


### Разные инициализации + индексирование (3 балла)

Задание 8.

Необходимо построить квадрат $3 \times 3$ из нечётных чисел

In [10]:
a=np.arange(19)
print(a[a%2 != 0].reshape(3,3))

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]


Задание 9.

Необходимо построить квадрат $4 \times 4$ из четных чисел в обратном порядке

In [11]:
b=np.arange(32)
b=b[b%2 == 0].reshape(4,4)
print(np.flip(b))

[[30 28 26 24]
 [22 20 18 16]
 [14 12 10  8]
 [ 6  4  2  0]]


Задание 10.

Необходимо построить сетку координат $11 \times 11$ с точкой $(0,0)$ в центре и шагом $0.1$ между клетками

In [12]:
# Ваш код

Задание 11.

Замощение сетки $8\times8$ при помощи $0$ и $1$ в шахматном порядке, клетка с индексом $(0,0)$ замощается $1$

In [13]:
j = np.zeros((8,8), dtype = int)
j[0::2, ::2]=1
j[1::2, 1::2]=1
print(j)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


Задание 12.

То же замощение, но клетка с индексом $(0,0)$ замощается $0$

In [14]:
j = np.zeros((8,8), dtype = int)
j[1::2, ::2]=1
j[::2,1::2]=1
print(j)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Задание 13.

Необходимо построить нижне-треугольную матрицу переменного размера (задается передачей параметра в функцию). Это единичная матрица,замощённая $1$ под главной диагональю

In [15]:
np.tri(5, 5, dtype=int)

array([[1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1]])

Задание 14.

Необходимо построить верхне-треугольную матрицу переменного размера. Это единичная матрица, замощённая $1$ над главной диагональю

In [16]:
np.triu(np.ones(5).astype(int), 0)

array([[1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1],
       [0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1],
       [0, 0, 0, 0, 1]])

Задание 15.

Необходимо построить матрицу, в которой единицы стоят на побочной диагонали (идущей из левого нижнего угла в правый верхний), в остальных местах стоят $0$

In [17]:
j = np.eye(5,5)
print(np.fliplr(j))

SyntaxError: '(' was never closed (1352962195.py, line 2)

### Операции + аггрегации (3 балла)

Задание 16.

Дана выборка $\{X_i\}$ некоторой случайной величины $X$, необходимо оценить
* Математическое ожидание $E[X] = \frac{1}{N}\sum_{i=1}^N X_i$ этой случайной величины
* Дисперсию $D[X] = \frac{1}{N}\sum_{i=1}^N (X_i - E[X])^2$ этой случайной величины

In [ ]:
def expected_value(x):
    assert len(x) > 0
    return sum(x) / len(x)


def dispersion(x):
    assert len(x) > 0
    d = 0
    e = expected_value(x)
    for x_i in x:
        d += (x_i - e) ** 2
    return d / len(x)

In [ ]:
def expected_value_np(x):
    return np.sum(x)/x.size

In [ ]:
def dispersion_np(x):
    return np.var(x)

In [ ]:
np.testing.assert_array_equal(expected_value([1]), expected_value_np(np.array([1])))
np.testing.assert_array_equal(expected_value([3, 4]), expected_value_np(np.array([3, 4])))
np.testing.assert_array_equal(expected_value([-1, 0, 1]), expected_value_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(expected_value([-99, -98]), expected_value_np(np.array([-99, -98])))

np.testing.assert_array_equal(dispersion([1]), dispersion_np(np.array([1])))
np.testing.assert_array_equal(dispersion([3, 4]), dispersion_np(np.array([3, 4])))
np.testing.assert_array_equal(dispersion([-1, 0, 1]), dispersion_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(dispersion([-99, -98]), dispersion_np(np.array([-99, -98])))

Задание 17.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое квадратов разностей их значений

In [ ]:
def mean_square_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    # Здесь и далее эти проверки !не нужно! дублировать в свои функции; Здесь они для того, чтобы лишний раз подчеркнуть валидность входных данных
    s = 0
    for i in range(len(y1)):
        s += (y1[i] - y2[i]) ** 2
    return s / len(y1)

In [ ]:
def mean_square_difference_np(y1, y2):
    return np.mean(np.square(y1-y2))

In [ ]:
assert mean_square_difference([1], [1]) == mean_square_difference_np(np.array([1]), np.array([1]))
assert mean_square_difference([1, 2], [1, 2]) == mean_square_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_square_difference([-1, 1], [0, 0]) == mean_square_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_square_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_square_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 18.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое модулей разностей их значений

In [ ]:
def mean_abs_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    s = 0
    for i in range(len(y1)):
        s += abs(y1[i] - y2[i])
    return s / len(y1)

In [ ]:
def mean_abs_difference_np(y1, y2):
    return np.mean(np.abs(y1-y2))

In [ ]:
assert mean_abs_difference([1], [1]) == mean_abs_difference_np(np.array([1]), np.array([1]))
assert mean_abs_difference([1, 2], [1, 2]) == mean_abs_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_abs_difference([-1, 1], [0, 0]) == mean_abs_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_abs_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_abs_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 19.

Даны два вектора $y_1$ и $y_2$, в которых присутствуют только $0$ и $1$. Необходимо посчитать вероятность совпадения - в скольких точках значения двух векторов совпадают

In [ ]:
def matching_proba(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    assert len(set(y1)) <= 2
    assert len(set(y2)) <= 2
    assert 0 in set(y1) or 1 in set(y1) or (0 in set(y1) and 1 in set(y1))
    assert 0 in set(y2) or 1 in set(y2) or (0 in set(y2) and 1 in set(y2))

    return sum([y1[i] == y2[i] for i in range(len(y1))]) / len(y1)

In [ ]:
def matching_proba_np(y1, y2):
    x = y1 == y2
    return np.sum(x)/y1.size

In [ ]:
np.testing.assert_array_equal(matching_proba([0, 1], [1, 0]), matching_proba_np(np.array([0, 1]), np.array([1, 0])))
np.testing.assert_array_equal(matching_proba([0, 1, 0, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 1, 0, 1]), np.array([0, 0, 1, 1])))
np.testing.assert_array_equal(matching_proba([0, 0, 1, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1])))

Задание 20.

Даны два вектора: $y_1$, $y_2$. В $y_1$ и $y_2$ присутствуют только $0$ и $1$.

Необходимо найти границы (индексы), такие, что если мы разделим вдоль какой-то из этих границ оба вектора на две части, то
* в левой части пересекающихся в $y_1$ и $y_2$ нулей будет строго больше, чем пересекающихся единиц или непересекающихся элементов
* в правой - пересекающихся единиц строго больше, чем пересекающихся нулей или непересекающихся элементов.

Если какая-то из частей не содержит элементов вовсе, то будем считать, что она подходит под условие.

In [ ]:
def find_thresholds(y1, y2, debug=False):
    assert len(y1) == len(y2) and len(y1) > 0
    n = len(y1)
    matching_zeros = [1 if y1[i] == y2[i] == 0 else 0 for i in range(n)]
    matching_ones = [1 if y1[i] == y2[i] == 1 else 0 for i in range(n)]
    res = []
    if sum(matching_ones) / n > 0.5:
        res.append(0)
    for i in range(1, n):
        if debug: # если вам непонятна логика работы этой функции, передайте третьим аргументом True
            print(matching_zeros[:i], matching_ones[i:], i)
        if sum(matching_zeros[:i]) / i > 0.5 and sum(matching_ones[i:]) / (n - i) > 0.5:
            res.append(i)
    if sum(matching_zeros) / n > 0.5:
        res.append(n)
    return res

In [ ]:
def find_thresholds_np(y1, y2):
    return # Ваш код

In [ ]:
np.testing.assert_array_equal(find_thresholds([0], [0]), find_thresholds_np(np.array([0]), np.array([0])))
np.testing.assert_array_equal(find_thresholds([1], [1]), find_thresholds_np(np.array([1]), np.array([1])))
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 1], [0, 0, 1, 1]), 
    find_thresholds_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1]))
)
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 0, 0, 1, 1, 1], [0, 0, 0, 0, 0, 1, 1, 1]),
    find_thresholds_np(np.array([0, 0, 1, 0, 0, 1, 1, 1]), np.array([0, 0, 0, 0, 0, 1, 1, 1]))
)

### Разные действия с матрицами (3 балла)

Задание 21.

Дана матрица размера $(32, 3, 16, 16)$, заполненная случайными числами от 0 до 9. При помощи **ровно двух** преобразований приведите её к виду $(32, 1)$. При выполнении задания **можно** создавать вспомогательные матрицы!

In [18]:
data = np.random.randint(0, 10, size=(32, 3, 16, 16))
j = np.ones((32, 32)).astype(int)
data = np.resize(data, (32, 1))
data = np.dot(j, data)
assert data.shape == (32, 1)

Задание 22.

Даны две матрицы $m_1$ размером $(32, 256)$ и $m_2$ размером $(32, 512)$, а также две вспомогательные матрицы $W_1$ размером $(256, 32)$ и $W_2$ размером $(512, 16)$. Используя **все** данные матрицы, сделайте так, чтобы на выходе получилась **ровно одна** матрица размером $(32, 32)$

In [ ]:
m1 = np.random.randint(0, 10, size=(32, 256))
m2 = np.random.randint(0, 10, size=(32, 512))
W1 = np.random.randint(0, 10, size=(256, 32))
W2 = np.random.randint(0, 10, size=(512, 16))

W2_2 = np.zeros((512, 32))
W2_2[:512, :16] = W2
a = np.dot(m1, W1)
b = np.dot(m2,W2_2)
result = np.dot(a, b)

assert result.shape == (32, 32)

Задание 23.

Приведите полученную на последнем шаге матрицу к виду $(32, 3)$ и сделайте так, чтобы все значения в этой матрице были в промежутке от $0$ до $1$

In [24]:
# Вжух! (∩｀-´)⊃━☆ﾟ.*･｡ﾟ

ValueError: shapes (32,3) and (32,3) not aligned: 3 (dim 1) != 32 (dim 0)