## Домашнее задание

В этой тетрадке вам предлагается реализовать задания при помощи библиотеки numpy. Крайне желательно при выполнении разных заданий не использовать циклы. Если вы не понимаете, как выполнить конкретную задачу без циклов - убирайте их постепенно, разбейте выполнение задачи на этапы и постепенно векторизуйте каждый этап.

Если вам непонятно, как выполнить ту или иную операцию - не стесняйтесь гуглить, если над вами повис дедлайн, а вы всё ещё на чём-то застряли - пишите преподу/в чат, это ок.

**Обсудить решение лучше и сделать в итоге хоть что-то гораздо лучше, чем скатать чужой код или сдать пустую тетрадку.**

In [2]:
import numpy as np

### Drill (1 балл)

Задание 1.

Инициализируйте нулями массивы следующих форм:

* (5)
* (5, 1)
* (10, 2)
* (3, 6, 2)
* (4, 3, 2, 1)

In [17]:
a = np.zeros(5)
b = np.zeros((5, 1))
c = np.zeros((10, 2))
d = np.zeros((3, 6, 2))
d = np.zeros((4, 3, 2, 1))

Задание 2.

Инициализируйте единицами массивы таких же форм и приведите их к целочисленному виду:

In [16]:
ar_1 = np.ones(5).astype(int)
ar_2= np.ones((5, 1)).astype(int)
ar_3 = np.ones((10, 2)).astype(int)
ar_4 = np.ones((3, 6, 2)).astype(int)
ar_5 = np.ones((4, 3, 2, 1)).astype(int)

Задание 3.

Выполните для векторов выше `reshape` в "форму"
* с двумя компонентами
* с тремя компонентами
* с четырьмя компонентами

In [21]:
# с двумя компонентами
ar_1.reshape((1, 5))
ar_2.reshape((1, 5))
ar_3.reshape((5, 4))
ar_4.reshape((6, 6))
ar_5.reshape((12, 2))

# с тремя компонентами 
ar_1.reshape((1, 5, 1))
ar_2.reshape((1, 1, 5))
ar_3.reshape((2, 2, 5))
ar_4.reshape((9, 4, 1))
ar_5.reshape((6, 2, 2))

# с четырьмя компонентами 
ar_1.reshape((1, 1, 1, 5))
ar_2.reshape((1, 1, 5, 1))
ar_3.reshape((2, 2, 1, 5))
ar_4.reshape((3, 3, 2, 2))
ar_5.reshape((3, 2, 2, 2))


array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]])

Задание 4.

Для вектора ниже посчитайте его
* Максимум по 1 оси
* Минимум по 0 оси
* Сумму по всем осям
* Среднее по 0 оси
* Медиану по 1 оси

In [43]:
v = np.random.randint(0, 9, size=(5, 7))
v

array([[8, 1, 8, 1, 2, 5, 8],
       [0, 1, 3, 6, 7, 0, 2],
       [3, 0, 8, 8, 5, 7, 3],
       [8, 3, 3, 4, 8, 1, 4],
       [1, 2, 3, 1, 4, 6, 0]])

In [44]:
print('Максимум по 1 оси: ', v.max(axis=1))
print('Минимум по 0 оси: ', v.min(axis=0))
print('Сумму по всем осям: ', v.sum())
print('Среднее по 0 оси: ', v.mean(axis=0))
print('Медиану по 1 оси: ', np.median(v, axis=1) )

Максимум по 1 оси:  [8 7 8 8 6]
Минимум по 0 оси:  [0 0 3 1 2 0 0]
Сумму по всем осям:  134
Среднее по 0 оси:  [4.  1.4 5.  4.  5.2 3.8 3.4]
Медиану по 1 оси:  [5. 2. 5. 4. 2.]


Задание 5.

Для всё того же вектора `v` выведите
* Его shape
* 0 компоненту его "формы"
* 1 компоненту его "формы"

In [45]:
print(v.shape)
print(v.shape[0])
print(v.shape[1])

(5, 7)
5
7


Задание 6.

Для этого же вектора выведите
* Все числа больше 5
* Все числа меньше 7 в обратном порядке
* Все числа больше 3, которые делятся на 4 без остатка
* Все числа, остаток от деления на 5 которых равен 3
* Индекс максимума
* Индекс минимума
* Cписок с индексами элементов отсортированного массива в исходном (неотсортированном)

In [46]:
print('Все числа больше 5: ', v[v > 5])
print('Все числа меньше 7 в обратном порядке:', v[v < 7][::-1])
print('Все числа больше 3, которые делятся на 4 без остатка: ', v[(v>3) & (v % 4 == 0)])  
print('Все числа, остаток от деления на 5 которых равен 3: ', v[v%5==3])
print('Индекс максимума: ', v.argmax())
print('Индекс минимума: ', v.argmin())
print('Cписок с индексами элементов отсортированного массива: ', v.argsort(axis=None))


Все числа больше 5:  [8 8 8 6 7 8 8 7 8 8 6]
Все числа меньше 7 в обратном порядке: [0 6 4 1 3 2 1 4 1 4 3 3 3 5 0 3 2 0 6 3 1 0 5 2 1 1]
Все числа больше 3, которые делятся на 4 без остатка:  [8 8 8 8 8 8 4 8 4 4]
Все числа, остаток от деления на 5 которых равен 3:  [8 8 8 3 3 8 8 3 8 3 3 8 3]
Индекс максимума:  0
Индекс минимума:  7
Cписок с индексами элементов отсортированного массива:  [34 15  7 12  1 28  3 31  8 26 29 13  4  9 14 30 20 22 23 24 32 27  5 18
 10 33 19 11  0 21 16  6  2 25 17]


Задание 7.

Выполните следующие операции над вектором (независимо, не обязательно делать это в последовательности):
* Умножьте его на 3
* Разделите на 7
* Возведите в степень $\frac{2}{3}$
* Посчитайте $\sin$ от него
* Посчитайте $\log$ от него

In [47]:
v = v * 3
v = v / 7
v = v ** (2/3)
v = np.sin(v)
v = np.log(v)
v

<ipython-input-47-4de1e795bbb7>:5: RuntimeWarning: divide by zero encountered in log
  v = np.log(v)


array([[-0.27057851, -0.61931086, -0.27057851, -0.61931086, -0.24235501,
        -0.00417574, -0.27057851],
       [       -inf, -0.61931086, -0.07740377, -0.0476118 , -0.13571421,
               -inf, -0.24235501],
       [-0.07740377,        -inf, -0.27057851, -0.27057851, -0.00417574,
        -0.13571421, -0.07740377],
       [-0.27057851, -0.07740377, -0.07740377, -0.00961156, -0.27057851,
        -0.61931086, -0.00961156],
       [-0.61931086, -0.24235501, -0.07740377, -0.61931086, -0.00961156,
        -0.0476118 ,        -inf]])

### Разные инициализации + индексирование (3 балла)

Задание 8.

Необходимо построить квадрат $3 \times 3$ из нечётных чисел

In [53]:
np.arange(2, 2*3*3 + 1, 2, dtype=int).reshape(3, 3)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

Задание 9.

Необходимо построить квадрат $4 \times 4$ из четных чисел в обратном порядке

In [56]:
np.arange(2, 2*4*4 + 1, 2, dtype=int)[::-1].reshape(4, 4)

array([[32, 30, 28, 26],
       [24, 22, 20, 18],
       [16, 14, 12, 10],
       [ 8,  6,  4,  2]])

Задание 10.

Необходимо построить сетку координат $11 \times 11$ с точкой $(0,0)$ в центре и шагом $0.1$ между клетками

In [69]:
# пришлось округлить все элементы массива, т.к. выводились числа по типу 6.00000000000e+00
np.round(np.arange(-0.1 * (121 // 2), 0.1 * (121 / 2) , 0.1).reshape((11, 11)), 2)

array([[-6. , -5.9, -5.8, -5.7, -5.6, -5.5, -5.4, -5.3, -5.2, -5.1, -5. ],
       [-4.9, -4.8, -4.7, -4.6, -4.5, -4.4, -4.3, -4.2, -4.1, -4. , -3.9],
       [-3.8, -3.7, -3.6, -3.5, -3.4, -3.3, -3.2, -3.1, -3. , -2.9, -2.8],
       [-2.7, -2.6, -2.5, -2.4, -2.3, -2.2, -2.1, -2. , -1.9, -1.8, -1.7],
       [-1.6, -1.5, -1.4, -1.3, -1.2, -1.1, -1. , -0.9, -0.8, -0.7, -0.6],
       [-0.5, -0.4, -0.3, -0.2, -0.1, -0. ,  0.1,  0.2,  0.3,  0.4,  0.5],
       [ 0.6,  0.7,  0.8,  0.9,  1. ,  1.1,  1.2,  1.3,  1.4,  1.5,  1.6],
       [ 1.7,  1.8,  1.9,  2. ,  2.1,  2.2,  2.3,  2.4,  2.5,  2.6,  2.7],
       [ 2.8,  2.9,  3. ,  3.1,  3.2,  3.3,  3.4,  3.5,  3.6,  3.7,  3.8],
       [ 3.9,  4. ,  4.1,  4.2,  4.3,  4.4,  4.5,  4.6,  4.7,  4.8,  4.9],
       [ 5. ,  5.1,  5.2,  5.3,  5.4,  5.5,  5.6,  5.7,  5.8,  5.9,  6. ]])

Задание 11.

Замощение сетки $8\times8$ при помощи $0$ и $1$ в шахматном порядке, клетка с индексом $(0,0)$ замощается $1$

In [77]:
np.fromfunction(lambda i,j : (i+j+1)%2, (8, 8), dtype=int)

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]], dtype=int32)

Задание 12.

То же замощение, но клетка с индексом $(0,0)$ замощается $0$

In [78]:
np.fromfunction(lambda i,j : (i+j)%2, (8, 8), dtype=int)

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]], dtype=int32)

Задание 13.

Необходимо построить нижне-треугольную матрицу переменного размера (задается передачей параметра в функцию). Это единичная матрица,замощённая $1$ под главной диагональю

In [96]:
def lower_array(size):
    return np.tril(np.ones((size, size), dtype=int))
lower_array(4)

array([[1, 0, 0, 0],
       [1, 1, 0, 0],
       [1, 1, 1, 0],
       [1, 1, 1, 1]])

Задание 14.

Необходимо построить верхне-треугольную матрицу переменного размера. Это единичная матрица, замощённая $1$ над главной диагональю

In [97]:
def upper_array(size):
    return np.triu(np.ones((size, size), dtype=int))
upper_array(4)

array([[1, 1, 1, 1],
       [0, 1, 1, 1],
       [0, 0, 1, 1],
       [0, 0, 0, 1]])

Задание 15.

Необходимо построить матрицу, в которой единицы стоят на побочной диагонали (идущей из левого нижнего угла в правый верхний), в остальных местах стоят $0$

In [98]:
def reversed_eye(size):
    return np.eye(size, dtype=int)[:, ::-1]
reversed_eye(4)

array([[0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0]])

### Операции + аггрегации (3 балла)

Задание 16.

Дана выборка $\{X_i\}$ некоторой случайной величины $X$, необходимо оценить
* Математическое ожидание $E[X] = \frac{1}{N}\sum_{i=1}^N X_i$ этой случайной величины
* Дисперсию $D[X] = \frac{1}{N}\sum_{i=1}^N (X_i - E[X])^2$ этой случайной величины

In [4]:
def expected_value(x):
    assert len(x) > 0
    return sum(x) / len(x)


def dispersion(x):
    assert len(x) > 0
    d = 0
    e = expected_value(x)
    for x_i in x:
        d += (x_i - e) ** 2
    return d / len(x)

In [25]:
def expected_value_np(x):
    return np.sum(x) / np.size(x)

In [26]:
def dispersion_np(x):
    return np.var(x)

In [27]:
np.testing.assert_array_equal(expected_value([1]), expected_value_np(np.array([1])))
np.testing.assert_array_equal(expected_value([3, 4]), expected_value_np(np.array([3, 4])))
np.testing.assert_array_equal(expected_value([-1, 0, 1]), expected_value_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(expected_value([-99, -98]), expected_value_np(np.array([-99, -98])))

np.testing.assert_array_equal(dispersion([1]), dispersion_np(np.array([1])))
np.testing.assert_array_equal(dispersion([3, 4]), dispersion_np(np.array([3, 4])))
np.testing.assert_array_equal(dispersion([-1, 0, 1]), dispersion_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(dispersion([-99, -98]), dispersion_np(np.array([-99, -98])))

Задание 17.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое квадратов разностей их значений

In [32]:
def mean_square_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    # Здесь и далее эти проверки !не нужно! дублировать в свои функции; Здесь они для того, чтобы лишний раз подчеркнуть валидность входных данных
    s = 0
    for i in range(len(y1)):
        s += (y1[i] - y2[i]) ** 2
    return s / len(y1)


In [36]:
def mean_square_difference_np(y1, y2):
    return np.mean((y1 - y2)**2)

In [37]:
assert mean_square_difference([1], [1]) == mean_square_difference_np(np.array([1]), np.array([1]))
assert mean_square_difference([1, 2], [1, 2]) == mean_square_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_square_difference([-1, 1], [0, 0]) == mean_square_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_square_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_square_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 18.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое модулей разностей их значений

In [41]:
def mean_abs_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    s = 0
    for i in range(len(y1)):
        s += abs(y1[i] - y2[i])
    return s / len(y1)

In [51]:
def mean_abs_difference_np(y1, y2):
    return np.mean(np.absolute(y1 - y2))

In [52]:
assert mean_abs_difference([1], [1]) == mean_abs_difference_np(np.array([1]), np.array([1]))
assert mean_abs_difference([1, 2], [1, 2]) == mean_abs_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_abs_difference([-1, 1], [0, 0]) == mean_abs_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_abs_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_abs_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 19.

Даны два вектора $y_1$ и $y_2$, в которых присутствуют только $0$ и $1$. Необходимо посчитать вероятность совпадения - в скольких точках значения двух векторов совпадают

In [67]:
def matching_proba(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    assert len(set(y1)) <= 2
    assert len(set(y2)) <= 2
    assert 0 in set(y1) or 1 in set(y1) or (0 in set(y1) and 1 in set(y1))
    assert 0 in set(y2) or 1 in set(y2) or (0 in set(y2) and 1 in set(y2))

    return sum([y1[i] == y2[i] for i in range(len(y1))]) / len(y1)

In [90]:
def matching_proba_np(y1, y2):
    return np.count_nonzero((y1==y2)) / np.size(y1==y2)

In [91]:
np.testing.assert_array_equal(matching_proba([0, 1], [1, 0]), matching_proba_np(np.array([0, 1]), np.array([1, 0])))
np.testing.assert_array_equal(matching_proba([0, 1, 0, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 1, 0, 1]), np.array([0, 0, 1, 1])))
np.testing.assert_array_equal(matching_proba([0, 0, 1, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1])))

Задание 20.

Даны два вектора: $y_1$, $y_2$. В $y_1$ и $y_2$ присутствуют только $0$ и $1$.

Необходимо найти границы (индексы), такие, что если мы разделим вдоль какой-то из этих границ оба вектора на две части, то
* в левой части пересекающихся в $y_1$ и $y_2$ нулей будет строго больше, чем пересекающихся единиц или непересекающихся элементов
* в правой - пересекающихся единиц строго больше, чем пересекающихся нулей или непересекающихся элементов.

Если какая-то из частей не содержит элементов вовсе, то будем считать, что она подходит под условие.

In [112]:
def find_thresholds(y1, y2, debug=False):
    assert len(y1) == len(y2) and len(y1) > 0
    n = len(y1)
    matching_zeros = [1 if y1[i] == y2[i] == 0 else 0 for i in range(n)]
    matching_ones = [1 if y1[i] == y2[i] == 1 else 0 for i in range(n)]
    res = []
    if sum(matching_ones) / n > 0.5:
        res.append(0)
    for i in range(1, n):
        if debug: # если вам непонятна логика работы этой функции, передайте третьим аргументом True
            print(matching_zeros[:i], matching_ones[i:], i)
        if sum(matching_zeros[:i]) / i > 0.5 and sum(matching_ones[i:]) / (n - i) > 0.5:
            res.append(i)
    if sum(matching_zeros) / n > 0.5:
        res.append(n)
    return res

find_thresholds([1], [1])

[0]

In [210]:
def find_thresholds_np(y1, y2):
    a = np.arange(1, np.size(y1) + 1)
    a_1 = ((np.cumsum(((y1 == y2) & (y1 == 0))) / a) > 0.5)[::-1]
    a_2 = (np.cumsum(((y1 == y2) & (y1 == 1))[::-1]) / a[::-1]) > 0.5
    result = np.where((a_1 & a_2) == True)[0].tolist()
    if (np.max(a_1) / np.size(a_1)) > 0.5:
        result.append(np.size(a_1))
    if (np.max(a_2) / np.size(a_2)) > 0.5:
        result.append(0)
    return result

In [211]:
np.testing.assert_array_equal(find_thresholds([0], [0]), find_thresholds_np(np.array([0]), np.array([0])))
np.testing.assert_array_equal(find_thresholds([1], [1]), find_thresholds_np(np.array([1]), np.array([1])))
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 1], [0, 0, 1, 1]), 
    find_thresholds_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1]))
)
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 0, 0, 1, 1, 1], [0, 0, 0, 0, 0, 1, 1, 1]),
    find_thresholds_np(np.array([0, 0, 1, 0, 0, 1, 1, 1]), np.array([0, 0, 0, 0, 0, 1, 1, 1]))
)

### Разные действия с матрицами (3 балла)

Задание 21.

Дана матрица размера $(32, 3, 16, 16)$, заполненная случайными числами от 0 до 9. При помощи **ровно двух** преобразований приведите её к виду $(32, 1)$. При выполнении задания **можно** создавать вспомогательные матрицы!

In [212]:
data = np.random.randint(0, 10, size=(32, 3, 16, 16))

# Преобразование 1
data = data.reshape((32, 3 * 16 * 16))
# Преобразование 2
data_2 = np.ones((3 * 16 * 16, 1), dtype=int)
data = np.matmul(data, data_2)

assert data.shape == (32, 1)

Задание 22.

Даны две матрицы $m_1$ размером $(32, 256)$ и $m_2$ размером $(32, 512)$, а также две вспомогательные матрицы $W_1$ размером $(256, 32)$ и $W_2$ размером $(512, 16)$. Используя **все** данные матрицы, сделайте так, чтобы на выходе получилась **ровно одна** матрица размером $(32, 32)$

In [213]:
m1 = np.random.randint(0, 10, size=(32, 256))
m2 = np.random.randint(0, 10, size=(32, 512))
W1 = np.random.randint(0, 10, size=(256, 32))
W2 = np.random.randint(0, 10, size=(512, 16))

res_1 = np.matmul(np.matmul(np.transpose(np.matmul(m2, W2)), m1), W1)
result = np.matmul(np.transpose(res_1), res_1)

assert result.shape == (32, 32)

Задание 23.

Приведите полученную на последнем шаге матрицу к виду $(32, 3)$ и сделайте так, чтобы все значения в этой матрице были в промежутке от $0$ до $1$

In [214]:
# Вжух! (∩｀-´)⊃━☆ﾟ.*･｡ﾟ
result = np.matmul(result, np.ones((32, 3)))
result = abs(result / np.max(abs(result)))

assert result.shape == (32, 3)
assert ((result >= 0) & (result <= 1)).all()