## Домашнее задание

В этой тетрадке вам предлагается реализовать задания при помощи библиотеки numpy. Крайне желательно при выполнении разных заданий не использовать циклы. Если вы не понимаете, как выполнить конкретную задачу без циклов - убирайте их постепенно, разбейте выполнение задачи на этапы и постепенно векторизуйте каждый этап.

Если вам непонятно, как выполнить ту или иную операцию - не стесняйтесь гуглить, если над вами повис дедлайн, а вы всё ещё на чём-то застряли - пишите преподу/в чат, это ок.

**Обсудить решение лучше и сделать в итоге хоть что-то гораздо лучше, чем скатать чужой код или сдать пустую тетрадку.**

In [161]:
import numpy as np

### Drill (1 балл)

Задание 1.

Инициализируйте нулями массивы следующих форм:

* (5)
* (5, 1)
* (10, 2)
* (3, 6, 2)
* (4, 3, 2, 1)

In [162]:
a1 = np.zeros(5, dtype=int)
a2 = np.zeros((5,1), dtype=int)
a3 = np.zeros((10,2), dtype=int)
a4 = np.zeros((3,6,2), dtype=int)
a5 = np.zeros((4,3,2,1), dtype=int)

Задание 2.

Инициализируйте единицами массивы таких же форм и приведите их к целочисленному виду:

In [163]:
a1 = np.ones(5, dtype=int)
a2 = np.ones((5,1), dtype=int)
a3 = np.ones((10,2), dtype=int)
a4 = np.ones((3,6,2), dtype=int)
a5 = np.ones((4,3,2,1), dtype=int)

Задание 3.

Выполните для векторов выше `reshape` в "форму"
* с двумя компонентами
* с тремя компонентами
* с четырьмя компонентами

In [164]:
a1.reshape((1, 5))
a1.reshape((1, 1, 5))
a1.reshape((1, 1, 5, 1))

a2.reshape((1, 5))
a2.reshape((1, 5, 1))
a2.reshape((1, 1, 1, 5))

a3.reshape((2, 10))
a3.reshape((2, 5, 2))
a3.reshape((2, 5, 2, 1))

a4.reshape((6, 6))
a4.reshape((6, 3, 2))
a4.reshape((2, 3, 2, 3))

a5.reshape((8, 3))
a5.reshape((12, 1, 2))
a5.reshape((2, 2, 2, 3))
print()

Задание 4.

Для вектора ниже посчитайте его
* Максимум по 1 оси
* Минимум по 0 оси
* Сумму по всем осям
* Среднее по 0 оси
* Медиану по 1 оси

In [165]:
v = np.random.randint(0, 9, size=(5, 7))

In [166]:
np.max(v, axis=1), np.min(v, axis=0), np.sum(v), np.mean(v, axis=0), np.median(v, axis=1)

(array([7, 8, 8, 8, 8]),
 array([0, 0, 3, 1, 0, 1, 0]),
 128,
 array([3.6, 3.8, 5.8, 1.8, 2.6, 4. , 4. ]),
 array([5., 3., 3., 4., 3.]))

Задание 5.

Для всё того же вектора `v` выведите
* Его shape
* 0 компоненту его "формы"
* 1 компоненту его "формы"

In [167]:
v.shape, v.shape[0], v.shape[1]

((5, 7), 5, 7)

Задание 6.

Для этого же вектора выведите
* Все числа больше 5
* Все числа меньше 7 в обратном порядке
* Все числа больше 3, которые делятся на 4 без остатка
* Все числа, остаток от деления на 5 которых равен 3
* Индекс максимума
* Индекс минимума
* Cписок с индексами элементов отсортированного массива в исходном (неотсортированном)

In [168]:
v[v > 5]

array([7, 6, 6, 7, 8, 8, 6, 6, 8, 8, 6, 8])

In [169]:
v2 = v[v < 7]
v2[::-1]

array([3, 0, 2, 3, 3, 6, 0, 4, 1, 0, 5, 6, 2, 6, 1, 3, 0, 0, 1, 0, 3, 3,
       6, 6, 3, 2, 5, 0])

In [170]:
v[(v > 3) & (v % 4 == 0)]

array([8, 8, 8, 4, 8, 8])

In [171]:
v[v % 5 == 3]

array([3, 8, 3, 3, 3, 8, 8, 8, 3, 3, 3, 8])

In [172]:
v.argmax()

8

In [173]:
v.argmin()

0

In [174]:
v.argsort(axis=None)

array([ 0, 32, 27, 22, 14, 13, 11, 24, 12, 17, 31,  3, 19, 10, 30, 29,  9,
        4, 15, 33, 25,  1, 21, 18, 20,  5, 28,  6,  2,  7,  8, 26, 16, 23,
       34])

Задание 7.

Выполните следующие операции над вектором (независимо, не обязательно делать это в последовательности):
* Умножьте его на 3
* Разделите на 7
* Возведите в степень $\frac{2}{3}$
* Посчитайте $\sin$ от него
* Посчитайте $\log$ от него

In [175]:
print(v * 3, '\n\n', v / 7, '\n\n', v ** (2/3), '\n\n', np.sin(v), '\n\n', np.log(v))

[[ 0 15 21  6  9 18 18]
 [21 24  9  9  0  3  0]
 [ 0  9 24  3 18  6 18]
 [15  0 24  3 12 24  0]
 [18  9  9  6  0  9 24]] 

 [[0.         0.71428571 1.         0.28571429 0.42857143 0.85714286
  0.85714286]
 [1.         1.14285714 0.42857143 0.42857143 0.         0.14285714
  0.        ]
 [0.         0.42857143 1.14285714 0.14285714 0.85714286 0.28571429
  0.85714286]
 [0.71428571 0.         1.14285714 0.14285714 0.57142857 1.14285714
  0.        ]
 [0.85714286 0.42857143 0.42857143 0.28571429 0.         0.42857143
  1.14285714]] 

 [[0.         2.92401774 3.65930571 1.58740105 2.08008382 3.30192725
  3.30192725]
 [3.65930571 4.         2.08008382 2.08008382 0.         1.
  0.        ]
 [0.         2.08008382 4.         1.         3.30192725 1.58740105
  3.30192725]
 [2.92401774 0.         4.         1.         2.5198421  4.
  0.        ]
 [3.30192725 2.08008382 2.08008382 1.58740105 0.         2.08008382
  4.        ]] 

 [[ 0.         -0.95892427  0.6569866   0.90929743  0.14112001 -0

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


### Разные инициализации + индексирование (3 балла)

Задание 8.

Необходимо построить квадрат $3 \times 3$ из нечётных чисел

In [176]:
m = np.arange(1, 18, 2).reshape(3, 3)
print (m)

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]


Задание 9.

Необходимо построить квадрат $4 \times 4$ из четных чисел в обратном порядке

In [177]:
m = np.arange(0, 31, 2)
m = m[::-1].reshape(4, 4)
print(m)

[[30 28 26 24]
 [22 20 18 16]
 [14 12 10  8]
 [ 6  4  2  0]]


Задание 10.

Необходимо построить сетку координат $11 \times 11$ с точкой $(0,0)$ в центре и шагом $0.1$ между клетками

In [178]:
grid = np.zeros((11,11), [('x', 'f2'),('y', 'f2')])
grid['x'], grid['y'] = np.meshgrid(np.arange(-0.5, 0.6, 0.1),
                                   np.arange(-0.5, 0.6, 0.1),
                                   indexing="ij")
print(grid)

[[(-0.5, -0.5) (-0.5, -0.4) (-0.5, -0.3) (-0.5, -0.2) (-0.5, -0.1)
  (-0.5, -0. ) (-0.5,  0.1) (-0.5,  0.2) (-0.5,  0.3) (-0.5,  0.4)
  (-0.5,  0.5)]
 [(-0.4, -0.5) (-0.4, -0.4) (-0.4, -0.3) (-0.4, -0.2) (-0.4, -0.1)
  (-0.4, -0. ) (-0.4,  0.1) (-0.4,  0.2) (-0.4,  0.3) (-0.4,  0.4)
  (-0.4,  0.5)]
 [(-0.3, -0.5) (-0.3, -0.4) (-0.3, -0.3) (-0.3, -0.2) (-0.3, -0.1)
  (-0.3, -0. ) (-0.3,  0.1) (-0.3,  0.2) (-0.3,  0.3) (-0.3,  0.4)
  (-0.3,  0.5)]
 [(-0.2, -0.5) (-0.2, -0.4) (-0.2, -0.3) (-0.2, -0.2) (-0.2, -0.1)
  (-0.2, -0. ) (-0.2,  0.1) (-0.2,  0.2) (-0.2,  0.3) (-0.2,  0.4)
  (-0.2,  0.5)]
 [(-0.1, -0.5) (-0.1, -0.4) (-0.1, -0.3) (-0.1, -0.2) (-0.1, -0.1)
  (-0.1, -0. ) (-0.1,  0.1) (-0.1,  0.2) (-0.1,  0.3) (-0.1,  0.4)
  (-0.1,  0.5)]
 [(-0. , -0.5) (-0. , -0.4) (-0. , -0.3) (-0. , -0.2) (-0. , -0.1)
  (-0. , -0. ) (-0. ,  0.1) (-0. ,  0.2) (-0. ,  0.3) (-0. ,  0.4)
  (-0. ,  0.5)]
 [( 0.1, -0.5) ( 0.1, -0.4) ( 0.1, -0.3) ( 0.1, -0.2) ( 0.1, -0.1)
  ( 0.1, -0. ) ( 0.1,  0.1) ( 0.1

Задание 11.

Замощение сетки $8\times8$ при помощи $0$ и $1$ в шахматном порядке, клетка с индексом $(0,0)$ замощается $1$

In [179]:
grid = np.zeros((8,8), dtype=int)
grid[1::2,1::2] = 1
grid[::2,::2] = 1
print(grid)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


Задание 12.

То же замощение, но клетка с индексом $(0,0)$ замощается $0$

In [180]:
grid = np.zeros((8,8), dtype=int)
grid[1::2,::2] = 1
grid[::2,1::2] = 1
print(grid)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Задание 13.

Необходимо построить нижне-треугольную матрицу переменного размера (задается передачей параметра в функцию). Это единичная матрица,замощённая $1$ под главной диагональю

In [181]:
def lower_triangular(n,m):
  matr = np.zeros((n,m), dtype=int)
  tril_ind = np.tril_indices(n=n, m=m)
  matr[tril_ind] = 1
  return matr

print(lower_triangular(5,5))

[[1 0 0 0 0]
 [1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]
 [1 1 1 1 1]]


Задание 14.

Необходимо построить верхне-треугольную матрицу переменного размера. Это единичная матрица, замощённая $1$ над главной диагональю

In [182]:
def upper_triangular(n,m):
  matr = np.ones((n,m), dtype=int)
  tril_ind = np.tril_indices(n=n, k=-1, m=m)
  matr[tril_ind] = 0
  return matr

print(upper_triangular(5,5))

[[1 1 1 1 1]
 [0 1 1 1 1]
 [0 0 1 1 1]
 [0 0 0 1 1]
 [0 0 0 0 1]]


Задание 15.

Необходимо построить матрицу, в которой единицы стоят на побочной диагонали (идущей из левого нижнего угла в правый верхний), в остальных местах стоят $0$

In [183]:
def create_matrix(n):
  matr = np.eye(n, dtype=int).tolist()
  matr.reverse()
  return np.array(matr)

print(create_matrix(5))

[[0 0 0 0 1]
 [0 0 0 1 0]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [1 0 0 0 0]]


### Операции + аггрегации (3 балла)

Задание 16.

Дана выборка $\{X_i\}$ некоторой случайной величины $X$, необходимо оценить
* Математическое ожидание $E[X] = \frac{1}{N}\sum_{i=1}^N X_i$ этой случайной величины
* Дисперсию $D[X] = \frac{1}{N}\sum_{i=1}^N (X_i - E[X])^2$ этой случайной величины

In [184]:
def expected_value(x):
    assert len(x) > 0
    return sum(x) / len(x)


def dispersion(x):
    assert len(x) > 0
    d = 0
    e = expected_value(x)
    for x_i in x:
        d += (x_i - e) ** 2
    return d / len(x)

In [185]:
def expected_value_np(x):
  assert len(x) > 0
  return np.sum(x) / len(x)

In [186]:
def dispersion_np(x):
  assert len(x) > 0
  y = x - expected_value_np(x)
  return np.sum(y ** 2) / len(x)

In [187]:
np.testing.assert_array_equal(expected_value([1]), expected_value_np(np.array([1])))
np.testing.assert_array_equal(expected_value([3, 4]), expected_value_np(np.array([3, 4])))
np.testing.assert_array_equal(expected_value([-1, 0, 1]), expected_value_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(expected_value([-99, -98]), expected_value_np(np.array([-99, -98])))

np.testing.assert_array_equal(dispersion([1]), dispersion_np(np.array([1])))
np.testing.assert_array_equal(dispersion([3, 4]), dispersion_np(np.array([3, 4])))
np.testing.assert_array_equal(dispersion([-1, 0, 1]), dispersion_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(dispersion([-99, -98]), dispersion_np(np.array([-99, -98])))

Задание 17.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое квадратов разностей их значений

In [188]:
def mean_square_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    # Здесь и далее эти проверки !не нужно! дублировать в свои функции; Здесь они для того, чтобы лишний раз подчеркнуть валидность входных данных
    s = 0
    for i in range(len(y1)):
        s += (y1[i] - y2[i]) ** 2
    return s / len(y1)

In [189]:
def mean_square_difference_np(y1, y2):
    return np.sum((y1 - y2) ** 2) / len(y1)

In [190]:
assert mean_square_difference([1], [1]) == mean_square_difference_np(np.array([1]), np.array([1]))
assert mean_square_difference([1, 2], [1, 2]) == mean_square_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_square_difference([-1, 1], [0, 0]) == mean_square_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_square_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_square_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 18.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое модулей разностей их значений

In [191]:
def mean_abs_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    s = 0
    for i in range(len(y1)):
        s += abs(y1[i] - y2[i])
    return s / len(y1)

In [192]:
def mean_abs_difference_np(y1, y2):
    return np.sum(np.abs(y1 - y2)) / len(y1)

In [193]:
assert mean_abs_difference([1], [1]) == mean_abs_difference_np(np.array([1]), np.array([1]))
assert mean_abs_difference([1, 2], [1, 2]) == mean_abs_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_abs_difference([-1, 1], [0, 0]) == mean_abs_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_abs_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_abs_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 19.

Даны два вектора $y_1$ и $y_2$, в которых присутствуют только $0$ и $1$. Необходимо посчитать вероятность совпадения - в скольких точках значения двух векторов совпадают

In [194]:
def matching_proba(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    assert len(set(y1)) <= 2
    assert len(set(y2)) <= 2
    assert 0 in set(y1) or 1 in set(y1) or (0 in set(y1) and 1 in set(y1))
    assert 0 in set(y2) or 1 in set(y2) or (0 in set(y2) and 1 in set(y2))

    return sum([y1[i] == y2[i] for i in range(len(y1))]) / len(y1)

In [195]:
def matching_proba_np(y1, y2):
    return np.sum(y1 == y2) / len(y1)

In [196]:
np.testing.assert_array_equal(matching_proba([0, 1], [1, 0]), matching_proba_np(np.array([0, 1]), np.array([1, 0])))
np.testing.assert_array_equal(matching_proba([0, 1, 0, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 1, 0, 1]), np.array([0, 0, 1, 1])))
np.testing.assert_array_equal(matching_proba([0, 0, 1, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1])))

Задание 20.

Даны два вектора: $y_1$, $y_2$. В $y_1$ и $y_2$ присутствуют только $0$ и $1$.

Необходимо найти границы (индексы), такие, что если мы разделим вдоль какой-то из этих границ оба вектора на две части, то
* в левой части пересекающихся в $y_1$ и $y_2$ нулей будет строго больше, чем пересекающихся единиц или непересекающихся элементов
* в правой - пересекающихся единиц строго больше, чем пересекающихся нулей или непересекающихся элементов.

Если какая-то из частей не содержит элементов вовсе, то будем считать, что она подходит под условие.

In [197]:
def find_thresholds(y1, y2, debug=False):
    assert len(y1) == len(y2) and len(y1) > 0
    n = len(y1)
    matching_zeros = [1 if y1[i] == y2[i] == 0 else 0 for i in range(n)]
    matching_ones = [1 if y1[i] == y2[i] == 1 else 0 for i in range(n)]
    res = []
    if sum(matching_ones) / n > 0.5:
        res.append(0)
    for i in range(1, n):
        if debug: # если вам непонятна логика работы этой функции, передайте третьим аргументом True
            print(matching_zeros[:i], matching_ones[i:], i)
        if sum(matching_zeros[:i]) / i > 0.5 and sum(matching_ones[i:]) / (n - i) > 0.5:
            res.append(i)
    if sum(matching_zeros) / n > 0.5:
        res.append(n)
    return res

In [198]:
def find_thresholds_np(y1, y2):
  n = len(y1)

  matching_zeros = np.zeros(n, dtype = int)
  matching_zeros[(y1 == y2) & (y1 == 0)] = 1

  matching_ones = np.zeros(n, dtype = int)
  matching_ones[(y1 == y2) & (y1 == 1)] = 1

  res = []
  if sum(matching_ones) / n > 0.5:
      res.append(0)

  sum_zeros = np.sum(np.tril([matching_zeros] * n), axis=1)

  matr_ones = np.array([matching_ones] * n)
  tril_ind = np.tril_indices(n=len(matching_ones), k=-1, m=len(matching_ones))
  matr_ones[tril_ind] = 0
  sum_ones = np.sum(matr_ones, axis=1)

  result = np.where((sum_zeros[1:] / np.arange(1,n) > 0.5) & (sum_ones[1:] / np.flip(np.arange(1,n)) > 0.5))
  res.extend((result[0]+1).tolist())
          
  if sum(matching_zeros) / n > 0.5:
      res.append(n)

  return res

In [199]:
np.testing.assert_array_equal(find_thresholds([0], [0]), find_thresholds_np(np.array([0]), np.array([0])))
np.testing.assert_array_equal(find_thresholds([1], [1]), find_thresholds_np(np.array([1]), np.array([1])))
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 1], [0, 0, 1, 1]), 
    find_thresholds_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1]))
)
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 0, 0, 1, 1, 1], [0, 0, 0, 0, 0, 1, 1, 1]),
    find_thresholds_np(np.array([0, 0, 1, 0, 0, 1, 1, 1]), np.array([0, 0, 0, 0, 0, 1, 1, 1]))
)

### Разные действия с матрицами (3 балла)

Задание 21.

Дана матрица размера $(32, 3, 16, 16)$, заполненная случайными числами от 0 до 9. При помощи **ровно двух** преобразований приведите её к виду $(32, 1)$. При выполнении задания **можно** создавать вспомогательные матрицы!

In [200]:
data = np.random.randint(0, 10, size=(32, 3, 16, 16))

# Преобразование 1
data = data.reshape(-1, 32)[0]

# Преобразование 2
data = data.reshape(32, 1)

assert data.shape == (32, 1)

Задание 22.

Даны две матрицы $m_1$ размером $(32, 256)$ и $m_2$ размером $(32, 512)$, а также две вспомогательные матрицы $W_1$ размером $(256, 32)$ и $W_2$ размером $(512, 16)$. Используя **все** данные матрицы, сделайте так, чтобы на выходе получилась **ровно одна** матрица размером $(32, 32)$

In [201]:
m1 = np.random.randint(0, 10, size=(32, 256))
m2 = np.random.randint(0, 10, size=(32, 512))
W1 = np.random.randint(0, 10, size=(256, 32))
W2 = np.random.randint(0, 10, size=(512, 16))

a = np.matmul(m1, W1)
b = np.matmul(m2, W2)
result = np.matmul(np.matmul(a, b), b.transpose())

assert result.shape == (32, 32)

Задание 23.

Приведите полученную на последнем шаге матрицу к виду $(32, 3)$ и сделайте так, чтобы все значения в этой матрице были в промежутке от $0$ до $1$

In [202]:
# Вжух! (∩｀-´)⊃━☆ﾟ.*･｡ﾟ
result = result[0:3].transpose()
result = np.divide(result, np.max(result))
result[(result < 0) | (result > 1)] = 0

assert result.shape == (32, 3)
assert ((result >= 0) & (result <= 1)).all()