## Домашнее задание

В этой тетрадке вам предлагается реализовать задания при помощи библиотеки numpy. Крайне желательно при выполнении разных заданий не использовать циклы. Если вы не понимаете, как выполнить конкретную задачу без циклов - убирайте их постепенно, разбейте выполнение задачи на этапы и постепенно векторизуйте каждый этап.

Если вам непонятно, как выполнить ту или иную операцию - не стесняйтесь гуглить, если над вами повис дедлайн, а вы всё ещё на чём-то застряли - пишите преподу/в чат, это ок.

**Обсудить решение лучше и сделать в итоге хоть что-то гораздо лучше, чем скатать чужой код или сдать пустую тетрадку.**

In [1]:
import numpy as np

### Drill (1 балл)

Задание 1.

Инициализируйте нулями массивы следующих форм:

* (5)
* (5, 1)
* (10, 2)
* (3, 6, 2)
* (4, 3, 2, 1)

In [14]:
a = np.zeros(5)
b = np.zeros((5,1))
c = np.zeros((10,2))
d = np.zeros((3,6,2))
e = np.zeros((4,3,2,1))


Задание 2.

Инициализируйте единицами массивы таких же форм и приведите их к целочисленному виду:

In [ ]:
a1 = np.ones_like(a).astype(int)
b1 = np.ones_like(b).astype(int)
c1 = np.ones_like(c).astype(int)
d1 = np.ones_like(d).astype(int)
e1 = np.ones_like(e).astype(int)

Задание 3.

Выполните для векторов выше `reshape` в "форму"
* с двумя компонентами
* с тремя компонентами
* с четырьмя компонентами

In [20]:
#тензоры ранга 2 (2 "компоненты")
a.reshape((5, 1))
b.reshape((5, 1))
c.reshape((10, 2))
d.reshape((3, 12))
e.reshape((12, 2));

In [21]:
#тензоры ранга 3
a.reshape((5, 1, 1))
b.reshape((5, 1, 1))
c.reshape((10, 2, 1))
d.reshape((3, 12, 1))
e.reshape((12, 2, 1));

In [22]:
#тензоры ранга 4
a.reshape((5, 1, 1, 1))
b.reshape((5, 1, 1, 1))
c.reshape((5, 2, 2, 1))
d.reshape((3, 3, 2, 2))
e.reshape((3, 2, 2, 2));

Задание 4.

Для вектора ниже посчитайте его
* Максимум по 1 оси
* Минимум по 0 оси
* Сумму по всем осям
* Среднее по 0 оси
* Медиану по 1 оси

In [ ]:
v = np.random.randint(0, 9, size=(5, 7))

In [ ]:
np.max(v, axis = 1)
np.min(v, axis = 0)
np.sum(v)
np.mean(v, axis = 0)
np.median(v, axis = 1)

array([6., 4., 6., 2., 4.])

Задание 5.

Для всё того же вектора `v` выведите
* Его shape
* 0 компоненту его "формы"
* 1 компоненту его "формы"

In [ ]:
print(v.shape)
print(v.shape[0])
print(v.shape[1])

(5, 7)
5
7


Задание 6.

Для этого же вектора выведите
* Все числа больше 5
* Все числа меньше 7 в обратном порядке
* Все числа больше 3, которые делятся на 4 без остатка
* Все числа, остаток от деления на 5 которых равен 3
* Индекс максимума
* Индекс минимума
* Cписок с индексами элементов отсортированного массива в исходном (неотсортированном)

In [ ]:
print(v)

[[8 8 6 6 6 5 1]
 [4 0 2 1 6 8 8]
 [6 7 5 8 5 8 5]
 [3 0 0 8 2 4 0]
 [3 1 8 6 1 5 4]]


In [ ]:
print(v[v > 5])

[8 8 6 6 6 6 8 8 6 7 8 8 8 8 6]


In [ ]:
print(v[v<7][::-1])

[4 5 1 6 1 3 0 4 2 0 0 3 5 5 5 6 6 1 2 0 4 1 5 6 6 6]


In [ ]:
print(v[(v>3) & (v % 4 == 0)])

[8 8 4 8 8 8 8 8 4 8 4]


In [ ]:
print(v[v % 5 == 3])

[8 8 8 8 8 8 3 8 3 8]


In [ ]:
print(v.argmax())

0


In [ ]:
print(v.argmin())

8


In [ ]:
print(v.flatten().argsort().reshape(v.shape))

[[27 23 22  8 32  6 10]
 [29 25  9 28 21 26 34]
 [ 7 16 33 18 20  5 14]
 [11  4  3  2 31 15 30]
 [ 0 19 13 12  1 24 17]]


Задание 7.

Выполните следующие операции над вектором (независимо, не обязательно делать это в последовательности):
* Умножьте его на 3
* Разделите на 7
* Возведите в степень $\frac{2}{3}$
* Посчитайте $\sin$ от него
* Посчитайте $\log$ от него

In [ ]:
3 * v

array([[24, 24, 18, 18, 18, 15,  3],
       [12,  0,  6,  3, 18, 24, 24],
       [18, 21, 15, 24, 15, 24, 15],
       [ 9,  0,  0, 24,  6, 12,  0],
       [ 9,  3, 24, 18,  3, 15, 12]])

In [ ]:
v / 7

array([[1.14285714, 1.14285714, 0.85714286, 0.85714286, 0.85714286,
        0.71428571, 0.14285714],
       [0.57142857, 0.        , 0.28571429, 0.14285714, 0.85714286,
        1.14285714, 1.14285714],
       [0.85714286, 1.        , 0.71428571, 1.14285714, 0.71428571,
        1.14285714, 0.71428571],
       [0.42857143, 0.        , 0.        , 1.14285714, 0.28571429,
        0.57142857, 0.        ],
       [0.42857143, 0.14285714, 1.14285714, 0.85714286, 0.14285714,
        0.71428571, 0.57142857]])

In [ ]:
v ** (2/3)

array([[4.        , 4.        , 3.30192725, 3.30192725, 3.30192725,
        2.92401774, 1.        ],
       [2.5198421 , 0.        , 1.58740105, 1.        , 3.30192725,
        4.        , 4.        ],
       [3.30192725, 3.65930571, 2.92401774, 4.        , 2.92401774,
        4.        , 2.92401774],
       [2.08008382, 0.        , 0.        , 4.        , 1.58740105,
        2.5198421 , 0.        ],
       [2.08008382, 1.        , 4.        , 3.30192725, 1.        ,
        2.92401774, 2.5198421 ]])

In [ ]:
np.sin(v)

array([[ 0.98935825,  0.98935825, -0.2794155 , -0.2794155 , -0.2794155 ,
        -0.95892427,  0.84147098],
       [-0.7568025 ,  0.        ,  0.90929743,  0.84147098, -0.2794155 ,
         0.98935825,  0.98935825],
       [-0.2794155 ,  0.6569866 , -0.95892427,  0.98935825, -0.95892427,
         0.98935825, -0.95892427],
       [ 0.14112001,  0.        ,  0.        ,  0.98935825,  0.90929743,
        -0.7568025 ,  0.        ],
       [ 0.14112001,  0.84147098,  0.98935825, -0.2794155 ,  0.84147098,
        -0.95892427, -0.7568025 ]])

In [ ]:
np.log(v)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([[2.07944154, 2.07944154, 1.79175947, 1.79175947, 1.79175947,
        1.60943791, 0.        ],
       [1.38629436,       -inf, 0.69314718, 0.        , 1.79175947,
        2.07944154, 2.07944154],
       [1.79175947, 1.94591015, 1.60943791, 2.07944154, 1.60943791,
        2.07944154, 1.60943791],
       [1.09861229,       -inf,       -inf, 2.07944154, 0.69314718,
        1.38629436,       -inf],
       [1.09861229, 0.        , 2.07944154, 1.79175947, 0.        ,
        1.60943791, 1.38629436]])

### Разные инициализации + индексирование (3 балла)

Задание 8.

Необходимо построить квадрат $3 \times 3$ из нечётных чисел

In [ ]:
np.arange(1, 1+(3*3)*2, 2).reshape((3,3))

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

Задание 9.

Необходимо построить квадрат $4 \times 4$ из четных чисел в обратном порядке

In [ ]:
np.arange(1+(4*4-1)*2, -1, -2).reshape((4,4))

array([[31, 29, 27, 25],
       [23, 21, 19, 17],
       [15, 13, 11,  9],
       [ 7,  5,  3,  1]])

Задание 10.

Необходимо построить сетку координат $11 \times 11$ с точкой $(0,0)$ в центре и шагом $0.1$ между клетками

In [ ]:
np.set_printoptions(formatter={'float': lambda x: "{0:0.1f}".format(x)})

In [ ]:
x = np.arange(0 - 11//2*0.1, (11//2+1)*0.1, 0.1)
y = np.arange(0 - 11//2*0.1, (11//2+1)*0.1, 0.1)
xx, yy = np.meshgrid(x, y)

In [ ]:
xx+yy

array([[-1.0, -0.9, -0.8, -0.7, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1, -0.0],
       [-0.9, -0.8, -0.7, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1, -0.0, 0.1],
       [-0.8, -0.7, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1, -0.0, 0.1, 0.2],
       [-0.7, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1, -0.0, 0.1, 0.2, 0.3],
       [-0.6, -0.5, -0.4, -0.3, -0.2, -0.1, -0.0, 0.1, 0.2, 0.3, 0.4],
       [-0.5, -0.4, -0.3, -0.2, -0.1, -0.0, 0.1, 0.2, 0.3, 0.4, 0.5],
       [-0.4, -0.3, -0.2, -0.1, -0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6],
       [-0.3, -0.2, -0.1, -0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7],
       [-0.2, -0.1, -0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8],
       [-0.1, -0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
       [-0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]])

Задание 11.

Замощение сетки $8\times8$ при помощи $0$ и $1$ в шахматном порядке, клетка с индексом $(0,0)$ замощается $1$

In [ ]:
xx, yy = np.meshgrid(np.arange(0,8,1), np.arange(0,8,1))
(xx+yy+1) % 2 

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

Задание 12.

То же замощение, но клетка с индексом $(0,0)$ замощается $0$

In [ ]:
(xx+yy) % 2 

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

Задание 13.

Необходимо построить нижне-треугольную матрицу переменного размера (задается передачей параметра в функцию). Это единичная матрица,замощённая $1$ под главной диагональю

In [ ]:
def lower_triangular(n:int):
  xx, yy = np.meshgrid(np.arange(0,n,1), -np.arange(0,n,1))
  return (xx + yy <= 0).astype(int)

In [ ]:
lower_triangular(5)

array([[1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1]])

Задание 14.

Необходимо построить верхне-треугольную матрицу переменного размера. Это единичная матрица, замощённая $1$ над главной диагональю

In [ ]:
def upper_triangular(n:int):
  return np.transpose(lower_triangular(n))
#лучше конечно скопировать аналогичный алгоритм из lower_triangular чтобы не замедлять операцию на больших n

In [ ]:
upper_triangular(7)

array([[1, 1, 1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1, 1, 1],
       [0, 0, 1, 1, 1, 1, 1],
       [0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 1, 1],
       [0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 1]])

Задание 15.

Необходимо построить матрицу, в которой единицы стоят на побочной диагонали (идущей из левого нижнего угла в правый верхний), в остальных местах стоят $0$

In [ ]:
def antidiagonal(n:int):
  xx, yy = np.meshgrid(np.arange(-(n//2),n//2+1, 1), np.arange(-(n//2),n//2+1, 1))
  return (xx+yy==0).astype(int)

In [ ]:
antidiagonal(5)

array([[0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0]])

In [ ]:
antidiagonal(6)

array([[0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0]])

In [ ]:
def antidiagonal1(n:int): #probably faster
  return np.eye(n, dtype=int)[:,::-1]

In [ ]:
antidiagonal1(5)

array([[0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0]])

### Операции + аггрегации (3 балла)

Задание 16.

Дана выборка $\{X_i\}$ некоторой случайной величины $X$, необходимо оценить
* Математическое ожидание $E[X] = \frac{1}{N}\sum_{i=1}^N X_i$ этой случайной величины
* Дисперсию $D[X] = \frac{1}{N}\sum_{i=1}^N (X_i - E[X])^2$ этой случайной величины

In [ ]:
def expected_value(x):
    assert len(x) > 0
    return sum(x) / len(x)


def dispersion(x):
    assert len(x) > 0
    d = 0
    e = expected_value(x)
    for x_i in x:
        d += (x_i - e) ** 2
    return d / len(x)

In [ ]:
def expected_value_np(x):
    return np.mean(x)

In [ ]:
def dispersion_np(x):
    return np.var(x)

In [ ]:
np.testing.assert_array_equal(expected_value([1]), expected_value_np(np.array([1])))
np.testing.assert_array_equal(expected_value([3, 4]), expected_value_np(np.array([3, 4])))
np.testing.assert_array_equal(expected_value([-1, 0, 1]), expected_value_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(expected_value([-99, -98]), expected_value_np(np.array([-99, -98])))

np.testing.assert_array_equal(dispersion([1]), dispersion_np(np.array([1])))
np.testing.assert_array_equal(dispersion([3, 4]), dispersion_np(np.array([3, 4])))
np.testing.assert_array_equal(dispersion([-1, 0, 1]), dispersion_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(dispersion([-99, -98]), dispersion_np(np.array([-99, -98])))

Задание 17.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое квадратов разностей их значений

In [ ]:
def mean_square_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    # Здесь и далее эти проверки !не нужно! дублировать в свои функции; Здесь они для того, чтобы лишний раз подчеркнуть валидность входных данных
    s = 0
    for i in range(len(y1)):
        s += (y1[i] - y2[i]) ** 2
    return s / len(y1)

In [ ]:
def mean_square_difference_np(y1, y2):
    return np.var(np.concatenate((y1-y2,y2-y1)))
    # Ваш код
    '''
    Здесь мы считаем среднее квадратов y1-y2. Оно будет совпадать со среднеквадратичным отклонением y1-y2 если матожидание (E) равно нулю, 
    что верно для массива, содержащего попарно противоположные величины
    '''

In [ ]:
assert mean_square_difference([1], [1]) == mean_square_difference_np(np.array([1]), np.array([1]))
assert mean_square_difference([1, 2], [1, 2]) == mean_square_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_square_difference([-1, 1], [0, 0]) == mean_square_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_square_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_square_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 18.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое модулей разностей их значений

In [ ]:
def mean_abs_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    s = 0
    for i in range(len(y1)):
        s += abs(y1[i] - y2[i])
    return s / len(y1)

In [ ]:
def mean_abs_difference_np(y1, y2):
    return np.mean(np.abs(y1-y2))

In [ ]:
assert mean_abs_difference([1], [1]) == mean_abs_difference_np(np.array([1]), np.array([1]))
assert mean_abs_difference([1, 2], [1, 2]) == mean_abs_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_abs_difference([-1, 1], [0, 0]) == mean_abs_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_abs_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_abs_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 19.

Даны два вектора $y_1$ и $y_2$, в которых присутствуют только $0$ и $1$. Необходимо посчитать вероятность совпадения - в скольких точках значения двух векторов совпадают

In [ ]:
def matching_proba(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    assert len(set(y1)) <= 2
    assert len(set(y2)) <= 2
    assert 0 in set(y1) or 1 in set(y1) or (0 in set(y1) and 1 in set(y1))
    assert 0 in set(y2) or 1 in set(y2) or (0 in set(y2) and 1 in set(y2))

    return sum([y1[i] == y2[i] for i in range(len(y1))]) / len(y1)

In [ ]:
def matching_proba_np(y1, y2):
    return np.sum(y1==y2)/np.sum(y1.shape)

In [ ]:
np.testing.assert_array_equal(matching_proba([0, 1], [1, 0]), matching_proba_np(np.array([0, 1]), np.array([1, 0])))
np.testing.assert_array_equal(matching_proba([0, 1, 0, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 1, 0, 1]), np.array([0, 0, 1, 1])))
np.testing.assert_array_equal(matching_proba([0, 0, 1, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1])))

Задание 20.

Даны два вектора: $y_1$, $y_2$. В $y_1$ и $y_2$ присутствуют только $0$ и $1$.

Необходимо найти границы (индексы), такие, что если мы разделим вдоль какой-то из этих границ оба вектора на две части, то
* в левой части пересекающихся в $y_1$ и $y_2$ нулей будет строго больше, чем пересекающихся единиц или непересекающихся элементов
* в правой - пересекающихся единиц строго больше, чем пересекающихся нулей или непересекающихся элементов.

Если какая-то из частей не содержит элементов вовсе, то будем считать, что она подходит под условие.

In [ ]:
def find_thresholds(y1, y2, debug=False):
    assert len(y1) == len(y2) and len(y1) > 0
    n = len(y1)
    matching_zeros = [1 if y1[i] == y2[i] == 0 else 0 for i in range(n)]
    matching_ones = [1 if y1[i] == y2[i] == 1 else 0 for i in range(n)]
    res = []
    if sum(matching_ones) / n > 0.5:
        res.append(0)
    for i in range(1, n):
        if debug: # если вам непонятна логика работы этой функции, передайте третьим аргументом True
            print(matching_zeros[:i], matching_ones[i:], i)
        if sum(matching_zeros[:i]) / i > 0.5 and sum(matching_ones[i:]) / (n - i) > 0.5:
            res.append(i)
    if sum(matching_zeros) / n > 0.5:
        res.append(n)
    return res

In [ ]:
def find_thresholds_np(y1, y2):
    n = len(y1)
    matching_zeros = ((y1 == 0) & (y2 == 0))*1
    matching_ones = ((y1 == 1) & (y2 == 1))*1
    zeros_cum_sum = np.cumsum(matching_zeros)
    ones_cum_sum = np.cumsum(matching_ones)
    ones_cum_sum = ones_cum_sum[-1] - ones_cum_sum #we've 'inverted' the array so that it shows how many matching ones are there to the right
    is_left_ok = zeros_cum_sum[1:]/range(1, n) > 0.5 #binarry array. At index i shows whether for divisor at i+1 first i elements satisfy the left-part condition
    is_right_ok = ones_cum_sum[:-1]/np.arange(n-1,0,-1) > 0.5
    when_ok = is_left_ok & is_right_ok
    indices = np.nonzero(when_ok)[0] + 1 #np.nonzero return a tuple of arrays. In the case of 1d array, we can just take the first element. We also add one since our indices were shifted in cum_sums and 'ok' arrays
    res = []
    if sum(matching_ones) / n > 0.5:
        res.append(0)
    res = np.concatenate((res, indices))
    if sum(matching_zeros) / n > 0.5:
        res = np.append(res, n)
    return res

In [ ]:
np.testing.assert_array_equal(find_thresholds([0], [0]), find_thresholds_np(np.array([0]), np.array([0])))
np.testing.assert_array_equal(find_thresholds([1], [1]), find_thresholds_np(np.array([1]), np.array([1])))
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 1], [0, 0, 1, 1]), 
    find_thresholds_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1]))
)
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 0, 0, 1, 1, 1], [0, 0, 0, 0, 0, 1, 1, 1]),
    find_thresholds_np(np.array([0, 0, 1, 0, 0, 1, 1, 1]), np.array([0, 0, 0, 0, 0, 1, 1, 1]))
)

### Разные действия с матрицами (3 балла)

Задание 21.

Дана матрица размера $(32, 3, 16, 16)$, заполненная случайными числами от 0 до 9. При помощи **ровно двух** преобразований приведите её к виду $(32, 1)$. При выполнении задания **можно** создавать вспомогательные матрицы!

In [8]:
data = np.random.randint(0, 10, size=(32, 3, 16, 16))
#я не понял что тут надо конкретно сделать, поэтому вот
# Преобразование 1
data = data.mean(axis = (1,2,3))
# Преобразование 2
data = data.reshape(32,1)

assert data.shape == (32, 1)

Задание 22.

Даны две матрицы $m_1$ размером $(32, 256)$ и $m_2$ размером $(32, 512)$, а также две вспомогательные матрицы $W_1$ размером $(256, 32)$ и $W_2$ размером $(512, 16)$. Используя **все** данные матрицы, сделайте так, чтобы на выходе получилась **ровно одна** матрица размером $(32, 32)$

In [10]:
m1 = np.random.randint(0, 10, size=(32, 256))
m2 = np.random.randint(0, 10, size=(32, 512))
W1 = np.random.randint(0, 10, size=(256, 32))
W2 = np.random.randint(0, 10, size=(512, 16))

result = m1@W1 + np.concatenate((m2@W2,m2@W2), axis = 1)# Ваш код

assert result.shape == (32, 32)

Задание 23.

Приведите полученную на последнем шаге матрицу к виду $(32, 3)$ и сделайте так, чтобы все значения в этой матрице были в промежутке от $0$ до $1$

In [12]:
# Вжух! (∩｀-´)⊃━☆ﾟ.*･｡ﾟ
result = np.clip(result[:,:3], a_min = 0, a_max = 1)# Ваш код

assert result.shape == (32, 3)
assert ((result >= 0) & (result <= 1)).all()