## Домашнее задание

В этой тетрадке вам предлагается реализовать задания при помощи библиотеки numpy. Крайне желательно при выполнении разных заданий не использовать циклы. Если вы не понимаете, как выполнить конкретную задачу без циклов - убирайте их постепенно, разбейте выполнение задачи на этапы и постепенно векторизуйте каждый этап.

Если вам непонятно, как выполнить ту или иную операцию - не стесняйтесь гуглить, если над вами повис дедлайн, а вы всё ещё на чём-то застряли - пишите преподу/в чат, это ок.

**Обсудить решение лучше и сделать в итоге хоть что-то гораздо лучше, чем скатать чужой код или сдать пустую тетрадку.**

In [151]:
import numpy as np

### Drill (1 балл)

Задание 1.

Инициализируйте нулями массивы следующих форм:

* (5)
* (5, 1)
* (10, 2)
* (3, 6, 2)
* (4, 3, 2, 1)

In [152]:
# Ваш код
a = np.zeros(5)
b = np.zeros(shape=(5,1))
c = np.zeros(shape=(10,2))
d = np.zeros(shape=(3,6,2))
e = np.zeros(shape=(4,3,2,1))
print(a.shape,b.shape,c.shape,d.shape,e.shape, sep="\n")

(5,)
(5, 1)
(10, 2)
(3, 6, 2)
(4, 3, 2, 1)


Задание 2.

Инициализируйте единицами массивы таких же форм и приведите их к целочисленному виду:

In [153]:
# Ваш код
a = np.full(shape=5, fill_value=1, dtype=int)
b = np.full(shape=(5,1), fill_value=1, dtype=int)
c = np.full(shape=(10,2),fill_value=1, dtype=int)
d = np.full(shape=(3,6,2), fill_value=1, dtype=int)
e = np.full(shape=(4,3,2,1), fill_value=1, dtype=int)
print(a.shape,b.shape,c.shape,d.shape,e.shape, sep="\n")
# print(a,b,c,d,e, sep="\n")

(5,)
(5, 1)
(10, 2)
(3, 6, 2)
(4, 3, 2, 1)


Задание 3.

Выполните для векторов выше `reshape` в "форму"
* с двумя компонентами
* с тремя компонентами
* с четырьмя компонентами

In [154]:
# Ваш код
# 2D
a = np.reshape(a, newshape=(5,1))
b = np.reshape(b, newshape=(1,5))
c = np.reshape(c, newshape=(5,4))
d = np.reshape(d, newshape=(2,18))
e = np.reshape(e, newshape=(12,2))
print("2D")
print(a.shape,b.shape,c.shape,d.shape,e.shape, sep="\n")

# 3D
a = np.reshape(a, newshape=(5,1,1))
b = np.reshape(b, newshape=(1,5,1))
c = np.reshape(c, newshape=(5,2,2))
d = np.reshape(d, newshape=(3,6,2))
e = np.reshape(e, newshape=(3,2,4))
print("3D")
print(a.shape,b.shape,c.shape,d.shape,e.shape, sep="\n")

# 4D
a = np.reshape(a, newshape=(5,1,1,1))
b = np.reshape(b, newshape=(1,5,1,1))
c = np.reshape(c, newshape=(5,2,2,1))
d = np.reshape(d, newshape=(3,2,3,2))
e = np.reshape(e, newshape=(3,2,2,2))
print("4D")
print(a.shape,b.shape,c.shape,d.shape,e.shape, sep="\n")

2D
(5, 1)
(1, 5)
(5, 4)
(2, 18)
(12, 2)
3D
(5, 1, 1)
(1, 5, 1)
(5, 2, 2)
(3, 6, 2)
(3, 2, 4)
4D
(5, 1, 1, 1)
(1, 5, 1, 1)
(5, 2, 2, 1)
(3, 2, 3, 2)
(3, 2, 2, 2)


Задание 4.

Для вектора ниже посчитайте его
* Максимум по 1 оси
* Минимум по 0 оси
* Сумму по всем осям
* Среднее по 0 оси
* Медиану по 1 оси

In [155]:
v = np.random.randint(0, 9, size=(5, 7))

In [156]:
# Ваш код
print(v.max(axis=1))
print(v.min(axis=0))
print("Sum along axis 0: ", v.sum(axis=0), "\nSum along axis 1: ", v.sum(axis=1), "\nSum of all elements: ",  v.sum())
print(v.mean(axis=0))
print(np.median(v, axis=1))


[6 7 7 7 8]
[0 0 0 1 0 2 0]
Sum along axis 0:  [10 17 12 17 19 20 20] 
Sum along axis 1:  [22 19 21 20 33] 
Sum of all elements:  115
[2.  3.4 2.4 3.4 3.8 4.  4. ]
[4. 0. 2. 2. 5.]


Задание 5.

Для всё того же вектора `v` выведите
* Его shape
* 0 компоненту его "формы"
* 1 компоненту его "формы"

In [157]:
# Ваш код
print("Shape: ", v.shape)
print(v.shape[0], v.shape[1], sep="\n")

Shape:  (5, 7)
5
7


Задание 6.

Для этого же вектора выведите
* Все числа больше 5
* Все числа меньше 7 в обратном порядке
* Все числа больше 3, которые делятся на 4 без остатка
* Все числа, остаток от деления на 5 которых равен 3
* Индекс максимума
* Индекс минимума
* Cписок с индексами элементов отсортированного массива в исходном (неотсортированном)

In [158]:
# Ваш код
print("Исходная матрица:\n")
print(v)
print()

print("Все числа больше 5:\n", v[v > 5])
print()

print("Все числа меньше 7 в обратном порядке:\n", v[v < 7][::-1])
print()

print("Все числа больше 3, которые делятся на 4 без остатка:\n", v[(v > 3) & (v % 4 == 0)])
print()

print("Все числа, остаток от деления на 5 которых равен 3:\n", v[v % 5 == 3])
print()

print("Индекс максимума: ", v.argmax())
print()

print("Индекс минимума: ", v.argmin())
print()

print("Cписок с индексами элементов отсортированного массива в исходном (неотсортированном):\n", v.argsort(axis=None))

Исходная матрица:

[[0 6 1 4 0 5 6]
 [0 0 0 5 7 7 0]
 [1 4 1 2 7 4 2]
 [1 3 6 1 0 2 7]
 [8 4 4 5 5 2 5]]

Все числа больше 5:
 [6 6 7 7 7 6 7 8]

Все числа меньше 7 в обратном порядке:
 [5 2 5 5 4 4 2 0 1 6 3 1 2 4 2 1 4 1 0 5 0 0 0 6 5 0 4 1 6 0]

Все числа больше 3, которые делятся на 4 без остатка:
 [4 4 4 8 4 4]

Все числа, остаток от деления на 5 которых равен 3:
 [3 8]

Индекс максимума:  28

Индекс минимума:  0

Cписок с индексами элементов отсортированного массива в исходном (неотсортированном):
 [ 0 25  4  7  8  9 13  2 24 21 16 14 26 20 33 17 22  3 19 30 29 15 32 31
 34 10  5 23  1  6 27 18 11 12 28]


Задание 7.

Выполните следующие операции над вектором (независимо, не обязательно делать это в последовательности):
* Умножьте его на 3
* Разделите на 7
* Возведите в степень $\frac{2}{3}$
* Посчитайте $\sin$ от него
* Посчитайте $\log$ от него

In [159]:
# Ваш код
print("Исходная матрица:")
print(v)
print()

print("v*3:\n", v * 3)
print()

print("v / 7:\n", v/7)
print()

print("v^(2/3):\n", v**(2/3))
print()

print("sin(v):\n", np.sin(v))
print()

print("log(v):\n", np.log(v))

Исходная матрица:
[[0 6 1 4 0 5 6]
 [0 0 0 5 7 7 0]
 [1 4 1 2 7 4 2]
 [1 3 6 1 0 2 7]
 [8 4 4 5 5 2 5]]

v*3:
 [[ 0 18  3 12  0 15 18]
 [ 0  0  0 15 21 21  0]
 [ 3 12  3  6 21 12  6]
 [ 3  9 18  3  0  6 21]
 [24 12 12 15 15  6 15]]

v / 7:
 [[0.         0.85714286 0.14285714 0.57142857 0.         0.71428571
  0.85714286]
 [0.         0.         0.         0.71428571 1.         1.
  0.        ]
 [0.14285714 0.57142857 0.14285714 0.28571429 1.         0.57142857
  0.28571429]
 [0.14285714 0.42857143 0.85714286 0.14285714 0.         0.28571429
  1.        ]
 [1.14285714 0.57142857 0.57142857 0.71428571 0.71428571 0.28571429
  0.71428571]]

v^(2/3):
 [[0.         3.30192725 1.         2.5198421  0.         2.92401774
  3.30192725]
 [0.         0.         0.         2.92401774 3.65930571 3.65930571
  0.        ]
 [1.         2.5198421  1.         1.58740105 3.65930571 2.5198421
  1.58740105]
 [1.         2.08008382 3.30192725 1.         0.         1.58740105
  3.65930571]
 [4.         2.519

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:18: RuntimeWarning: divide by zero encountered in log


### Разные инициализации + индексирование (3 балла)

Задание 8.

Необходимо построить квадрат $3 \times 3$ из нечётных чисел

In [160]:
# Ваш код
np.arange(1,3*3*2,2).reshape((3,3))

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

Задание 9.

Необходимо построить квадрат $4 \times 4$ из четных чисел в обратном порядке

In [161]:
# Ваш код
np.arange(0,4*4*2,2)[::-1].reshape((4,4))

array([[30, 28, 26, 24],
       [22, 20, 18, 16],
       [14, 12, 10,  8],
       [ 6,  4,  2,  0]])

Задание 10.

Необходимо построить сетку координат $11 \times 11$ с точкой $(0,0)$ в центре и шагом $0.1$ между клетками

In [162]:
# Ваш код
def make_grid(size, step):
  a = np.linspace((1-size)*step,0,size)
  for i in range(1,size):
    a = np.vstack((a, np.linspace((1-size+i)*step,i*step,size)))
  return a
make_grid(11, 0.1)
# np.linspace(-0.7,0.3,11)
# np.mgrid[1:5:1, -1:1:0.5]
# np.vstack((np.linspace(-1,0,11), np.linspace(-0.9,0.1,11), np.linspace(-0.8,0.2,11), np.linspace(-0.7,0.3,11)))

array([[-1. , -0.9, -0.8, -0.7, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1,  0. ],
       [-0.9, -0.8, -0.7, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1],
       [-0.8, -0.7, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2],
       [-0.7, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3],
       [-0.6, -0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4],
       [-0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,  0.5],
       [-0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6],
       [-0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7],
       [-0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8],
       [-0.1,  0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9],
       [ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ]])

Задание 11.

Замощение сетки $8\times8$ при помощи $0$ и $1$ в шахматном порядке, клетка с индексом $(0,0)$ замощается $1$

In [163]:
# Ваш код
np.fromfunction(lambda i, j: (i+j+1)%2, (8, 8), dtype=int)

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

Задание 12.

То же замощение, но клетка с индексом $(0,0)$ замощается $0$

In [164]:
# Ваш код
np.fromfunction(lambda i, j: (i+j)%2, (8, 8), dtype=int)

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

Задание 13.

Необходимо построить нижне-треугольную матрицу переменного размера (задается передачей параметра в функцию). Это единичная матрица,замощённая $1$ под главной диагональю

In [165]:
# Ваш код
def task13(size):
  return np.tril(np.ones((size, size)), 0)
task13(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

Задание 14.

Необходимо построить верхне-треугольную матрицу переменного размера. Это единичная матрица, замощённая $1$ над главной диагональю

In [166]:
# Ваш код
def task14(size):
  return np.triu(np.ones((size, size)), 0)
task14(8)

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

Задание 15.

Необходимо построить матрицу, в которой единицы стоят на побочной диагонали (идущей из левого нижнего угла в правый верхний), в остальных местах стоят $0$

In [167]:
# Ваш код
np.flipud(np.eye(8))

array([[0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0.]])

### Операции + аггрегации (3 балла)

Задание 16.

Дана выборка $\{X_i\}$ некоторой случайной величины $X$, необходимо оценить
* Математическое ожидание $E[X] = \frac{1}{N}\sum_{i=1}^N X_i$ этой случайной величины
* Дисперсию $D[X] = \frac{1}{N}\sum_{i=1}^N (X_i - E[X])^2$ этой случайной величины

In [168]:
def expected_value(x):
    assert len(x) > 0
    return sum(x) / len(x)


def dispersion(x):
    assert len(x) > 0
    d = 0
    e = expected_value(x)
    for x_i in x:
        d += (x_i - e) ** 2
    return d / len(x)

In [169]:
def expected_value_np(x):
    return np.sum(x)/len(x)

In [170]:
def dispersion_np(x):
    e = expected_value_np(x)
    return np.sum((x - e)**2)/len(x)
     

In [171]:
np.testing.assert_array_equal(expected_value([1]), expected_value_np(np.array([1])))
np.testing.assert_array_equal(expected_value([3, 4]), expected_value_np(np.array([3, 4])))
np.testing.assert_array_equal(expected_value([-1, 0, 1]), expected_value_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(expected_value([-99, -98]), expected_value_np(np.array([-99, -98])))

np.testing.assert_array_equal(dispersion([1]), dispersion_np(np.array([1])))
np.testing.assert_array_equal(dispersion([3, 4]), dispersion_np(np.array([3, 4])))
np.testing.assert_array_equal(dispersion([-1, 0, 1]), dispersion_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(dispersion([-99, -98]), dispersion_np(np.array([-99, -98])))

Задание 17.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое квадратов разностей их значений

In [172]:
def mean_square_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    # Здесь и далее эти проверки !не нужно! дублировать в свои функции; Здесь они для того, чтобы лишний раз подчеркнуть валидность входных данных
    s = 0
    for i in range(len(y1)):
        s += (y1[i] - y2[i]) ** 2
    return s / len(y1)

In [173]:
def mean_square_difference_np(y1, y2):
    return np.mean((y1 - y2)**2)

In [174]:
assert mean_square_difference([1], [1]) == mean_square_difference_np(np.array([1]), np.array([1]))
assert mean_square_difference([1, 2], [1, 2]) == mean_square_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_square_difference([-1, 1], [0, 0]) == mean_square_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_square_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_square_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 18.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое модулей разностей их значений

In [175]:
def mean_abs_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    s = 0
    for i in range(len(y1)):
        s += abs(y1[i] - y2[i])
    return s / len(y1)

In [176]:
def mean_abs_difference_np(y1, y2):
    return np.mean(np.abs(y1-y2))

In [177]:
assert mean_abs_difference([1], [1]) == mean_abs_difference_np(np.array([1]), np.array([1]))
assert mean_abs_difference([1, 2], [1, 2]) == mean_abs_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_abs_difference([-1, 1], [0, 0]) == mean_abs_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_abs_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_abs_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 19.

Даны два вектора $y_1$ и $y_2$, в которых присутствуют только $0$ и $1$. Необходимо посчитать вероятность совпадения - в скольких точках значения двух векторов совпадают

In [178]:
def matching_proba(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    assert len(set(y1)) <= 2
    assert len(set(y2)) <= 2
    assert 0 in set(y1) or 1 in set(y1) or (0 in set(y1) and 1 in set(y1))
    assert 0 in set(y2) or 1 in set(y2) or (0 in set(y2) and 1 in set(y2))

    return sum([y1[i] == y2[i] for i in range(len(y1))]) / len(y1)

In [179]:
def matching_proba_np(y1, y2):
    return np.sum(y1 == y2)/len(y1)

In [180]:
np.testing.assert_array_equal(matching_proba([0, 1], [1, 0]), matching_proba_np(np.array([0, 1]), np.array([1, 0])))
np.testing.assert_array_equal(matching_proba([0, 1, 0, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 1, 0, 1]), np.array([0, 0, 1, 1])))
np.testing.assert_array_equal(matching_proba([0, 0, 1, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1])))

Задание 20.

Даны два вектора: $y_1$, $y_2$. В $y_1$ и $y_2$ присутствуют только $0$ и $1$.

Необходимо найти границы (индексы), такие, что если мы разделим вдоль какой-то из этих границ оба вектора на две части, то
* в левой части пересекающихся в $y_1$ и $y_2$ нулей будет строго больше, чем пересекающихся единиц или непересекающихся элементов
* в правой - пересекающихся единиц строго больше, чем пересекающихся нулей или непересекающихся элементов.

Если какая-то из частей не содержит элементов вовсе, то будем считать, что она подходит под условие.

In [181]:
def find_thresholds(y1, y2, debug=False):
    assert len(y1) == len(y2) and len(y1) > 0
    n = len(y1)
    matching_zeros = [1 if y1[i] == y2[i] == 0 else 0 for i in range(n)]
    matching_ones = [1 if y1[i] == y2[i] == 1 else 0 for i in range(n)]

    res = []
    if sum(matching_ones) / n > 0.5:
        res.append(0)
    for i in range(1, n):
        if debug: # если вам непонятна логика работы этой функции, передайте третьим аргументом True
            print(matching_zeros[:i], matching_ones[i:], i)
        if sum(matching_zeros[:i]) / i > 0.5 and sum(matching_ones[i:]) / (n - i) > 0.5:
            res.append(i)
    if sum(matching_zeros) / n > 0.5:
        res.append(n)
    return res
print(find_thresholds([0], [0]))
# find_thresholds(np.array([0, 0, 1, 0, 0, 1, 1, 1]), np.array([0, 0, 0, 0, 0, 1, 1, 1]))


[1]


In [187]:
def find_thresholds_np(y1, y2):
    n = len(y1)
    indexes = np.arange(1,n)
    # print(y1 == y2)
    
    matching_zeros = (y1 == y2) & (y1 == np.zeros(n)).astype(int)
    matching_ones = (y1 == y2) & (y1 == np.ones(n)).astype(int)
    not_matching = ((y1 != y2) if len(y1) > 1 else np.array([y1 != y2])).astype(int)
    # print(matching_zeros)
    # print(matching_ones)
    # print(not_matching)
    # print()
    # print(np.cumsum(matching_zeros, axis=0))
    # print(np.cumsum(matching_ones, axis=0))
    # print(np.cumsum(not_matching, axis=0))
    # print()
    # print(np.cumsum(matching_zeros[::-1], axis=0)[::-1])
    # print(np.cumsum(matching_ones[::-1], axis=0)[::-1])
    # print(np.cumsum(not_matching[::-1], axis=0)[::-1])


    # return (((np.cumsum(matching_zeros, axis=0) > np.cumsum(matching_ones, axis=0)) & (np.cumsum(matching_zeros, axis=0) > np.cumsum(not_matching, axis=0)))
    # & ((np.cumsum(matching_ones[::-1], axis=0)[::-1] - matching_ones > np.cumsum(matching_zeros[::-1], axis=0)[::-1] - matching_zeros) & (np.cumsum(matching_ones[::-1], axis=0)[::-1] - matching_ones > np.cumsum(not_matching[::-1], axis=0)[::-1] - not_matching))).astype(int).tolist()

    # считаем процент сматченных нулей для каждого индекса i на промежутке от 0 до i включительно и храним его пож этим индексом
    percent_matching_zeros = np.cumsum(matching_zeros, axis=0)[:-1] / indexes
    # то же самое, но считаем процент сматченных единиц на промежутке от i+1 включительно и до конца
    percent_matching_ones = (np.cumsum(matching_ones[::-1], axis=0)[::-1])[1:] / np.arange(n-1, 0, -1)
    answer_indexes = ((percent_matching_zeros>0.5) & (percent_matching_ones>0.5)) * indexes
    answer = list(answer_indexes[answer_indexes>0])
    # если весь вектор слева от границы
    if (np.cumsum(matching_zeros, axis=0)[-1]/n > 0.5):
        answer += [n]
    # если весь вектор справа от границы
    if np.cumsum(matching_ones, axis=0)[-1]/n > 0.5:
        answer = [0] + answer
    return answer
# find_thresholds_np(np.array([0, 0, 1, 0, 0, 1, 1, 1]), np.array([0, 0, 0, 0, 0, 1, 1, 1]))
find_thresholds_np([0], [0])

[1]

In [183]:
## (๑˃̵ ᴗ ˂̵)و
np.testing.assert_array_equal(find_thresholds([0], [0]), find_thresholds_np(np.array([0]), np.array([0])))
np.testing.assert_array_equal(find_thresholds([1], [1]), find_thresholds_np(np.array([1]), np.array([1])))
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 1], [0, 0, 1, 1]), 
    find_thresholds_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1]))
)
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 0, 0, 1, 1, 1], [0, 0, 0, 0, 0, 1, 1, 1]),
    find_thresholds_np(np.array([0, 0, 1, 0, 0, 1, 1, 1]), np.array([0, 0, 0, 0, 0, 1, 1, 1]))
)

### Разные действия с матрицами (3 балла)

Задание 21.

Дана матрица размера $(32, 3, 16, 16)$, заполненная случайными числами от 0 до 9. При помощи **ровно двух** преобразований приведите её к виду $(32, 1)$. При выполнении задания **можно** создавать вспомогательные матрицы!

In [184]:
data = np.random.randint(0, 10, size=(32, 3, 16, 16))

# Преобразование 1
data = data.sum(axis=(1,2,3))
# Преобразование 2
data = data.reshape((32,1))

print(data.shape)
assert data.shape == (32, 1)

(32, 1)


Задание 22.

Даны две матрицы $m_1$ размером $(32, 256)$ и $m_2$ размером $(32, 512)$, а также две вспомогательные матрицы $W_1$ размером $(256, 32)$ и $W_2$ размером $(512, 16)$. Используя **все** данные матрицы, сделайте так, чтобы на выходе получилась **ровно одна** матрица размером $(32, 32)$

In [185]:
m1 = np.random.randint(0, 10, size=(32, 256))
m2 = np.random.randint(0, 10, size=(32, 512))
W1 = np.random.randint(0, 10, size=(256, 32))
W2 = np.random.randint(0, 10, size=(512, 16))

result = m1.dot(W1 + W2.reshape((256,32)) + m2.reshape((2,256,32)).sum(axis=0))

assert result.shape == (32, 32)

Задание 23.

Приведите полученную на последнем шаге матрицу к виду $(32, 3)$ и сделайте так, чтобы все значения в этой матрице были в промежутке от $0$ до $1$

In [186]:
# Вжух! (∩｀-´)⊃━☆ﾟ.*･｡ﾟ
result = result[:,:3]/np.max(np.abs(result))

assert result.shape == (32, 3)
assert ((result >= 0) & (result <= 1)).all()