## Домашнее задание

В этой тетрадке вам предлагается реализовать задания при помощи библиотеки numpy. Крайне желательно при выполнении разных заданий не использовать циклы. Если вы не понимаете, как выполнить конкретную задачу без циклов - убирайте их постепенно, разбейте выполнение задачи на этапы и постепенно векторизуйте каждый этап.

Если вам непонятно, как выполнить ту или иную операцию - не стесняйтесь гуглить, если над вами повис дедлайн, а вы всё ещё на чём-то застряли - пишите преподу/в чат, это ок.

**Обсудить решение лучше и сделать в итоге хоть что-то гораздо лучше, чем скатать чужой код или сдать пустую тетрадку.**

In [1]:
import numpy as np

### Drill (1 балл)

Задание 1.

Инициализируйте нулями массивы следующих форм:

* (5)
* (5, 1)
* (10, 2)
* (3, 6, 2)
* (4, 3, 2, 1)

In [ ]:
a1 = np.zeros(5)
a2 = np.zeros((5,1))
a3 = np.zeros((10,2))
a4 = np.zeros((3, 6, 2))
a5 = np.zeros((4,3, 2, 1))

Задание 2.

Инициализируйте единицами массивы таких же форм и приведите их к целочисленному виду:

In [ ]:
b1 = np.ones(5).astype(int)
b2 = np.ones((5, 1)).astype(int)
b3 = np.ones((10, 2)).astype(int)
b4 = np.ones((3, 6, 2)).astype(int)
b5 = np.ones((4, 3, 2, 1)).astype(int)

Задание 3.

Выполните для векторов выше `reshape` в "форму"
* с двумя компонентами
* с тремя компонентами
* с четырьмя компонентами

In [ ]:
print(b1.reshape((5, 1)))
print(b1.reshape((5, 1, 1)))
print(b1.reshape(5, 1, 1, 1))
print(b2.reshape(5, 1))
print(b2.reshape(5, 1, 1))
print(b2.reshape(5, 1, 1, 1))
print(b3.reshape(10, 2))
print(b3.reshape(10, 2, 1))
print(b3.reshape(10, 2, 1, 1))
print(b4.reshape(18, 2))
print(b4.reshape(3, 6, 2))
print(b4.reshape(3, 6, 2, 1))
print(b5.reshape(4, 6))
print(b5.reshape(4, 3, 2))
print(b5.reshape(4, 3, 2, 1))

Задание 4.

Для вектора ниже посчитайте его
* Максимум по 1 оси
* Минимум по 0 оси
* Сумму по всем осям
* Среднее по 0 оси
* Медиану по 1 оси

In [3]:
v = np.random.randint(0, 9, size=(5, 7))

In [ ]:
print(v.max(axis=1))
print(v.min(axis=0))
print(v.sum())
print(v.mean(axis=0))
print(np.median(v, axis=1))

Задание 5.

Для всё того же вектора `v` выведите
* Его shape
* 0 компоненту его "формы"
* 1 компоненту его "формы"

In [4]:
print(v.shape)
print(v.shape[0])
print(v.shape[1])

(5, 7)
5
7


Задание 6.

Для этого же вектора выведите
* Все числа больше 5
* Все числа меньше 7 в обратном порядке
* Все числа больше 3, которые делятся на 4 без остатка
* Все числа, остаток от деления на 5 которых равен 3
* Индекс максимума
* Индекс минимума
* Cписок с индексами элементов отсортированного массива в исходном (неотсортированном)

In [10]:
print(v[v > 5])
print(v[v < 7][::-1])
print(v[(v > 3) & (v % 4 == 0)])
print(v[v % 5 == 3])
print(v.argmax())
print(v.argmin())
print(v.argsort())

[8 7 7 7 8 7 7 8 6 8 6 7 8 6 8 6]
[6 6 4 3 0 5 4 3 6 1 3 1 0 3 3 6 2 3 3 1 2 2 0]
[8 8 8 8 4 8 4 8]
[8 8 8 3 3 3 8 3 3 3 8 3 8]
1
0
[[1 6 2 3 4 0 5]
 [3 1 5 6 0 2 4]
 [5 6 0 2 4 1 3]
 [1 0 3 5 6 2 4]
 [0 2 3 4 6 1 5]]


Задание 7.

Выполните следующие операции над вектором (независимо, не обязательно делать это в последовательности):
* Умножьте его на 3
* Разделите на 7
* Возведите в степень $\frac{2}{3}$
* Посчитайте $\sin$ от него
* Посчитайте $\log$ от него

In [5]:
print(v * 3)
print(v / 7)
print(v ** (2/3))
print(np.sin(v))
print(np.log(v[v != 0]))

[[ 9 15 15  3 21 24 21]
 [18  9  3  3  0 12  6]
 [18  6 18 18 24 15 18]
 [21 21 24  9 18  0  0]
 [ 3 21 21  9  9  6 21]]
[[0.42857143 0.71428571 0.71428571 0.14285714 1.         1.14285714
  1.        ]
 [0.85714286 0.42857143 0.14285714 0.14285714 0.         0.57142857
  0.28571429]
 [0.85714286 0.28571429 0.85714286 0.85714286 1.14285714 0.71428571
  0.85714286]
 [1.         1.         1.14285714 0.42857143 0.85714286 0.
  0.        ]
 [0.14285714 1.         1.         0.42857143 0.42857143 0.28571429
  1.        ]]
[[2.08008382 2.92401774 2.92401774 1.         3.65930571 4.
  3.65930571]
 [3.30192725 2.08008382 1.         1.         0.         2.5198421
  1.58740105]
 [3.30192725 1.58740105 3.30192725 3.30192725 4.         2.92401774
  3.30192725]
 [3.65930571 3.65930571 4.         2.08008382 3.30192725 0.
  0.        ]
 [1.         3.65930571 3.65930571 2.08008382 2.08008382 1.58740105
  3.65930571]]
[[ 0.14112001 -0.95892427 -0.95892427  0.84147098  0.6569866   0.98935825
   0.656

### Разные инициализации + индексирование (3 балла)

Задание 8.

Необходимо построить квадрат $3 \times 3$ из нечётных чисел

In [3]:
np.arange(1, 18, 2).reshape(3,3)

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

Задание 9.

Необходимо построить квадрат $4 \times 4$ из четных чисел в обратном порядке

In [5]:
np.arange(2, 33, 2)[::-1].reshape(4, 4)

array([[32, 30, 28, 26],
       [24, 22, 20, 18],
       [16, 14, 12, 10],
       [ 8,  6,  4,  2]])

Задание 10.

Необходимо построить сетку координат $11 \times 11$ с точкой $(0,0)$ в центре и шагом $0.1$ между клетками

In [41]:
x = np.linspace(-0.5, 0.5, 11)
y = np.linspace(0.5, -0.5, 11).reshape(11, 1)
x + y

array([[ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ],
       [-0.1,  0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9],
       [-0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8],
       [-0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7],
       [-0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6],
       [-0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,  0.5],
       [-0.6, -0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4],
       [-0.7, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3],
       [-0.8, -0.7, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2],
       [-0.9, -0.8, -0.7, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1],
       [-1. , -0.9, -0.8, -0.7, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1,  0. ]])

Задание 11.

Замощение сетки $8\times8$ при помощи $0$ и $1$ в шахматном порядке, клетка с индексом $(0,0)$ замощается $1$

In [63]:
a1 = np.arange(1, 9) % 2
a2 = (np.arange(8) % 2).reshape(8, 1)
(a1 + a2) % 2

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]], dtype=int32)

Задание 12.

То же замощение, но клетка с индексом $(0,0)$ замощается $0$

In [44]:
a1 = np.arange(8) % 2
a2 = (np.arange(8) % 2).reshape(8, 1)
(a1 + a2) % 2

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]], dtype=int32)

Задание 13.

Необходимо построить нижне-треугольную матрицу переменного размера (задается передачей параметра в функцию). Это единичная матрица,замощённая $1$ под главной диагональю

In [52]:
def  low_triangle(n):
    a = np.eye(n)
    a[np.tril_indices_from(a)] = 1
    print(a)

low_triangle(6)

[[1. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1. 1.]]


Задание 14.

Необходимо построить верхне-треугольную матрицу переменного размера. Это единичная матрица, замощённая $1$ над главной диагональю

In [53]:
def  low_triangle(n):
    a = np.eye(n)
    a[np.triu_indices_from(a)] = 1
    print(a)

low_triangle(6)

[[1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 1.]]


Задание 15.

Необходимо построить матрицу, в которой единицы стоят на побочной диагонали (идущей из левого нижнего угла в правый верхний), в остальных местах стоят $0$

In [58]:
def not_eye(n):
    print(np.eye(n)[::-1])

not_eye(6)

[[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]


### Операции + аггрегации (3 балла)

Задание 16.

Дана выборка $\{X_i\}$ некоторой случайной величины $X$, необходимо оценить
* Математическое ожидание $E[X] = \frac{1}{N}\sum_{i=1}^N X_i$ этой случайной величины
* Дисперсию $D[X] = \frac{1}{N}\sum_{i=1}^N (X_i - E[X])^2$ этой случайной величины

In [2]:
def expected_value(x):
    assert len(x) > 0
    return sum(x) / len(x)


def dispersion(x):
    assert len(x) > 0
    d = 0
    e = expected_value(x)
    for x_i in x:
        d += (x_i - e) ** 2
    return d / len(x)

In [3]:
def expected_value_np(x):
    return np.mean(x)

In [4]:
def dispersion_np(x):
    return np.var(x)

In [8]:
np.testing.assert_array_equal(expected_value([1]), expected_value_np(np.array([1])))
np.testing.assert_array_equal(expected_value([3, 4]), expected_value_np(np.array([3, 4])))
np.testing.assert_array_equal(expected_value([-1, 0, 1]), expected_value_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(expected_value([-99, -98]), expected_value_np(np.array([-99, -98])))

np.testing.assert_array_equal(dispersion([1]), dispersion_np(np.array([1])))
np.testing.assert_array_equal(dispersion([3, 4]), dispersion_np(np.array([3, 4])))
np.testing.assert_array_equal(dispersion([-1, 0, 1]), dispersion_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(dispersion([-99, -98]), dispersion_np(np.array([-99, -98])))

Задание 17.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое квадратов разностей их значений

In [9]:
def mean_square_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    # Здесь и далее эти проверки !не нужно! дублировать в свои функции; Здесь они для того, чтобы лишний раз подчеркнуть валидность входных данных
    s = 0
    for i in range(len(y1)):
        s += (y1[i] - y2[i]) ** 2
    return s / len(y1)

In [12]:
def mean_square_difference_np(y1, y2):
    return np.mean((y1 - y2) ** 2)

In [15]:
assert mean_square_difference([1], [1]) == mean_square_difference_np(np.array([1]), np.array([1]))
assert mean_square_difference([1, 2], [1, 2]) == mean_square_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_square_difference([-1, 1], [0, 0]) == mean_square_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_square_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_square_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 18.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое модулей разностей их значений

In [16]:
def mean_abs_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    s = 0
    for i in range(len(y1)):
        s += abs(y1[i] - y2[i])
    return s / len(y1)

In [17]:
def mean_abs_difference_np(y1, y2):
    return np.mean(np.abs(y1 - y2))

In [18]:
assert mean_abs_difference([1], [1]) == mean_abs_difference_np(np.array([1]), np.array([1]))
assert mean_abs_difference([1, 2], [1, 2]) == mean_abs_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_abs_difference([-1, 1], [0, 0]) == mean_abs_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_abs_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_abs_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

    Задание 19.

Даны два вектора $y_1$ и $y_2$, в которых присутствуют только $0$ и $1$. Необходимо посчитать вероятность совпадения - в скольких точках значения двух векторов совпадают

In [ ]:
def matching_proba(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    assert len(set(y1)) <= 2
    assert len(set(y2)) <= 2
    assert 0 in set(y1) or 1 in set(y1) or (0 in set(y1) and 1 in set(y1))
    assert 0 in set(y2) or 1 in set(y2) or (0 in set(y2) and 1 in set(y2))

    return sum([y1[i] == y2[i] for i in range(len(y1))]) / len(y1)

In [ ]:
def matching_proba_np(y1, y2):
    return np.sum(y1 == y2)/y1.shape[0]

In [ ]:
np.testing.assert_array_equal(matching_proba([0, 1], [1, 0]), matching_proba_np(np.array([0, 1]), np.array([1, 0])))
np.testing.assert_array_equal(matching_proba([0, 1, 0, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 1, 0, 1]), np.array([0, 0, 1, 1])))
np.testing.assert_array_equal(matching_proba([0, 0, 1, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1])))

Задание 20.

Даны два вектора: $y_1$, $y_2$. В $y_1$ и $y_2$ присутствуют только $0$ и $1$.

Необходимо найти границы (индексы), такие, что если мы разделим вдоль какой-то из этих границ оба вектора на две части, то
* в левой части пересекающихся в $y_1$ и $y_2$ нулей будет строго больше, чем пересекающихся единиц или непересекающихся элементов
* в правой - пересекающихся единиц строго больше, чем пересекающихся нулей или непересекающихся элементов.

Если какая-то из частей не содержит элементов вовсе, то будем считать, что она подходит под условие.

In [13]:
def find_thresholds(y1, y2, debug=False):
    assert len(y1) == len(y2) and len(y1) > 0
    n = len(y1)
    matching_zeros = [1 if y1[i] == y2[i] == 0 else 0 for i in range(n)]
    matching_ones = [1 if y1[i] == y2[i] == 1 else 0 for i in range(n)]
    res = []
    if sum(matching_ones) / n > 0.5:
        res.append(0)
    for i in range(1, n):
        if debug: # если вам непонятна логика работы этой функции, передайте третьим аргументом True
            print(matching_zeros[:i], matching_ones[i:], i)
        if sum(matching_zeros[:i]) / i > 0.5 and sum(matching_ones[i:]) / (n - i) > 0.5:
            res.append(i)
    if sum(matching_zeros) / n > 0.5:
        res.append(n)
    return res

In [34]:
def find_thresholds_np(y1, y2):
    n = y1.shape[0]
    equal_zeros = np.zeros(n)
    equal_zeros[(y1 == 0) & (y2 == 0)] = 1
    equal_ones = np.zeros(n)
    equal_ones[(y1 == 1) & (y2 == 1)] = 1
    factor1 = np.hstack((np.array([True]), (np.cumsum(equal_zeros) / np.arange(1, n + 1)) > 0.5))
    factor2 = np.hstack((((np.cumsum(equal_ones[::-1]) / np.arange(1, n + 1)) > 0.5)[::-1], np.array([True])))
    return list(np.arange(n + 1)[factor1 & factor2])

In [35]:
np.testing.assert_array_equal(find_thresholds([0], [0]), find_thresholds_np(np.array([0]), np.array([0])))
np.testing.assert_array_equal(find_thresholds([1], [1]), find_thresholds_np(np.array([1]), np.array([1])))
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 1], [0, 0, 1, 1]), 
    find_thresholds_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1]))
)
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 0, 0, 1, 1, 1], [0, 0, 0, 0, 0, 1, 1, 1]),
    find_thresholds_np(np.array([0, 0, 1, 0, 0, 1, 1, 1]), np.array([0, 0, 0, 0, 0, 1, 1, 1]))
)

### Разные действия с матрицами (3 балла)

Задание 21.

Дана матрица размера $(32, 3, 16, 16)$, заполненная случайными числами от 0 до 9. При помощи **ровно двух** преобразований приведите её к виду $(32, 1)$. При выполнении задания **можно** создавать вспомогательные матрицы!

In [42]:
data = np.random.randint(0, 10, size=(32, 3, 16, 16))
helpme = np.random.randint(0, 10, size=(3 * 16 * 16, 1))

data = data.reshape(32, 3 * 16 * 16)

data = data.dot(helpme)

assert data.shape == (32, 1)

Задание 22.

Даны две матрицы $m_1$ размером $(32, 256)$ и $m_2$ размером $(32, 512)$, а также две вспомогательные матрицы $W_1$ размером $(256, 32)$ и $W_2$ размером $(512, 16)$. Используя **все** данные матрицы, сделайте так, чтобы на выходе получилась **ровно одна** матрица размером $(32, 32)$

In [57]:
m1 = np.random.randint(0, 10, size=(32, 256))
m2 = np.random.randint(0, 10, size=(32, 512))
W1 = np.random.randint(0, 10, size=(256, 32))
W2 = np.random.randint(0, 10, size=(512, 16))


result = m1.dot(W1).dot(m2).dot(W2).dot(W2.T).dot(m2.T)
assert result.shape == (32, 32)

Задание 23.

Приведите полученную на последнем шаге матрицу к виду $(32, 3)$ и сделайте так, чтобы все значения в этой матрице были в промежутке от $0$ до $1$

In [62]:
# Вжух! (∩｀-´)⊃━☆ﾟ.*･｡ﾟ

vzuh = result.dot(np.random.randint(0, 10, size=(32, 3)))
result1 = abs(vzuh / np.max(abs(vzuh)))

assert result1.shape == (32, 3)
assert ((result1 >= 0) & (result1 <= 1)).all()