## Домашнее задание

В этой тетрадке вам предлагается реализовать задания при помощи библиотеки numpy. Крайне желательно при выполнении разных заданий не использовать циклы. Если вы не понимаете, как выполнить конкретную задачу без циклов - убирайте их постепенно, разбейте выполнение задачи на этапы и постепенно векторизуйте каждый этап.

Если вам непонятно, как выполнить ту или иную операцию - не стесняйтесь гуглить, если над вами повис дедлайн, а вы всё ещё на чём-то застряли - пишите преподу/в чат, это ок.

**Обсудить решение лучше и сделать в итоге хоть что-то гораздо лучше, чем скатать чужой код или сдать пустую тетрадку.**

In [1]:
import numpy as np

### Drill (1 балл)

Задание 1.

Инициализируйте нулями массивы следующих форм:

* (5)
* (5, 1)
* (10, 2)
* (3, 6, 2)
* (4, 3, 2, 1)

In [2]:
a = np.zeros(5)
b = np.zeros((5, 1))
c = np.zeros((10, 2))
d = np.zeros((3, 6, 2))
e = np.zeros((4, 3, 2, 1))

Задание 2.

Инициализируйте единицами массивы таких же форм и приведите их к целочисленному виду:

In [3]:
a = np.ones(5, dtype=int)
b = np.ones((5, 1), dtype=int)
c = np.ones((10, 2), dtype=int)
d = np.ones((3, 6, 2), dtype=int)
e = np.ones((4, 3, 2, 1), dtype=int)

Задание 3.

Выполните для векторов выше `reshape` в "форму"
* с двумя компонентами
* с тремя компонентами
* с четырьмя компонентами

In [4]:
a_2 = a.reshape(5, 1)
a_3 = a.reshape(5, 1, 1)
a_4 = a.reshape(1, 1, 1, 5)

b_2 = b.reshape(1, 5)
b_3 = b.reshape(1, 5, 1)
b_4 = b.reshape(1, 1, 5, 1)

c_3 = c.reshape(4, 5)
c_3 = c.reshape(5, 4, 1)
c_4 = c.reshape(2, 1, 2, 5)

d_2 = d.reshape(6, 6)
d_3 = d.reshape(4, 3, 3)
d_4 = d.reshape(3, 2, 3, 2)

e_2 = e.reshape(12, 2)
e_3 = e.reshape(8, 3, 1)
e_4 = e.reshape(6, 1, 2, 2)

Задание 4.

Для вектора ниже посчитайте его
* Максимум по 1 оси
* Минимум по 0 оси
* Сумму по всем осям
* Среднее по 0 оси
* Медиану по 1 оси

In [5]:
v = np.random.randint(0, 9, size=(5, 7))

In [6]:
print(v.max(axis=1))
print(v.max(axis=0))
print(v.sum())
print(v.mean(axis=0))
print(np.median(v, axis=1))

[8 8 7 8 8]
[8 7 8 7 8 7 6]
143
[4.2 3.  4.4 4.  6.  3.4 3.6]
[4. 3. 6. 2. 6.]


Задание 5.

Для всё того же вектора `v` выведите
* Его shape
* 0 компоненту его "формы"
* 1 компоненту его "формы"

In [7]:
print(v.shape)
print(v.shape[0])
print(v.shape[1])

(5, 7)
5
7


Задание 6.

Для этого же вектора выведите
* Все числа больше 5
* Все числа меньше 7 в обратном порядке
* Все числа больше 3, которые делятся на 4 без остатка
* Все числа, остаток от деления на 5 которых равен 3
* Индекс максимума
* Индекс минимума
* Cписок с индексами элементов отсортированного массива в исходном (неотсортированном)

In [8]:
print(v)
print(v[v > 5])
print(v[v < 7][::-1])
print(v[(v > 3) & (v % 4 == 0)])
print(v[(v % 5 == 3)])
print(v.argmax())
print(v.argmin())
print(v.argsort())

[[2 4 8 2 8 4 0]
 [8 2 0 6 0 3 4]
 [5 7 3 5 7 7 6]
 [4 2 3 0 8 0 2]
 [2 0 8 7 7 3 6]]
[8 8 8 6 7 7 7 6 8 8 7 7 6]
[6 3 0 2 2 0 0 3 2 4 6 5 3 5 4 3 0 6 0 2 0 4 2 4 2]
[4 8 8 4 8 4 4 8 8]
[8 8 8 3 3 3 8 8 3]
2
6
[[6 0 3 1 5 2 4]
 [2 4 1 5 6 3 0]
 [2 0 3 6 1 4 5]
 [3 5 1 6 2 0 4]
 [1 0 5 6 3 4 2]]


Задание 7.

Выполните следующие операции над вектором (независимо, не обязательно делать это в последовательности):
* Умножьте его на 3
* Разделите на 7
* Возведите в степень $\frac{2}{3}$
* Посчитайте $\sin$ от него
* Посчитайте $\log$ от него

In [9]:
v1 = v * 3
print(v1)

v2 = v / 7
print(v2)

v3 = v ** (2/3)
print(v3)

v4 = np.sin(v)
print(v4)

v5 = np.log(v)
print(v5)

[[ 6 12 24  6 24 12  0]
 [24  6  0 18  0  9 12]
 [15 21  9 15 21 21 18]
 [12  6  9  0 24  0  6]
 [ 6  0 24 21 21  9 18]]
[[0.28571429 0.57142857 1.14285714 0.28571429 1.14285714 0.57142857
  0.        ]
 [1.14285714 0.28571429 0.         0.85714286 0.         0.42857143
  0.57142857]
 [0.71428571 1.         0.42857143 0.71428571 1.         1.
  0.85714286]
 [0.57142857 0.28571429 0.42857143 0.         1.14285714 0.
  0.28571429]
 [0.28571429 0.         1.14285714 1.         1.         0.42857143
  0.85714286]]
[[1.58740105 2.5198421  4.         1.58740105 4.         2.5198421
  0.        ]
 [4.         1.58740105 0.         3.30192725 0.         2.08008382
  2.5198421 ]
 [2.92401774 3.65930571 2.08008382 2.92401774 3.65930571 3.65930571
  3.30192725]
 [2.5198421  1.58740105 2.08008382 0.         4.         0.
  1.58740105]
 [1.58740105 0.         4.         3.65930571 3.65930571 2.08008382
  3.30192725]]
[[ 0.90929743 -0.7568025   0.98935825  0.90929743  0.98935825 -0.7568025
   0.    

<ipython-input-9-1adbf573e9a4>:13: RuntimeWarning: divide by zero encountered in log
  v5 = np.log(v)


### Разные инициализации + индексирование (3 балла)

Задание 8.

Необходимо построить квадрат $3 \times 3$ из нечётных чисел

In [10]:
a = np.arange(1, 18, 2)
a = a.reshape((3, 3))
a

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

Задание 9.

Необходимо построить квадрат $4 \times 4$ из четных чисел в обратном порядке

In [11]:
b = np.arange(32, 1, -2)
b = b.reshape((4, 4))
b

array([[32, 30, 28, 26],
       [24, 22, 20, 18],
       [16, 14, 12, 10],
       [ 8,  6,  4,  2]])

Задание 10.

Необходимо построить сетку координат $11 \times 11$ с точкой $(0,0)$ в центре и шагом $0.1$ между клетками

In [64]:
x = np.linspace(-0.5, 0.5, 11)
y = np.linspace(0.5, -0.5, 11)

np.meshgrid(x, y)

[array([[-0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,  0.5],
        [-0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,  0.5],
        [-0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,  0.5],
        [-0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,  0.5],
        [-0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,  0.5],
        [-0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,  0.5],
        [-0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,  0.5],
        [-0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,  0.5],
        [-0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,  0.5],
        [-0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,  0.5],
        [-0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,  0.5]]),
 array([[ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
        [ 0.4,  0.4,  0.4,  0.4,  0.4,  0.4,  0.4,  0.4,  0.4,  0.4,  0.4],
        [ 

Задание 11.

Замощение сетки $8\times8$ при помощи $0$ и $1$ в шахматном порядке, клетка с индексом $(0,0)$ замощается $1$

In [12]:
f = np.fromfunction(lambda x, y: (x % 2 == 0) & (y % 2 == 0), shape=(8, 8)).astype(int)
print(f)

[[1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]]


Задание 12.

То же замощение, но клетка с индексом $(0,0)$ замощается $0$

In [13]:
g = np.fromfunction(lambda x, y: (x % 2 == 1) | (y % 2 == 1), shape=(8, 8), dtype=int).astype(int)
g

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

Задание 13.

Необходимо построить нижне-треугольную матрицу переменного размера (задается передачей параметра в функцию). Это единичная матрица,замощённая $1$ под главной диагональю

In [14]:
def create_lower_triangle_matrix(n):
    return np.fromfunction(lambda x, y: x > y, shape=(n, n)).astype(int)

create_lower_triangle_matrix(6)

array([[0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0],
       [1, 1, 1, 0, 0, 0],
       [1, 1, 1, 1, 0, 0],
       [1, 1, 1, 1, 1, 0]])

Задание 14.

Необходимо построить верхне-треугольную матрицу переменного размера. Это единичная матрица, замощённая $1$ над главной диагональю

In [15]:
def create_upper_triangle_matrix(n):
    return np.fromfunction(lambda x, y: x < y, shape=(n, n)).astype(int)

create_upper_triangle_matrix(7)

array([[0, 1, 1, 1, 1, 1, 1],
       [0, 0, 1, 1, 1, 1, 1],
       [0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 1, 1],
       [0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0]])

Задание 15.

Необходимо построить матрицу, в которой единицы стоят на побочной диагонали (идущей из левого нижнего угла в правый верхний), в остальных местах стоят $0$

In [16]:
def create_secondary_diagonal_matrix(n):
    return np.fromfunction(lambda x, y: x + y == n - 1, shape=(n, n)).astype(int)

create_secondary_diagonal_matrix(5)

array([[0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0]])

### Операции + аггрегации (3 балла)

Задание 16.

Дана выборка $\{X_i\}$ некоторой случайной величины $X$, необходимо оценить
* Математическое ожидание $E[X] = \frac{1}{N}\sum_{i=1}^N X_i$ этой случайной величины
* Дисперсию $D[X] = \frac{1}{N}\sum_{i=1}^N (X_i - E[X])^2$ этой случайной величины

In [17]:
def expected_value(x):
    assert len(x) > 0
    return sum(x) / len(x)


def dispersion(x):
    assert len(x) > 0
    d = 0
    e = expected_value(x)
    for x_i in x:
        d += (x_i - e) ** 2
    return d / len(x)

In [18]:
def expected_value_np(x):
    return np.mean(x)

In [19]:
def dispersion_np(x):
    return np.var(x)

In [20]:
np.testing.assert_array_equal(expected_value([1]), expected_value_np(np.array([1])))
np.testing.assert_array_equal(expected_value([3, 4]), expected_value_np(np.array([3, 4])))
np.testing.assert_array_equal(expected_value([-1, 0, 1]), expected_value_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(expected_value([-99, -98]), expected_value_np(np.array([-99, -98])))

np.testing.assert_array_equal(dispersion([1]), dispersion_np(np.array([1])))
np.testing.assert_array_equal(dispersion([3, 4]), dispersion_np(np.array([3, 4])))
np.testing.assert_array_equal(dispersion([-1, 0, 1]), dispersion_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(dispersion([-99, -98]), dispersion_np(np.array([-99, -98])))

Задание 17.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое квадратов разностей их значений

In [21]:
def mean_square_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    # Здесь и далее эти проверки !не нужно! дублировать в свои функции; Здесь они для того, чтобы лишний раз подчеркнуть валидность входных данных
    s = 0
    for i in range(len(y1)):
        s += (y1[i] - y2[i]) ** 2
    return s / len(y1)

In [18]:
def mean_square_difference_np(y1, y2):
    return ((y1 - y2) ** 2).mean()

In [25]:
assert mean_square_difference([1], [1]) == mean_square_difference_np(np.array([1]), np.array([1]))
assert mean_square_difference([1, 2], [1, 2]) == mean_square_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_square_difference([-1, 1], [0, 0]) == mean_square_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_square_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_square_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 18.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое модулей разностей их значений

In [27]:
def mean_abs_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    s = 0
    for i in range(len(y1)):
        s += abs(y1[i] - y2[i])
    return s / len(y1)

In [29]:
def mean_abs_difference_np(y1, y2):
    return np.absolute(y1 - y2).mean()

In [30]:
assert mean_abs_difference([1], [1]) == mean_abs_difference_np(np.array([1]), np.array([1]))
assert mean_abs_difference([1, 2], [1, 2]) == mean_abs_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_abs_difference([-1, 1], [0, 0]) == mean_abs_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_abs_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_abs_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 19.

Даны два вектора $y_1$ и $y_2$, в которых присутствуют только $0$ и $1$. Необходимо посчитать вероятность совпадения - в скольких точках значения двух векторов совпадают

In [33]:
def matching_proba(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    assert len(set(y1)) <= 2
    assert len(set(y2)) <= 2
    assert 0 in set(y1) or 1 in set(y1) or (0 in set(y1) and 1 in set(y1))
    assert 0 in set(y2) or 1 in set(y2) or (0 in set(y2) and 1 in set(y2))

    return sum([y1[i] == y2[i] for i in range(len(y1))]) / len(y1)

In [36]:
def matching_proba_np(y1, y2):
    return (y1 == y2).astype(int).mean()

In [37]:
np.testing.assert_array_equal(matching_proba([0, 1], [1, 0]), matching_proba_np(np.array([0, 1]), np.array([1, 0])))
np.testing.assert_array_equal(matching_proba([0, 1, 0, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 1, 0, 1]), np.array([0, 0, 1, 1])))
np.testing.assert_array_equal(matching_proba([0, 0, 1, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1])))

Задание 20.

Даны два вектора: $y_1$, $y_2$. В $y_1$ и $y_2$ присутствуют только $0$ и $1$.

Необходимо найти границы (индексы), такие, что если мы разделим вдоль какой-то из этих границ оба вектора на две части, то
* в левой части пересекающихся в $y_1$ и $y_2$ нулей будет строго больше, чем пересекающихся единиц или непересекающихся элементов
* в правой - пересекающихся единиц строго больше, чем пересекающихся нулей или непересекающихся элементов.

Если какая-то из частей не содержит элементов вовсе, то будем считать, что она подходит под условие.

In [21]:
def find_thresholds(y1, y2, debug=False):
    assert len(y1) == len(y2) and len(y1) > 0
    n = len(y1)
    matching_zeros = [1 if y1[i] == y2[i] == 0 else 0 for i in range(n)]
    matching_ones = [1 if y1[i] == y2[i] == 1 else 0 for i in range(n)]
    res = []
    if sum(matching_ones) / n > 0.5:
        res.append(0)
    for i in range(1, n):
        if debug: # если вам непонятна логика работы этой функции, передайте третьим аргументом True
            print(matching_zeros[:i], matching_ones[i:], i)
        if sum(matching_zeros[:i]) / i > 0.5 and sum(matching_ones[i:]) / (n - i) > 0.5:
            res.append(i)
    if sum(matching_zeros) / n > 0.5:
        res.append(n)
    return res

In [19]:
def find_thresholds_np(y1, y2):
    matching_zeros = np.array((y1 == y2) & (y1 == 0)).astype(int)
    matching_ones = np.array((y1 == y2) & (y1 == 1)).astype(int)

    res = []
    if matching_ones.mean() > 0.5:
        res.append(0)
    for i in range(1, y1.shape[0]):
        if matching_zeros[:i].mean() > 0.5 and matching_ones[i:].mean() > 0.5:
            res.append(i)
    if matching_zeros.mean() > 0.5:
        res.append(y1.shape[0])
    return res


In [22]:
np.testing.assert_array_equal(find_thresholds([0], [0]), find_thresholds_np(np.array([0]), np.array([0])))
np.testing.assert_array_equal(find_thresholds([1], [1]), find_thresholds_np(np.array([1]), np.array([1])))
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 1], [0, 0, 1, 1]), 
    find_thresholds_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1]))
)
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 0, 0, 1, 1, 1], [0, 0, 0, 0, 0, 1, 1, 1]),
    find_thresholds_np(np.array([0, 0, 1, 0, 0, 1, 1, 1]), np.array([0, 0, 0, 0, 0, 1, 1, 1]))
)

### Разные действия с матрицами (3 балла)

Задание 21.

Дана матрица размера $(32, 3, 16, 16)$, заполненная случайными числами от 0 до 9. При помощи **ровно двух** преобразований приведите её к виду $(32, 1)$. При выполнении задания **можно** создавать вспомогательные матрицы!

In [72]:
data = np.random.randint(0, 10, size=(32, 3, 16, 16))

# Преобразование 1
data = np.vstack((data[2], data[3]))
print(data.shape)
print(np.dot(data[2], data[3]).shape)
# Преобразование 2
data = np.dot(data[0], data[1])
print(data.shape)

assert data.shape == (32, 1)

(6, 16, 16)
(16, 16)
(1536,)


AssertionError: 

Задание 22.

Даны две матрицы $m_1$ размером $(32, 256)$ и $m_2$ размером $(32, 512)$, а также две вспомогательные матрицы $W_1$ размером $(256, 32)$ и $W_2$ размером $(512, 16)$. Используя **все** данные матрицы, сделайте так, чтобы на выходе получилась **ровно одна** матрица размером $(32, 32)$

In [ ]:
m1 = np.random.randint(0, 10, size=(32, 256))
m2 = np.random.randint(0, 10, size=(32, 512))
W1 = np.random.randint(0, 10, size=(256, 32))
W2 = np.random.randint(0, 10, size=(512, 16))

result = # Ваш код

assert result.shape == (32, 32)

Задание 23.

Приведите полученную на последнем шаге матрицу к виду $(32, 3)$ и сделайте так, чтобы все значения в этой матрице были в промежутке от $0$ до $1$

In [ ]:
# Вжух! (∩｀-´)⊃━☆ﾟ.*･｡ﾟ
result = # Ваш код

assert result.shape == (32, 3)
assert ((result >= 0) & (result <= 1)).all()