## Домашнее задание

В этой тетрадке вам предлагается реализовать задания при помощи библиотеки numpy. Крайне желательно при выполнении разных заданий не использовать циклы. Если вы не понимаете, как выполнить конкретную задачу без циклов - убирайте их постепенно, разбейте выполнение задачи на этапы и постепенно векторизуйте каждый этап.

Если вам непонятно, как выполнить ту или иную операцию - не стесняйтесь гуглить, если над вами повис дедлайн, а вы всё ещё на чём-то застряли - пишите преподу/в чат, это ок.

**Обсудить решение лучше и сделать в итоге хоть что-то гораздо лучше, чем скатать чужой код или сдать пустую тетрадку.**

In [154]:
import numpy as np

### Drill (1 балл)

Задание 1.

Инициализируйте нулями массивы следующих форм:

* (5)
* (5, 1)
* (10, 2)
* (3, 6, 2)
* (4, 3, 2, 1)

In [155]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [156]:
np.zeros((5, 1))

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [157]:
np.zeros((10, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [158]:
np.zeros((3, 6, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [159]:
np.zeros((4, 3, 2, 1))

array([[[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]],


       [[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]],


       [[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]],


       [[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]]])

Задание 2.

Инициализируйте единицами массивы таких же форм и приведите их к целочисленному виду:

In [160]:
np.ones(5, dtype=int)

array([1, 1, 1, 1, 1])

In [161]:
np.ones((5, 1), dtype=int)

array([[1],
       [1],
       [1],
       [1],
       [1]])

In [162]:
np.ones((10, 2), dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [163]:
np.ones((3, 6, 2), dtype=int)

array([[[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]])

In [164]:
np.ones((4, 3, 2, 1), dtype=int)

array([[[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]],


       [[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]],


       [[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]],


       [[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]]])

Задание 3.

Выполните для векторов выше `reshape` в "форму"
* с двумя компонентами
* с тремя компонентами
* с четырьмя компонентами

In [165]:
np.ones(5, dtype=int).reshape((5, 1))

array([[1],
       [1],
       [1],
       [1],
       [1]])

In [166]:
np.ones(5, dtype=int).reshape((5, 1, 1))

array([[[1]],

       [[1]],

       [[1]],

       [[1]],

       [[1]]])

In [167]:
np.ones(5, dtype=int).reshape((5, 1, 1, 1))

array([[[[1]]],


       [[[1]]],


       [[[1]]],


       [[[1]]],


       [[[1]]]])

In [168]:
np.ones((5, 1), dtype=int).reshape((5, 1))

array([[1],
       [1],
       [1],
       [1],
       [1]])

In [169]:
np.ones((5, 1), dtype=int).reshape((5, 1, 1))

array([[[1]],

       [[1]],

       [[1]],

       [[1]],

       [[1]]])

In [170]:
np.ones((5, 1), dtype=int).reshape((5, 1, 1, 1))

array([[[[1]]],


       [[[1]]],


       [[[1]]],


       [[[1]]],


       [[[1]]]])

In [171]:
np.ones((10, 2), dtype=int).reshape((5, 4))

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [172]:
np.ones((10, 2), dtype=int).reshape((5, 2, 2))

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [173]:
np.ones((10, 2), dtype=int).reshape((5, 2, 2, 1))

array([[[[1],
         [1]],

        [[1],
         [1]]],


       [[[1],
         [1]],

        [[1],
         [1]]],


       [[[1],
         [1]],

        [[1],
         [1]]],


       [[[1],
         [1]],

        [[1],
         [1]]],


       [[[1],
         [1]],

        [[1],
         [1]]]])

In [174]:
np.ones((3, 6, 2), dtype=int).reshape((9, 4))

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [175]:
np.ones((3, 6, 2), dtype=int).reshape((3, 3, 4))

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [176]:
np.ones((3, 6, 2), dtype=int).reshape((3, 3, 2, 2))

array([[[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]]])

In [177]:
np.ones((4, 3, 2, 1), dtype=int).reshape((12, 2))

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [178]:
np.ones((4, 3, 2, 1), dtype=int).reshape((3, 4, 2))

array([[[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]])

In [179]:
np.ones((4, 3, 2, 1), dtype=int).reshape((3, 2, 2, 2))

array([[[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]]])

Задание 4.

Для вектора ниже посчитайте его
* Максимум по 1 оси
* Минимум по 0 оси
* Сумму по всем осям
* Среднее по 0 оси
* Медиану по 1 оси

In [180]:
v = np.random.randint(0, 9, size=(5, 7))

In [181]:
v.max(axis=1)

array([7, 8, 8, 7, 8])

In [182]:
v.min(axis=0)

array([0, 0, 1, 0, 1, 0, 1])

In [183]:
v.sum(axis=(0, 1))

133

In [184]:
np.average(v, axis=0)

array([3.8, 3.8, 5. , 1.6, 3.2, 3.6, 5.6])

In [185]:
np.median(v, axis=1)

array([5., 6., 4., 1., 3.])

Задание 5.

Для всё того же вектора `v` выведите
* Его shape
* 0 компоненту его "формы"
* 1 компоненту его "формы"

In [186]:
v.shape

(5, 7)

In [187]:
v.shape[0]

5

In [188]:
v.shape[1]

7

Задание 6.

Для этого же вектора выведите
* Все числа больше 5
* Все числа меньше 7 в обратном порядке
* Все числа больше 3, которые делятся на 4 без остатка
* Все числа, остаток от деления на 5 которых равен 3
* Индекс максимума
* Индекс минимума
* Cписок с индексами элементов отсортированного массива в исходном (неотсортированном)

In [189]:
v[v > 5]

array([7, 6, 7, 8, 7, 6, 8, 8, 8, 6, 6, 7, 8])

In [190]:
np.flip(v[v < 7])

array([3, 4, 1, 5, 0, 0, 1, 0, 1, 0, 6, 1, 6, 2, 4, 0, 3, 6, 1, 1, 3, 5,
       6, 0, 4, 2])

In [191]:
v[(v > 3) & (v % 4 == 0)]

array([4, 8, 8, 8, 8, 4, 4, 8])

In [192]:
v.argmax()

7

In [193]:
v.argmin()

3

In [194]:
v.argsort()

array([[3, 1, 2, 6, 4, 0, 5],
       [2, 4, 1, 5, 3, 0, 6],
       [3, 5, 0, 4, 6, 1, 2],
       [3, 5, 0, 4, 6, 1, 2],
       [0, 1, 3, 5, 4, 2, 6]], dtype=int64)

Задание 7.

Выполните следующие операции над вектором (независимо, не обязательно делать это в последовательности):
* Умножьте его на 3
* Разделите на 7
* Возведите в степень $\frac{2}{3}$
* Посчитайте $\sin$ от него
* Посчитайте $\log$ от него

In [195]:
v * 3

array([[21,  6, 12,  0, 18, 21, 15],
       [24,  9,  3, 21,  3, 18, 24],
       [ 9, 24, 24,  0, 12,  6, 18],
       [ 3, 18, 21,  0,  3,  0,  3],
       [ 0,  0, 15,  3, 12,  9, 24]])

In [196]:
v / 7

array([[1.        , 0.28571429, 0.57142857, 0.        , 0.85714286,
        1.        , 0.71428571],
       [1.14285714, 0.42857143, 0.14285714, 1.        , 0.14285714,
        0.85714286, 1.14285714],
       [0.42857143, 1.14285714, 1.14285714, 0.        , 0.57142857,
        0.28571429, 0.85714286],
       [0.14285714, 0.85714286, 1.        , 0.        , 0.14285714,
        0.        , 0.14285714],
       [0.        , 0.        , 0.71428571, 0.14285714, 0.57142857,
        0.42857143, 1.14285714]])

In [197]:
v ** (2 / 3)

array([[3.65930571, 1.58740105, 2.5198421 , 0.        , 3.30192725,
        3.65930571, 2.92401774],
       [4.        , 2.08008382, 1.        , 3.65930571, 1.        ,
        3.30192725, 4.        ],
       [2.08008382, 4.        , 4.        , 0.        , 2.5198421 ,
        1.58740105, 3.30192725],
       [1.        , 3.30192725, 3.65930571, 0.        , 1.        ,
        0.        , 1.        ],
       [0.        , 0.        , 2.92401774, 1.        , 2.5198421 ,
        2.08008382, 4.        ]])

In [198]:
np.sin(v)

array([[ 0.6569866 ,  0.90929743, -0.7568025 ,  0.        , -0.2794155 ,
         0.6569866 , -0.95892427],
       [ 0.98935825,  0.14112001,  0.84147098,  0.6569866 ,  0.84147098,
        -0.2794155 ,  0.98935825],
       [ 0.14112001,  0.98935825,  0.98935825,  0.        , -0.7568025 ,
         0.90929743, -0.2794155 ],
       [ 0.84147098, -0.2794155 ,  0.6569866 ,  0.        ,  0.84147098,
         0.        ,  0.84147098],
       [ 0.        ,  0.        , -0.95892427,  0.84147098, -0.7568025 ,
         0.14112001,  0.98935825]])

In [199]:
np.log(v)

C:\Users\poisk\AppData\Local\Temp\ipykernel_3640\3686484441.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(v)


array([[1.94591015, 0.69314718, 1.38629436,       -inf, 1.79175947,
        1.94591015, 1.60943791],
       [2.07944154, 1.09861229, 0.        , 1.94591015, 0.        ,
        1.79175947, 2.07944154],
       [1.09861229, 2.07944154, 2.07944154,       -inf, 1.38629436,
        0.69314718, 1.79175947],
       [0.        , 1.79175947, 1.94591015,       -inf, 0.        ,
              -inf, 0.        ],
       [      -inf,       -inf, 1.60943791, 0.        , 1.38629436,
        1.09861229, 2.07944154]])

### Разные инициализации + индексирование (3 балла)

Задание 8.

Необходимо построить квадрат $3 \times 3$ из нечётных чисел

In [200]:
a = np.arange(1, 18, 2)
a.reshape((3, 3))

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

Задание 9.

Необходимо построить квадрат $4 \times 4$ из четных чисел в обратном порядке

In [201]:
b = np.arange(30, -1, -2)
b.reshape((4, 4))

array([[30, 28, 26, 24],
       [22, 20, 18, 16],
       [14, 12, 10,  8],
       [ 6,  4,  2,  0]])

Задание 10.

Необходимо построить сетку координат $11 \times 11$ с точкой $(0,0)$ в центре и шагом $0.1$ между клетками

In [202]:
arr1 = np.linspace(-0.5, 0.5, 11)
arr2 = np.zeros((11, 11), [('x', float), ('y', float)])
arr2['x'], arr2['y'] = np.meshgrid(arr1, arr1)
arr2

array([[(-0.5, -0.5), (-0.4, -0.5), (-0.3, -0.5), (-0.2, -0.5),
        (-0.1, -0.5), ( 0. , -0.5), ( 0.1, -0.5), ( 0.2, -0.5),
        ( 0.3, -0.5), ( 0.4, -0.5), ( 0.5, -0.5)],
       [(-0.5, -0.4), (-0.4, -0.4), (-0.3, -0.4), (-0.2, -0.4),
        (-0.1, -0.4), ( 0. , -0.4), ( 0.1, -0.4), ( 0.2, -0.4),
        ( 0.3, -0.4), ( 0.4, -0.4), ( 0.5, -0.4)],
       [(-0.5, -0.3), (-0.4, -0.3), (-0.3, -0.3), (-0.2, -0.3),
        (-0.1, -0.3), ( 0. , -0.3), ( 0.1, -0.3), ( 0.2, -0.3),
        ( 0.3, -0.3), ( 0.4, -0.3), ( 0.5, -0.3)],
       [(-0.5, -0.2), (-0.4, -0.2), (-0.3, -0.2), (-0.2, -0.2),
        (-0.1, -0.2), ( 0. , -0.2), ( 0.1, -0.2), ( 0.2, -0.2),
        ( 0.3, -0.2), ( 0.4, -0.2), ( 0.5, -0.2)],
       [(-0.5, -0.1), (-0.4, -0.1), (-0.3, -0.1), (-0.2, -0.1),
        (-0.1, -0.1), ( 0. , -0.1), ( 0.1, -0.1), ( 0.2, -0.1),
        ( 0.3, -0.1), ( 0.4, -0.1), ( 0.5, -0.1)],
       [(-0.5,  0. ), (-0.4,  0. ), (-0.3,  0. ), (-0.2,  0. ),
        (-0.1,  0. ), ( 0. ,  0. ), ( 0.1

Задание 11.

Замощение сетки $8\times8$ при помощи $0$ и $1$ в шахматном порядке, клетка с индексом $(0,0)$ замощается $1$

In [203]:
def f(i, j):
    return (i + j) % 2


np.fromfunction(f, (8, 8))

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

Задание 12.

То же замощение, но клетка с индексом $(0,0)$ замощается $0$

In [204]:
def f(i, j):
    return (i + j + 1) % 2


np.fromfunction(f, (8, 8))

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

Задание 13.

Необходимо построить нижне-треугольную матрицу переменного размера (задается передачей параметра в функцию). Это единичная матрица,замощённая $1$ под главной диагональю

In [205]:
n = int(input())


def f(i, j):
    return (n - i) + j


a = np.fromfunction(f, (n, n))
a = np.where(a <= n, 1, a)
np.where(a >= n, 0, a)

array([[1., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1., 1.]])

Задание 14.

Необходимо построить верхне-треугольную матрицу переменного размера. Это единичная матрица, замощённая $1$ над главной диагональю

In [206]:
n = int(input())


def f(i, j):
    return (n - i) + j


a = np.fromfunction(f, (n, n))
a = np.where(a < n, 0, a)
np.where(a >= n, 1, a)

array([[1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1.]])

Задание 15.

Необходимо построить матрицу, в которой единицы стоят на побочной диагонали (идущей из левого нижнего угла в правый верхний), в остальных местах стоят $0$

In [207]:
n = int(input())

a = np.fromfunction(lambda i, j: i + j == n - 1, (n, n))
a.astype(int)

array([[0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0]])

### Операции + аггрегации (3 балла)

Задание 16.

Дана выборка $\{X_i\}$ некоторой случайной величины $X$, необходимо оценить
* Математическое ожидание $E[X] = \frac{1}{N}\sum_{i=1}^N X_i$ этой случайной величины
* Дисперсию $D[X] = \frac{1}{N}\sum_{i=1}^N (X_i - E[X])^2$ этой случайной величины

In [208]:
def expected_value(x):
    assert len(x) > 0
    return sum(x) / len(x)


def dispersion(x):
    assert len(x) > 0
    d = 0
    e = expected_value(x)
    for x_i in x:
        d += (x_i - e) ** 2
    return d / len(x)

In [209]:
def expected_value_np(x):
    return sum(x) / len(x)

In [210]:
def dispersion_np(x):
    return np.var(x)

In [211]:
np.testing.assert_array_equal(expected_value([1]), expected_value_np(np.array([1])))
np.testing.assert_array_equal(expected_value([3, 4]), expected_value_np(np.array([3, 4])))
np.testing.assert_array_equal(expected_value([-1, 0, 1]), expected_value_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(expected_value([-99, -98]), expected_value_np(np.array([-99, -98])))

np.testing.assert_array_equal(dispersion([1]), dispersion_np(np.array([1])))
np.testing.assert_array_equal(dispersion([3, 4]), dispersion_np(np.array([3, 4])))
np.testing.assert_array_equal(dispersion([-1, 0, 1]), dispersion_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(dispersion([-99, -98]), dispersion_np(np.array([-99, -98])))

Задание 17.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое квадратов разностей их значений

In [212]:
def mean_square_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    # Здесь и далее эти проверки !не нужно! дублировать в свои функции; Здесь они для того, чтобы лишний раз подчеркнуть валидность входных данных
    s = 0
    for i in range(len(y1)):
        s += (y1[i] - y2[i]) ** 2
    return s / len(y1)

In [213]:
def mean_square_difference_np(y1, y2):
    arr = (y1 - y2) ** 2
    return np.sum(arr) / len(y1)

In [214]:
assert mean_square_difference([1], [1]) == mean_square_difference_np(np.array([1]), np.array([1]))
assert mean_square_difference([1, 2], [1, 2]) == mean_square_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_square_difference([-1, 1], [0, 0]) == mean_square_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_square_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_square_difference_np(
    np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 18.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое модулей разностей их значений

In [215]:
def mean_abs_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    s = 0
    for i in range(len(y1)):
        s += abs(y1[i] - y2[i])
    return s / len(y1)

In [216]:
def mean_abs_difference_np(y1, y2):
    arr = abs(y1 - y2)

    return np.sum(arr) / len(y1)


In [217]:
assert mean_abs_difference([1], [1]) == mean_abs_difference_np(np.array([1]), np.array([1]))
assert mean_abs_difference([1, 2], [1, 2]) == mean_abs_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_abs_difference([-1, 1], [0, 0]) == mean_abs_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_abs_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_abs_difference_np(
    np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 19.

Даны два вектора $y_1$ и $y_2$, в которых присутствуют только $0$ и $1$. Необходимо посчитать вероятность совпадения - в скольких точках значения двух векторов совпадают

In [218]:
def matching_proba(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    assert len(set(y1)) <= 2
    assert len(set(y2)) <= 2
    assert 0 in set(y1) or 1 in set(y1) or (0 in set(y1) and 1 in set(y1))
    assert 0 in set(y2) or 1 in set(y2) or (0 in set(y2) and 1 in set(y2))

    return sum([y1[i] == y2[i] for i in range(len(y1))]) / len(y1)

In [219]:
def matching_proba_np(y1, y2):
    return np.count_nonzero(y1 == y2) / len(y1)


In [220]:
np.testing.assert_array_equal(matching_proba([0, 1], [1, 0]), matching_proba_np(np.array([0, 1]), np.array([1, 0])))
np.testing.assert_array_equal(matching_proba([0, 1, 0, 1], [0, 0, 1, 1]),
                              matching_proba_np(np.array([0, 1, 0, 1]), np.array([0, 0, 1, 1])))
np.testing.assert_array_equal(matching_proba([0, 0, 1, 1], [0, 0, 1, 1]),
                              matching_proba_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1])))

Задание 20.

Даны два вектора: $y_1$, $y_2$. В $y_1$ и $y_2$ присутствуют только $0$ и $1$.

Необходимо найти границы (индексы), такие, что если мы разделим вдоль какой-то из этих границ оба вектора на две части, то
* в левой части пересекающихся в $y_1$ и $y_2$ нулей будет строго больше, чем пересекающихся единиц или непересекающихся элементов
* в правой - пересекающихся единиц строго больше, чем пересекающихся нулей или непересекающихся элементов.

Если какая-то из частей не содержит элементов вовсе, то будем считать, что она подходит под условие.

In [221]:
def find_thresholds(y1, y2, debug=False):
    assert len(y1) == len(y2) and len(y1) > 0
    n = len(y1)
    matching_zeros = [1 if y1[i] == y2[i] == 0 else 0 for i in range(n)]
    matching_ones = [1 if y1[i] == y2[i] == 1 else 0 for i in range(n)]
    res = []
    if sum(matching_ones) / n > 0.5:
        res.append(0)
    for i in range(1, n):
        if debug:  # если вам непонятна логика работы этой функции, передайте третьим аргументом True
            print(matching_zeros[:i], matching_ones[i:], i)
        if sum(matching_zeros[:i]) / i > 0.5 and sum(matching_ones[i:]) / (n - i) > 0.5:
            res.append(i)
    if sum(matching_zeros) / n > 0.5:
        res.append(n)
    return res

In [222]:
def find_thresholds_np(y1, y2):
    arr_zeros = ((y1 == y2) & (y2 == 0)).astype(int)
    arr_ones = ((y1 == y2) & (y2 == 1)).astype(int)

    arr1 = np.flip(arr_ones)
    arr1 = arr1.cumsum()
    arr1 = np.flip(arr1)
    arr1 = arr1[1:]
    arr2 = arr_zeros.cumsum()
    arr2 = arr2[:-1]
    arr3 = np.arange(1, len(y1)).astype(int)
    arr2 = arr2 / arr3
    arr1 = arr1 / np.flip(arr3)
    res = arr3[(arr2 > 0.5) & (arr1 > 0.5)]
    if arr_ones.mean() > 0.5:
        res = np.concatenate(([0], res))
    if arr_zeros.mean() > 0.5:
        res = np.concatenate((res, [len(y1)]))
    return res

In [223]:
np.testing.assert_array_equal(find_thresholds([0], [0]), find_thresholds_np(np.array([0]), np.array([0])))
np.testing.assert_array_equal(find_thresholds([1], [1]), find_thresholds_np(np.array([1]), np.array([1])))
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 1], [0, 0, 1, 1]),
    find_thresholds_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1]))
)
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 0, 0, 1, 1, 1], [0, 0, 0, 0, 0, 1, 1, 1]),
    find_thresholds_np(np.array([0, 0, 1, 0, 0, 1, 1, 1]), np.array([0, 0, 0, 0, 0, 1, 1, 1]))
)

### Разные действия с матрицами (3 балла)

Задание 21.

Дана матрица размера $(32, 3, 16, 16)$, заполненная случайными числами от 0 до 9. При помощи **ровно двух** преобразований приведите её к виду $(32, 1)$. При выполнении задания **можно** создавать вспомогательные матрицы!

In [224]:
data = np.random.randint(0, 10, size=(32, 3, 16, 16))

data = data.reshape(32, 3 * 16 * 16)
data = np.matmul(data, np.arange(0, 3 * 16 * 16).reshape(3 * 16 * 16, 1))

assert data.shape == (32, 1)

Задание 22.

Даны две матрицы $m_1$ размером $(32, 256)$ и $m_2$ размером $(32, 512)$, а также две вспомогательные матрицы $W_1$ размером $(256, 32)$ и $W_2$ размером $(512, 16)$. Используя **все** данные матрицы, сделайте так, чтобы на выходе получилась **ровно одна** матрица размером $(32, 32)$

In [226]:
m1 = np.random.randint(0, 10, size=(32, 256))
m2 = np.random.randint(0, 10, size=(32, 512))
W1 = np.random.randint(0, 10, size=(256, 32))
W2 = np.random.randint(0, 10, size=(512, 16))

W1 = W1.reshape((32, 256))
W2 = W2.reshape((32, 256))

W_new = np.concatenate((W1, W2), axis=1)
W_new = np.concatenate((W_new, m1), axis=1)
W_new = np.concatenate((W_new, m1), axis=1)
m_new = np.concatenate((m2, m2), axis=1)
m_new = m_new.reshape(1024, 32)
result = np.matmul(W_new, m_new)
assert result.shape == (32, 32)

Задание 23.

Приведите полученную на последнем шаге матрицу к виду $(32, 3)$ и сделайте так, чтобы все значения в этой матрице были в промежутке от $0$ до $1$

In [ ]:
z = np.ones((32, 3))
result = np.matmul(result, z)
result = result / result.max()
assert result.shape == (32, 3)
assert ((result >= 0) & (result <= 1)).all()