## Домашнее задание

В этой тетрадке вам предлагается реализовать задания при помощи библиотеки numpy. Крайне желательно при выполнении разных заданий не использовать циклы. Если вы не понимаете, как выполнить конкретную задачу без циклов - убирайте их постепенно, разбейте выполнение задачи на этапы и постепенно векторизуйте каждый этап.

Если вам непонятно, как выполнить ту или иную операцию - не стесняйтесь гуглить, если над вами повис дедлайн, а вы всё ещё на чём-то застряли - пишите преподу/в чат, это ок.

**Обсудить решение лучше и сделать в итоге хоть что-то гораздо лучше, чем скатать чужой код или сдать пустую тетрадку.**

In [230]:
import numpy as np

### Drill (1 балл)

Задание 1.

Инициализируйте нулями массивы следующих форм:

* (5)
* (5, 1)
* (10, 2)
* (3, 6, 2)
* (4, 3, 2, 1)

In [231]:
np.zeros(5)
np.zeros((5, 1))
np.zeros((10, 2))
np.zeros((3, 6, 2))
np.zeros((4, 3, 2, 1))

array([[[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]],


       [[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]],


       [[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]],


       [[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]]])

Задание 2.

Инициализируйте единицами массивы таких же форм и приведите их к целочисленному виду:

In [232]:
array5 = np.ones(5).astype(int)
array51 = np.ones((5, 1)).astype(int)
array102 = np.ones((10, 2)).astype(int)
array362 = np.ones((3, 6, 2)).astype(int)
array4321 = np.ones((4, 3, 2, 1)).astype(int)
array4321

array([[[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]],


       [[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]],


       [[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]],


       [[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]]])

Задание 3.

Выполните для векторов выше `reshape` в "форму"
* с двумя компонентами
* с тремя компонентами
* с четырьмя компонентами

In [233]:
array362 = array362.reshape(-1, 2)
array102 = array102.reshape(-1, 2)
array4321 = array4321.reshape(-1, 2)
array362 = array362.reshape(-1, 3)
array4321 = array4321.reshape(-1, 3)
array362 = array362.reshape(-1, 4)
array102 = array102.reshape(-1, 4)
array4321 = array4321.reshape(-1, 4)
display(array4321)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

Задание 4.

Для вектора ниже посчитайте его
* Максимум по 1 оси
* Минимум по 0 оси
* Сумму по всем осям
* Среднее по 0 оси
* Медиану по 1 оси

In [234]:
v = np.random.randint(0, 9, size=(5, 7))
v

array([[6, 2, 7, 0, 3, 7, 3],
       [2, 3, 3, 5, 0, 1, 5],
       [2, 8, 0, 0, 4, 0, 3],
       [2, 0, 2, 5, 5, 7, 6],
       [4, 2, 8, 7, 4, 5, 2]])

In [236]:
display(v.max(axis=1))
display(v.min(axis=0))
display(v.sum())
display(v.mean(axis=0))
display(np.median(v, axis=1))

array([7, 5, 8, 7, 8])

array([2, 0, 0, 0, 0, 0, 2])

123

array([3.2, 3. , 4. , 3.4, 3.2, 4. , 3.8])

array([3., 3., 2., 5., 4.])

Задание 5.

Для всё того же вектора `v` выведите
* Его shape
* 0 компоненту его "формы"
* 1 компоненту его "формы"

In [237]:
display(v.shape)
display(v.shape[0])
display(v.shape[1])

(5, 7)

5

7

Задание 6.

Для этого же вектора выведите
* Все числа больше 5
* Все числа меньше 7 в обратном порядке
* Все числа больше 3, которые делятся на 4 без остатка
* Все числа, остаток от деления на 5 которых равен 3
* Индекс максимума
* Индекс минимума
* Cписок с индексами элементов отсортированного массива в исходном (неотсортированном)

In [239]:
print("Все числа больше 5")
display(v[v > 5])
print('Все числа меньше 7 в обратном порядке')
display(v[v < 7][::-1])
print('Все числа больше 3, которые делятся на 4 без остатка')
display(v[(v > 3) & (v % 4 == 0)])
print('Все числа, остаток от деления на 5 которых равен 3')
display(v[(v % 5 == 3)])
print("max =", v.argmin(),"\nmin =", v.argmax())
display(v.argsort(axis=None))

Все числа больше 5


array([6, 7, 7, 8, 7, 6, 8, 7])

Все числа меньше 7 в обратном порядке


array([2, 5, 4, 2, 4, 6, 5, 5, 2, 0, 2, 3, 0, 4, 0, 0, 2, 5, 1, 0, 5, 3,
       3, 2, 3, 3, 0, 2, 6])

Все числа больше 3, которые делятся на 4 без остатка


array([8, 4, 4, 8, 4])

Все числа, остаток от деления на 5 которых равен 3


array([3, 3, 3, 3, 8, 3, 8])

max = 3 
min = 15


array([17,  3, 22, 19, 16, 11, 12, 29, 23, 21, 14, 34,  7,  1,  9,  8,  6,
       20,  4, 32, 18, 28, 13, 33, 10, 24, 25,  0, 27, 26,  5, 31,  2, 30,
       15])

Задание 7.

Выполните следующие операции над вектором (независимо, не обязательно делать это в последовательности):
* Умножьте его на 3
* Разделите на 7
* Возведите в степень $\frac{2}{3}$
* Посчитайте $\sin$ от него
* Посчитайте $\log$ от него

In [241]:
display(v * 3)
print(v / 7)
display(v ** (2 / 3))
print(np.sin(v))
display(np.log(v))

array([[18,  6, 21,  0,  9, 21,  9],
       [ 6,  9,  9, 15,  0,  3, 15],
       [ 6, 24,  0,  0, 12,  0,  9],
       [ 6,  0,  6, 15, 15, 21, 18],
       [12,  6, 24, 21, 12, 15,  6]])

[[0.85714286 0.28571429 1.         0.         0.42857143 1.
  0.42857143]
 [0.28571429 0.42857143 0.42857143 0.71428571 0.         0.14285714
  0.71428571]
 [0.28571429 1.14285714 0.         0.         0.57142857 0.
  0.42857143]
 [0.28571429 0.         0.28571429 0.71428571 0.71428571 1.
  0.85714286]
 [0.57142857 0.28571429 1.14285714 1.         0.57142857 0.71428571
  0.28571429]]


array([[3.30192725, 1.58740105, 3.65930571, 0.        , 2.08008382,
        3.65930571, 2.08008382],
       [1.58740105, 2.08008382, 2.08008382, 2.92401774, 0.        ,
        1.        , 2.92401774],
       [1.58740105, 4.        , 0.        , 0.        , 2.5198421 ,
        0.        , 2.08008382],
       [1.58740105, 0.        , 1.58740105, 2.92401774, 2.92401774,
        3.65930571, 3.30192725],
       [2.5198421 , 1.58740105, 4.        , 3.65930571, 2.5198421 ,
        2.92401774, 1.58740105]])

[[-0.2794155   0.90929743  0.6569866   0.          0.14112001  0.6569866
   0.14112001]
 [ 0.90929743  0.14112001  0.14112001 -0.95892427  0.          0.84147098
  -0.95892427]
 [ 0.90929743  0.98935825  0.          0.         -0.7568025   0.
   0.14112001]
 [ 0.90929743  0.          0.90929743 -0.95892427 -0.95892427  0.6569866
  -0.2794155 ]
 [-0.7568025   0.90929743  0.98935825  0.6569866  -0.7568025  -0.95892427
   0.90929743]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in log
  """


array([[1.79175947, 0.69314718, 1.94591015,       -inf, 1.09861229,
        1.94591015, 1.09861229],
       [0.69314718, 1.09861229, 1.09861229, 1.60943791,       -inf,
        0.        , 1.60943791],
       [0.69314718, 2.07944154,       -inf,       -inf, 1.38629436,
              -inf, 1.09861229],
       [0.69314718,       -inf, 0.69314718, 1.60943791, 1.60943791,
        1.94591015, 1.79175947],
       [1.38629436, 0.69314718, 2.07944154, 1.94591015, 1.38629436,
        1.60943791, 0.69314718]])

### Разные инициализации + индексирование (3 балла)

Задание 8.

Необходимо построить квадрат $3 \times 3$ из нечётных чисел

In [242]:
np.arange(1, 18, 2).reshape(-1, 3)

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

Задание 9.

Необходимо построить квадрат $4 \times 4$ из четных чисел в обратном порядке

In [243]:
np.arange(32, 0, -2).reshape(-1, 4)

array([[32, 30, 28, 26],
       [24, 22, 20, 18],
       [16, 14, 12, 10],
       [ 8,  6,  4,  2]])

Задание 10.

Необходимо построить сетку координат $11 \times 11$ с точкой $(0,0)$ в центре и шагом $0.1$ между клетками

In [244]:
a = np.c_[np.tile(np.arange(-5, 6, 1)/10, 11), np.repeat(np.arange(5, -6, -1)/10, 11)]
a.reshape(11, 11, -1)

array([[[-0.5,  0.5],
        [-0.4,  0.5],
        [-0.3,  0.5],
        [-0.2,  0.5],
        [-0.1,  0.5],
        [ 0. ,  0.5],
        [ 0.1,  0.5],
        [ 0.2,  0.5],
        [ 0.3,  0.5],
        [ 0.4,  0.5],
        [ 0.5,  0.5]],

       [[-0.5,  0.4],
        [-0.4,  0.4],
        [-0.3,  0.4],
        [-0.2,  0.4],
        [-0.1,  0.4],
        [ 0. ,  0.4],
        [ 0.1,  0.4],
        [ 0.2,  0.4],
        [ 0.3,  0.4],
        [ 0.4,  0.4],
        [ 0.5,  0.4]],

       [[-0.5,  0.3],
        [-0.4,  0.3],
        [-0.3,  0.3],
        [-0.2,  0.3],
        [-0.1,  0.3],
        [ 0. ,  0.3],
        [ 0.1,  0.3],
        [ 0.2,  0.3],
        [ 0.3,  0.3],
        [ 0.4,  0.3],
        [ 0.5,  0.3]],

       [[-0.5,  0.2],
        [-0.4,  0.2],
        [-0.3,  0.2],
        [-0.2,  0.2],
        [-0.1,  0.2],
        [ 0. ,  0.2],
        [ 0.1,  0.2],
        [ 0.2,  0.2],
        [ 0.3,  0.2],
        [ 0.4,  0.2],
        [ 0.5,  0.2]],

       [[-0.5,  0.1],
  

Задание 11.

Замощение сетки $8\times8$ при помощи $0$ и $1$ в шахматном порядке, клетка с индексом $(0,0)$ замощается $1$

In [14]:
ox = np.arange(0, 8, 1).reshape(8, -1)
oy = np.arange(1, 9, 1).reshape(1, -1)
print((ox+oy)%2)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


Задание 12.

То же замощение, но клетка с индексом $(0,0)$ замощается $0$

In [15]:
np.tile(np.array([[0,1],[1,0]]), (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

Задание 13.

Необходимо построить нижне-треугольную матрицу переменного размера (задается передачей параметра в функцию). Это единичная матрица,замощённая $1$ под главной диагональю

In [245]:
def LowerTriangle(n=1):
  A = np.arange(0, n * n).reshape(n, n)
  return (A % n <= ( A // n)) % 2
LowerTriangle(5)

array([[1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1]])

Задание 14.

Необходимо построить верхне-треугольную матрицу переменного размера. Это единичная матрица, замощённая $1$ над главной диагональю

In [246]:
def LowerTriangle(n=1):
  A = np.arange(0, n * n).reshape(n, n)
  return (A % n >= ( A // n)) % 2
LowerTriangle(5)

array([[1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1],
       [0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1],
       [0, 0, 0, 0, 1]])

Задание 15.

Необходимо построить матрицу, в которой единицы стоят на побочной диагонали (идущей из левого нижнего угла в правый верхний), в остальных местах стоят $0$

In [18]:
def EyeTransposed(n=1):
  A = np.eye(n)
  return np.rot90(A)
EyeTransposed(5)

array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.]])

### Операции + аггрегации (3 балла)

Задание 16.

Дана выборка $\{X_i\}$ некоторой случайной величины $X$, необходимо оценить
* Математическое ожидание $E[X] = \frac{1}{N}\sum_{i=1}^N X_i$ этой случайной величины
* Дисперсию $D[X] = \frac{1}{N}\sum_{i=1}^N (X_i - E[X])^2$ этой случайной величины

In [247]:
def expected_value(x):
    assert len(x) > 0
    return sum(x) / len(x)


def dispersion(x):
    assert len(x) > 0
    d = 0
    e = expected_value(x)
    for x_i in x:
        d += (x_i - e) ** 2
    return d / len(x)

In [248]:
def expected_value_np(x):
    return np.mean(x)

In [249]:
def dispersion_np(x):
    return np.var(x)

In [250]:
np.testing.assert_array_equal(expected_value([1]), expected_value_np(np.array([1])))
np.testing.assert_array_equal(expected_value([3, 4]), expected_value_np(np.array([3, 4])))
np.testing.assert_array_equal(expected_value([-1, 0, 1]), expected_value_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(expected_value([-99, -98]), expected_value_np(np.array([-99, -98])))

np.testing.assert_array_equal(dispersion([1]), dispersion_np(np.array([1])))
np.testing.assert_array_equal(dispersion([3, 4]), dispersion_np(np.array([3, 4])))
np.testing.assert_array_equal(dispersion([-1, 0, 1]), dispersion_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(dispersion([-99, -98]), dispersion_np(np.array([-99, -98])))

Задание 17.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое квадратов разностей их значений

In [251]:
def mean_square_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    # Здесь и далее эти проверки !не нужно! дублировать в свои функции; Здесь они для того, чтобы лишний раз подчеркнуть валидность входных данных
    s = 0
    for i in range(len(y1)):
        s += (y1[i] - y2[i]) ** 2
    return s / len(y1)

In [252]:
def mean_square_difference_np(y1, y2):
    return (((y1-y2)**2).sum()) / len(y1)

In [253]:
assert mean_square_difference([1], [1]) == mean_square_difference_np(np.array([1]), np.array([1]))
assert mean_square_difference([1, 2], [1, 2]) == mean_square_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_square_difference([-1, 1], [0, 0]) == mean_square_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_square_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_square_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 18.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое модулей разностей их значений

In [254]:
def mean_abs_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    s = 0
    for i in range(len(y1)):
        s += abs(y1[i] - y2[i])
    return s / len(y1)

In [255]:
def mean_abs_difference_np(y1, y2):
    return abs(y1 - y2).sum() / len(y1)

In [256]:
assert mean_abs_difference([1], [1]) == mean_abs_difference_np(np.array([1]), np.array([1]))
assert mean_abs_difference([1, 2], [1, 2]) == mean_abs_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_abs_difference([-1, 1], [0, 0]) == mean_abs_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_abs_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_abs_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 19.

Даны два вектора $y_1$ и $y_2$, в которых присутствуют только $0$ и $1$. Необходимо посчитать вероятность совпадения - в скольких точках значения двух векторов совпадают

In [257]:
def matching_proba(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    assert len(set(y1)) <= 2
    assert len(set(y2)) <= 2
    assert 0 in set(y1) or 1 in set(y1) or (0 in set(y1) and 1 in set(y1))
    assert 0 in set(y2) or 1 in set(y2) or (0 in set(y2) and 1 in set(y2))

    return sum([y1[i] == y2[i] for i in range(len(y1))]) / len(y1)

In [258]:
def matching_proba_np(y1, y2):
    return  sum(y1 == y2) / len(y1)

In [259]:
np.testing.assert_array_equal(matching_proba([0, 1], [1, 0]), matching_proba_np(np.array([0, 1]), np.array([1, 0])))
np.testing.assert_array_equal(matching_proba([0, 1, 0, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 1, 0, 1]), np.array([0, 0, 1, 1])))
np.testing.assert_array_equal(matching_proba([0, 0, 1, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1])))

Задание 20.

Даны два вектора: $y_1$, $y_2$. В $y_1$ и $y_2$ присутствуют только $0$ и $1$.

Необходимо найти границы (индексы), такие, что если мы разделим вдоль какой-то из этих границ оба вектора на две части, то
* в левой части пересекающихся в $y_1$ и $y_2$ нулей будет строго больше, чем пересекающихся единиц или непересекающихся элементов
* в правой - пересекающихся единиц строго больше, чем пересекающихся нулей или непересекающихся элементов.

Если какая-то из частей не содержит элементов вовсе, то будем считать, что она подходит под условие.

In [260]:
def find_thresholds(y1, y2, debug=False):
    assert len(y1) == len(y2) and len(y1) > 0
    n = len(y1)
    matching_zeros = [1 if y1[i] == y2[i] == 0 else 0 for i in range(n)]
    matching_ones = [1 if y1[i] == y2[i] == 1 else 0 for i in range(n)]
    res = []
    if sum(matching_ones) / n > 0.5:
        res.append(0)
    for i in range(1, n):
        if debug: # если вам непонятна логика работы этой функции, передайте третьим аргументом True
            print(matching_zeros[:i], matching_ones[i:], i)
        if sum(matching_zeros[:i]) / i > 0.5 and sum(matching_ones[i:]) / (n - i) > 0.5:
            res.append(i)
    if sum(matching_zeros) / n > 0.5:
        res.append(n)
    return res

In [261]:
def find_thresholds_np(y1, y2):
    n = len(y1)
    # Массив где на i-ой позиции стоит число равное количеству нулей на отрезке [0,i+1) деленое на i+1 (не считаем только левую и только правые части)
    lookZerous = (np.arange(1, n + 1) - np.cumsum(y1 | y2))[:-1] / np.arange(1, n)
    # Массив где на i-ой позиции стоит число равное количеству единий на отрезке [i+1, n) деленое на n - i - 1 (не считаем только левую и только правые части)
    lookOnes = (max(np.cumsum(y1 & y2)) - np.cumsum(y1 & y2))[:-1] / np.arange(n - 1, 0, -1)
    # Берем удовлетворяющие двум условиям левому и правому
    answ_pred = ((lookZerous>0.5) & (lookOnes>0.5)) * np.arange(1, n)
    answ = list(answ_pred[answ_pred>0])
    # считаем, если только левая и только правая часть
    if (max(np.cumsum(y1 & y2))/n > 0.5):
        answ = [0]+answ
    if max(np.arange(1, n + 1) - np.cumsum(y1 | y2))/n > 0.5:
        answ += [n]
    return answ

In [262]:
np.testing.assert_array_equal(find_thresholds([0], [0]), find_thresholds_np(np.array([0]), np.array([0])))
np.testing.assert_array_equal(find_thresholds([1], [1]), find_thresholds_np(np.array([1]), np.array([1])))
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 1], [0, 0, 1, 1]), 
    find_thresholds_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1]))
)
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 0, 0, 1, 1, 1], [0, 0, 0, 0, 0, 1, 1, 1]),
    find_thresholds_np(np.array([0, 0, 1, 0, 0, 1, 1, 1]), np.array([0, 0, 0, 0, 0, 1, 1, 1]))
)

### Разные действия с матрицами (3 балла)

Задание 21.

Дана матрица размера $(32, 3, 16, 16)$, заполненная случайными числами от 0 до 9. При помощи **ровно двух** преобразований приведите её к виду $(32, 1)$. При выполнении задания **можно** создавать вспомогательные матрицы!

In [263]:
data = np.random.randint(0, 10, size=(32, 3, 16, 16))
b = np.random.randint(0, 10, size=(3 * 16 * 16, 1))
data = np.matmul(data.reshape(32, -1), b)
assert data.shape == (32, 1)

Задание 22.

Даны две матрицы $m_1$ размером $(32, 256)$ и $m_2$ размером $(32, 512)$, а также две вспомогательные матрицы $W_1$ размером $(256, 32)$ и $W_2$ размером $(512, 16)$. Используя **все** данные матрицы, сделайте так, чтобы на выходе получилась **ровно одна** матрица размером $(32, 32)$

In [264]:
m1 = np.random.randint(0, 10, size=(32, 256))
m2 = np.random.randint(0, 10, size=(32, 512))
W1 = np.random.randint(0, 10, size=(256, 32))
W2 = np.random.randint(0, 10, size=(512, 16))

result = np.matmul(np.matmul(m1, W1), np.matmul(m2, np.hstack((W2, W2))))

assert result.shape == (32, 32)

Задание 23.

Приведите полученную на последнем шаге матрицу к виду $(32, 3)$ и сделайте так, чтобы все значения в этой матрице были в промежутке от $0$ до $1$

In [265]:
# Вжух! (∩｀-´)⊃━☆ﾟ.*･｡ﾟ
result = np.matmul(result, np.random.randint(0, 10, size=(32, 3))) % 2

assert result.shape == (32, 3)
assert ((result >= 0) & (result <= 1)).all()