## Домашнее задание

В этой тетрадке вам предлагается реализовать задания при помощи библиотеки numpy. Крайне желательно при выполнении разных заданий не использовать циклы. Если вы не понимаете, как выполнить конкретную задачу без циклов - убирайте их постепенно, разбейте выполнение задачи на этапы и постепенно векторизуйте каждый этап.

Если вам непонятно, как выполнить ту или иную операцию - не стесняйтесь гуглить, если над вами повис дедлайн, а вы всё ещё на чём-то застряли - пишите преподу/в чат, это ок.

**Обсудить решение лучше и сделать в итоге хоть что-то гораздо лучше, чем скатать чужой код или сдать пустую тетрадку.**

In [1]:
import numpy as np

### Drill (1 балл)

Задание 1.

Инициализируйте нулями массивы следующих форм:

* (5)
* (5, 1)
* (10, 2)
* (3, 6, 2)
* (4, 3, 2, 1)

In [35]:
print(np.zeros(5), ' shape->', np.zeros(5).shape, '\n')
print(np.zeros((5,1)), ' shape->', np.zeros((5,1)).shape, '\n')
print(np.zeros((10,2)), ' shape->', np.zeros((10,2)).shape, '\n')
print(np.zeros((3,6,2)), ' shape->', np.zeros((3,6,2)).shape, '\n')
print(np.zeros((4,3,2,1)), ' shape->', np.zeros((4,3,2,1)).shape, '\n')

[0. 0. 0. 0. 0.]  shape-> (5,) 

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]  shape-> (5, 1) 

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]  shape-> (10, 2) 

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]  shape-> (3, 6, 2) 

[[[[0.]
   [0.]]

  [[0.]
   [0.]]

  [[0.]
   [0.]]]


 [[[0.]
   [0.]]

  [[0.]
   [0.]]

  [[0.]
   [0.]]]


 [[[0.]
   [0.]]

  [[0.]
   [0.]]

  [[0.]
   [0.]]]


 [[[0.]
   [0.]]

  [[0.]
   [0.]]

  [[0.]
   [0.]]]]  shape-> (4, 3, 2, 1) 



Задание 2.

Инициализируйте единицами массивы таких же форм и приведите их к целочисленному виду:

In [42]:
print(np.ones(5, dtype=int), ' shape->', np.ones(5, dtype=int).shape, '\n')
print(np.ones((5,1), dtype=int), ' shape->', np.ones((5,1), dtype=int).shape, '\n')
print(np.ones((10,2), dtype=int), ' shape->', np.ones((10,2), dtype=int).shape, '\n')
print(np.ones((3,6,2)).astype(int), ' shape->', np.ones((3,6,2)).astype(int).shape, '\n')
print(np.ones((4,3,2,1)).astype(int), ' shape->', np.ones((4,3,2,1)).astype(int).shape, '\n')

[1 1 1 1 1]  shape-> (5,) 

[[1]
 [1]
 [1]
 [1]
 [1]]  shape-> (5, 1) 

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]  shape-> (10, 2) 

[[[1 1]
  [1 1]
  [1 1]
  [1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]
  [1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]
  [1 1]
  [1 1]
  [1 1]]]  shape-> (3, 6, 2) 

[[[[1]
   [1]]

  [[1]
   [1]]

  [[1]
   [1]]]


 [[[1]
   [1]]

  [[1]
   [1]]

  [[1]
   [1]]]


 [[[1]
   [1]]

  [[1]
   [1]]

  [[1]
   [1]]]


 [[[1]
   [1]]

  [[1]
   [1]]

  [[1]
   [1]]]]  shape-> (4, 3, 2, 1) 



Задание 3.

Выполните для векторов выше `reshape` в "форму"
* с двумя компонентами
* с тремя компонентами
* с четырьмя компонентами

In [88]:
np.reshape(np.ones((5)), (5,1))
np.reshape(np.ones((5)), (5,1,1))
np.reshape(np.ones((5)), (5,1,1,1))
print('last one in 1st \n', np.ones((5)), ' shape->', np.ones((5)).shape, '\n',
      np.reshape(np.ones((5)), (5,1,1,1)), 'shape after reshape ->', np.reshape(np.ones((5)), (5,1,1,1)).shape, '\n')

np.reshape(np.ones((5,1)), (5,1))
np.reshape(np.ones((5,1)), (5,1,1))
np.reshape(np.ones((5,1)), (5,1,1,1))
print('last one in 2nd \n', np.ones((5,1)), ' shape->', np.ones((5,1)).shape, '\n',
      np.reshape(np.ones((5,1)), (5,1,1,1)), 'shape after reshape ->', np.reshape(np.ones((5,1)), (5,1,1,1)).shape, '\n')

np.reshape(np.ones((10,2)), (5,4))
np.reshape(np.ones((10,2)), (1,4,5))
np.reshape(np.ones((10,2)), (1,4,1,5))
print('last one in 3d \n', np.ones((10,2)), ' shape->', np.ones((10,2)).shape, '\n',
      np.reshape(np.ones((10,2)), (1,4,1,5)), 'shape after reshape ->', np.reshape(np.ones((10,2)), (1,4,1,5)).shape, '\n')

np.reshape(np.ones((3,6,2)), (6,6))
np.reshape(np.ones((3,6,2)), (1,2,18))
np.reshape(np.ones((3,6,2)), (2,9,1,2))
print('last one in 4th \n', np.ones((3,6,2)), ' shape->', np.ones((3,6,2)).shape, '\n',
      np.reshape(np.ones((3,6,2)), (2,9,1,2)), 'shape after reshape ->', np.reshape(np.ones((3,6,2)), (2,9,1,2)).shape, '\n')

np.reshape(np.ones((4,3,2,1)), (12,2))
np.reshape(np.ones((4,3,2,1)), (2,2,6))
np.reshape(np.ones((4,3,2,1)), (1,2,3,4))
print('last one in 5th \n', np.ones((4,3,2,1)), ' shape->', np.ones((4,3,2,1)).shape, '\n',
      np.reshape(np.ones((4,3,2,1)), (1,2,3,4)), 'shape after reshape ->', np.reshape(np.ones((4,3,2,1)),
                                                                                      (1,2,3,4)).shape, '\n')

last one in 1st 
 [1. 1. 1. 1. 1.]  shape-> (5,) 
 [[[[1.]]]


 [[[1.]]]


 [[[1.]]]


 [[[1.]]]


 [[[1.]]]] shape after reshape -> (5, 1, 1, 1) 

last one in 2nd 
 [[1.]
 [1.]
 [1.]
 [1.]
 [1.]]  shape-> (5, 1) 
 [[[[1.]]]


 [[[1.]]]


 [[[1.]]]


 [[[1.]]]


 [[[1.]]]] shape after reshape -> (5, 1, 1, 1) 

last one in 3d 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]  shape-> (10, 2) 
 [[[[1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]]]] shape after reshape -> (1, 4, 1, 5) 

last one in 4th 
 [[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]  shape-> (3, 6, 2) 
 [[[[1. 1.]]

  [[1. 1.]]

  [[1. 1.]]

  [[1. 1.]]

  [[1. 1.]]

  [[1. 1.]]

  [[1. 1.]]

  [[1. 1.]]

  [[1. 1.]]]


 [[[1. 1.]]

  [[1. 1.]]

  [[1. 1.]]

  [[1. 1.]]

  [[1. 1.]]

  [[1. 1.]]

  [[1. 1.]]


Задание 4.

Для вектора ниже посчитайте его
* Максимум по 1 оси
* Минимум по 0 оси
* Сумму по всем осям
* Среднее по 0 оси
* Медиану по 1 оси

In [90]:
v = np.random.randint(0, 9, size=(5, 7))
v

array([[6, 2, 3, 2, 3, 5, 4],
       [5, 3, 8, 4, 8, 1, 8],
       [8, 6, 3, 3, 8, 2, 2],
       [3, 5, 2, 4, 1, 0, 6],
       [1, 7, 8, 8, 8, 0, 5]])

In [106]:
print('Максимум по 1 оси', v.max(axis=1))
print('Минимум по 0 оси', v.min(axis=0))
print('Сумма по всем осям',v.sum())
print('Среднее по 0 оси', v.mean(axis=0))
print('Медиана по 1 оси', np.median(v, axis=1))

Максимум по 1 оси [6 8 8 6 8]
Минимум по 0 оси [1 2 2 2 1 0 2]
Сумма по всем осям 152
Среднее по 0 оси [4.6 4.6 4.8 4.2 5.6 1.6 5. ]
Медиана по 1 оси [3. 5. 3. 3. 7.]


Задание 5.

Для всё того же вектора `v` выведите
* Его shape
* 0 компоненту его "формы"
* 1 компоненту его "формы"

In [111]:
print('shape', v.shape)
print('shape[0]: ', v.shape[0])
print('shape[1]: ', v.shape[1])

shape (5, 7)
shape[0]:  5
shape[1]:  7


Задание 6.

Для этого же вектора выведите
* Все числа больше 5
* Все числа меньше 7 в обратном порядке
* Все числа больше 3, которые делятся на 4 без остатка
* Все числа, остаток от деления на 5 которых равен 3
* Индекс максимума
* Индекс минимума
* Cписок с индексами элементов отсортированного массива в исходном (неотсортированном)

In [126]:
v

array([[6, 2, 3, 2, 3, 5, 4],
       [5, 3, 8, 4, 8, 1, 8],
       [8, 6, 3, 3, 8, 2, 2],
       [3, 5, 2, 4, 1, 0, 6],
       [1, 7, 8, 8, 8, 0, 5]])

In [114]:
# Все числа больше 5
v[v > 5]

array([6, 8, 8, 8, 8, 6, 8, 6, 7, 8, 8, 8])

In [122]:
# Все числа меньше 7 в обратном порядке
v[v < 7][::-1]

array([5, 0, 1, 6, 0, 1, 4, 2, 5, 3, 2, 2, 3, 3, 6, 1, 4, 3, 5, 4, 5, 3,
       2, 3, 2, 6])

In [123]:
# Все числа больше 3, которые делятся на 4 без остатка
v[(v > 3) & (v % 4 == 0)]

array([4, 8, 4, 8, 8, 8, 8, 4, 8, 8, 8])

In [124]:
# Все числа, остаток от деления на 5 которых равен 3
v[v % 5 == 3]

array([3, 3, 3, 8, 8, 8, 8, 3, 3, 8, 3, 8, 8, 8])

In [130]:
print('index of max: ', v.argmax())
print('max element: ', v.reshape((-1))[v.argmax()])

index of max:  9
max element:  8


In [135]:
print('index of min: ', v.argmin())
print('min element: ', v.reshape((-1))[v.argmin()])

index of min:  26
min element:  0


In [137]:
v.argsort(axis=None)

array([33, 26, 25, 12, 28, 23, 20, 19,  3,  1,  8,  4,  2, 21, 16, 17, 10,
       24,  6, 22, 34,  7,  5, 15, 27,  0, 29, 14, 13, 11,  9, 30, 31, 32,
       18], dtype=int64)

Задание 7.

Выполните следующие операции над вектором (независимо, не обязательно делать это в последовательности):
* Умножьте его на 3
* Разделите на 7
* Возведите в степень $\frac{2}{3}$
* Посчитайте $\sin$ от него
* Посчитайте $\log$ от него

In [143]:
v = np.random.randint(0, 10, size=5)
v

array([5, 8, 1, 7, 9])

In [144]:
v * 3

array([15, 24,  3, 21, 27])

In [145]:
v / 7

array([0.71428571, 1.14285714, 0.14285714, 1.        , 1.28571429])

In [146]:
v ** (2/3)

array([2.92401774, 4.        , 1.        , 3.65930571, 4.32674871])

In [148]:
np.sin(v)

array([-0.95892427,  0.98935825,  0.84147098,  0.6569866 ,  0.41211849])

In [149]:
np.log(v)

array([1.60943791, 2.07944154, 0.        , 1.94591015, 2.19722458])

### Разные инициализации + индексирование (3 балла)

Задание 8.

Необходимо построить квадрат $3 \times 3$ из нечётных чисел

In [165]:
np.arange(1,2*3*3,2).reshape((3,3))

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

Задание 9.

Необходимо построить квадрат $4 \times 4$ из четных чисел в обратном порядке

In [166]:
np.arange(0,2*4*4,2).reshape((4,4))[:, ::-1]

array([[ 6,  4,  2,  0],
       [14, 12, 10,  8],
       [22, 20, 18, 16],
       [30, 28, 26, 24]])

Задание 10.

Необходимо построить сетку координат $11 \times 11$ с точкой $(0,0)$ в центре и шагом $0.1$ между клетками

Задание 11.

Замощение сетки $8\times8$ при помощи $0$ и $1$ в шахматном порядке, клетка с индексом $(0,0)$ замощается $1$

In [ ]:
# Ваш код

Задание 12.

То же замощение, но клетка с индексом $(0,0)$ замощается $0$

In [ ]:
# Ваш код

Задание 13.

Необходимо построить нижне-треугольную матрицу переменного размера (задается передачей параметра в функцию). Это единичная матрица,замощённая $1$ под главной диагональю

In [ ]:
# Ваш код

Задание 14.

Необходимо построить верхне-треугольную матрицу переменного размера. Это единичная матрица, замощённая $1$ над главной диагональю

In [ ]:
# Ваш код

Задание 15.

Необходимо построить матрицу, в которой единицы стоят на побочной диагонали (идущей из левого нижнего угла в правый верхний), в остальных местах стоят $0$

In [ ]:
# Ваш код

### Операции + аггрегации (3 балла)

Задание 16.

Дана выборка $\{X_i\}$ некоторой случайной величины $X$, необходимо оценить
* Математическое ожидание $E[X] = \frac{1}{N}\sum_{i=1}^N X_i$ этой случайной величины
* Дисперсию $D[X] = \frac{1}{N}\sum_{i=1}^N (X_i - E[X])^2$ этой случайной величины

In [ ]:
def expected_value(x):
    assert len(x) > 0
    return sum(x) / len(x)


def dispersion(x):
    assert len(x) > 0
    d = 0
    e = expected_value(x)
    for x_i in x:
        d += (x_i - e) ** 2
    return d / len(x)

In [ ]:
def expected_value_np(x):
    return # Ваш код

In [ ]:
def dispersion_np(x):
    return # Ваш код

In [ ]:
np.testing.assert_array_equal(expected_value([1]), expected_value_np(np.array([1])))
np.testing.assert_array_equal(expected_value([3, 4]), expected_value_np(np.array([3, 4])))
np.testing.assert_array_equal(expected_value([-1, 0, 1]), expected_value_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(expected_value([-99, -98]), expected_value_np(np.array([-99, -98])))

np.testing.assert_array_equal(dispersion([1]), dispersion_np(np.array([1])))
np.testing.assert_array_equal(dispersion([3, 4]), dispersion_np(np.array([3, 4])))
np.testing.assert_array_equal(dispersion([-1, 0, 1]), dispersion_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(dispersion([-99, -98]), dispersion_np(np.array([-99, -98])))

Задание 17.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое квадратов разностей их значений

In [ ]:
def mean_square_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    # Здесь и далее эти проверки !не нужно! дублировать в свои функции; Здесь они для того, чтобы лишний раз подчеркнуть валидность входных данных
    s = 0
    for i in range(len(y1)):
        s += (y1[i] - y2[i]) ** 2
    return s / len(y1)

In [ ]:
def mean_square_difference_np(y1, y2):
    return # Ваш код

In [ ]:
assert mean_square_difference([1], [1]) == mean_square_difference_np(np.array([1]), np.array([1]))
assert mean_square_difference([1, 2], [1, 2]) == mean_square_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_square_difference([-1, 1], [0, 0]) == mean_square_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_square_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_square_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 18.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое модулей разностей их значений

In [ ]:
def mean_abs_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    s = 0
    for i in range(len(y1)):
        s += abs(y1[i] - y2[i])
    return s / len(y1)

In [ ]:
def mean_abs_difference_np(y1, y2):
    return # Ваш код

In [ ]:
assert mean_abs_difference([1], [1]) == mean_abs_difference_np(np.array([1]), np.array([1]))
assert mean_abs_difference([1, 2], [1, 2]) == mean_abs_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_abs_difference([-1, 1], [0, 0]) == mean_abs_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_abs_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_abs_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 19.

Даны два вектора $y_1$ и $y_2$, в которых присутствуют только $0$ и $1$. Необходимо посчитать вероятность совпадения - в скольких точках значения двух векторов совпадают

In [ ]:
def matching_proba(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    assert len(set(y1)) <= 2
    assert len(set(y2)) <= 2
    assert 0 in set(y1) or 1 in set(y1) or (0 in set(y1) and 1 in set(y1))
    assert 0 in set(y2) or 1 in set(y2) or (0 in set(y2) and 1 in set(y2))

    return sum([y1[i] == y2[i] for i in range(len(y1))]) / len(y1)

In [ ]:
def matching_proba_np(y1, y2):
    return # Ваш код

In [ ]:
np.testing.assert_array_equal(matching_proba([0, 1], [1, 0]), matching_proba_np(np.array([0, 1]), np.array([1, 0])))
np.testing.assert_array_equal(matching_proba([0, 1, 0, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 1, 0, 1]), np.array([0, 0, 1, 1])))
np.testing.assert_array_equal(matching_proba([0, 0, 1, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1])))

Задание 20.

Даны два вектора: $y_1$, $y_2$. В $y_1$ и $y_2$ присутствуют только $0$ и $1$.

Необходимо найти границы (индексы), такие, что если мы разделим вдоль какой-то из этих границ оба вектора на две части, то
* в левой части пересекающихся в $y_1$ и $y_2$ нулей будет строго больше, чем пересекающихся единиц или непересекающихся элементов
* в правой - пересекающихся единиц строго больше, чем пересекающихся нулей или непересекающихся элементов.

Если какая-то из частей не содержит элементов вовсе, то будем считать, что она подходит под условие.

In [ ]:
def find_thresholds(y1, y2, debug=False):
    assert len(y1) == len(y2) and len(y1) > 0
    n = len(y1)
    matching_zeros = [1 if y1[i] == y2[i] == 0 else 0 for i in range(n)]
    matching_ones = [1 if y1[i] == y2[i] == 1 else 0 for i in range(n)]
    res = []
    if sum(matching_ones) / n > 0.5:
        res.append(0)
    for i in range(1, n):
        if debug: # если вам непонятна логика работы этой функции, передайте третьим аргументом True
            print(matching_zeros[:i], matching_ones[i:], i)
        if sum(matching_zeros[:i]) / i > 0.5 and sum(matching_ones[i:]) / (n - i) > 0.5:
            res.append(i)
    if sum(matching_zeros) / n > 0.5:
        res.append(n)
    return res

In [ ]:
def find_thresholds_np(y1, y2):
    return # Ваш код

In [ ]:
np.testing.assert_array_equal(find_thresholds([0], [0]), find_thresholds_np(np.array([0]), np.array([0])))
np.testing.assert_array_equal(find_thresholds([1], [1]), find_thresholds_np(np.array([1]), np.array([1])))
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 1], [0, 0, 1, 1]), 
    find_thresholds_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1]))
)
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 0, 0, 1, 1, 1], [0, 0, 0, 0, 0, 1, 1, 1]),
    find_thresholds_np(np.array([0, 0, 1, 0, 0, 1, 1, 1]), np.array([0, 0, 0, 0, 0, 1, 1, 1]))
)

### Разные действия с матрицами (3 балла)

Задание 21.

Дана матрица размера $(32, 3, 16, 16)$, заполненная случайными числами от 0 до 9. При помощи **ровно двух** преобразований приведите её к виду $(32, 1)$. При выполнении задания **можно** создавать вспомогательные матрицы!

In [ ]:
data = np.random.randint(0, 10, size=(32, 3, 16, 16))

# Преобразование 1
# Преобразование 2

assert data.shape == (32, 1)

Задание 22.

Даны две матрицы $m_1$ размером $(32, 256)$ и $m_2$ размером $(32, 512)$, а также две вспомогательные матрицы $W_1$ размером $(256, 32)$ и $W_2$ размером $(512, 16)$. Используя **все** данные матрицы, сделайте так, чтобы на выходе получилась **ровно одна** матрица размером $(32, 32)$

In [ ]:
m1 = np.random.randint(0, 10, size=(32, 256))
m2 = np.random.randint(0, 10, size=(32, 512))
W1 = np.random.randint(0, 10, size=(256, 32))
W2 = np.random.randint(0, 10, size=(512, 16))

result = # Ваш код

assert result.shape == (32, 32)

Задание 23.

Приведите полученную на последнем шаге матрицу к виду $(32, 3)$ и сделайте так, чтобы все значения в этой матрице были в промежутке от $0$ до $1$

In [ ]:
# Вжух! (∩｀-´)⊃━☆ﾟ.*･｡ﾟ
result = # Ваш код

assert result.shape == (32, 3)
assert ((result >= 0) & (result <= 1)).all()