## Домашнее задание

В этой тетрадке вам предлагается реализовать задания при помощи библиотеки numpy. Крайне желательно при выполнении разных заданий не использовать циклы. Если вы не понимаете, как выполнить конкретную задачу без циклов - убирайте их постепенно, разбейте выполнение задачи на этапы и постепенно векторизуйте каждый этап.

Если вам непонятно, как выполнить ту или иную операцию - не стесняйтесь гуглить, если над вами повис дедлайн, а вы всё ещё на чём-то застряли - пишите преподу/в чат, это ок.

**Обсудить решение лучше и сделать в итоге хоть что-то гораздо лучше, чем скатать чужой код или сдать пустую тетрадку.**

In [1]:
import numpy as np

### Drill (1 балл)

Задание 1.

Инициализируйте нулями массивы следующих форм:

* (5)
* (5, 1)
* (10, 2)
* (3, 6, 2)
* (4, 3, 2, 1)

In [6]:
a = np.zeros(5)
b = np.zeros((5, 1))
c = np.zeros((10, 2))
d = np.zeros((3, 6, 2))
e = np.zeros((4, 3, 2, 1))

(4, 3, 2, 1)

Задание 2.

Инициализируйте единицами массивы таких же форм и приведите их к целочисленному виду:

In [34]:
a = np.ones(5, dtype=int)
b = np.ones((5, 1), dtype=int)
c = np.ones((10, 2), dtype=int)
d = np.ones((3, 6, 2), dtype=int)
e = np.ones((4, 3, 2, 1), dtype=int)

Задание 3.

Выполните для векторов выше `reshape` в "форму"
* с двумя компонентами
* с тремя компонентами
* с четырьмя компонентами

In [51]:
a.reshape(5, -1)
a.reshape(5, 1, -1)
a.reshape(5, 1, 1, -1)

b.reshape(5, -1)
b.reshape(5, 1, -1)
b.reshape(5, 1, 1, -1)

c.reshape(10, -1)
c.reshape(10, 2, -1)
c.reshape(10, 2, 1, -1)

d.reshape(3, -1)
d.reshape(3, 6, -1)
d.reshape(3, 6, 2, -1)

e.reshape(4, -1)
e.reshape(4, 3, -1)
e.reshape(4, 3, 2, -1)


(4, 3, 2, 1)

Задание 4.

Для вектора ниже посчитайте его
* Максимум по 1 оси
* Минимум по 0 оси
* Сумму по всем осям
* Среднее по 0 оси
* Медиану по 1 оси

In [22]:
v = np.random.randint(0, 9, size=(5, 7))
v

array([[7, 6, 0, 3, 8, 5, 0],
       [0, 0, 5, 4, 8, 5, 7],
       [4, 1, 0, 6, 0, 2, 4],
       [8, 4, 7, 1, 3, 8, 2],
       [5, 2, 2, 4, 4, 1, 1]])

In [23]:
print(v.max(axis=1))
print(v.min(axis=0))
print(v.sum())
print(v.mean(axis=0))
print(np.median(v, axis=1))

[8 8 6 8 5]
[0 0 0 1 0 1 0]
127
[4.8 2.6 2.8 3.6 4.6 4.2 2.8]
[5. 5. 2. 4. 2.]


Задание 5.

Для всё того же вектора `v` выведите
* Его shape
* 0 компоненту его "формы"
* 1 компоненту его "формы"

In [240]:
print(v.shape)
print(v.shape[0])
print(v.shape[1])

(5, 7)
5
7


Задание 6.

Для этого же вектора выведите
* Все числа больше 5
* Все числа меньше 7 в обратном порядке
* Все числа больше 3, которые делятся на 4 без остатка
* Все числа, остаток от деления на 5 которых равен 3
* Индекс максимума
* Индекс минимума
* Cписок с индексами элементов отсортированного массива в исходном (неотсортированном)

In [34]:
print(v[v > 5])
print(v[v < 7][::-1])
print(v[(v > 3) & (v % 4 == 0)])
print(v[(v % 5 == 3)])
print(v.argmax())
print(v.argmin())
print(v.reshape(1, -1).argsort().reshape(5, 7))

[7 6 8 8 7 6 8 7 8]
[1 1 4 4 2 2 5 2 3 1 4 4 2 0 6 0 1 4 5 4 5 0 0 0 5 3 0 6]
[8 4 8 4 4 8 4 8 4 4]
[3 8 8 8 3 8]
4
2
[[ 2 18  6  7  8 16 34]
 [33 15 24 27 19 30 29]
 [25  3 10 31 20 22 32]
 [14  9  5 28 12 17  1]
 [23 13  0 21 11  4 26]]


Задание 7.

Выполните следующие операции над вектором (независимо, не обязательно делать это в последовательности):
* Умножьте его на 3
* Разделите на 7
* Возведите в степень $\frac{2}{3}$
* Посчитайте $\sin$ от него
* Посчитайте $\log$ от него

In [37]:
w = np.random.randint(0, 9, size=(5, 7))
w

array([[6, 5, 4, 6, 1, 4, 6],
       [2, 4, 5, 6, 4, 0, 3],
       [7, 4, 0, 8, 3, 8, 1],
       [7, 6, 2, 2, 7, 1, 4],
       [4, 1, 4, 2, 2, 4, 8]])

In [42]:
print(w * 3)
print(w / 7)
print(w ** (2 / 3))
print(np.sin(w))
print(np.log(w))

[[18 15 12 18  3 12 18]
 [ 6 12 15 18 12  0  9]
 [21 12  0 24  9 24  3]
 [21 18  6  6 21  3 12]
 [12  3 12  6  6 12 24]]
[[0.85714286 0.71428571 0.57142857 0.85714286 0.14285714 0.57142857
  0.85714286]
 [0.28571429 0.57142857 0.71428571 0.85714286 0.57142857 0.
  0.42857143]
 [1.         0.57142857 0.         1.14285714 0.42857143 1.14285714
  0.14285714]
 [1.         0.85714286 0.28571429 0.28571429 1.         0.14285714
  0.57142857]
 [0.57142857 0.14285714 0.57142857 0.28571429 0.28571429 0.57142857
  1.14285714]]
[[3.30192725 2.92401774 2.5198421  3.30192725 1.         2.5198421
  3.30192725]
 [1.58740105 2.5198421  2.92401774 3.30192725 2.5198421  0.
  2.08008382]
 [3.65930571 2.5198421  0.         4.         2.08008382 4.
  1.        ]
 [3.65930571 3.30192725 1.58740105 1.58740105 3.65930571 1.
  2.5198421 ]
 [2.5198421  1.         2.5198421  1.58740105 1.58740105 2.5198421
  4.        ]]
[[-0.2794155  -0.95892427 -0.7568025  -0.2794155   0.84147098 -0.7568025
  -0.2794155 ]
 [ 

D:\danil\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in log
  """


### Разные инициализации + индексирование (3 балла)

Задание 8.

Необходимо построить квадрат $3 \times 3$ из нечётных чисел

In [47]:
print(np.arange(1, 18, 2).reshape(3, 3))

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]


Задание 9.

Необходимо построить квадрат $4 \times 4$ из четных чисел в обратном порядке

In [53]:
print(np.arange(2, 33, 2)[::-1].reshape(4, 4))

[[32 30 28 26]
 [24 22 20 18]
 [16 14 12 10]
 [ 8  6  4  2]]


Задание 10.

Необходимо построить сетку координат $11 \times 11$ с точкой $(0,0)$ в центре и шагом $0.1$ между клетками

In [244]:
x =  np.arange(-.5, .6, .1).round(1)
res = np.transpose([np.tile(x, len(x)), np.repeat(x, len(x))])
res.reshape(11, 11, 2)[::-1]

array([[[-0.5,  0.5],
        [-0.4,  0.5],
        [-0.3,  0.5],
        [-0.2,  0.5],
        [-0.1,  0.5],
        [-0. ,  0.5],
        [ 0.1,  0.5],
        [ 0.2,  0.5],
        [ 0.3,  0.5],
        [ 0.4,  0.5],
        [ 0.5,  0.5]],

       [[-0.5,  0.4],
        [-0.4,  0.4],
        [-0.3,  0.4],
        [-0.2,  0.4],
        [-0.1,  0.4],
        [-0. ,  0.4],
        [ 0.1,  0.4],
        [ 0.2,  0.4],
        [ 0.3,  0.4],
        [ 0.4,  0.4],
        [ 0.5,  0.4]],

       [[-0.5,  0.3],
        [-0.4,  0.3],
        [-0.3,  0.3],
        [-0.2,  0.3],
        [-0.1,  0.3],
        [-0. ,  0.3],
        [ 0.1,  0.3],
        [ 0.2,  0.3],
        [ 0.3,  0.3],
        [ 0.4,  0.3],
        [ 0.5,  0.3]],

       [[-0.5,  0.2],
        [-0.4,  0.2],
        [-0.3,  0.2],
        [-0.2,  0.2],
        [-0.1,  0.2],
        [-0. ,  0.2],
        [ 0.1,  0.2],
        [ 0.2,  0.2],
        [ 0.3,  0.2],
        [ 0.4,  0.2],
        [ 0.5,  0.2]],

       [[-0.5,  0.1],
  

Задание 11.

Замощение сетки $8\times8$ при помощи $0$ и $1$ в шахматном порядке, клетка с индексом $(0,0)$ замощается $1$

In [59]:
print(np.array([[1, 0] * 4, [0, 1] * 4] * 4))

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


Задание 12.

То же замощение, но клетка с индексом $(0,0)$ замощается $0$

In [60]:
# Ваш код
print(np.array([[0, 1] * 4, [1, 0] * 4] * 4))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Задание 13.

Необходимо построить нижне-треугольную матрицу переменного размера (задается передачей параметра в функцию). Это единичная матрица,замощённая $1$ под главной диагональю

In [61]:
# Ваш код
def down_tri(a):
    return np.tri(a)
print(down_tri(5))

[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]]


Задание 14.

Необходимо построить верхне-треугольную матрицу переменного размера. Это единичная матрица, замощённая $1$ над главной диагональю

In [71]:
# Ваш код
def up_tri(a):
    return np.tri(a)[::-1, ::-1]
print(up_tri(5))

[[1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 1.]]


Задание 15.

Необходимо построить матрицу, в которой единицы стоят на побочной диагонали (идущей из левого нижнего угла в правый верхний), в остальных местах стоят $0$

In [73]:
# Ваш код
print(np.eye(5)[::-1])

[[0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]


### Операции + аггрегации (3 балла)

Задание 16.

Дана выборка $\{X_i\}$ некоторой случайной величины $X$, необходимо оценить
* Математическое ожидание $E[X] = \frac{1}{N}\sum_{i=1}^N X_i$ этой случайной величины
* Дисперсию $D[X] = \frac{1}{N}\sum_{i=1}^N (X_i - E[X])^2$ этой случайной величины

In [80]:
def expected_value(x):
    assert len(x) > 0
    return sum(x) / len(x)


def dispersion(x):
    assert len(x) > 0
    d = 0
    e = expected_value(x)
    for x_i in x:
        d += (x_i - e) ** 2
    return d / len(x)

In [81]:
def expected_value_np(x):
    return np.mean(x)

In [86]:
def dispersion_np(x):
    return np.mean((x - expected_value_np(x)) ** 2)
dispersion_np([1, 2])

0.25

In [87]:
np.testing.assert_array_equal(expected_value([1]), expected_value_np(np.array([1])))
np.testing.assert_array_equal(expected_value([3, 4]), expected_value_np(np.array([3, 4])))
np.testing.assert_array_equal(expected_value([-1, 0, 1]), expected_value_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(expected_value([-99, -98]), expected_value_np(np.array([-99, -98])))

np.testing.assert_array_equal(dispersion([1]), dispersion_np(np.array([1])))
np.testing.assert_array_equal(dispersion([3, 4]), dispersion_np(np.array([3, 4])))
np.testing.assert_array_equal(dispersion([-1, 0, 1]), dispersion_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(dispersion([-99, -98]), dispersion_np(np.array([-99, -98])))

Задание 17.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое квадратов разностей их значений

In [89]:
def mean_square_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    # Здесь и далее эти проверки !не нужно! дублировать в свои функции; Здесь они для того, чтобы лишний раз подчеркнуть валидность входных данных
    s = 0
    for i in range(len(y1)):
        s += (y1[i] - y2[i]) ** 2
    return s / len(y1)

In [90]:
def mean_square_difference_np(y1, y2):
    return np.mean((y1 - y2) ** 2)

In [91]:
assert mean_square_difference([1], [1]) == mean_square_difference_np(np.array([1]), np.array([1]))
assert mean_square_difference([1, 2], [1, 2]) == mean_square_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_square_difference([-1, 1], [0, 0]) == mean_square_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_square_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_square_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 18.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое модулей разностей их значений

In [93]:
def mean_abs_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    s = 0
    for i in range(len(y1)):
        s += abs(y1[i] - y2[i])
    return s / len(y1)

In [96]:
def mean_abs_difference_np(y1, y2):
    return np.mean(np.abs(y1 - y2))

In [97]:
assert mean_abs_difference([1], [1]) == mean_abs_difference_np(np.array([1]), np.array([1]))
assert mean_abs_difference([1, 2], [1, 2]) == mean_abs_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_abs_difference([-1, 1], [0, 0]) == mean_abs_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_abs_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_abs_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 19.

Даны два вектора $y_1$ и $y_2$, в которых присутствуют только $0$ и $1$. Необходимо посчитать вероятность совпадения - в скольких точках значения двух векторов совпадают

In [99]:
def matching_proba(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    assert len(set(y1)) <= 2
    assert len(set(y2)) <= 2
    assert 0 in set(y1) or 1 in set(y1) or (0 in set(y1) and 1 in set(y1))
    assert 0 in set(y2) or 1 in set(y2) or (0 in set(y2) and 1 in set(y2))

    return sum([y1[i] == y2[i] for i in range(len(y1))]) / len(y1)

In [100]:
def matching_proba_np(y1, y2):
    return np.mean(y1 == y2)

In [101]:
np.testing.assert_array_equal(matching_proba([0, 1], [1, 0]), matching_proba_np(np.array([0, 1]), np.array([1, 0])))
np.testing.assert_array_equal(matching_proba([0, 1, 0, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 1, 0, 1]), np.array([0, 0, 1, 1])))
np.testing.assert_array_equal(matching_proba([0, 0, 1, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1])))

Задание 20.

Даны два вектора: $y_1$, $y_2$. В $y_1$ и $y_2$ присутствуют только $0$ и $1$.

Необходимо найти границы (индексы), такие, что если мы разделим вдоль какой-то из этих границ оба вектора на две части, то
* в левой части пересекающихся в $y_1$ и $y_2$ нулей будет строго больше, чем пересекающихся единиц или непересекающихся элементов
* в правой - пересекающихся единиц строго больше, чем пересекающихся нулей или непересекающихся элементов.

Если какая-то из частей не содержит элементов вовсе, то будем считать, что она подходит под условие.

In [102]:
def find_thresholds(y1, y2, debug=True):
    assert len(y1) == len(y2) and len(y1) > 0
    n = len(y1)
    matching_zeros = [1 if y1[i] == y2[i] == 0 else 0 for i in range(n)]
    matching_ones = [1 if y1[i] == y2[i] == 1 else 0 for i in range(n)]
    res = []
    if sum(matching_ones) / n > 0.5:
        res.append(0)
    for i in range(1, n):
        if debug: # если вам непонятна логика работы этой функции, передайте третьим аргументом True
            print(matching_zeros[:i], matching_ones[i:], i)
        if sum(matching_zeros[:i]) / i > 0.5 and sum(matching_ones[i:]) / (n - i) > 0.5:
            res.append(i)
    if sum(matching_zeros) / n > 0.5:
        res.append(n)
    return res

In [104]:
find_thresholds([0, 0, 1, 0, 0, 1, 1, 1], [0, 0, 0, 0, 0, 1, 1, 1])

[1] [0, 0, 0, 0, 1, 1, 1] 1
[1, 1] [0, 0, 0, 1, 1, 1] 2
[1, 1, 0] [0, 0, 1, 1, 1] 3
[1, 1, 0, 1] [0, 1, 1, 1] 4
[1, 1, 0, 1, 1] [1, 1, 1] 5
[1, 1, 0, 1, 1, 0] [1, 1] 6
[1, 1, 0, 1, 1, 0, 0] [1] 7


[3, 4, 5, 6, 7]

In [245]:
def find_thresholds_np(y1, y2):
    n1, n2 = len(y1), len(y2)
    v1 = y1 * y2
    v2 = (1 - y1) * (1 - y2)
    index_list = (np.arange(n1) + 1 ) * 0.5

    v2_cumsum = np.cumsum(v2)
    indexres1 = (v2_cumsum > index_list )
    indexres1 = np.insert(indexres1, 0, True)

    
    v1 = v1[::-1]
    v1_cumsum = np.cumsum(v1)
    indexres2 = (v1_cumsum > index_list)
    indexres2 = np.insert(indexres2, 0, True)
    indexres2 = indexres2[::-1]

    
    answer = np.where((indexres1 & indexres2) == True)
    return answer[0]

In [246]:
find_thresholds_np(np.array([0, 0, 1, 0, 0, 1, 1, 1]), np.array([0, 0, 0, 0, 0, 1, 1, 1]))

array([3, 4, 5, 6, 7], dtype=int64)

In [247]:
np.testing.assert_array_equal(find_thresholds([0], [0]), find_thresholds_np(np.array([0]), np.array([0])))
np.testing.assert_array_equal(find_thresholds([1], [1]), find_thresholds_np(np.array([1]), np.array([1])))
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 1], [0, 0, 1, 1]), 
    find_thresholds_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1]))
)
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 0, 0, 1, 1, 1], [0, 0, 0, 0, 0, 1, 1, 1]),
    find_thresholds_np(np.array([0, 0, 1, 0, 0, 1, 1, 1]), np.array([0, 0, 0, 0, 0, 1, 1, 1]))
)

[1] [0, 1, 1] 1
[1, 1] [1, 1] 2
[1, 1, 0] [1] 3
[1] [0, 0, 0, 0, 1, 1, 1] 1
[1, 1] [0, 0, 0, 1, 1, 1] 2
[1, 1, 0] [0, 0, 1, 1, 1] 3
[1, 1, 0, 1] [0, 1, 1, 1] 4
[1, 1, 0, 1, 1] [1, 1, 1] 5
[1, 1, 0, 1, 1, 0] [1, 1] 6
[1, 1, 0, 1, 1, 0, 0] [1] 7


### Разные действия с матрицами (3 балла)

Задание 21.

Дана матрица размера $(32, 3, 16, 16)$, заполненная случайными числами от 0 до 9. При помощи **ровно двух** преобразований приведите её к виду $(32, 1)$. При выполнении задания **можно** создавать вспомогательные матрицы!

In [208]:
data = np.random.randint(0, 10, size=(32, 3, 16, 16))

x = np.ones((16 * 16 * 3, 1))
# Преобразование 1
data = data.reshape(32, 16 * 16 * 3)
# Преобразование 2
data = data @ x

assert data.shape == (32, 1)

Задание 22.

Даны две матрицы $m_1$ размером $(32, 256)$ и $m_2$ размером $(32, 512)$, а также две вспомогательные матрицы $W_1$ размером $(256, 32)$ и $W_2$ размером $(512, 16)$. Используя **все** данные матрицы, сделайте так, чтобы на выходе получилась **ровно одна** матрица размером $(32, 32)$

In [231]:
m1 = np.random.randint(0, 10, size=(32, 256))
m2 = np.random.randint(0, 10, size=(32, 512))
W1 = np.random.randint(0, 10, size=(256, 32))
W2 = np.random.randint(0, 10, size=(512, 16))

W2 = W2.reshape(256, 32)
W1 = np.concatenate((W1, W1))
temp1 = m1 @ W2
temp2 = m2 @ W1

# W1.shape
# temp1.shape, temp2.shape

result = temp1 * temp2
assert result.shape == (32, 32)

(32, 32)

Задание 23.

Приведите полученную на последнем шаге матрицу к виду $(32, 3)$ и сделайте так, чтобы все значения в этой матрице были в промежутке от $0$ до $1$

In [239]:
# Вжух! (∩｀-´)⊃━☆ﾟ.*･｡ﾟ
res = temp1 * temp2
x = np.ones((32, 3))
result = (res @ x)/(res @ x).max()
result

assert result.shape == (32, 3)
assert ((result >= 0) & (result <= 1)).all()