## Домашнее задание

In [514]:
import numpy as np

### Drill (1 балл)

Задание 1.

Инициализируйте нулями массивы следующих форм:

* (5)
* (5, 1)
* (10, 2)
* (3, 6, 2)
* (4, 3, 2, 1)

In [515]:
a = np.zeros((5)) 
a

array([0., 0., 0., 0., 0.])

In [516]:
b = np.zeros((5, 1)) 
b

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [517]:
c = np.zeros((10, 2)) 
c

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [518]:
d = np.zeros((3, 6, 2)) 
d

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [519]:
e = np.zeros((4, 3, 2, 1)) 
e

array([[[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]],


       [[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]],


       [[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]],


       [[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]]])

Задание 2.

Инициализируйте единицами массивы таких же форм и приведите их к целочисленному виду:

In [520]:
a = np.ones((5)).astype(int)
a

array([1, 1, 1, 1, 1])

In [521]:
b = np.ones((5, 1)).astype(int)
b

array([[1],
       [1],
       [1],
       [1],
       [1]])

In [522]:
c = np.ones((10, 2)).astype(int)
c

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [523]:
d = np.ones((3, 6, 2)).astype(int)
d

array([[[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]])

In [524]:
e = np.ones((4, 3, 2, 1)).astype(int)
e

array([[[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]],


       [[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]],


       [[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]],


       [[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]]])

Задание 3.

Выполните для векторов выше `reshape` в "форму"
* с двумя компонентами
* с тремя компонентами
* с четырьмя компонентами

In [525]:
a.reshape((1, 5))

array([[1, 1, 1, 1, 1]])

In [526]:
c.reshape((1, 10, 2))

array([[[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]])

In [527]:
d.reshape((3, 12))

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [528]:
e.reshape((12, 2))

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [529]:
a.reshape((1, 1, 5))

array([[[1, 1, 1, 1, 1]]])

In [530]:
b.reshape((1, 5, 1))

array([[[1],
        [1],
        [1],
        [1],
        [1]]])

In [531]:
c.reshape((10, 2, 1))

array([[[1],
        [1]],

       [[1],
        [1]],

       [[1],
        [1]],

       [[1],
        [1]],

       [[1],
        [1]],

       [[1],
        [1]],

       [[1],
        [1]],

       [[1],
        [1]],

       [[1],
        [1]],

       [[1],
        [1]]])

In [532]:
e.reshape((4, 3, 2))

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])

In [533]:
a.reshape((1, 1, 1, 5))

array([[[[1, 1, 1, 1, 1]]]])

In [534]:
b.reshape((5, 1, 1, 1))

array([[[[1]]],


       [[[1]]],


       [[[1]]],


       [[[1]]],


       [[[1]]]])

In [535]:
c.reshape((10, 2, 1, 1))

array([[[[1]],

        [[1]]],


       [[[1]],

        [[1]]],


       [[[1]],

        [[1]]],


       [[[1]],

        [[1]]],


       [[[1]],

        [[1]]],


       [[[1]],

        [[1]]],


       [[[1]],

        [[1]]],


       [[[1]],

        [[1]]],


       [[[1]],

        [[1]]],


       [[[1]],

        [[1]]]])

In [536]:
d.reshape((3, 2, 3, 2))

array([[[[1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1]]]])

Задание 4.

Для вектора ниже посчитайте его
* Максимум по 1 оси
* Минимум по 0 оси
* Сумму по всем осям
* Среднее по 0 оси
* Медиану по 1 оси

In [537]:
v = np.random.randint(0, 9, size=(5, 7))

In [538]:
v.max(axis=1)

array([8, 8, 7, 8, 7])

In [539]:
v.min(axis=0)

array([4, 1, 1, 0, 3, 0, 2])

In [540]:
v.sum()

147

In [541]:
v.mean(axis=0)

array([6.6, 4.6, 3.6, 3.8, 4.4, 2. , 4.4])

In [542]:
np.median(v, axis=1)

array([6., 1., 5., 4., 4.])

Задание 5.

Для всё того же вектора `v` выведите
* Его shape
* 0 компоненту его "формы"
* 1 компоненту его "формы"

In [543]:
v.shape

(5, 7)

In [544]:
v.shape[0]

5

In [545]:
v.shape[1]

7

Задание 6.

Для этого же вектора выведите
* Все числа больше 5
* Все числа меньше 7 в обратном порядке
* Все числа больше 3, которые делятся на 4 без остатка
* Все числа, остаток от деления на 5 которых равен 3
* Индекс максимума
* Индекс минимума
* Cписок с индексами элементов отсортированного массива в исходном (неотсортированном)

In [546]:
v[v > 5]

array([6, 7, 8, 6, 8, 7, 7, 7, 6, 8, 8, 7])

In [547]:
np.rot90(v[v < 7].reshape((1, -1)), k=2)

array([[2, 2, 5, 2, 4, 4, 4, 2, 3, 5, 2, 6, 2, 0, 5, 3, 0, 3, 1, 1, 1, 3,
        4, 4, 6, 6]])

In [548]:
v[(v > 3) & (v % 4 == 0)]

array([8, 4, 4, 8, 8, 8, 4, 4, 4])

In [549]:
v[v % 5 == 3]

array([8, 3, 8, 3, 3, 8, 8, 3])

In [550]:
(v.argmax() // v.shape[1], v.argmax() % v.shape[1])

(0, 2)

In [551]:
(v.argmin() // v.shape[1], v.argmin() % v.shape[1])

(1, 5)

In [552]:
v.argsort()

array([[6, 4, 5, 0, 3, 1, 2],
       [5, 1, 2, 3, 4, 6, 0],
       [3, 5, 1, 2, 6, 0, 4],
       [2, 5, 4, 6, 3, 0, 1],
       [2, 5, 6, 0, 1, 4, 3]])

Задание 7.

Выполните следующие операции над вектором (независимо, не обязательно делать это в последовательности):
* Умножьте его на 3
* Разделите на 7
* Возведите в степень $\frac{2}{3}$
* Посчитайте $\sin$ от него
* Посчитайте $\log$ от него

In [553]:
v * 3

array([[18, 21, 24, 18, 12, 12,  9],
       [24,  3,  3,  3,  9,  0, 21],
       [21,  9, 15,  0, 21,  6, 18],
       [24, 24,  6, 15,  9,  6, 12],
       [12, 12,  6, 21, 15,  6,  6]])

In [554]:
v / 7

array([[0.85714286, 1.        , 1.14285714, 0.85714286, 0.57142857,
        0.57142857, 0.42857143],
       [1.14285714, 0.14285714, 0.14285714, 0.14285714, 0.42857143,
        0.        , 1.        ],
       [1.        , 0.42857143, 0.71428571, 0.        , 1.        ,
        0.28571429, 0.85714286],
       [1.14285714, 1.14285714, 0.28571429, 0.71428571, 0.42857143,
        0.28571429, 0.57142857],
       [0.57142857, 0.57142857, 0.28571429, 1.        , 0.71428571,
        0.28571429, 0.28571429]])

In [555]:
v ** (2/3)

array([[3.30192725, 3.65930571, 4.        , 3.30192725, 2.5198421 ,
        2.5198421 , 2.08008382],
       [4.        , 1.        , 1.        , 1.        , 2.08008382,
        0.        , 3.65930571],
       [3.65930571, 2.08008382, 2.92401774, 0.        , 3.65930571,
        1.58740105, 3.30192725],
       [4.        , 4.        , 1.58740105, 2.92401774, 2.08008382,
        1.58740105, 2.5198421 ],
       [2.5198421 , 2.5198421 , 1.58740105, 3.65930571, 2.92401774,
        1.58740105, 1.58740105]])

In [556]:
np.sin(v)

array([[-0.2794155 ,  0.6569866 ,  0.98935825, -0.2794155 , -0.7568025 ,
        -0.7568025 ,  0.14112001],
       [ 0.98935825,  0.84147098,  0.84147098,  0.84147098,  0.14112001,
         0.        ,  0.6569866 ],
       [ 0.6569866 ,  0.14112001, -0.95892427,  0.        ,  0.6569866 ,
         0.90929743, -0.2794155 ],
       [ 0.98935825,  0.98935825,  0.90929743, -0.95892427,  0.14112001,
         0.90929743, -0.7568025 ],
       [-0.7568025 , -0.7568025 ,  0.90929743,  0.6569866 , -0.95892427,
         0.90929743,  0.90929743]])

In [557]:
np.log(v)

<ipython-input-557-4062a2f5d71c>:1: RuntimeWarning: divide by zero encountered in log
  np.log(v)


array([[1.79175947, 1.94591015, 2.07944154, 1.79175947, 1.38629436,
        1.38629436, 1.09861229],
       [2.07944154, 0.        , 0.        , 0.        , 1.09861229,
              -inf, 1.94591015],
       [1.94591015, 1.09861229, 1.60943791,       -inf, 1.94591015,
        0.69314718, 1.79175947],
       [2.07944154, 2.07944154, 0.69314718, 1.60943791, 1.09861229,
        0.69314718, 1.38629436],
       [1.38629436, 1.38629436, 0.69314718, 1.94591015, 1.60943791,
        0.69314718, 0.69314718]])

### Разные инициализации + индексирование (3 балла)

Задание 8.

Необходимо построить квадрат $3 \times 3$ из нечётных чисел

In [558]:
np.arange(1, 18, 2).reshape((3, 3))

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

Задание 9.

Необходимо построить квадрат $4 \times 4$ из четных чисел в обратном порядке

In [559]:
np.rot90(np.arange(2, 33, 2).reshape((1, -1)), k=2).reshape(4, 4)

array([[32, 30, 28, 26],
       [24, 22, 20, 18],
       [16, 14, 12, 10],
       [ 8,  6,  4,  2]])

Задание 10.

Необходимо построить сетку координат $11 \times 11$ с точкой $(0,0)$ в центре и шагом $0.1$ между клетками

In [560]:
xv, yv = np.mgrid[-0.5:0.6:0.1, -0.5:0.6:0.1]
print(xv)
print()
print(yv)

[[-0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5]
 [-0.4 -0.4 -0.4 -0.4 -0.4 -0.4 -0.4 -0.4 -0.4 -0.4 -0.4]
 [-0.3 -0.3 -0.3 -0.3 -0.3 -0.3 -0.3 -0.3 -0.3 -0.3 -0.3]
 [-0.2 -0.2 -0.2 -0.2 -0.2 -0.2 -0.2 -0.2 -0.2 -0.2 -0.2]
 [-0.1 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1]
 [ 0.2  0.2  0.2  0.2  0.2  0.2  0.2  0.2  0.2  0.2  0.2]
 [ 0.3  0.3  0.3  0.3  0.3  0.3  0.3  0.3  0.3  0.3  0.3]
 [ 0.4  0.4  0.4  0.4  0.4  0.4  0.4  0.4  0.4  0.4  0.4]
 [ 0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5]]

[[-0.5 -0.4 -0.3 -0.2 -0.1  0.   0.1  0.2  0.3  0.4  0.5]
 [-0.5 -0.4 -0.3 -0.2 -0.1  0.   0.1  0.2  0.3  0.4  0.5]
 [-0.5 -0.4 -0.3 -0.2 -0.1  0.   0.1  0.2  0.3  0.4  0.5]
 [-0.5 -0.4 -0.3 -0.2 -0.1  0.   0.1  0.2  0.3  0.4  0.5]
 [-0.5 -0.4 -0.3 -0.2 -0.1  0.   0.1  0.2  0.3  0.4  0.5]
 [-0.5 -0.4 -0.3 -0.2 -0.1  0.   0.1  0.2  0.3  0.4  0.5]
 [-0.5 -0.4 

Задание 11.

Замощение сетки $8\times8$ при помощи $0$ и $1$ в шахматном порядке, клетка с индексом $(0,0)$ замощается $1$

In [561]:
np.indices((8, 8)).sum(axis=0) % 2

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

или

In [562]:
x = np.arange(1, 9) % 2
y = np.arange(1, 9) % 2
xv, yv = np.meshgrid(x, y)
print(xv)
print()
print(yv)

[[1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]]

[[1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0]]


Задание 12.

То же замощение, но клетка с индексом $(0,0)$ замощается $0$

In [563]:
x = np.arange(0, 8) % 2
y = np.arange(0, 8) % 2
xv, yv = np.meshgrid(x, y)
print(xv)
print()
print(yv)

[[0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]]

[[0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1]]


Задание 13.

Необходимо построить нижне-треугольную матрицу переменного размера (задается передачей параметра в функцию). Это единичная матрица,замощённая $1$ под главной диагональю

In [564]:
def lower_triangular_matrix(n):
    return np.tril(np.ones((n, n)).astype(int))
lower_triangular_matrix(5)

array([[1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1]])

Задание 14.

Необходимо построить верхне-треугольную матрицу переменного размера. Это единичная матрица, замощённая $1$ над главной диагональю

In [565]:
def uper_triangular_matrix(n):
    return np.triu(np.ones((n, n)).astype(int))
uper_triangular_matrix(5)

array([[1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1],
       [0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1],
       [0, 0, 0, 0, 1]])

Задание 15.

Необходимо построить матрицу, в которой единицы стоят на побочной диагонали (идущей из левого нижнего угла в правый верхний), в остальных местах стоят $0$

In [566]:
def eye_unit_matrix(n):
    return np.rot90(np.eye(n).astype(int))
eye_unit_matrix(5)

array([[0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0]])

### Операции + аггрегации (3 балла)

Задание 16.

Дана выборка $\{X_i\}$ некоторой случайной величины $X$, необходимо оценить
* Математическое ожидание $E[X] = \frac{1}{N}\sum_{i=1}^N X_i$ этой случайной величины
* Дисперсию $D[X] = \frac{1}{N}\sum_{i=1}^N (X_i - E[X])^2$ этой случайной величины

In [567]:
def expected_value(x):
    assert len(x) > 0
    return sum(x) / len(x)


def dispersion(x):
    assert len(x) > 0
    d = 0
    e = expected_value(x)
    for x_i in x:
        d += (x_i - e) ** 2
    return d / len(x)

In [568]:
def expected_value_np(x):
    return x.mean()

In [569]:
def dispersion_np(x):
    return x.var()

In [570]:
np.testing.assert_array_equal(expected_value([1]), expected_value_np(np.array([1])))
np.testing.assert_array_equal(expected_value([3, 4]), expected_value_np(np.array([3, 4])))
np.testing.assert_array_equal(expected_value([-1, 0, 1]), expected_value_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(expected_value([-99, -98]), expected_value_np(np.array([-99, -98])))

np.testing.assert_array_equal(dispersion([1]), dispersion_np(np.array([1])))
np.testing.assert_array_equal(dispersion([3, 4]), dispersion_np(np.array([3, 4])))
np.testing.assert_array_equal(dispersion([-1, 0, 1]), dispersion_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(dispersion([-99, -98]), dispersion_np(np.array([-99, -98])))

Задание 17.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое квадратов разностей их значений

In [571]:
def mean_square_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    # Здесь и далее эти проверки !не нужно! дублировать в свои функции; Здесь они для того, чтобы лишний раз подчеркнуть валидность входных данных
    s = 0
    for i in range(len(y1)):
        s += (y1[i] - y2[i]) ** 2
    return s / len(y1)

In [572]:
def mean_square_difference_np(y1, y2):
    return ((y1 - y2)**2).mean()

In [573]:
assert mean_square_difference([1], [1]) == mean_square_difference_np(np.array([1]), np.array([1]))
assert mean_square_difference([1, 2], [1, 2]) == mean_square_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_square_difference([-1, 1], [0, 0]) == mean_square_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_square_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_square_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 18.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое модулей разностей их значений

In [574]:
def mean_abs_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    s = 0
    for i in range(len(y1)):
        s += abs(y1[i] - y2[i])
    return s / len(y1)

In [575]:
def mean_abs_difference_np(y1, y2):
    return (np.abs(y1 - y2)).mean()

In [576]:
assert mean_abs_difference([1], [1]) == mean_abs_difference_np(np.array([1]), np.array([1]))
assert mean_abs_difference([1, 2], [1, 2]) == mean_abs_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_abs_difference([-1, 1], [0, 0]) == mean_abs_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_abs_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_abs_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 19.

Даны два вектора $y_1$ и $y_2$, в которых присутствуют только $0$ и $1$. Необходимо посчитать вероятность совпадения - в скольких точках значения двух векторов совпадают

In [577]:
def matching_proba(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    assert len(set(y1)) <= 2
    assert len(set(y2)) <= 2
    assert 0 in set(y1) or 1 in set(y1) or (0 in set(y1) and 1 in set(y1))
    assert 0 in set(y2) or 1 in set(y2) or (0 in set(y2) and 1 in set(y2))

    return sum([y1[i] == y2[i] for i in range(len(y1))]) / len(y1)

In [578]:
def matching_proba_np(y1, y2):
    return len(y1[y1 == y2]) / len(y1)

In [579]:
np.testing.assert_array_equal(matching_proba([0, 1], [1, 0]), matching_proba_np(np.array([0, 1]), np.array([1, 0])))
np.testing.assert_array_equal(matching_proba([0, 1, 0, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 1, 0, 1]), np.array([0, 0, 1, 1])))
np.testing.assert_array_equal(matching_proba([0, 0, 1, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1])))

Задание 20.

Даны два вектора: $y_1$, $y_2$. В $y_1$ и $y_2$ присутствуют только $0$ и $1$.

Необходимо найти границы (индексы), такие, что если мы разделим вдоль какой-то из этих границ оба вектора на две части, то
* в левой части пересекающихся в $y_1$ и $y_2$ нулей будет строго больше, чем пересекающихся единиц или непересекающихся элементов
* в правой - пересекающихся единиц строго больше, чем пересекающихся нулей или непересекающихся элементов.

Если какая-то из частей не содержит элементов вовсе, то будем считать, что она подходит под условие.

In [580]:
def find_thresholds(y1, y2, debug=False):
    assert len(y1) == len(y2) and len(y1) > 0
    n = len(y1)
    matching_zeros = [1 if y1[i] == y2[i] == 0 else 0 for i in range(n)]
    matching_ones = [1 if y1[i] == y2[i] == 1 else 0 for i in range(n)]
    res = []
    if sum(matching_ones) / n > 0.5:
        res.append(0)
    for i in range(1, n):
        if debug: # если вам непонятна логика работы этой функции, передайте третьим аргументом True
            print(matching_zeros[:i], matching_ones[i:], i)
        if sum(matching_zeros[:i]) / i > 0.5 and sum(matching_ones[i:]) / (n - i) > 0.5:
            res.append(i)
    if sum(matching_zeros) / n > 0.5:
        res.append(n)
    return res

In [581]:
def find_thresholds_np(y1, y2):
    n = len(y1)
    matching_zeros = 1 - (y1 | y2)
    zer = matching_zeros
    matching_ones = y1 & y2
    res = np.array([])
    
    if sum(matching_ones) / n > 0.5:
        res = np.append(res, 1)
    else:
        res = np.append(res, 0)
        
    ones = np.arange(1, n).reshape((1, -1))
    r_ones = np.rot90(ones, k=2)
    
    matching_zeros = np.tril(matching_zeros.reshape((1, n)) + np.zeros((n - 1, n))).sum(axis=1) / ones
    matching_ones = np.triu(matching_ones.reshape((1, n)) + np.zeros((n - 1, n))).sum(axis=1) / r_ones
    
    res = np.append(res, ((matching_zeros > 0.5) & (matching_ones > 0.5)).reshape((n - 1)))
    
    if sum(zer) / n > 0.5:
        res = np.append(res, 1)
    else:
        res = np.append(res, 0)
        
    m = int(n - res.sum() + 1)
    res = res.argsort()[m::]
    return res

In [582]:
np.testing.assert_array_equal(find_thresholds([0], [0]), find_thresholds_np(np.array([0]), np.array([0])))
np.testing.assert_array_equal(find_thresholds([1], [1]), find_thresholds_np(np.array([1]), np.array([1])))
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 1], [0, 0, 1, 1]), 
    find_thresholds_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1]))
)
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 0, 0, 1, 1, 1], [0, 0, 0, 0, 0, 1, 1, 1]),
    find_thresholds_np(np.array([0, 0, 1, 0, 0, 1, 1, 1]), np.array([0, 0, 0, 0, 0, 1, 1, 1]))
)

### Разные действия с матрицами (3 балла)

Задание 21.

Дана матрица размера $(32, 3, 16, 16)$, заполненная случайными числами от 0 до 9. При помощи **ровно двух** преобразований приведите её к виду $(32, 1)$. При выполнении задания **можно** создавать вспомогательные матрицы!

In [583]:
data = np.random.randint(0, 10, size=(32, 3, 16, 16))

data = data.reshape((32, 1, -1))
data = data.sum(axis=2)

assert data.shape == (32, 1)

Задание 22.

Даны две матрицы $m_1$ размером $(32, 256)$ и $m_2$ размером $(32, 512)$, а также две вспомогательные матрицы $W_1$ размером $(256, 32)$ и $W_2$ размером $(512, 16)$. Используя **все** данные матрицы, сделайте так, чтобы на выходе получилась **ровно одна** матрица размером $(32, 32)$

In [584]:
m1 = np.random.randint(0, 10, size=(32, 256))
m2 = np.random.randint(0, 10, size=(32, 512))
W1 = np.random.randint(0, 10, size=(256, 32))
W2 = np.random.randint(0, 10, size=(512, 16))

result = m1.reshape((32, 32, -1)).sum(axis=2) \
    + m2.reshape((32, 32, -1)).sum(axis=2) \
    + W1.reshape((32, 32, -1)).sum(axis=2) \
    + W2.reshape((32, 32, -1)).sum(axis=2)


assert result.shape == (32, 32)

Задание 23.

Приведите полученную на последнем шаге матрицу к виду $(32, 3)$ и сделайте так, чтобы все значения в этой матрице были в промежутке от $0$ до $1$

In [585]:
# Вжух! (∩｀-´)⊃━☆ﾟ.*･｡ﾟ
result = result.reshape((32, 1, -1)).sum(axis=2)
result = (result + np.zeros((32, 3))) % 2

assert result.shape == (32, 3)
assert ((result >= 0) & (result <= 1)).all()