## Домашнее задание

В этой тетрадке вам предлагается реализовать задания при помощи библиотеки numpy. Крайне желательно при выполнении разных заданий не использовать циклы. Если вы не понимаете, как выполнить конкретную задачу без циклов - убирайте их постепенно, разбейте выполнение задачи на этапы и постепенно векторизуйте каждый этап.

Если вам непонятно, как выполнить ту или иную операцию - не стесняйтесь гуглить, если над вами повис дедлайн, а вы всё ещё на чём-то застряли - пишите преподу/в чат, это ок.

**Обсудить решение лучше и сделать в итоге хоть что-то гораздо лучше, чем скатать чужой код или сдать пустую тетрадку.**

In [1]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')

### Drill (1 балл)
_flexxx_

Задание 1.

Инициализируйте нулями массивы следующих форм:

* (5)
* (5, 1)
* (10, 2)
* (3, 6, 2)
* (4, 3, 2, 1)

In [2]:
array_1 = np.zeros((5))
array_2 = np.zeros((5, 1))
array_3 = np.zeros((10, 2))
array_4 = np.zeros((3, 6, 2))
array_5 = np.zeros((4, 3, 2, 1))

Задание 2.

Инициализируйте единицами массивы таких же форм и приведите их к целочисленному виду:

In [3]:
array_1 = np.ones((5)).astype(int)
array_2 = np.ones((5, 1)).astype(int)
array_3 = np.ones((10, 2)).astype(int)
array_4 = np.ones((3, 6, 2)).astype(int)
array_5 = np.ones((4, 3, 2, 1)).astype(int)

Задание 3.

Выполните для векторов выше `reshape` в "форму"
* с двумя компонентами
* с тремя компонентами
* с четырьмя компонентами

In [4]:
#Choose your fighter

array_1.reshape((5, 1))
array_1.reshape((5, 1, 1))
array_1.reshape((5, 1, 1, 1))

array_2.reshape((5, 1))
array_2.reshape((5, 1, 1))
array_2.reshape((5, 1, 1, 1))

array_3.reshape((5, 4))
array_3.reshape((5, 2, 2))
array_3.reshape((5, 2, 2, 1))

array_4.reshape((6, 6))
array_4.reshape((6, 3, 2))
array_4.reshape((3, 3, 2, 2))

array_5.reshape((6, 4))
array_5.reshape((6, 2, 2))
array_5.reshape((3, 2, 2, 2));

#а главное зачем

Задание 4.

Для вектора ниже посчитайте его
* Максимум по 1 оси
* Минимум по 0 оси
* Сумму по всем осям
* Среднее по 0 оси
* Медиану по 1 оси

In [5]:
v = np.random.randint(0, 9, size=(5, 7))
v

array([[4, 6, 8, 5, 2, 5, 4],
       [1, 4, 1, 1, 4, 2, 8],
       [7, 5, 5, 2, 2, 7, 6],
       [0, 8, 3, 0, 2, 5, 0],
       [5, 2, 0, 7, 4, 0, 8]])

In [6]:
print('max_ax_1:', np.max(v, axis = 1))
print('min_ax_0:', np.min(v, axis = 0))
print('sum:', np.sum(v))
print('mean_ax_0:', np.mean(v, axis = 0))
print('median_ax_1:', np.median(v, axis = 1))

max_ax_1: [8 8 7 8 8]
min_ax_0: [0 2 0 0 2 0 0]
sum: 133
mean_ax_0: [3.4 5.  3.4 3.  2.8 3.8 5.2]
median_ax_1: [5. 2. 5. 2. 4.]


Задание 5.

Для всё того же вектора `v` выведите
* Его shape
* 0 компоненту его "формы"
* 1 компоненту его "формы"

In [7]:
print(v.shape)
print(v.shape[0])
print(v.shape[1])

(5, 7)
5
7


Задание 6.

Для этого же вектора выведите
* Все числа больше 5
* Все числа меньше 7 в обратном порядке
* Все числа больше 3, которые делятся на 4 без остатка
* Все числа, остаток от деления на 5 которых равен 3
* Индекс максимума
* Индекс минимума
* Cписок с индексами элементов отсортированного массива в исходном (неотсортированном)

In [8]:
print('========== 1 ==========')
print(v[v > 5], '\n')
print('========== 2 ==========')
print(sorted(v[v < 7], reverse = True), '\n')
print('========== 3 ==========')
print(v[(v > 3) & (v % 4 == 0)], '\n')
print('========== 4 ==========')
print(v[v % 5 == 3], '\n')
print('========== 5 ==========')
print(v.argmax(), '\n')
print('========== 6 ==========')
print(v.argmin(), '\n')
print('========== 7 ==========')
print(v.argsort())

========== 1 ==========
[6 8 8 7 7 6 8 7 8] 

========== 2 ==========
[6, 6, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 3, 2, 2, 2, 2, 2, 2, 1, 1, 1, 0, 0, 0, 0, 0] 

========== 3 ==========
[4 8 4 4 4 8 8 4 8] 

========== 4 ==========
[8 8 8 3 8] 

========== 5 ==========
2 

========== 6 ==========
21 

========== 7 ==========
[[4 0 6 3 5 1 2]
 [0 2 3 5 1 4 6]
 [3 4 1 2 6 0 5]
 [0 3 6 4 2 5 1]
 [2 5 1 4 0 3 6]]


Задание 7.

Выполните следующие операции над вектором (независимо, не обязательно делать это в последовательности):
* Умножьте его на 3
* Разделите на 7
* Возведите в степень $\frac{2}{3}$
* Посчитайте $\sin$ от него
* Посчитайте $\log$ от него

In [9]:
print('========== 1 ==========')
print(v*3, '\n')
print('========== 2 ==========')
print(v / 7, '\n')
print('========== 3 ==========')
print(v ** (2/3), '\n')
print('========== 4 ==========')
print(np.sin(v), '\n')
print('========== 5 ==========')
print(np.log(v), '\n')

========== 1 ==========
[[12 18 24 15  6 15 12]
 [ 3 12  3  3 12  6 24]
 [21 15 15  6  6 21 18]
 [ 0 24  9  0  6 15  0]
 [15  6  0 21 12  0 24]] 

========== 2 ==========
[[0.57142857 0.85714286 1.14285714 0.71428571 0.28571429 0.71428571
  0.57142857]
 [0.14285714 0.57142857 0.14285714 0.14285714 0.57142857 0.28571429
  1.14285714]
 [1.         0.71428571 0.71428571 0.28571429 0.28571429 1.
  0.85714286]
 [0.         1.14285714 0.42857143 0.         0.28571429 0.71428571
  0.        ]
 [0.71428571 0.28571429 0.         1.         0.57142857 0.
  1.14285714]] 

========== 3 ==========
[[2.5198421  3.30192725 4.         2.92401774 1.58740105 2.92401774
  2.5198421 ]
 [1.         2.5198421  1.         1.         2.5198421  1.58740105
  4.        ]
 [3.65930571 2.92401774 2.92401774 1.58740105 1.58740105 3.65930571
  3.30192725]
 [0.         4.         2.08008382 0.         1.58740105 2.92401774
  0.        ]
 [2.92401774 1.58740105 0.         3.65930571 2.5198421  0.
  4.        ]] 

===

_логарифм нуля би лайк_

![jupyter](media/log.png)

### Разные инициализации + индексирование (3 балла)

Задание 8.

Необходимо построить квадрат $3 \times 3$ из нечётных чисел

In [10]:
array = np.random.randint(0, 9, size=(3, 3))*2 + 1
array

array([[15, 15,  3],
       [13, 11, 15],
       [ 1,  1,  5]])

Задание 9.

Необходимо построить квадрат $4 \times 4$ из четных чисел в обратном порядке

In [11]:
array = np.arange(32, 0, -2).reshape((4, 4))
array

array([[32, 30, 28, 26],
       [24, 22, 20, 18],
       [16, 14, 12, 10],
       [ 8,  6,  4,  2]])

Задание 10.

Необходимо построить сетку координат $11 \times 11$ с точкой $(0,0)$ в центре и шагом $0.1$ между клетками - _возможно я гипертупой, но не совсем понял, что вы хотите видеть, поэтому сделал два варика, до которых допер_


__варик рас__

In [12]:
array = np.tile(np.arange(6)[::-1]/10, (6,1))
array = np.tril(array) + np.triu(array.T, k = 1)
array = np.hstack((array, array[::, 4::-1]))
array = np.vstack((array, array[4::-1,::]))
print(array.shape)
array

(11, 11)


array([[0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.5],
       [0.5, 0.4, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.4, 0.5],
       [0.5, 0.4, 0.3, 0.2, 0.2, 0.2, 0.2, 0.2, 0.3, 0.4, 0.5],
       [0.5, 0.4, 0.3, 0.2, 0.1, 0.1, 0.1, 0.2, 0.3, 0.4, 0.5],
       [0.5, 0.4, 0.3, 0.2, 0.1, 0. , 0.1, 0.2, 0.3, 0.4, 0.5],
       [0.5, 0.4, 0.3, 0.2, 0.1, 0.1, 0.1, 0.2, 0.3, 0.4, 0.5],
       [0.5, 0.4, 0.3, 0.2, 0.2, 0.2, 0.2, 0.2, 0.3, 0.4, 0.5],
       [0.5, 0.4, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.4, 0.5],
       [0.5, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]])

In [13]:
array * 10 #так ведь приятнее

array([[5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 4., 4., 4., 4., 4., 4., 4., 4., 4., 5.],
       [5., 4., 3., 3., 3., 3., 3., 3., 3., 4., 5.],
       [5., 4., 3., 2., 2., 2., 2., 2., 3., 4., 5.],
       [5., 4., 3., 2., 1., 1., 1., 2., 3., 4., 5.],
       [5., 4., 3., 2., 1., 0., 1., 2., 3., 4., 5.],
       [5., 4., 3., 2., 1., 1., 1., 2., 3., 4., 5.],
       [5., 4., 3., 2., 2., 2., 2., 2., 3., 4., 5.],
       [5., 4., 3., 3., 3., 3., 3., 3., 3., 4., 5.],
       [5., 4., 4., 4., 4., 4., 4., 4., 4., 4., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

__варик два__

In [14]:
a = (np.arange(-5, 6, 1) /10).reshape(11,1)

a = np.repeat(a, 11, axis = 1).reshape(11,11,1)
b = a.T.reshape(11,11,1)
a = np.concatenate([a, b], axis=2)

for i in range(11): #ну это просто чтоб посмотреть что все ок (не бейте)
    for j in range(11):
        print(a[i,j], end= ' ')
    print()

[-0.5 -0.5] [-0.5 -0.4] [-0.5 -0.3] [-0.5 -0.2] [-0.5 -0.1] [-0.5  0. ] [-0.5  0.1] [-0.5  0.2] [-0.5  0.3] [-0.5  0.4] [-0.5  0.5] 
[-0.4 -0.5] [-0.4 -0.4] [-0.4 -0.3] [-0.4 -0.2] [-0.4 -0.1] [-0.4  0. ] [-0.4  0.1] [-0.4  0.2] [-0.4  0.3] [-0.4  0.4] [-0.4  0.5] 
[-0.3 -0.5] [-0.3 -0.4] [-0.3 -0.3] [-0.3 -0.2] [-0.3 -0.1] [-0.3  0. ] [-0.3  0.1] [-0.3  0.2] [-0.3  0.3] [-0.3  0.4] [-0.3  0.5] 
[-0.2 -0.5] [-0.2 -0.4] [-0.2 -0.3] [-0.2 -0.2] [-0.2 -0.1] [-0.2  0. ] [-0.2  0.1] [-0.2  0.2] [-0.2  0.3] [-0.2  0.4] [-0.2  0.5] 
[-0.1 -0.5] [-0.1 -0.4] [-0.1 -0.3] [-0.1 -0.2] [-0.1 -0.1] [-0.1  0. ] [-0.1  0.1] [-0.1  0.2] [-0.1  0.3] [-0.1  0.4] [-0.1  0.5] 
[ 0.  -0.5] [ 0.  -0.4] [ 0.  -0.3] [ 0.  -0.2] [ 0.  -0.1] [0. 0.] [0.  0.1] [0.  0.2] [0.  0.3] [0.  0.4] [0.  0.5] 
[ 0.1 -0.5] [ 0.1 -0.4] [ 0.1 -0.3] [ 0.1 -0.2] [ 0.1 -0.1] [0.1 0. ] [0.1 0.1] [0.1 0.2] [0.1 0.3] [0.1 0.4] [0.1 0.5] 
[ 0.2 -0.5] [ 0.2 -0.4] [ 0.2 -0.3] [ 0.2 -0.2] [ 0.2 -0.1] [0.2 0. ] [0.2 0.1] [0.2 0.2] [0.2 

Задание 11.

Замощение сетки $8\times8$ при помощи $0$ и $1$ в шахматном порядке, клетка с индексом $(0,0)$ замощается $1$

In [15]:
array = (np.arange(1, 73).reshape((8, 9)) % 2)[:,:8]
array

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [16]:
array = np.zeros((8, 8)).astype(int)
array[::2, ::2] = 1
array[1::2, 1::2] = 1
array

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

Задание 12.

То же замощение, но клетка с индексом $(0,0)$ замощается $0$

In [17]:
array = (np.arange(72).reshape((8, 9)) % 2)[:,:8]
array

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [18]:
array = np.zeros((8, 8)).astype(int)
array[1::2, ::2] = 1
array[0::2, 1::2] = 1
array

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

Задание 13.

Необходимо построить нижне-треугольную матрицу переменного размера (задается передачей параметра в функцию). Это единичная матрица,замощённая $1$ под главной диагональю

In [19]:
def l_trieangle(n):
    
    array = np.tril(np.ones((n, n)))
    return array

l_trieangle(5)

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])

Задание 14.

Необходимо построить верхне-треугольную матрицу переменного размера. Это единичная матрица, замощённая $1$ над главной диагональю

In [20]:
def u_trieangle(n):
    return l_trieangle(n).T

u_trieangle(5)

array([[1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1.]])

Задание 15.

Необходимо построить матрицу, в которой единицы стоят на побочной диагонали (идущей из левого нижнего угла в правый верхний), в остальных местах стоят $0$

In [21]:
def r_diag(n):
    
    array = np.zeros(n**2)
    array[n-1:n**2-1:n-1] = 1
    array = array.reshape((n, n))
    
    return array

r_diag(42)

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

### Операции + аггрегации (3 балла)

Задание 16.

Дана выборка $\{X_i\}$ некоторой случайной величины $X$, необходимо оценить
* Математическое ожидание $E[X] = \frac{1}{N}\sum_{i=1}^N X_i$ этой случайной величины
* Дисперсию $D[X] = \frac{1}{N}\sum_{i=1}^N (X_i - E[X])^2$ этой случайной величины

In [22]:
def expected_value(x):
    assert len(x) > 0
    return sum(x) / len(x)

def dispersion(x):
    assert len(x) > 0
    d = 0
    e = expected_value(x)
    for x_i in x:
        d += (x_i - e) ** 2
    return d / len(x)

In [23]:
def expected_value_np(x):
    return np.mean(x)

In [24]:
def dispersion_np(x):
    return np.mean((x - expected_value_np(x))**2)

In [25]:
np.testing.assert_array_equal(expected_value([1]), expected_value_np(np.array([1])))
np.testing.assert_array_equal(expected_value([3, 4]), expected_value_np(np.array([3, 4])))
np.testing.assert_array_equal(expected_value([-1, 0, 1]), expected_value_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(expected_value([-99, -98]), expected_value_np(np.array([-99, -98])))

np.testing.assert_array_equal(dispersion([1]), dispersion_np(np.array([1])))
np.testing.assert_array_equal(dispersion([3, 4]), dispersion_np(np.array([3, 4])))
np.testing.assert_array_equal(dispersion([-1, 0, 1]), dispersion_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(dispersion([-99, -98]), dispersion_np(np.array([-99, -98])))

Задание 17.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое квадратов разностей их значений

In [26]:
def mean_square_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    # Здесь и далее эти проверки !не нужно! дублировать в свои функции; Здесь они для того, чтобы лишний раз подчеркнуть валидность входных данных
    s = 0
    for i in range(len(y1)):
        s += (y1[i] - y2[i]) ** 2
    return s / len(y1)

In [27]:
def mean_square_difference_np(y1, y2):
    return np.mean((y1 - y2)**2)

In [28]:
assert mean_square_difference([1], [1]) == mean_square_difference_np(np.array([1]), np.array([1]))
assert mean_square_difference([1, 2], [1, 2]) == mean_square_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_square_difference([-1, 1], [0, 0]) == mean_square_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_square_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_square_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 18.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое модулей разностей их значений

In [29]:
def mean_abs_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    s = 0
    for i in range(len(y1)):
        s += abs(y1[i] - y2[i])
    return s / len(y1)

In [30]:
def mean_abs_difference_np(y1, y2):
    return np.mean(abs(y1 - y2))

In [31]:
assert mean_abs_difference([1], [1]) == mean_abs_difference_np(np.array([1]), np.array([1]))
assert mean_abs_difference([1, 2], [1, 2]) == mean_abs_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_abs_difference([-1, 1], [0, 0]) == mean_abs_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_abs_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_abs_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 19.

Даны два вектора $y_1$ и $y_2$, в которых присутствуют только $0$ и $1$. Необходимо посчитать вероятность совпадения - в скольких точках значения двух векторов совпадают

In [32]:
def matching_proba(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    assert len(set(y1)) <= 2
    assert len(set(y2)) <= 2
    assert 0 in set(y1) or 1 in set(y1) or (0 in set(y1) and 1 in set(y1))
    assert 0 in set(y2) or 1 in set(y2) or (0 in set(y2) and 1 in set(y2))

    return sum([y1[i] == y2[i] for i in range(len(y1))]) / len(y1)

In [33]:
def matching_proba_np(y1, y2):
    return np.mean(y1 == y2)

In [34]:
np.testing.assert_array_equal(matching_proba([0, 1], [1, 0]), matching_proba_np(np.array([0, 1]), np.array([1, 0])))
np.testing.assert_array_equal(matching_proba([0, 1, 0, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 1, 0, 1]), np.array([0, 0, 1, 1])))
np.testing.assert_array_equal(matching_proba([0, 0, 1, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1])))

Задание 20.

Даны два вектора: $y_1$, $y_2$. В $y_1$ и $y_2$ присутствуют только $0$ и $1$.

Необходимо найти границы (индексы), такие, что если мы разделим вдоль какой-то из этих границ оба вектора на две части, то
* в левой части пересекающихся в $y_1$ и $y_2$ нулей будет строго больше, чем пересекающихся единиц или непересекающихся элементов
* в правой - пересекающихся единиц строго больше, чем пересекающихся нулей или непересекающихся элементов.

Если какая-то из частей не содержит элементов вовсе, то будем считать, что она подходит под условие.

In [35]:
def find_thresholds(y1, y2, debug=False):
    assert len(y1) == len(y2) and len(y1) > 0
    n = len(y1)
    matching_zeros = [1 if y1[i] == y2[i] == 0 else 0 for i in range(n)]
    matching_ones = [1 if y1[i] == y2[i] == 1 else 0 for i in range(n)]
    res = []
    if sum(matching_ones) / n > 0.5:
        res.append(0)
    for i in range(1, n):
        if debug: # если вам непонятна логика работы этой функции, передайте третьим аргументом True
            print(matching_zeros[:i], matching_ones[i:], i)
        if sum(matching_zeros[:i]) / i > 0.5 and sum(matching_ones[i:]) / (n - i) > 0.5:
            res.append(i)
    if sum(matching_zeros) / n > 0.5:
        res.append(n)
    return res

In [36]:
def find_thresholds_np(y1, y2):
    
    count = np.arange(1, len(y1)+1)
    left = ((np.cumsum((y1 - 1)*(y2 - 1)) / count) > 0.5)
    left = np.insert(left, 0, True)
    right = ((np.cumsum((y1*y2)[::-1])[::-1] /count[::-1] > 0.5))
    right = np.append(right, True)
    a = np.array(left*right)

    return list(np.where(a == True)[0])

In [37]:
np.testing.assert_array_equal(find_thresholds([0], [0]), find_thresholds_np(np.array([0]), np.array([0])))
np.testing.assert_array_equal(find_thresholds([1], [1]), find_thresholds_np(np.array([1]), np.array([1])))
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 1], [0, 0, 1, 1]), 
    find_thresholds_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1]))
)
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 0, 0, 1, 1, 1], [0, 0, 0, 0, 0, 1, 1, 1]),
    find_thresholds_np(np.array([0, 0, 1, 0, 0, 1, 1, 1]), np.array([0, 0, 0, 0, 0, 1, 1, 1]))
)

### Разные действия с матрицами (3 балла)

Задание 21.

Дана матрица размера $(32, 3, 16, 16)$, заполненная случайными числами от 0 до 9. При помощи **ровно двух** преобразований приведите её к виду $(32, 1)$. При выполнении задания **можно** создавать вспомогательные матрицы!

In [38]:
data = np.random.randint(0, 10, size=(32, 3, 16, 16))

data = np.sum(data, axis = (1,2,3))
data = data.reshape((32, 1))

assert data.shape == (32, 1)

Задание 22.

Даны две матрицы $m_1$ размером $(32, 256)$ и $m_2$ размером $(32, 512)$, а также две вспомогательные матрицы $W_1$ размером $(256, 32)$ и $W_2$ размером $(512, 16)$. Используя **все** данные матрицы, сделайте так, чтобы на выходе получилась **ровно одна** матрица размером $(32, 32)$

In [39]:
m1 = np.random.randint(0, 10, size=(32, 256))
m2 = np.random.randint(0, 10, size=(32, 512))
W1 = np.random.randint(0, 10, size=(256, 32))
W2 = np.random.randint(0, 10, size=(512, 16))

result = (m2 @ np.hstack((W2, W2))) @ (m1@W1)

assert result.shape == (32, 32)

Задание 23.

Приведите полученную на последнем шаге матрицу к виду $(32, 3)$ и сделайте так, чтобы все значения в этой матрице были в промежутке от $0$ до $1$

In [40]:
# Вжух! (∩｀-´)⊃━☆ﾟ.*･｡ﾟ

scale = np.max(result) - np.min(result)
shift = np.min(result)
result = (np.vstack((np.max(result, axis = 0), np.min(result, axis = 0), np.mean(result, axis = 0))).T - shift) / scale

assert result.shape == (32, 3)
assert ((result >= 0) & (result <= 1)).all()