## Домашнее задание

В этой тетрадке вам предлагается реализовать задания при помощи библиотеки numpy. Крайне желательно при выполнении разных заданий не использовать циклы. Если вы не понимаете, как выполнить конкретную задачу без циклов - убирайте их постепенно, разбейте выполнение задачи на этапы и постепенно векторизуйте каждый этап.

Если вам непонятно, как выполнить ту или иную операцию - не стесняйтесь гуглить, если над вами повис дедлайн, а вы всё ещё на чём-то застряли - пишите преподу/в чат, это ок.

**Обсудить решение лучше и сделать в итоге хоть что-то гораздо лучше, чем скатать чужой код или сдать пустую тетрадку.**

In [2]:
import numpy as np

### Drill (1 балл)

Задание 1.

Инициализируйте нулями массивы следующих форм:

* (5)
* (5, 1)
* (10, 2)
* (3, 6, 2)
* (4, 3, 2, 1)

In [35]:
print(np.zeros(5), ' shape->', np.zeros(5).shape, '\n')
print(np.zeros((5,1)), ' shape->', np.zeros((5,1)).shape, '\n')
print(np.zeros((10,2)), ' shape->', np.zeros((10,2)).shape, '\n')
print(np.zeros((3,6,2)), ' shape->', np.zeros((3,6,2)).shape, '\n')
print(np.zeros((4,3,2,1)), ' shape->', np.zeros((4,3,2,1)).shape, '\n')

[0. 0. 0. 0. 0.]  shape-> (5,) 

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]  shape-> (5, 1) 

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]  shape-> (10, 2) 

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]  shape-> (3, 6, 2) 

[[[[0.]
   [0.]]

  [[0.]
   [0.]]

  [[0.]
   [0.]]]


 [[[0.]
   [0.]]

  [[0.]
   [0.]]

  [[0.]
   [0.]]]


 [[[0.]
   [0.]]

  [[0.]
   [0.]]

  [[0.]
   [0.]]]


 [[[0.]
   [0.]]

  [[0.]
   [0.]]

  [[0.]
   [0.]]]]  shape-> (4, 3, 2, 1) 



Задание 2.

Инициализируйте единицами массивы таких же форм и приведите их к целочисленному виду:

In [42]:
print(np.ones(5, dtype=int), ' shape->', np.ones(5, dtype=int).shape, '\n')
print(np.ones((5,1), dtype=int), ' shape->', np.ones((5,1), dtype=int).shape, '\n')
print(np.ones((10,2), dtype=int), ' shape->', np.ones((10,2), dtype=int).shape, '\n')
print(np.ones((3,6,2)).astype(int), ' shape->', np.ones((3,6,2)).astype(int).shape, '\n')
print(np.ones((4,3,2,1)).astype(int), ' shape->', np.ones((4,3,2,1)).astype(int).shape, '\n')

[1 1 1 1 1]  shape-> (5,) 

[[1]
 [1]
 [1]
 [1]
 [1]]  shape-> (5, 1) 

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]  shape-> (10, 2) 

[[[1 1]
  [1 1]
  [1 1]
  [1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]
  [1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]
  [1 1]
  [1 1]
  [1 1]]]  shape-> (3, 6, 2) 

[[[[1]
   [1]]

  [[1]
   [1]]

  [[1]
   [1]]]


 [[[1]
   [1]]

  [[1]
   [1]]

  [[1]
   [1]]]


 [[[1]
   [1]]

  [[1]
   [1]]

  [[1]
   [1]]]


 [[[1]
   [1]]

  [[1]
   [1]]

  [[1]
   [1]]]]  shape-> (4, 3, 2, 1) 



Задание 3.

Выполните для векторов выше `reshape` в "форму"
* с двумя компонентами
* с тремя компонентами
* с четырьмя компонентами

In [3]:
np.reshape(np.ones((5)), (5,1))
np.reshape(np.ones((5)), (5,1,1))
np.reshape(np.ones((5)), (5,1,1,1))
print('last one in 1st \n', np.ones((5)), ' shape->', np.ones((5)).shape, '\n',
      np.reshape(np.ones((5)), (5,1,1,1)), 'shape after reshape ->', np.reshape(np.ones((5)), (5,1,1,1)).shape, '\n')

np.reshape(np.ones((5,1)), (5,1))
np.reshape(np.ones((5,1)), (5,1,1))
np.reshape(np.ones((5,1)), (5,1,1,1))
print('last one in 2nd \n', np.ones((5,1)), ' shape->', np.ones((5,1)).shape, '\n',
      np.reshape(np.ones((5,1)), (5,1,1,1)), 'shape after reshape ->', np.reshape(np.ones((5,1)), (5,1,1,1)).shape, '\n')

np.reshape(np.ones((10,2)), (5,4))
np.reshape(np.ones((10,2)), (1,4,5))
np.reshape(np.ones((10,2)), (1,4,1,5))
print('last one in 3d \n', np.ones((10,2)), ' shape->', np.ones((10,2)).shape, '\n',
      np.reshape(np.ones((10,2)), (1,4,1,5)), 'shape after reshape ->', np.reshape(np.ones((10,2)), (1,4,1,5)).shape, '\n')

np.reshape(np.ones((3,6,2)), (6,6))
np.reshape(np.ones((3,6,2)), (1,2,18))
np.reshape(np.ones((3,6,2)), (2,9,1,2))
print('last one in 4th \n', np.ones((3,6,2)), ' shape->', np.ones((3,6,2)).shape, '\n',
      np.reshape(np.ones((3,6,2)), (2,9,1,2)), 'shape after reshape ->', np.reshape(np.ones((3,6,2)), (2,9,1,2)).shape, '\n')

np.reshape(np.ones((4,3,2,1)), (12,2))
np.reshape(np.ones((4,3,2,1)), (2,2,6))
np.reshape(np.ones((4,3,2,1)), (1,2,3,4))
print('last one in 5th \n', np.ones((4,3,2,1)), ' shape->', np.ones((4,3,2,1)).shape, '\n',
      np.reshape(np.ones((4,3,2,1)), (1,2,3,4)), 'shape after reshape ->', np.reshape(np.ones((4,3,2,1)),
                                                                                      (1,2,3,4)).shape, '\n')

last one in 1st 
 [1. 1. 1. 1. 1.]  shape-> (5,) 
 [[[[1.]]]


 [[[1.]]]


 [[[1.]]]


 [[[1.]]]


 [[[1.]]]] shape after reshape -> (5, 1, 1, 1) 

last one in 2nd 
 [[1.]
 [1.]
 [1.]
 [1.]
 [1.]]  shape-> (5, 1) 
 [[[[1.]]]


 [[[1.]]]


 [[[1.]]]


 [[[1.]]]


 [[[1.]]]] shape after reshape -> (5, 1, 1, 1) 

last one in 3d 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]  shape-> (10, 2) 
 [[[[1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]]]] shape after reshape -> (1, 4, 1, 5) 

last one in 4th 
 [[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]  shape-> (3, 6, 2) 
 [[[[1. 1.]]

  [[1. 1.]]

  [[1. 1.]]

  [[1. 1.]]

  [[1. 1.]]

  [[1. 1.]]

  [[1. 1.]]

  [[1. 1.]]

  [[1. 1.]]]


 [[[1. 1.]]

  [[1. 1.]]

  [[1. 1.]]

  [[1. 1.]]

  [[1. 1.]]

  [[1. 1.]]

  [[1. 1.]]


Задание 4.

Для вектора ниже посчитайте его
* Максимум по 1 оси
* Минимум по 0 оси
* Сумму по всем осям
* Среднее по 0 оси
* Медиану по 1 оси

In [4]:
v = np.random.randint(0, 9, size=(5, 7))
v

array([[5, 7, 1, 8, 4, 1, 4],
       [1, 7, 5, 0, 8, 2, 2],
       [5, 0, 2, 3, 0, 3, 0],
       [0, 1, 4, 3, 1, 3, 0],
       [3, 5, 1, 8, 1, 8, 8]])

In [5]:
print('Максимум по 1 оси', v.max(axis=1))
print('Минимум по 0 оси', v.min(axis=0))
print('Сумма по всем осям',v.sum())
print('Среднее по 0 оси', v.mean(axis=0))
print('Медиана по 1 оси', np.median(v, axis=1))

Максимум по 1 оси [8 8 5 4 8]
Минимум по 0 оси [0 0 1 0 0 1 0]
Сумма по всем осям 114
Среднее по 0 оси [2.8 4.  2.6 4.4 2.8 3.4 2.8]
Медиана по 1 оси [4. 2. 2. 1. 5.]


Задание 5.

Для всё того же вектора `v` выведите
* Его shape
* 0 компоненту его "формы"
* 1 компоненту его "формы"

In [6]:
print('shape', v.shape)
print('shape[0]: ', v.shape[0])
print('shape[1]: ', v.shape[1])

shape (5, 7)
shape[0]:  5
shape[1]:  7


Задание 6.

Для этого же вектора выведите
* Все числа больше 5
* Все числа меньше 7 в обратном порядке
* Все числа больше 3, которые делятся на 4 без остатка
* Все числа, остаток от деления на 5 которых равен 3
* Индекс максимума
* Индекс минимума
* Cписок с индексами элементов отсортированного массива в исходном (неотсортированном)

In [7]:
v

array([[5, 7, 1, 8, 4, 1, 4],
       [1, 7, 5, 0, 8, 2, 2],
       [5, 0, 2, 3, 0, 3, 0],
       [0, 1, 4, 3, 1, 3, 0],
       [3, 5, 1, 8, 1, 8, 8]])

In [8]:
# Все числа больше 5
v[v > 5]

array([7, 8, 7, 8, 8, 8, 8])

In [9]:
# Все числа меньше 7 в обратном порядке
v[v < 7][::-1]

array([1, 1, 5, 3, 0, 3, 1, 3, 4, 1, 0, 0, 3, 0, 3, 2, 0, 5, 2, 2, 0, 5,
       1, 4, 1, 4, 1, 5])

In [10]:
# Все числа больше 3, которые делятся на 4 без остатка
v[(v > 3) & (v % 4 == 0)]

array([8, 4, 4, 8, 4, 8, 8, 8])

In [11]:
# Все числа, остаток от деления на 5 которых равен 3
v[v % 5 == 3]

array([8, 8, 3, 3, 3, 3, 3, 8, 8, 8])

In [12]:
print('index of max: ', v.argmax())
print('max element: ', v.reshape((-1))[v.argmax()])

index of max:  3
max element:  8


In [13]:
print('index of min: ', v.argmin())
print('min element: ', v.reshape((-1))[v.argmin()])

index of min:  10
min element:  0


In [14]:
v.argsort(axis=None)

array([20, 21, 15, 10, 27, 18, 32,  2, 30, 22,  5,  7, 25, 12, 13, 16, 19,
       17, 28, 26, 24, 23,  6,  4, 29,  0, 14,  9,  8,  1, 11,  3, 31, 33,
       34], dtype=int64)

Задание 7.

Выполните следующие операции над вектором (независимо, не обязательно делать это в последовательности):
* Умножьте его на 3
* Разделите на 7
* Возведите в степень $\frac{2}{3}$
* Посчитайте $\sin$ от него
* Посчитайте $\log$ от него

In [15]:
v = np.random.randint(0, 10, size=5)
v

array([6, 9, 9, 7, 9])

In [16]:
v * 3

array([18, 27, 27, 21, 27])

In [17]:
v / 7

array([0.85714286, 1.28571429, 1.28571429, 1.        , 1.28571429])

In [18]:
v ** (2/3)

array([3.30192725, 4.32674871, 4.32674871, 3.65930571, 4.32674871])

In [19]:
np.sin(v)

array([-0.2794155 ,  0.41211849,  0.41211849,  0.6569866 ,  0.41211849])

In [20]:
np.log(v)

array([1.79175947, 2.19722458, 2.19722458, 1.94591015, 2.19722458])

### Разные инициализации + индексирование (3 балла)

Задание 8.

Необходимо построить квадрат $3 \times 3$ из нечётных чисел

In [165]:
np.arange(1,2*3*3,2).reshape((3,3))

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

Задание 9.

Необходимо построить квадрат $4 \times 4$ из четных чисел в обратном порядке

In [166]:
np.arange(0,2*4*4,2).reshape((4,4))[:, ::-1]

array([[ 6,  4,  2,  0],
       [14, 12, 10,  8],
       [22, 20, 18, 16],
       [30, 28, 26, 24]])

In [21]:
np.arange(32, 0, -2).reshape(4, 4)

array([[32, 30, 28, 26],
       [24, 22, 20, 18],
       [16, 14, 12, 10],
       [ 8,  6,  4,  2]])

Задание 10.

Необходимо построить сетку координат $11 \times 11$ с точкой $(0,0)$ в центре и шагом $0.1$ между клетками

In [32]:
np.round(np.arange(-6, 6.1, 0.1).reshape((11,11)),2)

array([[-6. , -5.9, -5.8, -5.7, -5.6, -5.5, -5.4, -5.3, -5.2, -5.1, -5. ],
       [-4.9, -4.8, -4.7, -4.6, -4.5, -4.4, -4.3, -4.2, -4.1, -4. , -3.9],
       [-3.8, -3.7, -3.6, -3.5, -3.4, -3.3, -3.2, -3.1, -3. , -2.9, -2.8],
       [-2.7, -2.6, -2.5, -2.4, -2.3, -2.2, -2.1, -2. , -1.9, -1.8, -1.7],
       [-1.6, -1.5, -1.4, -1.3, -1.2, -1.1, -1. , -0.9, -0.8, -0.7, -0.6],
       [-0.5, -0.4, -0.3, -0.2, -0.1, -0. ,  0.1,  0.2,  0.3,  0.4,  0.5],
       [ 0.6,  0.7,  0.8,  0.9,  1. ,  1.1,  1.2,  1.3,  1.4,  1.5,  1.6],
       [ 1.7,  1.8,  1.9,  2. ,  2.1,  2.2,  2.3,  2.4,  2.5,  2.6,  2.7],
       [ 2.8,  2.9,  3. ,  3.1,  3.2,  3.3,  3.4,  3.5,  3.6,  3.7,  3.8],
       [ 3.9,  4. ,  4.1,  4.2,  4.3,  4.4,  4.5,  4.6,  4.7,  4.8,  4.9],
       [ 5. ,  5.1,  5.2,  5.3,  5.4,  5.5,  5.6,  5.7,  5.8,  5.9,  6. ]])

In [ ]:
# 

In [29]:
a = np.arange(-0.5, 0.6, 0.1)
b = np.arange(-0.5, 0.6, 0.1)
b.reshape(11, 1)

ans = np.meshgrid(a, b)
np.round(np.dstack((ans[0], ans[1])), 2)

array([[[-0.5, -0.5],
        [-0.4, -0.5],
        [-0.3, -0.5],
        [-0.2, -0.5],
        [-0.1, -0.5],
        [-0. , -0.5],
        [ 0.1, -0.5],
        [ 0.2, -0.5],
        [ 0.3, -0.5],
        [ 0.4, -0.5],
        [ 0.5, -0.5]],

       [[-0.5, -0.4],
        [-0.4, -0.4],
        [-0.3, -0.4],
        [-0.2, -0.4],
        [-0.1, -0.4],
        [-0. , -0.4],
        [ 0.1, -0.4],
        [ 0.2, -0.4],
        [ 0.3, -0.4],
        [ 0.4, -0.4],
        [ 0.5, -0.4]],

       [[-0.5, -0.3],
        [-0.4, -0.3],
        [-0.3, -0.3],
        [-0.2, -0.3],
        [-0.1, -0.3],
        [-0. , -0.3],
        [ 0.1, -0.3],
        [ 0.2, -0.3],
        [ 0.3, -0.3],
        [ 0.4, -0.3],
        [ 0.5, -0.3]],

       [[-0.5, -0.2],
        [-0.4, -0.2],
        [-0.3, -0.2],
        [-0.2, -0.2],
        [-0.1, -0.2],
        [-0. , -0.2],
        [ 0.1, -0.2],
        [ 0.2, -0.2],
        [ 0.3, -0.2],
        [ 0.4, -0.2],
        [ 0.5, -0.2]],

       [[-0.5, -0.1],
  

Задание 11.

Замощение сетки $8\times8$ при помощи $0$ и $1$ в шахматном порядке, клетка с индексом $(0,0)$ замощается $1$

In [46]:
# [1,0]*4 + [0,1]*4

In [40]:
a = np.array(([1,0]*4+[0,1]*4)*4).reshape((8,8))
print(a)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


Задание 12.

То же замощение, но клетка с индексом $(0,0)$ замощается $0$

In [47]:
a = np.array(([0,1]*4+[1,0]*4)*4).reshape((8,8))
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Задание 13.

Необходимо построить нижне-треугольную матрицу переменного размера (задается передачей параметра в функцию). Это единичная матрица,замощённая $1$ под главной диагональю

In [112]:
def create_lower_tr(n):
    k = 0
    while n > 0:
        if k == 0:
            a = np.array(([1]*(k)+[0]*(n)))
        elif k > 0:
            a = np.vstack((a, np.array(([1]*(k)+[0]*(n)))))
        n -= 1
        k += 1
    return a

In [113]:
create_lower_tr(4)

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 1, 0, 0],
       [1, 1, 1, 0]])

In [33]:
n, m = 6, 5
matrix = np.ones(n*m)
np.tril(matrix.reshape(n, m))

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Задание 14.

Необходимо построить верхне-треугольную матрицу переменного размера. Это единичная матрица, замощённая $1$ над главной диагональю

In [122]:
def create_upper_tr(n):
    k = 1
    while n > 0:
        if k == 1:
            a = np.array(([0]*(k)+[1]*(n-1)))
        elif k > 1:
            a = np.vstack((a, np.array(([0]*(k)+[1]*(n-1)))))
        n -= 1
        k += 1
    return a

In [123]:
create_upper_tr(n)

array([[0, 1, 1, 1, 1],
       [0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]])

In [39]:
n, m = 6, 5
matrix = np.ones(n*m)
np.triu(matrix.reshape(a, b), k=1)

array([[0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Задание 15.

Необходимо построить матрицу, в которой единицы стоят на побочной диагонали (идущей из левого нижнего угла в правый верхний), в остальных местах стоят $0$

In [136]:
np.eye(3)[::-1]

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])

### Операции + аггрегации (3 балла)

Задание 16.

Дана выборка $\{X_i\}$ некоторой случайной величины $X$, необходимо оценить
* Математическое ожидание $E[X] = \frac{1}{N}\sum_{i=1}^N X_i$ этой случайной величины
* Дисперсию $D[X] = \frac{1}{N}\sum_{i=1}^N (X_i - E[X])^2$ этой случайной величины

In [138]:
def expected_value(x):
    assert len(x) > 0
    return sum(x) / len(x)


def dispersion(x):
    assert len(x) > 0
    d = 0
    e = expected_value(x)
    for x_i in x:
        d += (x_i - e) ** 2
    return d / len(x)

In [144]:
a=np.array([1])
len(a)

1

In [154]:
def expected_value_np(x):
    assert len(x) > 0
    return x.sum() / len(x)

In [155]:
def dispersion_np(x):
    assert len(x) > 0
    d = 0
    e = expected_value_np(x)
    d += ((x - e) ** 2).sum()
    return d / len(x)

In [156]:
np.testing.assert_array_equal(expected_value([1]), expected_value_np(np.array([1])))
np.testing.assert_array_equal(expected_value([3, 4]), expected_value_np(np.array([3, 4])))
np.testing.assert_array_equal(expected_value([-1, 0, 1]), expected_value_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(expected_value([-99, -98]), expected_value_np(np.array([-99, -98])))

np.testing.assert_array_equal(dispersion([1]), dispersion_np(np.array([1])))
np.testing.assert_array_equal(dispersion([3, 4]), dispersion_np(np.array([3, 4])))
np.testing.assert_array_equal(dispersion([-1, 0, 1]), dispersion_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(dispersion([-99, -98]), dispersion_np(np.array([-99, -98])))

Задание 17.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое квадратов разностей их значений

In [162]:
def mean_square_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    # Здесь и далее эти проверки !не нужно! дублировать в свои функции;
    # Здесь они для того, чтобы лишний раз подчеркнуть валидность входных данных
    s = 0
    for i in range(len(y1)):
        s += (y1[i] - y2[i]) ** 2
    return s / len(y1)

In [163]:
def mean_square_difference_np(y1, y2):
    return ((y1 - y2) ** 2).sum() / len(y1)

In [164]:
assert mean_square_difference([1], [1]) == mean_square_difference_np(np.array([1]), np.array([1]))
assert mean_square_difference([1, 2], [1, 2]) == mean_square_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_square_difference([-1, 1], [0, 0]) == mean_square_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_square_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_square_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 18.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое модулей разностей их значений

In [166]:
def mean_abs_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    s = 0
    for i in range(len(y1)):
        s += abs(y1[i] - y2[i])
    return s / len(y1)

In [209]:
def mean_abs_difference_np(y1, y2):
    return np.absolute(y1 - y2).sum() / len(y1)

In [210]:
assert mean_abs_difference([1], [1]) == mean_abs_difference_np(np.array([1]), np.array([1]))
assert mean_abs_difference([1, 2], [1, 2]) == mean_abs_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_abs_difference([-1, 1], [0, 0]) == mean_abs_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_abs_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_abs_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 19.

Даны два вектора $y_1$ и $y_2$, в которых присутствуют только $0$ и $1$. Необходимо посчитать вероятность совпадения - в скольких точках значения двух векторов совпадают

In [191]:
def matching_proba(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    assert len(set(y1)) <= 2
    assert len(set(y2)) <= 2
    assert 0 in set(y1) or 1 in set(y1) or (0 in set(y1) and 1 in set(y1))
    assert 0 in set(y2) or 1 in set(y2) or (0 in set(y2) and 1 in set(y2))

    return sum([y1[i] == y2[i] for i in range(len(y1))]) / len(y1)

In [192]:
def matching_proba_np(y1, y2):
    return (y1 == y2).sum() / len(y1)

In [193]:
np.testing.assert_array_equal(matching_proba([0, 1], [1, 0]), matching_proba_np(np.array([0, 1]), np.array([1, 0])))
np.testing.assert_array_equal(matching_proba([0, 1, 0, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 1, 0, 1]), np.array([0, 0, 1, 1])))
np.testing.assert_array_equal(matching_proba([0, 0, 1, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1])))

Задание 20.

Даны два вектора: $y_1$, $y_2$. В $y_1$ и $y_2$ присутствуют только $0$ и $1$.

Необходимо найти границы (индексы), такие, что если мы разделим вдоль какой-то из этих границ оба вектора на две части, то
* в левой части пересекающихся в $y_1$ и $y_2$ нулей будет строго больше, чем пересекающихся единиц или непересекающихся элементов
* в правой - пересекающихся единиц строго больше, чем пересекающихся нулей или непересекающихся элементов.

Если какая-то из частей не содержит элементов вовсе, то будем считать, что она подходит под условие.

In [40]:
def find_thresholds(y1, y2, debug=False):
    assert len(y1) == len(y2) and len(y1) > 0
    n = len(y1)
    matching_zeros = [1 if y1[i] == y2[i] == 0 else 0 for i in range(n)]
    matching_ones = [1 if y1[i] == y2[i] == 1 else 0 for i in range(n)]
    res = []
    if sum(matching_ones) / n > 0.5:
        res.append(0)
    for i in range(1, n):
        if debug: # если вам непонятна логика работы этой функции, передайте третьим аргументом True
            print(matching_zeros[:i], matching_ones[i:], i)
        if sum(matching_zeros[:i]) / i > 0.5 and sum(matching_ones[i:]) / (n - i) > 0.5:
            res.append(i)
    if sum(matching_zeros) / n > 0.5:
        res.append(n)
    return res

In [41]:
def find_thresholds_np(y1, y2, debug=False):
    n = y1.shape[0]
    matching_zeros = ((y1 == y2)&(y1 == 0)).astype(int)
    matching_ones = ((y1 == y2)&(y1 == 1)).astype(int)
    res = []
    if sum(matching_ones) > sum(matching_zeros):
        res.append(0)
    for i in range(1, n):
        if debug: # если вам непонятна логика работы этой функции, передайте третьим аргументом True
            print(matching_zeros[:i], matching_ones[i:], i)
        if sum(matching_zeros[:i]) / i > 0.5 and sum(matching_ones[i:]) / (n - i) > 0.5:
            res.append(i)
    if sum(matching_zeros) / n > 0.5:
        res.append(n)
    return res

In [42]:
np.testing.assert_array_equal(find_thresholds([0], [0]), find_thresholds_np(np.array([0]), np.array([0])))
np.testing.assert_array_equal(find_thresholds([1], [1]), find_thresholds_np(np.array([1]), np.array([1])))
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 1], [0, 0, 1, 1]), 
    find_thresholds_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1]))
)
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 0, 0, 1, 1, 1], [0, 0, 0, 0, 0, 1, 1, 1]),
    find_thresholds_np(np.array([0, 0, 1, 0, 0, 1, 1, 1]), np.array([0, 0, 0, 0, 0, 1, 1, 1]))
)

### Разные действия с матрицами (3 балла)

Задание 21.

Дана матрица размера $(32, 3, 16, 16)$, заполненная случайными числами от 0 до 9. При помощи **ровно двух** преобразований приведите её к виду $(32, 1)$. При выполнении задания **можно** создавать вспомогательные матрицы!

In [44]:
data = np.random.randint(0, 10, size=(32, 3, 16, 16))

# Преобразование 1
data = data.reshape(32, 3*16*16)
# Преобразование 2
data = np.matmul(data, np.arange(0, 3*16*16).reshape(3*16*16, 1))

assert data.shape == (32, 1)

Задание 22.

Даны две матрицы $m_1$ размером $(32, 256)$ и $m_2$ размером $(32, 512)$, а также две вспомогательные матрицы $W_1$ размером $(256, 32)$ и $W_2$ размером $(512, 16)$. Используя **все** данные матрицы, сделайте так, чтобы на выходе получилась **ровно одна** матрица размером $(32, 32)$

In [67]:
m2.shape

(32, 512)

In [74]:
m1 = np.random.randint(0, 10, size=(32, 256))
m2 = np.random.randint(0, 10, size=(32, 512))
W1 = np.random.randint(0, 10, size=(256, 32))
W2 = np.random.randint(0, 10, size=(512, 16))

result = np.matmul(m1, W1) + np.matmul(m2, np.matmul(W2, np.ones((16,32))))

assert result.shape == (32, 32)

Задание 23.

Приведите полученную на последнем шаге матрицу к виду $(32, 3)$ и сделайте так, чтобы все значения в этой матрице были в промежутке от $0$ до $1$

In [75]:
# Вжух! (∩｀-´)⊃━☆ﾟ.*･｡ﾟ
result = np.matmul(result, np.ones((32,3)))
result = result / result.max()
assert result.shape == (32, 3)
assert ((result >= 0) & (result <= 1)).all()

In [ ]:
# [0 .. 0]