## Домашнее задание

В этой тетрадке вам предлагается реализовать задания при помощи библиотеки numpy. Крайне желательно при выполнении разных заданий не использовать циклы. Если вы не понимаете, как выполнить конкретную задачу без циклов - убирайте их постепенно, разбейте выполнение задачи на этапы и постепенно векторизуйте каждый этап.

Если вам непонятно, как выполнить ту или иную операцию - не стесняйтесь гуглить, если над вами повис дедлайн, а вы всё ещё на чём-то застряли - пишите преподу/в чат, это ок.

**Обсудить решение лучше и сделать в итоге хоть что-то гораздо лучше, чем скатать чужой код или сдать пустую тетрадку.**

In [1]:
import numpy as np

### Drill (1 балл)

Задание 1.

Инициализируйте нулями массивы следующих форм:

* (5)
* (5, 1)
* (10, 2)
* (3, 6, 2)
* (4, 3, 2, 1)

In [29]:
np.zeros(5)
np.zeros((5, 1))
np.zeros((10, 2))
np.zeros((3, 6, 2))
np.zeros((4, 3, 2, 1))

array([[[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]],


       [[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]],


       [[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]],


       [[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]]])

Задание 2.

Инициализируйте единицами массивы таких же форм и приведите их к целочисленному виду:

In [16]:
a = np.ones(5, int)
b = np.ones((5, 1), int)
c = np.ones((10, 2), int)
d = np.ones((3, 6, 2), int)
e = np.ones((4, 3, 2, 1), int)

Задание 3.

Выполните для векторов выше `reshape` в "форму"
* с двумя компонентами
* с тремя компонентами
* с четырьмя компонентами

In [27]:
a.reshape(5, -1)
a.reshape(5, -1, 1)
a.reshape(5, 1, 1, -1)

b.reshape(5, 1, -1)
b.reshape(5, -1, 1, 1)

c.reshape(5, 2, -1)
c.reshape(5, 2, 2, 1)

d.reshape(6, -1)
d.reshape(3, 3, 2, -1)

e.reshape(8, -2)
e.reshape(4, 6, -1)

array([[[1],
        [1],
        [1],
        [1],
        [1],
        [1]],

       [[1],
        [1],
        [1],
        [1],
        [1],
        [1]],

       [[1],
        [1],
        [1],
        [1],
        [1],
        [1]],

       [[1],
        [1],
        [1],
        [1],
        [1],
        [1]]])

Задание 4.

Для вектора ниже посчитайте его
* Максимум по 1 оси
* Минимум по 0 оси
* Сумму по всем осям
* Среднее по 0 оси
* Медиану по 1 оси

In [32]:
v = np.random.randint(0, 9, size=(5, 7))
print(v)

[[7 8 5 4 1 1 2]
 [0 3 4 0 4 5 5]
 [0 2 7 1 3 3 6]
 [7 3 8 5 8 1 2]
 [5 7 3 7 7 1 6]]


In [30]:
v.max(axis=1), v.min(axis=0), v.sum(), v.mean(axis=0), np.median(v, axis=1)

(array([8, 8, 8, 8, 8]),
 array([1, 0, 2, 0, 1, 0, 5]),
 141,
 array([3.8, 3.2, 2.4, 3.8, 5. , 3.6, 6.4]),
 array([3., 5., 5., 2., 3.]))

Задание 5.

Для всё того же вектора `v` выведите
* Его shape
* 0 компоненту его "формы"
* 1 компоненту его "формы"

In [38]:
v.shape, v[0], v[1]

((5, 7), array([7, 8, 5, 4, 1, 1, 2]), array([0, 3, 4, 0, 4, 5, 5]))

Задание 6.

Для этого же вектора выведите
* Все числа больше 5
* Все числа меньше 7 в обратном порядке
* Все числа больше 3, которые делятся на 4 без остатка
* Все числа, остаток от деления на 5 которых равен 3
* Индекс максимума
* Индекс минимума
* Cписок с индексами элементов отсортированного массива в исходном (неотсортированном)

In [310]:
v[v>5], v[v<7][::-1], v[(v>3) & (v%4==0)], v[v%5==3], v.argmax(), v.argmin(), v.argsort()

(array([7, 8, 7, 6, 7, 8, 8, 7, 7, 7, 6]),
 array([6, 1, 3, 5, 2, 1, 5, 3, 6, 3, 3, 1, 2, 0, 5, 5, 4, 0, 4, 3, 0, 2,
        1, 1, 4, 5]),
 array([8, 4, 4, 4, 8, 8]),
 array([8, 3, 3, 3, 3, 8, 8, 3]),
 1,
 7,
 array([[4, 5, 6, 3, 2, 0, 1],
        [0, 3, 1, 2, 4, 5, 6],
        [0, 3, 1, 4, 5, 6, 2],
        [5, 6, 1, 3, 0, 2, 4],
        [5, 2, 0, 6, 1, 3, 4]], dtype=int64))

Задание 7.

Выполните следующие операции над вектором (независимо, не обязательно делать это в последовательности):
* Умножьте его на 3
* Разделите на 7
* Возведите в степень $\frac{2}{3}$
* Посчитайте $\sin$ от него
* Посчитайте $\log$ от него

In [311]:
v*3, v/7, v**(2/3), np.sin(v), np.log(v)

<ipython-input-311-a55f3534aa53>:1: RuntimeWarning: divide by zero encountered in log
  v*3, v/7, v**(2/3), np.sin(v), np.log(v)


(array([[21, 24, 15, 12,  3,  3,  6],
        [ 0,  9, 12,  0, 12, 15, 15],
        [ 0,  6, 21,  3,  9,  9, 18],
        [21,  9, 24, 15, 24,  3,  6],
        [15, 21,  9, 21, 21,  3, 18]]),
 array([[1.        , 1.14285714, 0.71428571, 0.57142857, 0.14285714,
         0.14285714, 0.28571429],
        [0.        , 0.42857143, 0.57142857, 0.        , 0.57142857,
         0.71428571, 0.71428571],
        [0.        , 0.28571429, 1.        , 0.14285714, 0.42857143,
         0.42857143, 0.85714286],
        [1.        , 0.42857143, 1.14285714, 0.71428571, 1.14285714,
         0.14285714, 0.28571429],
        [0.71428571, 1.        , 0.42857143, 1.        , 1.        ,
         0.14285714, 0.85714286]]),
 array([[3.65930571, 4.        , 2.92401774, 2.5198421 , 1.        ,
         1.        , 1.58740105],
        [0.        , 2.08008382, 2.5198421 , 0.        , 2.5198421 ,
         2.92401774, 2.92401774],
        [0.        , 1.58740105, 3.65930571, 1.        , 2.08008382,
         2.08008

### Разные инициализации + индексирование (3 балла)

Задание 8.

Необходимо построить квадрат $3 \times 3$ из нечётных чисел

In [72]:
np.arange(1, 19, 2).reshape(3, 3)

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

Задание 9.

Необходимо построить квадрат $4 \times 4$ из четных чисел в обратном порядке

In [81]:
np.arange(2, 4*4*2+1, 2).reshape(4, 4)[::-1, ::-1]

array([[32, 30, 28, 26],
       [24, 22, 20, 18],
       [16, 14, 12, 10],
       [ 8,  6,  4,  2]])

Задание 10.

Необходимо построить сетку координат $11 \times 11$ с точкой $(0,0)$ в центре и шагом $0.1$ между клетками

In [176]:
np.arange(-5, 6, 1)*0.1*np.ones((11,11))+np.arange(5,-6,-1).reshape(11, 1)*np.ones((11,11))*0.1

array([[ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ],
       [-0.1,  0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9],
       [-0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8],
       [-0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7],
       [-0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6],
       [-0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,  0.5],
       [-0.6, -0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4],
       [-0.7, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3],
       [-0.8, -0.7, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2],
       [-0.9, -0.8, -0.7, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1],
       [-1. , -0.9, -0.8, -0.7, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1,  0. ]])

Задание 11.

Замощение сетки $8\times8$ при помощи $0$ и $1$ в шахматном порядке, клетка с индексом $(0,0)$ замощается $1$

In [112]:
a = np.ones((8, 8), int)
a[::2, 1::2]=0
a[1::2, ::2]=0
a

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

Задание 12.

То же замощение, но клетка с индексом $(0,0)$ замощается $0$

In [113]:
a = np.ones((8, 8), int)
a[1::2, 1::2]=0
a[::2, ::2]=0
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

Задание 13.

Необходимо построить нижне-треугольную матрицу переменного размера (задается передачей параметра в функцию). Это единичная матрица,замощённая $1$ под главной диагональю

In [135]:
def matrix(n):
    print(np.tri(n, n, -1, int))
    
matrix(5)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]]


Задание 14.

Необходимо построить верхне-треугольную матрицу переменного размера. Это единичная матрица, замощённая $1$ над главной диагональю

In [136]:
def matrix(n):
    print(1-np.tri(n, n, 0, int))
    
matrix(5)

[[0 1 1 1 1]
 [0 0 1 1 1]
 [0 0 0 1 1]
 [0 0 0 0 1]
 [0 0 0 0 0]]


Задание 15.

Необходимо построить матрицу, в которой единицы стоят на побочной диагонали (идущей из левого нижнего угла в правый верхний), в остальных местах стоят $0$

In [119]:
np.eye(3, 3, dtype=int)[::-1]

array([[0, 0, 1],
       [0, 1, 0],
       [1, 0, 0]])

### Операции + аггрегации (3 балла)

Задание 16.

Дана выборка $\{X_i\}$ некоторой случайной величины $X$, необходимо оценить
* Математическое ожидание $E[X] = \frac{1}{N}\sum_{i=1}^N X_i$ этой случайной величины
* Дисперсию $D[X] = \frac{1}{N}\sum_{i=1}^N (X_i - E[X])^2$ этой случайной величины

In [185]:
def expected_value(x):
    assert len(x) > 0
    return sum(x) / len(x)


def dispersion(x):
    assert len(x) > 0
    d = 0
    e = expected_value(x)
    for x_i in x:
        d += (x_i - e) ** 2
    return d / len(x)

In [186]:
def expected_value_np(x):
    return np.mean(x)

In [187]:
def dispersion_np(x):
    return np.var(x)

In [188]:
np.testing.assert_array_equal(expected_value([1]), expected_value_np(np.array([1])))
np.testing.assert_array_equal(expected_value([3, 4]), expected_value_np(np.array([3, 4])))
np.testing.assert_array_equal(expected_value([-1, 0, 1]), expected_value_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(expected_value([-99, -98]), expected_value_np(np.array([-99, -98])))

np.testing.assert_array_equal(dispersion([1]), dispersion_np(np.array([1])))
np.testing.assert_array_equal(dispersion([3, 4]), dispersion_np(np.array([3, 4])))
np.testing.assert_array_equal(dispersion([-1, 0, 1]), dispersion_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(dispersion([-99, -98]), dispersion_np(np.array([-99, -98])))

Задание 17.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое квадратов разностей их значений

In [191]:
def mean_square_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    # Здесь и далее эти проверки !не нужно! дублировать в свои функции; Здесь они для того, чтобы лишний раз подчеркнуть валидность входных данных
    s = 0
    for i in range(len(y1)):
        s += (y1[i] - y2[i]) ** 2
    return s / len(y1)

In [204]:
def mean_square_difference_np(y1, y2):
    return np.sum((y1-y2)**2)/y1.shape

In [205]:
assert mean_square_difference([1], [1]) == mean_square_difference_np(np.array([1]), np.array([1]))
assert mean_square_difference([1, 2], [1, 2]) == mean_square_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_square_difference([-1, 1], [0, 0]) == mean_square_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_square_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_square_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 18.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое модулей разностей их значений

In [208]:
def mean_abs_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    s = 0
    for i in range(len(y1)):
        s += abs(y1[i] - y2[i])
    return s / len(y1)

In [209]:
def mean_abs_difference_np(y1, y2):
    return np.sum(np.absolute(y1-y2))/y1.shape

In [210]:
assert mean_abs_difference([1], [1]) == mean_abs_difference_np(np.array([1]), np.array([1]))
assert mean_abs_difference([1, 2], [1, 2]) == mean_abs_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_abs_difference([-1, 1], [0, 0]) == mean_abs_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_abs_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_abs_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 19.

Даны два вектора $y_1$ и $y_2$, в которых присутствуют только $0$ и $1$. Необходимо посчитать вероятность совпадения - в скольких точках значения двух векторов совпадают

In [261]:
def matching_proba(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    assert len(set(y1)) <= 2
    assert len(set(y2)) <= 2
    assert 0 in set(y1) or 1 in set(y1) or (0 in set(y1) and 1 in set(y1))
    assert 0 in set(y2) or 1 in set(y2) or (0 in set(y2) and 1 in set(y2))

    return sum([y1[i] == y2[i] for i in range(len(y1))]) / len(y1)

In [262]:
def matching_proba_np(y1, y2):
    return np.sum((y1==y2))/y1.shape

In [263]:
np.testing.assert_array_equal(matching_proba([0, 1], [1, 0]), matching_proba_np(np.array([0, 1]), np.array([1, 0])))
np.testing.assert_array_equal(matching_proba([0, 1, 0, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 1, 0, 1]), np.array([0, 0, 1, 1])))
np.testing.assert_array_equal(matching_proba([0, 0, 1, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1])))

Задание 20.

Даны два вектора: $y_1$, $y_2$. В $y_1$ и $y_2$ присутствуют только $0$ и $1$.

Необходимо найти границы (индексы), такие, что если мы разделим вдоль какой-то из этих границ оба вектора на две части, то
* в левой части пересекающихся в $y_1$ и $y_2$ нулей будет строго больше, чем пересекающихся единиц или непересекающихся элементов
* в правой - пересекающихся единиц строго больше, чем пересекающихся нулей или непересекающихся элементов.

Если какая-то из частей не содержит элементов вовсе, то будем считать, что она подходит под условие.

In [402]:
def find_thresholds(y1, y2, debug=False):
    assert len(y1) == len(y2) and len(y1) > 0
    n = len(y1)
    matching_zeros = [1 if y1[i] == y2[i] == 0 else 0 for i in range(n)]
    matching_ones = [1 if y1[i] == y2[i] == 1 else 0 for i in range(n)]
    res = []
    if sum(matching_ones) / n > 0.5:
        res.append(0)
    for i in range(1, n):
        if debug: # если вам непонятна логика работы этой функции, передайте третьим аргументом True
            print(matching_zeros[:i], matching_ones[i:], i)
        if sum(matching_zeros[:i]) / i > 0.5 and sum(matching_ones[i:]) / (n - i) > 0.5:
            res.append(i)
    if sum(matching_zeros) / n > 0.5:
        res.append(n)
    return res

In [536]:
def find_thresholds_np(y1, y2):
    a = np.append(np.array([1]),np.cumsum(1-np.logical_or(y1, y2))) 
    b = np.append(np.array([0]),np.cumsum(np.logical_and(y1, y2)))
    c = np.append(np.array([0]),np.cumsum(np.logical_xor(y1, y2)))
    a1 = np.append(np.cumsum((1-np.logical_or(y1, y2))[::-1])[::-1], np.array([0]))
    b1 = np.append(np.cumsum((np.logical_and(y1, y2))[::-1])[::-1], np.array([1]))
    c1 = np.append(np.cumsum((np.logical_xor(y1, y2))[::-1])[::-1], np.array([0]))
    return np.array(np.logical_and(np.array(b1>a1+c1), np.array(a>b+c)).nonzero()).reshape(-1)

In [538]:
np.testing.assert_array_equal(find_thresholds([0], [0]), find_thresholds_np(np.array([0]), np.array([0])))
np.testing.assert_array_equal(find_thresholds([1], [1]), find_thresholds_np(np.array([1]), np.array([1])))
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 1], [0, 0, 1, 1]), 
    find_thresholds_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1]))
)
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 0, 0, 1, 1, 1], [0, 0, 0, 0, 0, 1, 1, 1]),
    find_thresholds_np(np.array([0, 0, 1, 0, 0, 1, 1, 1]), np.array([0, 0, 0, 0, 0, 1, 1, 1]))
)

### Разные действия с матрицами (3 балла)

Задание 21.

Дана матрица размера $(32, 3, 16, 16)$, заполненная случайными числами от 0 до 9. При помощи **ровно двух** преобразований приведите её к виду $(32, 1)$. При выполнении задания **можно** создавать вспомогательные матрицы!

In [283]:
data = np.random.randint(0, 10, size=(32, 3, 16, 16))

#data = data.reshape(32, -1)
data = np.matmul(data.reshape(32, -1), np.random.randint(0, 10, size=(3*16*16, 1)))

assert data.shape == (32, 1)

Задание 22.

Даны две матрицы $m_1$ размером $(32, 256)$ и $m_2$ размером $(32, 512)$, а также две вспомогательные матрицы $W_1$ размером $(256, 32)$ и $W_2$ размером $(512, 16)$. Используя **все** данные матрицы, сделайте так, чтобы на выходе получилась **ровно одна** матрица размером $(32, 32)$

In [308]:
m1 = np.random.randint(0, 10, size=(32, 256))
m2 = np.random.randint(0, 10, size=(32, 512))
W1 = np.random.randint(0, 10, size=(256, 32))
W2 = np.random.randint(0, 10, size=(512, 16))

result = np.matmul(np.matmul(m1,W1), np.matmul(np.matmul(m2, W2), np.matmul(m2, W2).reshape(16, 32)))

assert result.shape == (32, 32)

Задание 23.

Приведите полученную на последнем шаге матрицу к виду $(32, 3)$ и сделайте так, чтобы все значения в этой матрице были в промежутке от $0$ до $1$

In [309]:
# Вжух! (∩｀-´)⊃━☆ﾟ.*･｡ﾟ
result = np.matmul(result, np.random.randint(0, 1, size=(32, ))) 

assert result.shape == (32, 3)
assert ((result >= 0) & (result <= 1)).all()