## Домашнее задание

В этой тетрадке вам предлагается реализовать задания при помощи библиотеки numpy. Крайне желательно при выполнении разных заданий не использовать циклы. Если вы не понимаете, как выполнить конкретную задачу без циклов - убирайте их постепенно, разбейте выполнение задачи на этапы и постепенно векторизуйте каждый этап.

Если вам непонятно, как выполнить ту или иную операцию - не стесняйтесь гуглить, если над вами повис дедлайн, а вы всё ещё на чём-то застряли - пишите преподу/в чат, это ок.

**Обсудить решение лучше и сделать в итоге хоть что-то гораздо лучше, чем скатать чужой код или сдать пустую тетрадку.**

In [1]:
import numpy as np

### Drill (1 балл)

Задание 1.

Инициализируйте нулями массивы следующих форм:

* (5)
* (5, 1)
* (10, 2)
* (3, 6, 2)
* (4, 3, 2, 1)

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.zeros((5, 1))

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [4]:
np.zeros((10, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [5]:
np.zeros((3, 6, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [6]:
np.zeros((4, 3, 2, 1))

array([[[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]],


       [[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]],


       [[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]],


       [[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]]])

Задание 2.

Инициализируйте единицами массивы таких же форм и приведите их к целочисленному виду:

In [7]:
np.ones(5).astype(int)

array([1, 1, 1, 1, 1])

In [8]:
np.ones((5, 1)).astype(int)

array([[1],
       [1],
       [1],
       [1],
       [1]])

In [9]:
np.ones((10, 2)).astype(int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [10]:
np.ones((3, 6, 2)).astype(int)

array([[[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]])

In [11]:
np.ones((4, 3, 2, 1)).astype(int)

array([[[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]],


       [[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]],


       [[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]],


       [[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]]])

Задание 3.

Выполните для векторов выше `reshape` в "форму"
* с двумя компонентами
* с тремя компонентами
* с четырьмя компонентами

In [12]:
np.zeros(5).reshape((1, 5))

array([[0., 0., 0., 0., 0.]])

In [13]:
np.zeros(5).reshape((1, 1, 5))

array([[[0., 0., 0., 0., 0.]]])

In [14]:
np.zeros(5).reshape((1, 1, 1, 5))

array([[[[0., 0., 0., 0., 0.]]]])

In [15]:
np.zeros((5, 1)).reshape((5, 1))

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [16]:
np.zeros((5, 1)).reshape((1, 5, 1))

array([[[0.],
        [0.],
        [0.],
        [0.],
        [0.]]])

In [17]:
np.zeros((5, 1)).reshape((1, 1, 5, 1))

array([[[[0.],
         [0.],
         [0.],
         [0.],
         [0.]]]])

In [18]:
np.zeros((10, 2)).reshape((4, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.zeros((10, 2)).reshape((4, 5, 1))

array([[[0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.]]])

In [20]:
np.zeros((10, 2)).reshape((2, 2, 1, 5))

array([[[[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]]]])

In [21]:
np.zeros((3, 6, 2)).reshape((3, 12))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [22]:
np.zeros((3, 6, 2)).reshape((3, 2, 6))

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

In [23]:
np.zeros((3, 6, 2)).reshape((3, 2, 2, 3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [24]:
np.zeros((4, 3, 2, 1)).reshape((4, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [25]:
np.zeros((4, 3, 2, 1)).reshape((4, 2, 3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [26]:
np.zeros((4, 3, 2, 1)).reshape((4, 2, 1, 3))

array([[[[0., 0., 0.]],

        [[0., 0., 0.]]],


       [[[0., 0., 0.]],

        [[0., 0., 0.]]],


       [[[0., 0., 0.]],

        [[0., 0., 0.]]],


       [[[0., 0., 0.]],

        [[0., 0., 0.]]]])

In [27]:
np.ones(5).astype(int).reshape((1, 5))

array([[1, 1, 1, 1, 1]])

In [28]:
np.ones(5).astype(int).reshape((1, 1, 5))

array([[[1, 1, 1, 1, 1]]])

In [29]:
np.ones(5).astype(int).reshape((1, 1, 1, 5))

array([[[[1, 1, 1, 1, 1]]]])

In [30]:
np.ones((5, 1)).astype(int).reshape((5, 1))

array([[1],
       [1],
       [1],
       [1],
       [1]])

In [31]:
np.ones((5, 1)).astype(int).reshape((5, 1, 1))

array([[[1]],

       [[1]],

       [[1]],

       [[1]],

       [[1]]])

In [32]:
np.ones((5, 1)).astype(int).reshape((5, 1, 1, 1))

array([[[[1]]],


       [[[1]]],


       [[[1]]],


       [[[1]]],


       [[[1]]]])

In [33]:
np.ones((10, 2)).astype(int).reshape((4, 5))

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [34]:
np.ones((10, 2)).astype(int).reshape((2, 2, 5))

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [35]:
np.ones((10, 2)).astype(int).reshape((1, 2, 2, 5))

array([[[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]]])

In [36]:
np.ones((3, 6, 2)).astype(int).reshape((3, 12))

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [37]:
np.ones((3, 6, 2)).astype(int).reshape((3, 2, 6))

array([[[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]]])

In [38]:
np.ones((3, 6, 2)).astype(int).reshape((3, 2, 3, 2))

array([[[[1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1]]]])

In [39]:
np.ones((4, 3, 2, 1)).astype(int).reshape((4, 6))

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [40]:
np.ones((4, 3, 2, 1)).astype(int).reshape((4, 3, 2))

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])

In [41]:
np.ones((4, 3, 2, 1)).astype(int).reshape((4, 3, 1, 2))

array([[[[1, 1]],

        [[1, 1]],

        [[1, 1]]],


       [[[1, 1]],

        [[1, 1]],

        [[1, 1]]],


       [[[1, 1]],

        [[1, 1]],

        [[1, 1]]],


       [[[1, 1]],

        [[1, 1]],

        [[1, 1]]]])

Задание 4.

Для вектора ниже посчитайте его
* Максимум по 1 оси
* Минимум по 0 оси
* Сумму по всем осям
* Среднее по 0 оси
* Медиану по 1 оси

In [42]:
v = np.random.randint(0, 9, size=(5, 7))

In [43]:
v.max(axis=1)

array([8, 8, 8, 8, 5])

In [44]:
v.min(axis=0)

array([1, 3, 1, 1, 0, 1, 0])

In [45]:
v.sum()

128

In [46]:
v.mean(axis=0)

array([3.6, 6.2, 4.6, 4.4, 1. , 3. , 2.8])

In [47]:
np.median(v, axis=1)

array([4., 4., 4., 4., 3.])

Задание 5.

Для всё того же вектора `v` выведите
* Его shape
* 0 компоненту его "формы"
* 1 компоненту его "формы"

In [48]:
v.shape

(5, 7)

In [49]:
v.shape[0]

5

In [50]:
v.shape[1]

7

Задание 6.

Для этого же вектора выведите
* Все числа больше 5
* Все числа меньше 7 в обратном порядке
* Все числа больше 3, которые делятся на 4 без остатка
* Все числа, остаток от деления на 5 которых равен 3
* Индекс максимума
* Индекс минимума
* Cписок с индексами элементов отсортированного массива в исходном (неотсортированном)

In [51]:
v[v > 5]

array([8, 8, 8, 8, 7, 8, 7, 6])

In [52]:
v[v < 7]

array([4, 4, 0, 2, 1, 3, 4, 4, 0, 5, 4, 1, 5, 4, 2, 0, 4, 1, 1, 1, 6, 2,
       3, 1, 4, 0, 5, 3])

In [53]:
v[(v > 3) & (v % 4 == 0)]

array([8, 8, 4, 4, 4, 4, 8, 4, 8, 4, 4, 8, 4])

In [54]:
v[v % 5 == 3]

array([8, 8, 3, 8, 8, 8, 3, 3])

In [55]:
(v.argmax() // v.shape[1], v.argmax() % v.shape[1])

(0, 0)

In [56]:
(v.argmin() // v.shape[1], v.argmin() % v.shape[1])

(0, 4)

In [57]:
v.argsort()

array([[4, 6, 5, 2, 3, 0, 1],
       [4, 0, 1, 2, 6, 5, 3],
       [6, 0, 5, 4, 3, 2, 1],
       [3, 4, 5, 0, 6, 2, 1],
       [4, 2, 0, 1, 6, 3, 5]])

Задание 7.

Выполните следующие операции над вектором (независимо, не обязательно делать это в последовательности):
* Умножьте его на 3
* Разделите на 7
* Возведите в степень $\frac{2}{3}$
* Посчитайте $\sin$ от него
* Посчитайте $\log$ от него

In [58]:
v * 3

array([[24, 24, 12, 12,  0,  6,  3],
       [ 9, 12, 12, 24,  0, 15, 12],
       [ 3, 24, 21, 15, 12,  6,  0],
       [12, 24, 21,  3,  3,  3, 18],
       [ 6,  9,  3, 12,  0, 15,  9]])

In [59]:
v / 7

array([[1.14285714, 1.14285714, 0.57142857, 0.57142857, 0.        ,
        0.28571429, 0.14285714],
       [0.42857143, 0.57142857, 0.57142857, 1.14285714, 0.        ,
        0.71428571, 0.57142857],
       [0.14285714, 1.14285714, 1.        , 0.71428571, 0.57142857,
        0.28571429, 0.        ],
       [0.57142857, 1.14285714, 1.        , 0.14285714, 0.14285714,
        0.14285714, 0.85714286],
       [0.28571429, 0.42857143, 0.14285714, 0.57142857, 0.        ,
        0.71428571, 0.42857143]])

In [60]:
v ** (2 / 3)

array([[4.        , 4.        , 2.5198421 , 2.5198421 , 0.        ,
        1.58740105, 1.        ],
       [2.08008382, 2.5198421 , 2.5198421 , 4.        , 0.        ,
        2.92401774, 2.5198421 ],
       [1.        , 4.        , 3.65930571, 2.92401774, 2.5198421 ,
        1.58740105, 0.        ],
       [2.5198421 , 4.        , 3.65930571, 1.        , 1.        ,
        1.        , 3.30192725],
       [1.58740105, 2.08008382, 1.        , 2.5198421 , 0.        ,
        2.92401774, 2.08008382]])

In [61]:
np.sin(v)

array([[ 0.98935825,  0.98935825, -0.7568025 , -0.7568025 ,  0.        ,
         0.90929743,  0.84147098],
       [ 0.14112001, -0.7568025 , -0.7568025 ,  0.98935825,  0.        ,
        -0.95892427, -0.7568025 ],
       [ 0.84147098,  0.98935825,  0.6569866 , -0.95892427, -0.7568025 ,
         0.90929743,  0.        ],
       [-0.7568025 ,  0.98935825,  0.6569866 ,  0.84147098,  0.84147098,
         0.84147098, -0.2794155 ],
       [ 0.90929743,  0.14112001,  0.84147098, -0.7568025 ,  0.        ,
        -0.95892427,  0.14112001]])

In [62]:
np.log(v)

/tmp/ipykernel_3541971/957696640.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(v)


array([[2.07944154, 2.07944154, 1.38629436, 1.38629436,       -inf,
        0.69314718, 0.        ],
       [1.09861229, 1.38629436, 1.38629436, 2.07944154,       -inf,
        1.60943791, 1.38629436],
       [0.        , 2.07944154, 1.94591015, 1.60943791, 1.38629436,
        0.69314718,       -inf],
       [1.38629436, 2.07944154, 1.94591015, 0.        , 0.        ,
        0.        , 1.79175947],
       [0.69314718, 1.09861229, 0.        , 1.38629436,       -inf,
        1.60943791, 1.09861229]])

### Разные инициализации + индексирование (3 балла)

Задание 8.

Необходимо построить квадрат $3 \times 3$ из нечётных чисел

In [63]:
np.arange(1, 18, 2).reshape(3, 3)

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

Задание 9.

Необходимо построить квадрат $4 \times 4$ из четных чисел в обратном порядке

In [64]:
np.arange(32, 1, -2).reshape(4, 4)

array([[32, 30, 28, 26],
       [24, 22, 20, 18],
       [16, 14, 12, 10],
       [ 8,  6,  4,  2]])

Задание 10.

Необходимо построить сетку координат $11 \times 11$ с точкой $(0,0)$ в центре и шагом $0.1$ между клетками

In [65]:
np.round(np.mgrid[-0.5:0.6:0.1, -0.5:0.6:0.1], decimals=1)

array([[[-0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5,
         -0.5],
        [-0.4, -0.4, -0.4, -0.4, -0.4, -0.4, -0.4, -0.4, -0.4, -0.4,
         -0.4],
        [-0.3, -0.3, -0.3, -0.3, -0.3, -0.3, -0.3, -0.3, -0.3, -0.3,
         -0.3],
        [-0.2, -0.2, -0.2, -0.2, -0.2, -0.2, -0.2, -0.2, -0.2, -0.2,
         -0.2],
        [-0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1,
         -0.1],
        [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
          0. ],
        [ 0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,
          0.1],
        [ 0.2,  0.2,  0.2,  0.2,  0.2,  0.2,  0.2,  0.2,  0.2,  0.2,
          0.2],
        [ 0.3,  0.3,  0.3,  0.3,  0.3,  0.3,  0.3,  0.3,  0.3,  0.3,
          0.3],
        [ 0.4,  0.4,  0.4,  0.4,  0.4,  0.4,  0.4,  0.4,  0.4,  0.4,
          0.4],
        [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,
          0.5]],

       [[-0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3, 

Задание 11.

Замощение сетки $8\times8$ при помощи $0$ и $1$ в шахматном порядке, клетка с индексом $(0,0)$ замощается $1$

In [66]:
shape = (8, 8)

(np.indices(shape).sum(axis=0) + np.ones(shape, dtype=int)) % 2

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

Задание 12.

То же замощение, но клетка с индексом $(0,0)$ замощается $0$

In [67]:
np.indices((8, 8)).sum(axis=0) % 2

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

Задание 13.

Необходимо построить нижне-треугольную матрицу переменного размера (задается передачей параметра в функцию). Это единичная матрица,замощённая $1$ под главной диагональю

In [68]:
def create_tril(size):
    return np.tril(np.ones((size, size)))
    
create_tril(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

Задание 14.

Необходимо построить верхне-треугольную матрицу переменного размера. Это единичная матрица, замощённая $1$ над главной диагональю

In [69]:
def create_triu(size):
    return np.triu(np.ones((size, size)))
    
create_triu(10)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

Задание 15.

Необходимо построить матрицу, в которой единицы стоят на побочной диагонали (идущей из левого нижнего угла в правый верхний), в остальных местах стоят $0$

In [92]:
size = 10

np.rot90(np.eye(size, dtype=int))

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

### Операции + аггрегации (3 балла)

Задание 16.

Дана выборка $\{X_i\}$ некоторой случайной величины $X$, необходимо оценить
* Математическое ожидание $E[X] = \frac{1}{N}\sum_{i=1}^N X_i$ этой случайной величины
* Дисперсию $D[X] = \frac{1}{N}\sum_{i=1}^N (X_i - E[X])^2$ этой случайной величины

In [71]:
def expected_value(x):
    assert len(x) > 0
    return sum(x) / len(x)


def dispersion(x):
    assert len(x) > 0
    d = 0
    e = expected_value(x)
    for x_i in x:
        d += (x_i - e) ** 2
    return d / len(x)

In [72]:
def expected_value_np(x):
    return x.sum() / x.shape[0]

In [73]:
def dispersion_np(x):
    return ((x - expected_value_np(x)) ** 2).sum() / x.shape[0]

In [74]:
np.testing.assert_array_equal(expected_value([1]), expected_value_np(np.array([1])))
np.testing.assert_array_equal(expected_value([3, 4]), expected_value_np(np.array([3, 4])))
np.testing.assert_array_equal(expected_value([-1, 0, 1]), expected_value_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(expected_value([-99, -98]), expected_value_np(np.array([-99, -98])))

np.testing.assert_array_equal(dispersion([1]), dispersion_np(np.array([1])))
np.testing.assert_array_equal(dispersion([3, 4]), dispersion_np(np.array([3, 4])))
np.testing.assert_array_equal(dispersion([-1, 0, 1]), dispersion_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(dispersion([-99, -98]), dispersion_np(np.array([-99, -98])))

Задание 17.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое квадратов разностей их значений

In [75]:
def mean_square_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    # Здесь и далее эти проверки !не нужно! дублировать в свои функции; Здесь они для того, чтобы лишний раз подчеркнуть валидность входных данных
    s = 0
    for i in range(len(y1)):
        s += (y1[i] - y2[i]) ** 2
    return s / len(y1)

In [76]:
def mean_square_difference_np(y1, y2):
    return ((y1 - y2) ** 2).sum() / y1.shape[0]

In [77]:
assert mean_square_difference([1], [1]) == mean_square_difference_np(np.array([1]), np.array([1]))
assert mean_square_difference([1, 2], [1, 2]) == mean_square_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_square_difference([-1, 1], [0, 0]) == mean_square_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_square_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_square_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 18.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое модулей разностей их значений

In [78]:
def mean_abs_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    s = 0
    for i in range(len(y1)):
        s += abs(y1[i] - y2[i])
    return s / len(y1)

In [79]:
def mean_abs_difference_np(y1, y2):
    return (np.abs(y1 - y2)).sum() / y1.shape[0]

In [80]:
assert mean_abs_difference([1], [1]) == mean_abs_difference_np(np.array([1]), np.array([1]))
assert mean_abs_difference([1, 2], [1, 2]) == mean_abs_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_abs_difference([-1, 1], [0, 0]) == mean_abs_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_abs_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_abs_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 19.

Даны два вектора $y_1$ и $y_2$, в которых присутствуют только $0$ и $1$. Необходимо посчитать вероятность совпадения - в скольких точках значения двух векторов совпадают

In [81]:
def matching_proba(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    assert len(set(y1)) <= 2
    assert len(set(y2)) <= 2
    assert 0 in set(y1) or 1 in set(y1) or (0 in set(y1) and 1 in set(y1))
    assert 0 in set(y2) or 1 in set(y2) or (0 in set(y2) and 1 in set(y2))

    return sum([y1[i] == y2[i] for i in range(len(y1))]) / len(y1)

In [82]:
def matching_proba_np(y1, y2):
    return 1 - np.bitwise_xor(y1, y2).sum() / y1.shape[0]

In [83]:
np.testing.assert_array_equal(matching_proba([0, 1], [1, 0]), matching_proba_np(np.array([0, 1]), np.array([1, 0])))
np.testing.assert_array_equal(matching_proba([0, 1, 0, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 1, 0, 1]), np.array([0, 0, 1, 1])))
np.testing.assert_array_equal(matching_proba([0, 0, 1, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1])))

Задание 20.

Даны два вектора: $y_1$, $y_2$. В $y_1$ и $y_2$ присутствуют только $0$ и $1$.

Необходимо найти границы (индексы), такие, что если мы разделим вдоль какой-то из этих границ оба вектора на две части, то
* в левой части пересекающихся в $y_1$ и $y_2$ нулей будет строго больше, чем пересекающихся единиц или непересекающихся элементов
* в правой - пересекающихся единиц строго больше, чем пересекающихся нулей или непересекающихся элементов.

Если какая-то из частей не содержит элементов вовсе, то будем считать, что она подходит под условие.

In [84]:
def find_thresholds(y1, y2, debug=False):
    assert len(y1) == len(y2) and len(y1) > 0
    n = len(y1)
    matching_zeros = [1 if y1[i] == y2[i] == 0 else 0 for i in range(n)]
    matching_ones = [1 if y1[i] == y2[i] == 1 else 0 for i in range(n)]
    res = []
    if sum(matching_ones) / n > 0.5:
        res.append(0)
    for i in range(1, n):
        if debug: # если вам непонятна логика работы этой функции, передайте третьим аргументом True
            print(matching_zeros[:i], matching_ones[i:], i)
        if sum(matching_zeros[:i]) / i > 0.5 and sum(matching_ones[i:]) / (n - i) > 0.5:
            res.append(i)
    if sum(matching_zeros) / n > 0.5:
        res.append(n)
    return res

In [85]:
def find_thresholds_np(y1, y2):
    length = y1.shape[0]
    
    matching_zeros = np.bitwise_and(np.ones(length, dtype=int) - y1, np.ones(length, dtype=int) - y2)
    matching_ones = np.bitwise_and(y1, y2)
    
    triu_matr = np.triu(np.ones((length, length), dtype=int))[:,:length - 1];
    tril_matr = np.tril(np.ones((length, length), dtype=int), -1)[:,:length - 1];
        
    ind = np.arange(1, length)
    
    res = np.array([], dtype=int)
    
    
    if matching_ones.sum() / length > 0.5:
        res = np.append(res, 0)
    
    zero_pref = np.matmul(matching_zeros[:length], triu_matr)
    one_pref = np.matmul(matching_ones[:length], tril_matr)
    
    res = np.append(res, ind[(zero_pref / ind > 0.5) & (one_pref / ind[::-1] > 0.5)])
        
    if matching_zeros.sum() / length > 0.5:
        res = np.append(res, length)
    
    return res


In [86]:
np.testing.assert_array_equal(find_thresholds([0], [0]), find_thresholds_np(np.array([0]), np.array([0])))
np.testing.assert_array_equal(find_thresholds([1], [1]), find_thresholds_np(np.array([1]), np.array([1])))
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 1], [0, 0, 1, 1]), 
    find_thresholds_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1]))
)
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 0, 0, 1, 1, 1], [0, 0, 0, 0, 0, 1, 1, 1]),
    find_thresholds_np(np.array([0, 0, 1, 0, 0, 1, 1, 1]), np.array([0, 0, 0, 0, 0, 1, 1, 1]))
)

### Разные действия с матрицами (3 балла)

Задание 21.

Дана матрица размера $(32, 3, 16, 16)$, заполненная случайными числами от 0 до 9. При помощи **ровно двух** преобразований приведите её к виду $(32, 1)$. При выполнении задания **можно** создавать вспомогательные матрицы!

In [87]:
data = np.random.randint(0, 10, size=(32, 3, 16, 16))

temp_first = np.random.randint(0, 10, size=(16, 1))
data = np.matmul(data, temp_first)

data = data.reshape((32, 1, -1)).sum(axis=2)

assert data.shape == (32, 1)

Задание 22.

Даны две матрицы $m_1$ размером $(32, 256)$ и $m_2$ размером $(32, 512)$, а также две вспомогательные матрицы $W_1$ размером $(256, 32)$ и $W_2$ размером $(512, 16)$. Используя **все** данные матрицы, сделайте так, чтобы на выходе получилась **ровно одна** матрица размером $(32, 32)$

In [88]:
m1 = np.random.randint(0, 10, size=(32, 256))
m2 = np.random.randint(0, 10, size=(32, 512))
W1 = np.random.randint(0, 10, size=(256, 32))
W2 = np.random.randint(0, 10, size=(512, 16))


temp = np.matmul(m2, W2)
result = np.matmul(m1, W1) + np.hstack((temp, temp))
assert result.shape == (32, 32)

Задание 23.

Приведите полученную на последнем шаге матрицу к виду $(32, 3)$ и сделайте так, чтобы все значения в этой матрице были в промежутке от $0$ до $1$

In [89]:
# Вжух! (∩｀-´)⊃━☆ﾟ.*･｡ﾟ
result = result[0:, :3]
result = result / result.max()

assert result.shape == (32, 3)
assert ((result >= 0) & (result <= 1)).all()