## Домашнее задание

В этой тетрадке вам предлагается реализовать задания при помощи библиотеки numpy. Крайне желательно при выполнении разных заданий не использовать циклы. Если вы не понимаете, как выполнить конкретную задачу без циклов - убирайте их постепенно, разбейте выполнение задачи на этапы и постепенно векторизуйте каждый этап.

Если вам непонятно, как выполнить ту или иную операцию - не стесняйтесь гуглить, если над вами повис дедлайн, а вы всё ещё на чём-то застряли - пишите преподу/в чат, это ок.

**Обсудить решение лучше и сделать в итоге хоть что-то гораздо лучше, чем скатать чужой код или сдать пустую тетрадку.**

In [6]:
import numpy as np

### Drill (1 балл)

Задание 1.

Инициализируйте нулями массивы следующих форм:

* (5)
* (5, 1)
* (10, 2)
* (3, 6, 2)
* (4, 3, 2, 1)

In [3]:
a = np.zeros(5)
b = np.zeros((5,1))
c = np.zeros((10,2))
d = np.zeros((3,6,3))
e = np.zeros((4,3,2,1))

In [4]:
c

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

Задание 2.

Инициализируйте единицами массивы таких же форм и приведите их к целочисленному виду:

In [35]:
a = np.ones(5).astype(int)
b = np.ones((5,1)).astype(int)
c = np.ones((10,2)).astype(int)
d = np.ones((3,6,3)).astype(int)
e = np.ones((4,3,2,1)).astype(int)


In [36]:
c

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

Задание 3.

Выполните для векторов выше `reshape` в "форму"
* с двумя компонентами
* с тремя компонентами
* с четырьмя компонентами

In [38]:
# Массив a

a.reshape(5,1)
a.reshape(5,1,1)
a.reshape(5,1,1,1)
# Массив b

b.reshape(1,5)
b.reshape(1, 1, 5)
b.reshape(1, 1, 1, 5)
# Массив c

c.reshape(5,4)
c.reshape(5,2,2)
c.reshape(1, 10, 2, 1)
# Массив d

d.reshape(9, 6)
d.reshape(3, 3, 6)
d.reshape(3,3,3,2)
# Массив e

e.reshape(4, 6)
e.reshape(4,3,2)
e.reshape(2, 3, 2, 2)

e

array([[[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]],


       [[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]],


       [[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]],


       [[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]]])

Задание 4.

Для вектора ниже посчитайте его
* Максимум по 1 оси
* Минимум по 0 оси
* Сумму по всем осям
* Среднее по 0 оси
* Медиану по 1 оси

In [21]:
v = np.random.randint(0, 9, size=(5, 7))

In [39]:
print(v)
print(f"Максимум по 1 оси: {np.max(v, axis=1)}")
print(f"Минимум по 0 оси: {np.min(v, axis=0)}")
print(f"Сумма по всем осям: {np.sum(v)}")
print(f"Среднее по 0 оси: {np.mean(v, axis=0)}")
print(f"Медиана по 1 оси: {np.median(v, axis=1).astype(int)}") # точно знаем, что работаем с целыми числами,
# поэтому для красоты можно в целочисленный тип перевести

[[7 4 1 8 4 4 7]
 [3 2 2 7 3 2 1]
 [6 2 3 6 4 6 7]
 [5 6 6 8 1 5 3]
 [2 1 1 8 2 7 3]]
Максимум по 1 оси: [8 7 7 8 8]
Минимум по 0 оси: [2 1 1 6 1 2 1]
Сумма по всем осям: 147
Среднее по 0 оси: [4.6 3.  2.6 7.4 2.8 4.8 4.2]
Медиана по 1 оси: [4 2 6 5 2]


Задание 5.

Для всё того же вектора `v` выведите
* Его shape
* 0 компоненту его "формы"
* 1 компоненту его "формы"

In [23]:
print(v.shape)
print(len(v))
print(len(v[0]))

(5, 7)
5
7


Задание 6.

Для этого же вектора выведите
* Все числа больше 5
* Все числа меньше 7 в обратном порядке
* Все числа больше 3, которые делятся на 4 без остатка
* Все числа, остаток от деления на 5 которых равен 3
* Индекс максимума
* Индекс минимума
* Cписок с индексами элементов отсортированного массива в исходном (неотсортированном)

In [33]:
print(v[v > 5]) 
print(np.flip(v[v < 7]))
print(v[(v > 3) & (v % 4 == 0)])
print(v[v % 5 == 3])
print(np.argmax(v))
print(np.argmin(v))
print(np.argsort(v))

[7 8 7 7 6 6 6 7 6 6 8 8 7]
[3 2 1 1 2 3 5 1 6 6 5 6 4 6 3 2 6 1 2 3 2 2 3 4 4 1 4]
[4 8 4 4 4 8 8]
[8 3 3 3 8 3 8 3]
3
2
[[2 1 4 5 0 6 3]
 [6 1 2 5 0 4 3]
 [1 2 4 0 3 5 6]
 [4 6 0 5 1 2 3]
 [1 2 0 4 6 5 3]]


Задание 7.

Выполните следующие операции над вектором (независимо, не обязательно делать это в последовательности):
* Умножьте его на 3
* Разделите на 7
* Возведите в степень $\frac{2}{3}$
* Посчитайте $\sin$ от него
* Посчитайте $\log$ от него

In [25]:
np.sin(v)
v*3
np.log(v)
v / 7
v ** (2/3)



array([[3.65930571, 2.5198421 , 1.        , 4.        , 2.5198421 ,
        2.5198421 , 3.65930571],
       [2.08008382, 1.58740105, 1.58740105, 3.65930571, 2.08008382,
        1.58740105, 1.        ],
       [3.30192725, 1.58740105, 2.08008382, 3.30192725, 2.5198421 ,
        3.30192725, 3.65930571],
       [2.92401774, 3.30192725, 3.30192725, 4.        , 1.        ,
        2.92401774, 2.08008382],
       [1.58740105, 1.        , 1.        , 4.        , 1.58740105,
        3.65930571, 2.08008382]])

### Разные инициализации + индексирование (3 балла)

Задание 8.

Необходимо построить квадрат $3 \times 3$ из нечётных чисел

In [13]:
print(np.arange(1, 18, 2).reshape(3,3))


[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]


Задание 9.

Необходимо построить квадрат $4 \times 4$ из четных чисел в обратном порядке

In [14]:
print(np.flip(np.arange(0,31,2)).reshape(4,4))


[[30 28 26 24]
 [22 20 18 16]
 [14 12 10  8]
 [ 6  4  2  0]]


Задание 10.

Необходимо построить сетку координат $11 \times 11$ с точкой $(0,0)$ в центре и шагом $0.1$ между клетками

In [152]:
import pprint as pp
x = np.linspace(-0.5, 0.5, 11)
y = np.linspace(-0.5, 0.5, 11)
[X, Y] = np.meshgrid(x, y)

np.concatenate((X.reshape(11,11,1), Y.reshape(11,11,1)), axis = 2)





array([[[-0.5, -0.5],
        [-0.4, -0.5],
        [-0.3, -0.5],
        [-0.2, -0.5],
        [-0.1, -0.5],
        [ 0. , -0.5],
        [ 0.1, -0.5],
        [ 0.2, -0.5],
        [ 0.3, -0.5],
        [ 0.4, -0.5],
        [ 0.5, -0.5]],

       [[-0.5, -0.4],
        [-0.4, -0.4],
        [-0.3, -0.4],
        [-0.2, -0.4],
        [-0.1, -0.4],
        [ 0. , -0.4],
        [ 0.1, -0.4],
        [ 0.2, -0.4],
        [ 0.3, -0.4],
        [ 0.4, -0.4],
        [ 0.5, -0.4]],

       [[-0.5, -0.3],
        [-0.4, -0.3],
        [-0.3, -0.3],
        [-0.2, -0.3],
        [-0.1, -0.3],
        [ 0. , -0.3],
        [ 0.1, -0.3],
        [ 0.2, -0.3],
        [ 0.3, -0.3],
        [ 0.4, -0.3],
        [ 0.5, -0.3]],

       [[-0.5, -0.2],
        [-0.4, -0.2],
        [-0.3, -0.2],
        [-0.2, -0.2],
        [-0.1, -0.2],
        [ 0. , -0.2],
        [ 0.1, -0.2],
        [ 0.2, -0.2],
        [ 0.3, -0.2],
        [ 0.4, -0.2],
        [ 0.5, -0.2]],

       [[-0.5, -0.1],
  

Задание 11.

Замощение сетки $8\times8$ при помощи $0$ и $1$ в шахматном порядке, клетка с индексом $(0,0)$ замощается $1$

In [16]:
chess = np.delete((np.arange(1,73,1) % 2).reshape(8,9), 8, 1)
print(chess)



[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


Задание 12.

То же замощение, но клетка с индексом $(0,0)$ замощается $0$

In [17]:
print(1 - chess)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Задание 13.

Необходимо построить нижне-треугольную матрицу переменного размера (задается передачей параметра в функцию). Это единичная матрица,замощённая $1$ под главной диагональю

In [41]:
def low_triangle(n):
    return np.tril(np.ones(n)).astype(int)

a = low_triangle(5)
print(a)

[[1 0 0 0 0]
 [1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]
 [1 1 1 1 1]]


Задание 14.

Необходимо построить верхне-треугольную матрицу переменного размера. Это единичная матрица, замощённая $1$ над главной диагональю

In [247]:
def up_triangle(n):
    return np.triu(np.ones(n)).astype(int)

a = up_triangle(5)
print(a)

[[1 1 1 1 1]
 [0 1 1 1 1]
 [0 0 1 1 1]
 [0 0 0 1 1]
 [0 0 0 0 1]]


Задание 15.

Необходимо построить матрицу, в которой единицы стоят на побочной диагонали (идущей из левого нижнего угла в правый верхний), в остальных местах стоят $0$

In [19]:
a = np.eye(3,3).astype(int)
print(np.flipud(a))

[[0 0 1]
 [0 1 0]
 [1 0 0]]


### Операции + аггрегации (3 балла)

Задание 16.

Дана выборка $\{X_i\}$ некоторой случайной величины $X$, необходимо оценить
* Математическое ожидание $E[X] = \frac{1}{N}\sum_{i=1}^N X_i$ этой случайной величины
* Дисперсию $D[X] = \frac{1}{N}\sum_{i=1}^N (X_i - E[X])^2$ этой случайной величины

In [20]:
def expected_value(x):
    assert len(x) > 0
    return sum(x) / len(x)


def dispersion(x):
    assert len(x) > 0
    d = 0
    e = expected_value(x)
    for x_i in x:
        d += (x_i - e) ** 2
    return d / len(x)

In [21]:
def expected_value_np(x):
    return np.average(x)

In [22]:
def dispersion_np(x):
    return np.var(x)

In [23]:
np.testing.assert_array_equal(expected_value([1]), expected_value_np(np.array([1])))
np.testing.assert_array_equal(expected_value([3, 4]), expected_value_np(np.array([3, 4])))
np.testing.assert_array_equal(expected_value([-1, 0, 1]), expected_value_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(expected_value([-99, -98]), expected_value_np(np.array([-99, -98])))

np.testing.assert_array_equal(dispersion([1]), dispersion_np(np.array([1])))
np.testing.assert_array_equal(dispersion([3, 4]), dispersion_np(np.array([3, 4])))
np.testing.assert_array_equal(dispersion([-1, 0, 1]), dispersion_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(dispersion([-99, -98]), dispersion_np(np.array([-99, -98])))
print("Correct")

Correct


Задание 17.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое квадратов разностей их значений

In [7]:
def mean_square_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    # Здесь и далее эти проверки !не нужно! дублировать в свои функции; Здесь они для того, чтобы лишний раз подчеркнуть валидность входных данных
    s = 0
    for i in range(len(y1)):
        s += (y1[i] - y2[i]) ** 2
    return s / len(y1)

In [15]:
def mean_square_difference_np(y1, y2):
    return np.mean(((y1 - y2)**2))

In [17]:
assert mean_square_difference([1], [1]) == mean_square_difference_np(np.array([1]), np.array([1]))
assert mean_square_difference([1, 2], [1, 2]) == mean_square_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_square_difference([-1, 1], [0, 0]) == mean_square_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_square_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_square_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))
print("Correct")

Correct


Задание 18.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое модулей разностей их значений

In [86]:
def mean_abs_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    s = 0
    for i in range(len(y1)):
        s += abs(y1[i] - y2[i])
    return s / len(y1)

In [87]:
def mean_abs_difference_np(y1, y2):
    return np.mean(np.abs(y1 - y2))

In [152]:
assert mean_abs_difference([1], [1]) == mean_abs_difference_np(np.array([1]), np.array([1]))
assert mean_abs_difference([1, 2], [1, 2]) == mean_abs_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_abs_difference([-1, 1], [0, 0]) == mean_abs_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_abs_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_abs_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))
print("Correct")

Correct


Задание 19.

Даны два вектора $y_1$ и $y_2$, в которых присутствуют только $0$ и $1$. Необходимо посчитать вероятность совпадения - в скольких точках значения двух векторов совпадают

In [18]:
def matching_proba(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    assert len(set(y1)) <= 2
    assert len(set(y2)) <= 2
    assert 0 in set(y1) or 1 in set(y1) or (0 in set(y1) and 1 in set(y1))
    assert 0 in set(y2) or 1 in set(y2) or (0 in set(y2) and 1 in set(y2))

    return sum([y1[i] == y2[i] for i in range(len(y1))]) / len(y1)

In [19]:
def matching_proba_np(y1, y2):
    return np.mean(y1 == y2)

In [20]:
np.testing.assert_array_equal(matching_proba([0, 1], [1, 0]), matching_proba_np(np.array([0, 1]), np.array([1, 0])))
np.testing.assert_array_equal(matching_proba([0, 1, 0, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 1, 0, 1]), np.array([0, 0, 1, 1])))
np.testing.assert_array_equal(matching_proba([0, 0, 1, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1])))
print("Correct")

Correct


Задание 20.

Даны два вектора: $y_1$, $y_2$. В $y_1$ и $y_2$ присутствуют только $0$ и $1$.

Необходимо найти границы (индексы), такие, что если мы разделим вдоль какой-то из этих границ оба вектора на две части, то
* в левой части пересекающихся в $y_1$ и $y_2$ нулей будет строго больше, чем пересекающихся единиц или непересекающихся элементов
* в правой - пересекающихся единиц строго больше, чем пересекающихся нулей или непересекающихся элементов.

Если какая-то из частей не содержит элементов вовсе, то будем считать, что она подходит под условие.

In [196]:
def find_thresholds(y1, y2, debug=False):
    assert len(y1) == len(y2) and len(y1) > 0
    n = len(y1)
    matching_zeros = [1 if y1[i] == y2[i] == 0 else 0 for i in range(n)]
    matching_ones = [1 if y1[i] == y2[i] == 1 else 0 for i in range(n)]
    res = []
    if sum(matching_ones) / n > 0.5:
        res.append(0)
    for i in range(1, n):
        if debug: # если вам непонятна логика работы этой функции, передайте третьим аргументом True
            print(matching_zeros[:i], matching_ones[i:], i)
        if sum(matching_zeros[:i]) / i > 0.5 and sum(matching_ones[i:]) / (n - i) > 0.5:
            res.append(i)
    if sum(matching_zeros) / n > 0.5:
        res.append(n)
    return res

In [289]:
def find_thresholds_np(y1, y2):
    y3 = y1 + y2
    average = np.arange(1, len(y1) + 1, 1)
    zeros = (y3 == 0)
    ones = (y3 == 2)
    ones = np.flip(ones)
    extra2 = np.cumsum(ones) / average
    extra1 = np.cumsum(zeros) / average
    extra1 = extra1 > 1/2
    extra2 = extra2 > 1/2
    extra2 = np.flip(extra2)
    extra1 = np.flip(extra1)
    return np.where(extra1 * extra2 == 1)

#проходит только второй и третий тест, не проходит тест, где нужно сделать нулевой или самый последний слайс
# не получилось немного((

In [286]:
find_thresholds_np(np.array([1]), np.array([1]))


(array([], dtype=int64),)

In [288]:
find_thresholds([0], [0])

[1]

In [284]:
np.testing.assert_array_equal(find_thresholds([0], [0]), find_thresholds_np(np.array([0]), np.array([0])))
np.testing.assert_array_equal(find_thresholds([1], [1]), find_thresholds_np(np.array([1]), np.array([1])))
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 1], [0, 0, 1, 1]), 
    find_thresholds_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1]))
)
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 0, 0, 1, 1, 1], [0, 0, 0, 0, 0, 1, 1, 1]),
    find_thresholds_np(np.array([0, 0, 1, 0, 0, 1, 1, 1]), np.array([0, 0, 0, 0, 0, 1, 1, 1]))
)
print("Correct")

AssertionError: 
Arrays are not equal

(shapes (1,), (1, 0) mismatch)
 x: array([1])
 y: array([], shape=(1, 0), dtype=int64)

### Разные действия с матрицами (3 балла)

Задание 21.

Дана матрица размера $(32, 3, 16, 16)$, заполненная случайными числами от 0 до 9. При помощи **ровно двух** преобразований приведите её к виду $(32, 1)$. При выполнении задания **можно** создавать вспомогательные матрицы!

In [151]:
data = np.random.randint(0, 10, size=(32, 3, 16, 16))


extra = np.random.randint(0, 10, size=(768, 1))
data = np.matmul(data.reshape((32, 768)), extra)
# Первое преобразование - reshape, второе - умножение

assert data.shape == (32, 1)
print("Correct")

Correct


Задание 22.

Даны две матрицы $m_1$ размером $(32, 256)$ и $m_2$ размером $(32, 512)$, а также две вспомогательные матрицы $W_1$ размером $(256, 32)$ и $W_2$ размером $(512, 16)$. Используя **все** данные матрицы, сделайте так, чтобы на выходе получилась **ровно одна** матрица размером $(32, 32)$

In [46]:
m1 = np.random.randint(0, 10, size=(32, 256))
m2 = np.random.randint(0, 10, size=(32, 512))
W1 = np.random.randint(0, 10, size=(256, 32))
W2 = np.random.randint(0, 10, size=(512, 16))

result = np.matmul(np.matmul(np.matmul(m2, np.matmul(W2, m1.reshape(16, 512))), np.matmul(W2, W1.reshape(16, 512))), m2.transpose())
# все матрицы использованы 

assert result.shape == (32, 32)
print("Correct")

Correct


Задание 23.

Приведите полученную на последнем шаге матрицу к виду $(32, 3)$ и сделайте так, чтобы все значения в этой матрице были в промежутке от $0$ до $1$

In [49]:
# Вжух! (∩｀-´)⊃━☆ﾟ.*･｡ﾟ
extra = np.random.randint(0, 1, size = (32, 3))

result = np.matmul(result, extra) / np.max(result)

assert result.shape == (32, 3)
assert ((result >= 0) & (result <= 1)).all()
print("Correct")

Correct
