## Домашнее задание

В этой тетрадке вам предлагается реализовать задания при помощи библиотеки numpy. Крайне желательно при выполнении разных заданий не использовать циклы. Если вы не понимаете, как выполнить конкретную задачу без циклов - убирайте их постепенно, разбейте выполнение задачи на этапы и постепенно векторизуйте каждый этап.

Если вам непонятно, как выполнить ту или иную операцию - не стесняйтесь гуглить, если над вами повис дедлайн, а вы всё ещё на чём-то застряли - пишите преподу/в чат, это ок.

**Обсудить решение лучше и сделать в итоге хоть что-то гораздо лучше, чем скатать чужой код или сдать пустую тетрадку.**

In [67]:
import numpy as np

### Drill (1 балл)

Задание 1.

Инициализируйте нулями массивы следующих форм:

* (5)
* (5, 1)
* (10, 2)
* (3, 6, 2)
* (4, 3, 2, 1)

In [68]:
a1 = np.zeros(5)
a2 = np.zeros((5, 2))
a3 = np.zeros((10, 2))
a4 = np.zeros((3, 6, 2))
a5 = np.zeros((4, 3, 2, 1))

In [69]:
a1.shape, a2.shape, a3.shape, a4.shape, a5.shape

((5,), (5, 2), (10, 2), (3, 6, 2), (4, 3, 2, 1))

Задание 2.

Инициализируйте единицами массивы таких же форм и приведите их к целочисленному виду:

In [70]:
b1 = np.ones(5, dtype=int)
b2 = np.ones((5, 2), dtype=int)
b3 = np.ones((10, 2), dtype=int)
b4 = np.ones((3, 6, 2), dtype=int)
b5 = np.ones((4, 3, 2, 1), dtype=int)
b2

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

Задание 3.

Выполните для векторов выше `reshape` в "форму"
* с двумя компонентами
* с тремя компонентами
* с четырьмя компонентами

In [71]:
b1.reshape((5, 1))
b2.reshape((10, 1))
b3.reshape((20, 1))
b4.reshape((36, 1))
b5.reshape((24, 1))

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [72]:
b1.reshape((5, 1, 1))
b2.reshape((10, 1, 1))
b3.reshape((20, 1, 1))
b4.reshape((36, 1, 1))
b5.reshape((24, 1, 1))

array([[[1]],

       [[1]],

       [[1]],

       [[1]],

       [[1]],

       [[1]],

       [[1]],

       [[1]],

       [[1]],

       [[1]],

       [[1]],

       [[1]],

       [[1]],

       [[1]],

       [[1]],

       [[1]],

       [[1]],

       [[1]],

       [[1]],

       [[1]],

       [[1]],

       [[1]],

       [[1]],

       [[1]]])

In [73]:
b1.reshape((5, 1, 1, 1))
b2.reshape((10, 1, 1, 1))
b3.reshape((20, 1, 1, 1))
b4.reshape((36, 1, 1, 1))
b5.reshape((24, 1, 1, 1))

array([[[[1]]],


       [[[1]]],


       [[[1]]],


       [[[1]]],


       [[[1]]],


       [[[1]]],


       [[[1]]],


       [[[1]]],


       [[[1]]],


       [[[1]]],


       [[[1]]],


       [[[1]]],


       [[[1]]],


       [[[1]]],


       [[[1]]],


       [[[1]]],


       [[[1]]],


       [[[1]]],


       [[[1]]],


       [[[1]]],


       [[[1]]],


       [[[1]]],


       [[[1]]],


       [[[1]]]])

Задание 4.

Для вектора ниже посчитайте его
* Максимум по 1 оси
* Минимум по 0 оси
* Сумму по всем осям
* Среднее по 0 оси
* Медиану по 1 оси

In [74]:
v = np.random.randint(0, 9, size=(5, 7))
v

array([[8, 0, 4, 3, 2, 0, 0],
       [2, 4, 3, 0, 1, 2, 8],
       [7, 4, 3, 7, 6, 1, 7],
       [7, 7, 0, 4, 4, 6, 1],
       [5, 8, 7, 3, 8, 3, 3]])

In [75]:
print(v.max(axis=1))
print(v.max(axis=0))
print(v.sum())
print(v.mean(axis=0))
print(np.median(v, axis=1))

[8 8 7 7 8]
[8 8 7 7 8 6 8]
138
[5.8 4.6 3.4 3.4 4.2 2.4 3.8]
[2. 2. 6. 4. 5.]


Задание 5.

Для всё того же вектора `v` выведите
* Его shape
* 0 компоненту его "формы"
* 1 компоненту его "формы"

In [76]:
print(v.shape)
print(v.shape[0])
print(v.shape[1])

(5, 7)
5
7


Задание 6.

Для этого же вектора выведите
* Все числа больше 5
* Все числа меньше 7 в обратном порядке
* Все числа больше 3, которые делятся на 4 без остатка
* Все числа, остаток от деления на 5 которых равен 3
* Индекс максимума
* Индекс минимума
* Cписок с индексами элементов отсортированного массива в исходном (неотсортированном)

In [77]:
print(v[v > 5])
print(v[v < 7][::-1])
print(v[(v > 3) & (v % 4 == 0)])
print(v[v % 5 == 3])
print(v.argmax())
print(v.argmin())
print(v.argsort())

[8 8 7 7 6 7 7 7 6 8 7 8]
[3 3 3 5 1 6 4 4 0 1 6 3 4 2 1 0 3 4 2 0 0 2 3 4 0]
[8 4 4 8 4 4 4 8 8]
[8 3 3 8 3 8 3 8 3 3]
0
1
[[1 5 6 4 3 2 0]
 [3 4 0 5 2 1 6]
 [5 2 1 4 0 3 6]
 [2 6 3 4 5 0 1]
 [3 5 6 0 2 1 4]]


Задание 7.

Выполните следующие операции над вектором (независимо, не обязательно делать это в последовательности):
* Умножьте его на 3
* Разделите на 7
* Возведите в степень $\frac{2}{3}$
* Посчитайте $\sin$ от него
* Посчитайте $\log$ от него

In [78]:
print(3 * v)
print(v / 7)
print(v ** (2 / 3))
print(np.sin(v))
print(np.log(v)) # из-за того, что в v есть 0 возникает ошибка

[[24  0 12  9  6  0  0]
 [ 6 12  9  0  3  6 24]
 [21 12  9 21 18  3 21]
 [21 21  0 12 12 18  3]
 [15 24 21  9 24  9  9]]
[[1.14285714 0.         0.57142857 0.42857143 0.28571429 0.
  0.        ]
 [0.28571429 0.57142857 0.42857143 0.         0.14285714 0.28571429
  1.14285714]
 [1.         0.57142857 0.42857143 1.         0.85714286 0.14285714
  1.        ]
 [1.         1.         0.         0.57142857 0.57142857 0.85714286
  0.14285714]
 [0.71428571 1.14285714 1.         0.42857143 1.14285714 0.42857143
  0.42857143]]
[[4.         0.         2.5198421  2.08008382 1.58740105 0.
  0.        ]
 [1.58740105 2.5198421  2.08008382 0.         1.         1.58740105
  4.        ]
 [3.65930571 2.5198421  2.08008382 3.65930571 3.30192725 1.
  3.65930571]
 [3.65930571 3.65930571 0.         2.5198421  2.5198421  3.30192725
  1.        ]
 [2.92401774 4.         3.65930571 2.08008382 4.         2.08008382
  2.08008382]]
[[ 0.98935825  0.         -0.7568025   0.14112001  0.90929743  0.
   0.        ]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in log
  """


### Разные инициализации + индексирование (3 балла)

Задание 8.

Необходимо построить квадрат $3 \times 3$ из нечётных чисел

In [79]:
np.arange(1, 18, 2).reshape((3, 3))

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

Задание 9.

Необходимо построить квадрат $4 \times 4$ из четных чисел в обратном порядке

In [80]:
np.arange(32, 0, -2).reshape((4, 4))

array([[32, 30, 28, 26],
       [24, 22, 20, 18],
       [16, 14, 12, 10],
       [ 8,  6,  4,  2]])

Задание 10.

Необходимо построить сетку координат $11 \times 11$ с точкой $(0,0)$ в центре и шагом $0.1$ между клетками

Я не смог придумать чего-то красивого, я понимаю, что это тупо копипаста вместо цикла


In [81]:
rowx = np.arange(-0.5, 0.6, 0.1)
ansx = rowx.copy()
ansx = np.vstack((ansx, rowx))
ansx = np.vstack((ansx, rowx))
ansx = np.vstack((ansx, rowx))
ansx = np.vstack((ansx, rowx))
ansx = np.vstack((ansx, rowx))
ansx = np.vstack((ansx, rowx))
ansx = np.vstack((ansx, rowx))
ansx = np.vstack((ansx, rowx))
ansx = np.vstack((ansx, rowx))
ansx = np.vstack((ansx, rowx))
print(ansx.shape)

(11, 11)


In [82]:
coly = (np.arange(-0.5, 0.6, 0.1)).reshape(11, 1)
ansy = coly.copy()
ansy = np.hstack((ansy, coly))
ansy = np.hstack((ansy, coly))
ansy = np.hstack((ansy, coly))
ansy = np.hstack((ansy, coly))
ansy = np.hstack((ansy, coly))
ansy = np.hstack((ansy, coly))
ansy = np.hstack((ansy, coly))
ansy = np.hstack((ansy, coly))
ansy = np.hstack((ansy, coly))
ansy = np.hstack((ansy, coly))
print(ansy.shape)

(11, 11)


In [83]:
ans = np.concatenate((ansx.reshape(11, 11, 1), ansy.reshape(11, 11, 1)), axis=2)
ans

array([[[-5.00000000e-01, -5.00000000e-01],
        [-4.00000000e-01, -5.00000000e-01],
        [-3.00000000e-01, -5.00000000e-01],
        [-2.00000000e-01, -5.00000000e-01],
        [-1.00000000e-01, -5.00000000e-01],
        [-1.11022302e-16, -5.00000000e-01],
        [ 1.00000000e-01, -5.00000000e-01],
        [ 2.00000000e-01, -5.00000000e-01],
        [ 3.00000000e-01, -5.00000000e-01],
        [ 4.00000000e-01, -5.00000000e-01],
        [ 5.00000000e-01, -5.00000000e-01]],

       [[-5.00000000e-01, -4.00000000e-01],
        [-4.00000000e-01, -4.00000000e-01],
        [-3.00000000e-01, -4.00000000e-01],
        [-2.00000000e-01, -4.00000000e-01],
        [-1.00000000e-01, -4.00000000e-01],
        [-1.11022302e-16, -4.00000000e-01],
        [ 1.00000000e-01, -4.00000000e-01],
        [ 2.00000000e-01, -4.00000000e-01],
        [ 3.00000000e-01, -4.00000000e-01],
        [ 4.00000000e-01, -4.00000000e-01],
        [ 5.00000000e-01, -4.00000000e-01]],

       [[-5.00000000e-01, -3

Задание 11.

Замощение сетки $8\times8$ при помощи $0$ и $1$ в шахматном порядке, клетка с индексом $(0,0)$ замощается $1$

In [84]:
np.delete((np.arange(1, 82, 1).reshape((9, 9)) % 2)[:-1], -1, axis=1)

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

Задание 12.

То же замощение, но клетка с индексом $(0,0)$ замощается $0$

In [85]:
np.delete((np.arange(0, 81, 1).reshape((9, 9)) % 2)[:-1], -1, axis=1)

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

Задание 13.

Необходимо построить нижне-треугольную матрицу переменного размера (задается передачей параметра в функцию). Это единичная матрица,замощённая $1$ под главной диагональю

Возможно можно проще, я здесь подумал, что матрицу где на главной диоганале 1, а под главной -1. Т.е. таково вида:
\begin{align*}
M =
\left(\begin{matrix} 
1 & 0 & 0 & 0\\
-1 & 1 & 0 & 0\\
0 & -1 & 1 & 0\\
0 & 0 & -1 & 1
\end{matrix}\right)
\end{align*}
сделать проще. А это матрица обратная к той которая нам нужна

In [86]:
def make_low_triangle(n):
  zero_row = np.zeros(n - 1)
  zero_col = np.zeros((n, 1))
  part_ans_rev = -1 * np.concatenate((np.vstack((zero_row, np.eye(n - 1))), zero_col), axis=1)
  ans = np.linalg.inv(part_ans_rev + np.eye(n))
  return ans


print(make_low_triangle(10))

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Задание 14.

Необходимо построить верхне-треугольную матрицу переменного размера. Это единичная матрица, замощённая $1$ над главной диагональю

In [87]:
def make_up_triangle(n):
  return np.eye(n) + (1 - make_low_triangle(n))


print(make_up_triangle(10))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


Задание 15.

Необходимо построить матрицу, в которой единицы стоят на побочной диагонали (идущей из левого нижнего угла в правый верхний), в остальных местах стоят $0$

In [88]:
def strange_eye(n):
  arr = np.delete((np.arange(0, (n + 1) ** 2, 1).reshape(n + 1, n + 1) % n)[:-1], -1, axis=-1)
  arr[arr % n != n - 1] = 0
  arr[arr % n == n - 1] = 1
  return arr

strange_eye(10)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

### Операции + аггрегации (3 балла)

Задание 16.

Дана выборка $\{X_i\}$ некоторой случайной величины $X$, необходимо оценить
* Математическое ожидание $E[X] = \frac{1}{N}\sum_{i=1}^N X_i$ этой случайной величины
* Дисперсию $D[X] = \frac{1}{N}\sum_{i=1}^N (X_i - E[X])^2$ этой случайной величины

In [89]:
def expected_value(x):
    assert len(x) > 0
    return sum(x) / len(x)


def dispersion(x):
    assert len(x) > 0
    d = 0
    e = expected_value(x)
    for x_i in x:
        d += (x_i - e) ** 2
    return d / len(x)

In [90]:
def expected_value_np(x):
    return x.mean()

In [91]:
def dispersion_np(x):
    return ((x - expected_value_np(x)) ** 2).sum() / len(x)

In [92]:
np.testing.assert_array_equal(expected_value([1]), expected_value_np(np.array([1])))
np.testing.assert_array_equal(expected_value([3, 4]), expected_value_np(np.array([3, 4])))
np.testing.assert_array_equal(expected_value([-1, 0, 1]), expected_value_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(expected_value([-99, -98]), expected_value_np(np.array([-99, -98])))

np.testing.assert_array_equal(dispersion([1]), dispersion_np(np.array([1])))
np.testing.assert_array_equal(dispersion([3, 4]), dispersion_np(np.array([3, 4])))
np.testing.assert_array_equal(dispersion([-1, 0, 1]), dispersion_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(dispersion([-99, -98]), dispersion_np(np.array([-99, -98])))

Задание 17.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое квадратов разностей их значений

In [93]:
def mean_square_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    # Здесь и далее эти проверки !не нужно! дублировать в свои функции; Здесь они для того, чтобы лишний раз подчеркнуть валидность входных данных
    s = 0
    for i in range(len(y1)):
        s += (y1[i] - y2[i]) ** 2
    return s / len(y1)

In [94]:
def mean_square_difference_np(y1, y2):
    return ((y1 - y2) ** 2).mean()

In [95]:
assert mean_square_difference([1], [1]) == mean_square_difference_np(np.array([1]), np.array([1]))
assert mean_square_difference([1, 2], [1, 2]) == mean_square_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_square_difference([-1, 1], [0, 0]) == mean_square_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_square_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_square_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 18.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое модулей разностей их значений

In [96]:
def mean_abs_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    s = 0
    for i in range(len(y1)):
        s += abs(y1[i] - y2[i])
    return s / len(y1)

In [97]:
def mean_abs_difference_np(y1, y2):
    return abs(y1 - y2).mean()

In [98]:
assert mean_abs_difference([1], [1]) == mean_abs_difference_np(np.array([1]), np.array([1]))
assert mean_abs_difference([1, 2], [1, 2]) == mean_abs_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_abs_difference([-1, 1], [0, 0]) == mean_abs_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_abs_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_abs_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 19.

Даны два вектора $y_1$ и $y_2$, в которых присутствуют только $0$ и $1$. Необходимо посчитать вероятность совпадения - в скольких точках значения двух векторов совпадают

In [99]:
def matching_proba(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    assert len(set(y1)) <= 2
    assert len(set(y2)) <= 2
    assert 0 in set(y1) or 1 in set(y1) or (0 in set(y1) and 1 in set(y1))
    assert 0 in set(y2) or 1 in set(y2) or (0 in set(y2) and 1 in set(y2))

    return sum([y1[i] == y2[i] for i in range(len(y1))]) / len(y1)

In [100]:
def matching_proba_np(y1, y2):
    return len(y1[y1 == y2]) / len(y1)

In [101]:
np.testing.assert_array_equal(matching_proba([0, 1], [1, 0]), matching_proba_np(np.array([0, 1]), np.array([1, 0])))
np.testing.assert_array_equal(matching_proba([0, 1, 0, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 1, 0, 1]), np.array([0, 0, 1, 1])))
np.testing.assert_array_equal(matching_proba([0, 0, 1, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1])))

Задание 20.

Даны два вектора: $y_1$, $y_2$. В $y_1$ и $y_2$ присутствуют только $0$ и $1$.

Необходимо найти границы (индексы), такие, что если мы разделим вдоль какой-то из этих границ оба вектора на две части, то
* в левой части пересекающихся в $y_1$ и $y_2$ нулей будет строго больше, чем пересекающихся единиц или непересекающихся элементов
* в правой - пересекающихся единиц строго больше, чем пересекающихся нулей или непересекающихся элементов.

Если какая-то из частей не содержит элементов вовсе, то будем считать, что она подходит под условие.

In [102]:
def find_thresholds(y1, y2, debug=False):
    assert len(y1) == len(y2) and len(y1) > 0
    n = len(y1)
    matching_zeros = [1 if y1[i] == y2[i] == 0 else 0 for i in range(n)]
    matching_ones = [1 if y1[i] == y2[i] == 1 else 0 for i in range(n)]
    res = []
    if sum(matching_ones) / n > 0.5:
        res.append(0)
    for i in range(1, n):
        if debug: # если вам непонятна логика работы этой функции, передайте третьим аргументом True
            print(matching_zeros[:i], matching_ones[i:], i)
        if sum(matching_zeros[:i]) / i > 0.5 and sum(matching_ones[i:]) / (n - i) > 0.5:
            res.append(i)
    if sum(matching_zeros) / n > 0.5:
        res.append(n)
    return res

In [103]:
def find_thresholds_np(y1, y2):
    n = y1.shape[0]
    zeros = (y1 == 0) & (y2 == 0)
    ones = (y1 == 1) & (y2 == 1)
    ans = np.zeros(1 if 2 * np.count_nonzero(ones) > n else 0, dtype=int) # костыль для 0)
    pref0 = zeros.cumsum()[:-1]
    suf1 = ones[::-1].cumsum()[::-1][1:]
    if pref0.shape[0] > 0 and suf1.shape[0] > 0:
        nrange = np.arange(1, n)
        backnrange = np.arange(n - 1, 0, -1)
        pref0 = pref0 / nrange
        suf1 = suf1 / backnrange
        ans = np.hstack((ans, nrange[(2 * pref0 > 1) & (2 * suf1 > 1)]))
    if 2 * np.count_nonzero(zeros) > n:
        ans = np.append(ans, n) # костыль для n)
    return ans.astype(int)

In [104]:
np.testing.assert_array_equal(find_thresholds([0], [0]), find_thresholds_np(np.array([0]), np.array([0])))
np.testing.assert_array_equal(find_thresholds([1], [1]), find_thresholds_np(np.array([1]), np.array([1])))
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 1], [0, 0, 1, 1]), 
    find_thresholds_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1]))
)
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 0, 0, 1, 1, 1], [0, 0, 0, 0, 0, 1, 1, 1]),
    find_thresholds_np(np.array([0, 0, 1, 0, 0, 1, 1, 1]), np.array([0, 0, 0, 0, 0, 1, 1, 1]))
)

### Разные действия с матрицами (3 балла)

Задание 21.

Дана матрица размера $(32, 3, 16, 16)$, заполненная случайными числами от 0 до 9. При помощи **ровно двух** преобразований приведите её к виду $(32, 1)$. При выполнении задания **можно** создавать вспомогательные матрицы!

In [105]:
data = np.random.randint(0, 10, size=(32, 3, 16, 16))

data = data.reshape(32, 3 * 16 * 16)
data = data @ np.ones((3 * 16 * 16, 1))

assert data.shape == (32, 1)

Задание 22.

Даны две матрицы $m_1$ размером $(32, 256)$ и $m_2$ размером $(32, 512)$, а также две вспомогательные матрицы $W_1$ размером $(256, 32)$ и $W_2$ размером $(512, 16)$. Используя **все** данные матрицы, сделайте так, чтобы на выходе получилась **ровно одна** матрица размером $(32, 32)$

In [106]:
m1 = np.random.randint(0, 10, size=(32, 256))
m2 = np.random.randint(0, 10, size=(32, 512))
W1 = np.random.randint(0, 10, size=(256, 32))
W2 = np.random.randint(0, 10, size=(512, 16))

result = np.concatenate((m1 @ W1 @ m2 @ W2, m1 @ W1 @ m2 @ W2), axis=1)
assert result.shape == (32, 32)

Задание 23.

Приведите полученную на последнем шаге матрицу к виду $(32, 3)$ и сделайте так, чтобы все значения в этой матрице были в промежутке от $0$ до $1$

In [107]:
# Вжух! (∩｀-´)⊃━☆ﾟ.*･｡ﾟ
result = result @ (np.linspace(1e-12, 1e-11, 32 * 3).reshape(32, 3))

assert result.shape == (32, 3)
assert ((result >= 0) & (result <= 1)).all()