### (0 баллов) Считываем данные

In [65]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline

In [66]:
from sklearn.datasets import load_boston

dataset = load_boston()
dataset.keys()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename', 'data_module'])

Каждая квартира имеет 13 признаков:

In [67]:
X = dataset['data']
X[:10]

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, 0.0000e+00, 5.3800e-01,
        6.5750e+00, 6.5200e+01, 4.0900e+00, 1.0000e+00, 2.9600e+02,
        1.5300e+01, 3.9690e+02, 4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, 0.0000e+00, 4.6900e-01,
        6.4210e+00, 7.8900e+01, 4.9671e+00, 2.0000e+00, 2.4200e+02,
        1.7800e+01, 3.9690e+02, 9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, 0.0000e+00, 4.6900e-01,
        7.1850e+00, 6.1100e+01, 4.9671e+00, 2.0000e+00, 2.4200e+02,
        1.7800e+01, 3.9283e+02, 4.0300e+00],
       [3.2370e-02, 0.0000e+00, 2.1800e+00, 0.0000e+00, 4.5800e-01,
        6.9980e+00, 4.5800e+01, 6.0622e+00, 3.0000e+00, 2.2200e+02,
        1.8700e+01, 3.9463e+02, 2.9400e+00],
       [6.9050e-02, 0.0000e+00, 2.1800e+00, 0.0000e+00, 4.5800e-01,
        7.1470e+00, 5.4200e+01, 6.0622e+00, 3.0000e+00, 2.2200e+02,
        1.8700e+01, 3.9690e+02, 5.3300e+00],
       [2.9850e-02, 0.0000e+00, 2.1800e+00, 0.0000e+00, 4.5800e-01,
        6.4300e+00, 5.8700e

In [68]:
dataset['feature_names']

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [69]:
print(dataset['DESCR'])

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

Хочется научиться предсказывать функцию цены квартиры. Предположительно, она зависит как-то от этих признаков.

In [70]:
y = dataset['target']
y[:10]

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9])

### (1 балл) Разделите данные на тренировочную и тестовую части.

Тестовая часть должна составлять 10% выборки.


In [71]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1)

### (1 балл) Обучение и применение модели
Обучите модель линейной регрессии на тренировочной части и предскажите результаты на тестовой части.



In [72]:
from sklearn.linear_model import LinearRegression

# Наша модель
reg = LinearRegression()
reg.fit(X_train, y_train)

LinearRegression()

In [73]:
reg.predict(X_test)

array([14.85726927, 25.27082206, 20.84991186, 17.78361323, 20.42416302,
       17.05290725, 22.63681704, 22.79409662, 37.12646167, 31.43863515,
       23.19015841, 23.75816363, 19.68055711, 13.30194416, 24.19661388,
       21.57045545, 19.94093002, 24.91174094, 22.07465391, 24.44908453,
       24.73346613,  0.46679753, 13.0576091 ,  6.26226099, 21.05385988,
       11.24736692, 29.02733507, 21.73278556, 20.34823761, 19.4286465 ,
        5.27958429, 25.38532892, 22.30160176, 24.85822488, 18.03424579,
       23.76926173, 42.39175534, 16.19235822,  2.87189421, 17.96130234,
       40.64898991, 20.43492108, 19.48545651, 16.97617767, 32.96027254,
       19.81872373, 15.53009595, 32.3805354 , 33.62159392, 34.99302785,
        7.99642742])

### (2 балл) Валидация результата

Напишите свою функцию MSE, убедитесь, что она совпадает с реализацией из sklearn и посчитайте своей результат на тестовой части.

In [74]:
from sklearn.metrics import mean_squared_error
def MSE(y_real, y_pred):
  return np.sum((y_pred - y_real) ** 2) / y_real.size

In [75]:
print(mean_squared_error(y_test, reg.predict(X_test)))
print(MSE(y_test, reg.predict(X_test)))

25.57486070376212
25.57486070376212


Насколько хорошо вы предсказали цену? Сравните с наивным алгоритмом (предсказать среднюю цену на тренировочной части вне зависимости от признаков).

In [76]:
MSE(y_test, reg.predict(X_test)) # Ошибка нашего предположения

25.57486070376212

Никаких слов, одни эмоции.

In [77]:
MSE(y_test, np.array(np.mean(y_train))) # Ошибка наивного алгоритма

83.38395037636356

### (2 балла) Улучшите результат.

Возможно, происходит переобучение, попробуйте применить регуляризацию, чтобы улучшить результат (то есть используйте Ridge вместо LinearRegression).

Нарисуйте график зависимости MSE от коэффициента регуляризации.

In [78]:
reg_no_alpha = LinearRegression()
reg_no_alpha.fit(X_train, y_train)

LinearRegression()

In [79]:
from sklearn.linear_model import Ridge

X_coords = np.arange(1, 500)
Y_coords = []
for alpha in X_coords:
  reg = Ridge(alpha=alpha).fit(X_train, y_train)
  Y_coords.append(MSE(y_test, reg.predict(X_test)))
plt.plot(X_coords, Y_coords)
plt.show()

Помогает ли регуляризация? Какой коэффициент регуляризации надо выбрать, чтобы ошибка была минимальной? Чему при этом равна ошибка? Напишите выводы о проведенных экспериментах

In [80]:
print("Лучший коэффициент и MSE при таком коэффе.")
print(f'α = {X_coords[Y_coords.index(min(Y_coords))]}, MSE = {min(Y_coords)}')
print("MSE без регуляризации.")
print(f'MSE = {MSE(y_test, reg_no_alpha.predict(X_test))}')

Лучший коэффициент и MSE при таком коэффе.
α = 119, MSE = 24.830657278300958
MSE без регуляризации.
MSE = 25.57486070376212


Регуляризациия помогает в 2 из 3 случаев, уменьшая ошибку хотя бы на несколько десятых, однако нередко она только мешает + при неправильном коэффициенте ошибка может сильно увеличиться в сравнении с ошибкой обычной регрессии.